### ISSUE TITLE
Webpanel

### ISSUE THREAD

**Issue by Kinkky** [splewis/get5#10]
Hi, I'm the founder of trip pugs and i have been using your pug system and moved to the get5 system but i need more then a in-game plugin, I need to be able to have someway for people to join the server with the cfg already loaded. I see you have a http pull so that helps with the cfg loading bit but the lobby bit is where im stuck. Can you help??

**Comment by splewis** [comment]
This project will only contain a game server plugin for the time being. If you want web lobby system, you'd have to make it yourself.

Don't advertise jobs here.

**Comment by Kinkky** [comment]
I was offering a job to you and ok no problems. thanks
