### ISSUE TITLE
[Feature] Scrim: When all clients .ready, sort teams according to template

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#100]
### Expected behavior / Wanted

When all clients in the scrim have used .ready, sort teams appropriately before knife round so that the scrim team do not all have to start on the original team, when all teams are ready sort teams so it's the template team, vs others. Cvar perhaps?

**Comment by splewis** [comment]
Unless you set ``get5_check_auths`` to 0 this is what it's supposed to do.

**Comment by Technoblazed** [comment]
Oh, well it doesn't, all players just stay on whichever team they were on when you did the scrim command, you're able to switch team to the correct one, but it doesn't force change your team.

**Comment by splewis** [comment]
Oh, I misunderstood. I usually assume (and test) running commands before clients join the server, so I didn't think about this case. 

Yes, this should be fixed.

**Comment by Technoblazed** [comment]
Yup, all good!
