### ISSUE TITLE
[Bug]: Reset connection timer

### ISSUE THREAD

**Issue by LowArte** [splewis/get5#1010]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

0.14.1

### The Issue

1. Create match
2. Players not connected
3. Wait 2 minutes. (you can less)
4. Connect another player who does not participate in the match
5. Connection timer reset from 8 minutes to 10 minutes
6. Can retry forever

**Comment by LowArte** [comment]
Hello ! Thanks It's working

**Comment by nickdnk** [comment]
Released in 0.14.2: https://github.com/splewis/get5/releases/tag/v0.14.2

**Comment by nickdnk** [comment]
I made a mistake in that release, that would cause the timer to not reset between maps. It should be fixed here: https://github.com/splewis/get5/releases/tag/v0.14.3 - I removed 0.14.2 from releases.
