### ISSUE TITLE
[Feature Request]: Loading match from url limitations

### ISSUE THREAD

**Issue by LowArte** [splewis/get5#1012]
### Prereleases & Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and I don't see the feature anywhere.
- [X] I have looked for [pre-releases](https://github.com/splewis/get5/releases) and the feature has not been added.

### Get5 Version

0.14.1

### The Feature

For creating matches right now i'm using get5_loadmatch_url, but i have a very long bearer token and url with guid's.
As i know commands have 255 character limitations for commands, how can i  get around this limitation ?

**Comment by nickdnk** [comment]
You cannot get around this, unfortunately. Make your auth token and link shorter.

**Comment by LowArte** [comment]
Thanks, but i have an idea. If you can create login in external systems it can be fixable. For example in get5_loadmatch_url instead of token argument, set 2 new parameters username and password for external system. And also add configuration parameter or another argument  "external auth url"

**Comment by nickdnk** [comment]
> Thanks, but i have an idea. If you can create login in external systems it can be fixable. For example in get5_loadmatch_url instead of token argument, set 2 new parameters username and password for external system. And also add configuration parameter or another argument "external auth url"

If you want to use username and password, just provide that as the header arguments? You don't have to use a JWT.

I don't understand the second part.

Regardless, I'm no longer adding features to Get5, so I won't be doing this.

**Comment by LowArte** [comment]
I undestand, thanks
