### ISSUE TITLE
.endmatch and scrim issue

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#102]
### Expected behavior

After using ``.endmatch``, you should instantly be able to use ``!scrim`` and teams be resorted correctly to the original template.

### Actual behavior

After ``.endmatch`` is used, followed by ``!scrim``, the teams are not autosorted. The match must be force ended again then the scrim command reused for teams to be sorted correctly.

- Plugin version: Latest
- Sourcemod version: Latest 1,8

**Comment by splewis** [comment]
I don't have the ability to test this now, but c1375952cb9ef4d637cf4f20008688f4411a4057 might fix it (the problem being trying to set the player teams before SetStartingTeams fixed the saved sides).

**Comment by royysz** [comment]
"plugin_version": "0.4.1-dev+239"
you can reproduce this if you spam the enter key when there are 9/10 players on the server, it will move you to the spec.

**Comment by Technoblazed** [comment]
That's not the same issue mentioned in the original post

**Comment by royysz** [comment]
wrong post

**Comment by splewis** [comment]
I did get5_endmatch and get5_scrim and saw teams get sorted correctly again, so I believe this is fixed.
