### ISSUE TITLE
[Feature Request]: Allow comments in teams.json

### ISSUE THREAD

**Issue by ar1a** [splewis/get5#1021]
### Prereleases & Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and I don't see the feature anywhere.
- [X] I have looked for [pre-releases](https://github.com/splewis/get5/releases) and the feature has not been added.

### Get5 Version

0.14.4

### The Feature

Would love to see comments allowed in JSON parsing, even though it's not strictly specced.

My use case is I am trialing a lot of players and need to change my teams.json constantly, not having to go and re-look up someone's steam id when they trial again a different night would be nice.

**Comment by nickdnk** [comment]
This is not going to happen unfortunately. If you want comments, you'll have to use the KeyValues file format instead, which allows this.

You can also potentially use the `!get5` menu to start games on demand without having to create files.

**Comment by nickdnk** [comment]
Correction: The teams and map files do not support the KeyValues format. Match config only unfortunately.

**Comment by nickdnk** [comment]
@ar1a Something else you could consider is just using `get5_addplayer` to add the trialing player to the team after loading the match configuration file. Then you don't have to change any files at all: https://splewis.github.io/get5/latest/commands/#get5_addplayer

**Comment by ar1a** [comment]
oh sweet! will that force them to switch teams (ct/t) too?

**Comment by nickdnk** [comment]
They won’t be on the server when you issue the command, so it will put them on the right team when they join, just like if they had been in the team file to begin with. It’s the same thing.
