### ISSUE TITLE
[Bug]: This plugin most likely forces my server to 64tick

### ISSUE THREAD

**Issue by sam1e-dev** [splewis/get5#1029]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

0.14.7

### The Issue

I have set these commands in startup config:
cl_cmdrate 128
cl_updaterate 128
sv_mincmdrate 128
sv_minupdaterate 128
To force user 128 tick.
I also have -tickrate 128 in my server startup option.
On my other servers, this works without any issue, but right now i am trying to make a PUG server for my friend but it seems that get5 forces these values to 64 on startup. Because when i execute this config manually once i am on the server it works like intended. In the same config i have hostname, server password etc, everything works since startup, only these values keep getting reset

### Debug Info

```log
It doesnt fit the whole file here :(
```

**Comment by sam1e-dev** [comment]
The file:
[get5_debuginfo.txt](https://github.com/splewis/get5/files/11521156/get5_debuginfo.txt)

(I dont know warmod.smx errors, i have disabled/deleted this plugin and files related with it and restarted server many times)

**Comment by nickdnk** [comment]
Hello

Get5 never changes the tickrate. I would suggest you remove any other plugins you may have and search your server directory for `rate` to see if you can find any config files that contain the commands that change the `update` or `cmdrate`, such as the ones you posted. The tickrate itself is set by the `-tickrate` launch parameter.

You have both `gloves.smx`, `weapons.smx` and `warmup.smx` that are non-standard. The last one would probably be something worth inspecting.

Either way, Get5 is not doing this.

Also, commands starting with `cl_` are for the clients, i.e. setting `cl_updaterate` on your server does not do anything. You are looking for `sv_` commands for the server.
