### ISSUE TITLE
.endmatch and get5_mysqlstats

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#103]
When using ``.endmatch``, the matches table in the get5_mysqlstats database should be updated with the end time, currently it is just left blank if a match is force ended.

**Comment by splewis** [comment]
I can't easily verify this, but I believe this is fixed by 5629eee0e1cb3df8541637df0287d9f1d08c31a1

**Comment by Technoblazed** [comment]
Yeah it was, my bad.
