### ISSUE TITLE
[Bug]: Players count smaller in server

### ISSUE THREAD

**Issue by N1HBK** [splewis/get5#1038]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

0.15.0

### The Issue

This is not a get5 problem but idk if u can help me. The player count in the hud looks smaller, i know its because of 12 slots but in my old server with 12 slots as well its used to be like normal. Do u know to fix it? I want to host a tournament in the server and its looks weird :/
![20230806231154_1](https://github.com/splewis/get5/assets/141598683/849244d3-894f-4829-af5c-7b39cac0b386)

### Match Configuration

```log
*
```

### Debug Info

```log
*
```

**Comment by nickdnk** [comment]
Hello

For things like this you can see if someone in the get5 Discord can help you. As this has nothing to do with get5, I'm closing the bug report.

You also have an error in your JSON maps file as evident from the error message.

**Comment by nickdnk** [comment]
For anyone coming across this. Set `sv_competitive_official_5v5 1` in your `server.cfg`.
