### ISSUE TITLE
[Bug]: Event map_result different from doc

### ISSUE THREAD

**Issue by MirkevychV** [splewis/get5#1042]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

0.15.0

### The Issue

I got message from map_result event throught HTTPS: 
`{'matchid': '44', 'winner': {'side': 't', 'team': 'team1'}, 'team2_score': 0, 'event': 'map_result', 'map_number': 0, 'team1_score': 16}`

But in documentation it looks like:
`{
  "event": "map_result",
  "matchid": "14272",
  "map_number": 0,
  "team1": {
    "id": "2843",
    "name": "Natus Vincere",
    "series_score": 0,
    "score": 14,
    "score_ct": 10,
    "score_t": 14,
    "players": [
      {
        "steamid": "76561198279375306",
        "name": "s1mple",
        "stats": {
          "kills": 34,
          "deaths": 8,
          "assists": 5,
          "flash_assists": 3,
          "team_kills": 0,
          "suicides": 0,
          "damage": 2948,
          "utility_damage": 173,
          "enemies_flashed": 6,
          "friendlies_flashed": 2,
          "knife_kills": 1,
          "headshot_kills": 19,
          "rounds_played": 27,
          "bomb_defuses": 4,
          "bomb_plants": 3,
          "1k": 3,
          "2k": 2,
          "3k": 3,
          "4k": 0,
          "5k": 1,
          "1v1": 1,
          "1v2": 3,
          "1v3": 2,
          "1v4": 0,
          "1v5": 1,
          "first_kills_t": 6,
          "first_kills_ct": 5,
          "first_deaths_t": 1,
          "first_deaths_ct": 1,
          "trade_kills": 3,
          "kast": 23,
          "score": 45,
          "mvp": 4
        }
      }
    ],
    "side": "ct",
    "starting_side": "ct"
  },
  "team2": {
    "id": "2843",
    "name": "Natus Vincere",
    "series_score": 0,
    "score": 14,
    "score_ct": 10,
    "score_t": 14,
    "players": [
      {
        "steamid": "76561198279375306",
        "name": "s1mple",
        "stats": {
          "kills": 34,
          "deaths": 8,
          "assists": 5,
          "flash_assists": 3,
          "team_kills": 0,
          "suicides": 0,
          "damage": 2948,
          "utility_damage": 173,
          "enemies_flashed": 6,
          "friendlies_flashed": 2,
          "knife_kills": 1,
          "headshot_kills": 19,
          "rounds_played": 27,
          "bomb_defuses": 4,
          "bomb_plants": 3,
          "1k": 3,
          "2k": 2,
          "3k": 3,
          "4k": 0,
          "5k": 1,
          "1v1": 1,
          "1v2": 3,
          "1v3": 2,
          "1v4": 0,
          "1v5": 1,
          "first_kills_t": 6,
          "first_kills_ct": 5,
          "first_deaths_t": 1,
          "first_deaths_ct": 1,
          "trade_kills": 3,
          "kast": 23,
          "score": 45,
          "mvp": 4
        }
      }
    ],
    "side": "ct",
    "starting_side": "ct"
  },
  "winner": {
    "side": "ct",
    "team": "team1"
  }
}`

### Match Configuration

```log
{"cvars": {"bot_add": "", "hostname": "Aboba from 2023 04 04 ", "game_mode": "0", "game_type": "0", "mp_roundtime": "9999", "bot_difficulty": "3", "bot_qouta_mode": 2, "mp_friendlyfire": "1", "mp_respawn_on_death_t": "0", "mp_respawn_on_death_ct": "0", "mp_teammates_are_enemies": "1", "get5_stop_command_enabled": "0", "sv_ggprogressive_shotgun_last": "1", "sm_practicemode_can_be_started": "0", "sv_ggprogressive_autosniper_first": "1", "mp_ggprogressive_use_random_weapons": "1", "mp_ggprogressive_round_restart_delay": "15", "mp_ggprogressive_healthshot_killcount": "3", "mp_ggprogressive_random_weapon_kills_needed": "2"}, "maplist": ["de_lake"], "matchid": "44", "wingman": false, "num_maps": 1, "map_sides": ["team1_ct", "team2_ct", "knife"], "side_type": "standard", "skip_veto": false, "spectators": {"name": "Blast PRO 2021", "players": {"76561197987511774": "Anders Blume"}}, "veto_first": "team1", "match_title": "Astralis vs. UNWEB", "clinch_series": true, "coaches_per_team": 0, "players_per_team": 5, "coaches_must_ready": false, "min_players_to_ready": 1, "min_spectators_to_ready": 0, "team1": {"name": "admin's team", "players": ["76561199444281647"]}, "team2": {"name": "BMW M5 CS's team", "players": ["76561198380296220"]}}
```

**Comment by MirkevychV** [comment]
also in get5_matchstats_44.cfg  file all data is ok, like in doc

**Comment by nickdnk** [comment]
Hello

You don't have version 0.15.0 if you're seeing this JSON. It's the 0.13 structure. Please verify your version with `get5_version` in the console.

**Comment by MirkevychV** [comment]
thank You so much, I really have version 0.13

**Comment by nickdnk** [comment]
Good. Update to 0.15.0 and remember to check the breaking changes: https://github.com/splewis/get5/blob/master/CHANGELOG.md#0140

**Comment by nickdnk** [comment]
You should also *not* set game mode and game type yourself. It's determined by the `wingman` parameter of your match configuration.
