### ISSUE TITLE
Player name forcing

### ISSUE THREAD

**Issue by splewis** [splewis/get5#106]
There should be a way of forcing player names. The keyvalue file format already has a obvious spot to include it (the empty string value where the steamids are the keys). 

For JSON formats, there can be a new section that does a key/value mapping of steamids to names, or there could be a native to add a new entry to a steam64->name mapping.

**Comment by atrefz** [comment]
Is there any progress on this? Can one possibly help? (and if so, could you give some pointers?)

**Comment by Technoblazed** [comment]
Takes about 10 minutes to implement but no one has time fo dat

**Comment by miped** [comment]
How about changing the `players` key to accept either a dictionary or an array (for backwards compatibility:
```json
{
    "team1": {
        "players": {
              "<steamid>": "<name"
        }
    }
}
```

This would maintain a nice symmetry with the KV format.

**Comment by PopiCSGO** [comment]
Is there any progress on this?

**Comment by splewis** [comment]
Mostly implemented on the [player-names](https://github.com/splewis/get5/tree/force-names) branch. I didn't finish managing to block the "X changed name to Y" in the chat area (hence the random Event_TextMsg function). 

If someone wants to finish it based on that branch, I'd encourage them do so!

**Comment by splewis** [comment]
Looks like I can just use the new sv_load_forced_client_names_file command: http://blog.counter-strike.net/index.php/2017/10/19582/

**Comment by PopiCSGO** [comment]
So that is somehow going to be intergrated to this plugin? Sounds cool.

**Comment by Technoblazed** [comment]
But then it’s a case of, would the plugin write the file by itself when the config is read, because that’d probably be the suitable option

**Comment by splewis** [comment]
Done.
