### ISSUE TITLE
Pause not working properly

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#107]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Max Pause count showing in wrong format. Instead of decreasing it is increasing in Number while saying number of Pauses Left , Max Pause Time currently not working , had 300 but did not work. 

While using Pause it shows like 
Max Pause = 3
You have 1 Pause Remaining for this match 
And again Pause
You have 2 Pause Remaining for this match
And again Pause
You have 3 Pause Remaining for this match 

And 4th time when written !pause , it says your team has used all pause for this match. 

### Steps to reproduce
- Plugin version: 0.5.0
- Sourcemod version: 1.8.0.5947

**Comment by splewis** [comment]
You should clarify what cvars you set. For the pause time, ``get5_max_pause_time`` only has an impact if ``get5_fixed_pause_time`` is set to 1.

**Comment by splewis** [comment]
I've fxied some pausing issues, but I don't specifically know if I resolved your issue. Can you try a more recent version (either compiled by you or from https://ci.splewis.net/job/get5/lastStableBuild/)?

**Comment by splewis** [comment]
Sorry, I realize I misspoke when I said
> get5_max_pause_time only has an impact if get5_fixed_pause_time is set to 1.

That's not true. It's the opposite - it only has in impact if it's set to 0 (the default).

**Comment by splewis** [comment]
Closing since I'm not aware of any bugs in the pausing system indicated in the original post. Feel free to reopen if you think there is still a bug.
