### ISSUE TITLE
Implementation of new BoX cvars.

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#108]
Adding these would be pretty cool, – Added convars mp_teamscore_max, mp_teamscore_1, mp_teamscore_2 to display best of N maps series in the spectator UI.

**Comment by splewis** [comment]
I'd gladly start setting those cvars, but I haven't managed to actually see what they looked like. I did a brief test where I set all the mp_team* cvars and looked in GOTV and didn't see any change from the Bo-X  cvars.

**Comment by splewis** [comment]
Actually I found someone got it to work: https://m.imgur.com/a/rM8Ce

I'm guessing it requires the mp_teammatchstat cvars to be clear. ("")

**Comment by splewis** [comment]
It looks like they are only displayed if mp_teammatchstat_txt is clear.

I'll add support for setting these.

**Comment by splewis** [comment]
Added
