### ISSUE TITLE
!unpause not working

### ISSUE THREAD

**Issue by jongcs** [splewis/get5#109]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When type !unpause in chat, the pause will be cancel.

### Actual behavior
I typed !unpause in chat,and countdown still running.

### Steps to reproduce
- Plugin version: 0.5.0
- Sourcemod version: 1.8.0.5969

**Comment by Technoblazed** [comment]
Vaguest description ever. 

!pause followed by !unpause works fine, provide more information.

**Comment by jongcs** [comment]
There is my pause config.
```
get5_max_pauses "2"
get5_reset_pauses_each_half` "0"
get5_fixed_pause_time` "120"
get5_max_pause_time` "0"
get5_pausing_enable` "1"
```
Is !unpause not working when ``get5_fixed_pause_time`` set to non-zero?

**Comment by Technoblazed** [comment]
get5_fixed_pause_time has no effect, unless get5_max_pause_time is set to 1

**Comment by splewis** [comment]
I believe this is because of ``get5_max_pause_time 0``. It doesn't respect the cvar description of 0=unlimited.

**Comment by splewis** [comment]
Also, fixed pause time means that the length of a pause is fixed at a certain value. You aren't supposed to be able to unpause.

**Comment by splewis** [comment]
I fixed some confusing behavior and messaging. You could try a newer build from https://ci.splewis.net/job/get5/lastStableBuild/ if you'd like.

But your specific issue of "I set fixed pause time, and can't unpause" is working as intended.
