### ISSUE TITLE
Not possible to join server with `get5_check_auths` enabled in latest master

### ISSUE THREAD

**Issue by miped** [splewis/get5#112]
### Expected behavior
Adding a player with a correct steam id to the list of players should allow that player to connect to the server and be placed on the right team (or spec).

### Actual behavior
Getting kicked regardless of format of steam id, or how it was added (in match.json or with `get5_addplayer`)

### Steps to reproduce
- Plugin version: master (10032f363d065740190a413b375915f4cf0319c6)
It works with latest release though (0.5.0, no other changes to configs or server), but we were trying master to see the pause time changes.

My guess is that it's this commit which did it: https://github.com/splewis/get5/commit/f38cf99ab4a4140d6069114b8f850776cfd96632

**Comment by Walks2000** [comment]
Yeah if I leave it enabled then everyone is currently getting kicked even players on team 1 because they are not a player in the match.

**Comment by splewis** [comment]
I've reverted that commit. I was originally trying to suppress error logs when it tried to get a steamid for bots, but that change broke things for players not in-game yet (aka every player when joining) - I should've use IsFakeClient. Should be fixed now.

**Comment by TandelK** [comment]
That is what i was thinking with pausing, i installed the lastest build you gave me the link . Will check out new 0.5.1 version soon.
