### ISSUE TITLE
Feature request: log in several users when get5_kick_when_no_match_loaded is set to 1

### ISSUE THREAD

**Issue by jfkz** [splewis/get5#113]
When `get5_kick_when_no_match_loaded` is set to `1` some users may log in to server. 
SteamIDs is have to be defined in get5.cfg.

**Comment by TandelK** [comment]
I think you might be talking specially for Admins , i think that feature would be way better if they are admins with specific flags they should be allowed to join even without match setup but only in Spectators list, if Players they have to be done via Panel

**Comment by jfkz** [comment]
Yeah that's may be too.

**Comment by splewis** [comment]
I think it'd be fine to have some form of admin immunity for not getting kicked on joining with no match setup. It would probably just require the changemap flag (g) like the other admin commands.

**Comment by TandelK** [comment]
I would recommend only Z flag , as any admins / Reserved Slots people can also join in middle of the match

**Comment by Technoblazed** [comment]
The changemap flag would be fine, either that or just make it a config to set the flag required to ignore the filter.

**Comment by TandelK** [comment]
Yeah @Technoblazed That would be way better .
