### ISSUE TITLE
[BUG] Changing players score info

### ISSUE THREAD

**Issue by Qevix** [splewis/get5#115]
It's changing the score at lasts rounds.

### Expected behavior
[Get5] Qba 2 - 1 Qevix
[Get5] Qba 2 - 2 Qevix
[Get5] Qba 3 - 2 Qevix
[Get5] Qba 4 - 2 Qevix
[Get5] Qba has won the match.

### Actual behavior
[Get5] Qba 2 - 1 Qevix
[Get5] Qba 2 - 2 Qevix
[Get5] Qba 2 - 3 Qevix
[Get5] Qba 2 - 4 Qevix
[Get5] Qevix has won the match.

### SOME LOGS:
L 02/25/2017 - 22:32:56: World triggered "Round_Start"
L 02/25/2017 - 22:33:04: "Kuba<4><STEAM_1:0:135102578><CT>" [-121 -1232 26] killed "Qevix [α]<3><STEAM_1:0:102172251><TERRORIST>" [551 -634 103] with "mp9"
L 02/25/2017 - 22:33:04: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "victim": "Qevix [α]<3><STEAM_1:0:102172251><>",
        "map_number": 1,
        "attacker": "Kuba<4><STEAM_1:0:135102578><>",
        "headshot": 0,
        "weapon": "mp9"
    },
    "matchid": "matchid",
    "event": "player_death"
}
L 02/25/2017 - 22:33:04: Team "CT" triggered "SFUI_Notice_CTs_Win" (CT "2") (T "0")
L 02/25/2017 - 22:33:04: Team "CT" scored "2" with "1" players
L 02/25/2017 - 22:33:04: Team "TERRORIST" scored "0" with "1" players
L 02/25/2017 - 22:33:04: World triggered "Round_End"
L 02/25/2017 - 22:33:04: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "winner_side": "CT",
        "map_number": 1,
        "team1_score": 2,
        "winner": "team1",
        "team2_score": 0
    },
    "matchid": "matchid",
    "event": "round_end"
}
L 02/25/2017 - 22:33:12: World triggered "Round_Start"
L 02/25/2017 - 22:33:19: "Qevix [α]<3><STEAM_1:0:102172251><TERRORIST>" [442 -599 33] killed "Kuba<4><STEAM_1:0:135102578><CT>" [350 -673 97] with "mp9"
L 02/25/2017 - 22:33:19: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "victim": "Kuba<4><STEAM_1:0:135102578><>",
        "map_number": 1,
        "attacker": "Qevix [α]<3><STEAM_1:0:102172251><>",
        "headshot": 0,
        "weapon": "mp9"
    },
    "matchid": "matchid",
    "event": "player_death"
}
L 02/25/2017 - 22:33:19: Team "TERRORIST" triggered "SFUI_Notice_Terrorists_Win" (CT "2") (T "1")
L 02/25/2017 - 22:33:19: Team "CT" scored "2" with "1" players
L 02/25/2017 - 22:33:19: Team "TERRORIST" scored "1" with "1" players
L 02/25/2017 - 22:33:19: World triggered "Round_End"
L 02/25/2017 - 22:33:19: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "winner_side": "T",
        "map_number": 1,
        "team1_score": 2,
        "winner": "team2",
        "team2_score": 1
    },
    "matchid": "matchid",
    "event": "round_end"
}
L 02/25/2017 - 22:33:27: World triggered "Round_Start"
L 02/25/2017 - 22:33:32: "Qevix [α]<3><STEAM_1:0:102172251><TERRORIST>" [171 -333 38] killed "Kuba<4><STEAM_1:0:135102578><CT>" [814 -1460 95] with "mp9" (headshot)
L 02/25/2017 - 22:33:32: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "victim": "Kuba<4><STEAM_1:0:135102578><>",
        "map_number": 1,
        "attacker": "Qevix [α]<3><STEAM_1:0:102172251><>",
        "headshot": 1,
        "weapon": "mp9"
    },
    "matchid": "matchid",
    "event": "player_death"
}
L 02/25/2017 - 22:33:32: Team "TERRORIST" triggered "SFUI_Notice_Terrorists_Win" (CT "2") (T "2")
L 02/25/2017 - 22:33:32: Team "CT" scored "2" with "1" players
L 02/25/2017 - 22:33:32: Team "TERRORIST" scored "2" with "1" players
L 02/25/2017 - 22:33:32: World triggered "Round_End"
L 02/25/2017 - 22:33:32: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "winner_side": "T",
        "map_number": 1,
        "team1_score": 2,
        "winner": "team1",
        "team2_score": 2
    },
    "matchid": "matchid",
    "event": "round_end"
}
L 02/25/2017 - 22:33:40: World triggered "Round_Start"
L 02/25/2017 - 22:33:47: "Kuba<4><STEAM_1:0:135102578><CT>" [-83 -1723 24] killed "Qevix [α]<3><STEAM_1:0:102172251><TERRORIST>" [753 -87 91] with "mp9"
L 02/25/2017 - 22:33:47: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "victim": "Qevix [α]<3><STEAM_1:0:102172251><>",
        "map_number": 1,
        "attacker": "Kuba<4><STEAM_1:0:135102578><>",
        "headshot": 0,
        "weapon": "mp9"
    },
    "matchid": "matchid",
    "event": "player_death"
}
L 02/25/2017 - 22:33:47: Team "CT" triggered "SFUI_Notice_CTs_Win" (CT "3") (T "2")
L 02/25/2017 - 22:33:47: Team "CT" scored "3" with "1" players
L 02/25/2017 - 22:33:47: Team "TERRORIST" scored "2" with "1" players
L 02/25/2017 - 22:33:47: World triggered "Round_End"
L 02/25/2017 - 22:33:47: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "winner_side": "CT",
        "map_number": 1,
        "team1_score": 2,
        "winner": "team2",
        "team2_score": 3
    },
    "matchid": "matchid",
    "event": "round_end"
}
L 02/25/2017 - 22:33:55: World triggered "Round_Start"
L 02/25/2017 - 22:33:57: "Kuba<4><STEAM_1:0:135102578><CT>" [48 -1920 29] killed "Qevix [α]<3><STEAM_1:0:102172251><TERRORIST>" [-32 361 102] with "mp9" (headshot)
L 02/25/2017 - 22:33:57: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "victim": "Qevix [α]<3><STEAM_1:0:102172251><>",
        "map_number": 1,
        "attacker": "Kuba<4><STEAM_1:0:135102578><>",
        "headshot": 1,
        "weapon": "mp9"
    },
    "matchid": "matchid",
    "event": "player_death"
}
L 02/25/2017 - 22:33:57: Team "CT" triggered "SFUI_Notice_CTs_Win" (CT "4") (T "2")
L 02/25/2017 - 22:33:57: Team "CT" scored "4" with "1" players
L 02/25/2017 - 22:33:57: Team "TERRORIST" scored "2" with "1" players
L 02/25/2017 - 22:33:57: World triggered "Round_End"
L 02/25/2017 - 22:33:57: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "winner_side": "CT",
        "map_number": 1,
        "team1_score": 2,
        "winner": "team2",
        "team2_score": 4
    },
    "matchid": "matchid",
    "event": "round_end"
}
L 02/25/2017 - 22:33:57: Game Over
L 02/25/2017 - 22:33:57: get5_event: {
    "params": {
        "map_name": "aim_mp9_dust",
        "map_number": 2,
        "team1_score": 2,
        "winner": "team2",
        "team2_score": 4
    },
    "matchid": "matchid",
    "event": "map_end"
}
L 02/25/2017 - 22:33:57: World triggered "Round_Start"
L 02/25/2017 - 22:34:35: [META] Loaded 0 plugins (1 already loaded)
L 02/25/2017 - 22:34:35: [META] Loaded 0 plugins (1 already loaded)
L 02/25/2017 - 22:34:35: Log file closed

### MATCH SETTINGS
"Match"
{

    "maps_to_win"       "2"
    "skip_veto"     "0"
    "side_type"     "always_knife"

    "maplist"
    {
        "aim_9h_ak"      ""
        "aim_glockon"      ""
        "aim_deagle"      ""
        "awp_arena"     ""
        "aim_map_p250"       ""
		"aim_mp9_dust"       ""
		"aim_usp_2016"       ""
    }

    "players_per_team"      "1"

    "team1"
    {
        "fromfile"      "get5/gracze/qba.cfg"
    }

    "team2"
    {
        "fromfile"      "get5/gracze/qevix.cfg"
    }

    "cvars"
    {
        "hostname"      "PLHC 1vs1 BO3 @pukawka.pl"
    }
}

### Steps to reproduce
[live.cfg.txt](https://github.com/splewis/get5/files/801531/live.cfg.txt)

- Plugin version: get5_0.5.1
- Sourcemod version: Metamod 1.10.7-git952 + SourceMod 1.8-git5970

**Comment by EAbychkov** [comment]
The same issue, also if u will use !SWAP command, as a result, you'll get wrong winner team.

**Comment by PhlexPlexico** [comment]
This issue is rather old, and we had a similar one pop up in #768 - I'm going to close this now and if there is anymore issues, either re-open this one or comment on the other so we can re-open and continue to investigate.
