### ISSUE TITLE
APIStats Plugin not able to create Logo Directory

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#116]
### Expected behavior
After Uploading Logo to Web Server and calling all the Matches from Get5-web , Logos of the teams should be shown properly and should work in game also. 

### Actual behavior
Get error regarding Creating Logo Directory in Console. 

### Steps to reproduce
- Plugin version: Get5 - v0.5.1
- Sourcemod version:

**Comment by Technoblazed** [comment]
- Check file permissions to the folder
- `Get error regarding Creating Logo Directory in Console.` - Well what is the error?

**Comment by splewis** [comment]
"Get error regarding Creating Logo Directory in Console."

Client console error? Server error? What is the error?

**Comment by TandelK** [comment]
I am not using Linux  system , what i saw from the Scripting of APIStats is it uses File Permissions of Linux, I already created manually the folder path defined in the script and seems to be working fine now. I am closing the Issue.
