### ISSUE TITLE
Feature Request: Add optional Damage Printing support

### ISSUE THREAD

**Issue by atrefz** [splewis/get5#117]
An option for damage printing (either in the console or in the Chat similar to ESEA) would be great. I would gladly attempt to write a PR for that, if you can give me some pointers on where to start.

**Comment by Technoblazed** [comment]
Check github.com/splewis/sm-misc and compile the damage printer

**Comment by atrefz** [comment]
I found that, but refrained from using that particular plugin, since the readme warned of the fact that there is no stable release, and also because I feared for unforseen interactions. If they are intended to be used together, then you can consider this issue closed, though maybe you could update the documentation here to point towards those plugins and be explicit about the support for them.

**Comment by Technoblazed** [comment]
Until it's directly implemented, the other plugin works fine. Its the same as the pug setup version with all of the dependencies removed.
