### ISSUE TITLE
Add option for waiting on spectator ready up

### ISSUE THREAD

**Issue by splewis** [splewis/get5#118]

**Comment by miped** [comment]
Hmm, this seems to be mostly implemented, except for a config to actually turn it on?

**Comment by splewis** [comment]
It still needs some extra logic to check if MatchTeam_TeamSpec is ready: see https://github.com/splewis/get5/blob/master/scripting/get5/readysystem.sp#L124

**Comment by miped** [comment]
Ok, i'll take a look at it tomorrow and see if i can get it ready for use.

**Comment by splewis** [comment]
Fixed by #127
