### ISSUE TITLE
BO3 or BO5 with map advantage

### ISSUE THREAD

**Issue by miped** [splewis/get5#119]
We'd like a way to do a 1 map advantage when doing a BO3 or a BO5. Currently, we've tried using series_score in the team settings to do this, but it interferes with veto's in a funky way. So this is a proposal for a couple of different ways to get around this.

Sorry in advance for the wall of text :-)

Current issue with using series_score for advantage:
----------------------------------------------------
Since the first map is the one being skipped, if you give the higher seeded team the first veto this is what will go down:

 - Map1 banned (team1)
 - Map2 banned (team2)
 - Map3 picked (team1) -- NOT PLAYED
 - Map4 picked (team2) -- PLAYED FIRST

Thus, there is no advantage to vetoing first, as you won't get to play your pick first, and if you don't know how what will happen, you'll be confused when your first pick isn't played.

If you give the lower seeded team the first veto, in order to let the higher seeded team play their pick first, it looks like this:

 - Map1 banned (team2)
 - Map2 banned (team1)
 - Map3 picked (team2) -- NOT PLAYED (essentially a third ban!)
 - Map4 picked (team1) -- PLAYED FIRST

So while the higher seeded team do get the benefit of playing their map choice first, the lower seeded team now gets 2 bans instead of one, and they could potentially choose a map to skip that they know the higher seeded team would prefer to play.

Issues with using series_score as a backup solution:
----------------------------------------------------
If you do want to use series_score as a backup solution you'd need to:

 - Turn off vetos (works)
 - Select exactly the map list to be played (including the maps to skip) (works)
 - Unless you use `always_knife` as your side type, you'd need to specify which side each team starts on the same way as they chose in their veto (not possible)

Since it's not possible to specify sides I would argue that it has limited use as a backup solution.

So, with that out of the way, and after looking through the code, i think there are a couple of ways to make this work better as a solution for map advantage

Proposal 1
----------
This is the simplest of the options, since it will reuse most of the current series_score functionality.

Basically, it will add this little piece of logic to the veto process (after vetoing is complete):
```
maplist = <finished map list>
total_series_score = team1_score + team2_score
for i = 0; i < total_series_score; i++:
    # get the last map in the map list to play
    last_map = maplist.pop()
    # put it in the front of the list
    maplist.shift(last_map)
```

This will make sure that the maps that will be skipped are the ones that were picked last (or the left over map). For the BO3 case, it would make sense to just skip the last 2 bans, since they won't have any impact anyway.

For example, a veto that goes like this:

 - Map1 ban (team1)
 - Map2 ban (team2)
 - Map3 pick (team1)
 - Map4 pick (team2)
 - Map5 pick (team1)
 - Map6 pick (team2)
 - Map7 left

Will result in this play order:

 - Map7 -- SKIPPED
 - Map3 (team1)
 - Map4 (team2)
 - Map5 (team1)
 - Map6 (team2)

It should work well, because if you're using series_score for manual backup, you should not be using vetos too (as the maplist has already been decided). And if you ARE using vetos, then the teams should be trying to veto exactly as they did before, thus resulting in the same play order.

Proposal 2
----------
Add a setting to each team called `advantage` which should be a number of maps. Make it work pretty much like the proposal above, and make it work in addition to the `series_score`. Thus, if you have a series score of 1, and advantage of 1, then 2 maps will be skipped. However, only the advantage maps will influence the veto (as described above), which means that you can get the backup solution by either turning off veto, or telling teams to veto exactly as they did before.

The downside here is that I think this might be unnecessarily complex, and there's a lot of interactions that would need to be tested.

Proposal 3
----------
Add a setting on the root level which is called `advantage` taking a string of either `team1`, `team2` or `none` (default). Use this to adjust the `series_score` on match config load, and also trigger the logic described above for shifting the maps around so the veto works as expected.

The upside of this is that it's almost as simple as the first option, the downside is that it only allows for an advantage of 1. It could be argued that an advantage of > 1 doesn't make a lot of sense until you get into BO7 territory, but it would be nice to keep it flexible.

Moving Forward:
---------------
I'd be ready to implement any of these solutions, but i obviously prefer the first one :-)

Please let me know what you think.

**Comment by splewis** [comment]
I agree the current capability is limited. As for backups, you technically can set the backup sides manually, though it's not well documented: see how "[map_sides](map_sides)" works.

I agree with proposal 1, mainly because it avoids having to add a new ``advantage`` key to the match configs. Thanks for the effective writeup :)

**Comment by miped** [comment]
Ahh yeah i see. Cool.

I'll take a stab at implementing proposal 1

**Comment by miped** [comment]
After having a functional version of proposal 1, i'm not sure it's the right way to go. The reason being that i don't think this solution meshes well with the events being sent, and the stats plugin.

When the MapPicked and MapVetoed events are sent, the map numbers will be off by the series score. Currently they aren't used in the plugin itself, but if anything external uses it, it will get messy. This could easily be fixed by adding the current series score to the map number being sent. But then the problem becomes that the maps picks will arrive out of order.

Another issue related to stats is that the mapstart and mapend events are never sent for the maps that get skipped. This means that advantage will need to be handled entirely on the mysql/web api side.

The fix for these issues depends entirely on how we believe that map advantage should be handled from a stats and api point of view.
