### ISSUE TITLE
Maintaining two sets of matchconfig loaders

### ISSUE THREAD

**Issue by miped** [splewis/get5#128]
This is just an idea, but since the smjansson extension is optional, would it make sense to just convert the json to KeyValue format and then only having a single match config load function?

Idea is basically this:
 1. See if we got json (already does this)
 2. Generically convert that json into KeyValue format, without checking anything related to match config format (basically a loop with some if statements for the type of the values)
 3. Use a single method to load (and validate) the match config

The only datatype which doesn't fit neatly from json to KeyValue is an array, but that can be fixed by using empty values as the current `players` key in KeyValue works, or by just using an incrementing index starting from `0` as the key.

**Comment by splewis** [comment]
This sounds like it would be a great idea.
