### ISSUE TITLE
get5_addplayer not working correctly

### ISSUE THREAD

**Issue by techlover1** [splewis/get5#13]
When I try to add a steamid to a team, it returns unknown team.

rcon get5_addplayer STEAM_1:1:48254312 team1
Unknown team: must be one of team1, team2, spec

Same results whether I use team1, team2, or spec

**Comment by splewis** [comment]
instead of 
``get5_addplayer STEAM_1:1:48254312 team1``
use
``get5_addplayer "STEAM_1:1:48254312" team1``

The colons cause it the steamid string to be considered different arguments.

**Comment by techlover1** [comment]
Same thing:
] rcon get5_addplayer "STEAM_1:1:48254312" team1
Unknown team: must be one of team1, team2, spec

**Comment by splewis** [comment]
Seems like a limitation with the game's rcon command and how arguments are being parsed. Not sure if there's a workaround. The command works fine when being run on the server directly.

**Comment by ragnos** [comment]
Would it be possible to use steam64 instead of classic steam ids? I guess it's easier to handle that single integer via rcon.

**Comment by splewis** [comment]
Yes, but would require a way of converting between ids / otherwise managing them, which I don't know how to do. Ideally there would be a way to which format an arbitrary id string is in and convert between them so any of them could be used.

**Comment by ragnos** [comment]
[There you go i guess](https://forums.alliedmods.net/showpost.php?p=2231850&postcount=2), doesn't look that hard tbh. Also i thought about this as a simple Workaround for this rcon issue, convert steam64 to steamClassic and continue with get5_addplayer like before.

**Comment by splewis** [comment]
I'm working on some changes to allow any form of steamid as input (in either this command or the match config files), where they are all internally stored via steam64 format. 

This would help the original issue here by letting you use the steam64 id instead of something with colons in it.

**Comment by splewis** [comment]
I've merged the changes to allow input steamids in any format. So you could do the following now:

``rcon get5_addplayer 76561198056774353 team1``

**Comment by techlover1** [comment]
Works perfectly. Consider this issue resolved
