### ISSUE TITLE
Wrong winner team in case of !swap

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#130]
### Expected behavior
1) Team1(CT) won Team2(T) in a KnifeRound
2) Team1 used !swap command
3) Team1 become(T) and Team2 become (CT)
4) Team1 won the match
5) Got message about winning and log like "Team1 is a winner or something like this" 

### Actual behavior
1) Team1(CT) won Team2(T) in a KnifeRound
2) Team1 used !swap command
3) Team1 become(T) and Team2 become (CT)
4) Team1 won the match
5) **WINNER IS TEAM2** like there was no swap command, also wrong winner team in the log message!

### Steps to reproduce
Please use Expected behavior section

- Plugin version: 0.5.1
- Sourcemod version: 1.8 build 5977

**Comment by miped** [comment]
There's been some updates on master to the team winning logic in the last couple of days. I'll test this with the latest build.

**Comment by EAbychkov** [comment]
Ok, thanks, feels like this is critical and easy to fix bug.

**Comment by splewis** [comment]
> Plugin version: 0.5.1

If that's correct then this wouldn't have anything to do with the recent changes. Can you post the match config you used, and I'll try to reproduce on 0.5.1 & current head? (feel free to remove steamids/names, I'm interested in any sides/map settings)

**Comment by EAbychkov** [comment]
Nothing really special, but anyway... please check this out
[match.txt](https://github.com/splewis/get5/files/867359/match.txt)

**Comment by splewis** [comment]
Your match config shows "veto_first". That wasn't added until recently, after 0.5.1. What version are you using? It's very difficult to reproduce issues unless you give an accurate version number (or commit/build number).

**Comment by miped** [comment]
I just came home from running a 18 team lan, where we ran 55 matches, of which only 3 wasn't using knife for sides. Didn't have a single match get reported incorrectly.

This is from the latest master.

**Comment by EAbychkov** [comment]
@miped Did they use !swap command?

**Comment by miped** [comment]
Yes, it was available to the team. I did not track specific usage of it, but i saw several teams use it, and i didn't get a single report about misreported scores.

**Comment by EAbychkov** [comment]
![wrongwinner](https://cloud.githubusercontent.com/assets/1067550/24401083/95e164c6-13bb-11e7-8454-4f86ce662faa.png)

Please check this out. 
Just tested with the latest version.

**Comment by splewis** [comment]
I've added some extra debug logging in 14359de35ab2ff897d1981b6e4cae983c399aaaf that may help me figure this out. If set the ``get5_debug`` cvar to 32 (see the values [here](https://github.com/splewis/get5/blob/master/scripting/include/logdebug.inc#L31)), it will record to a log file in addons/sourcemod/logs. If you can rereun this test with this extra logging, it would help.

My theory: the plugin is trying to do a "side swap" (probably from [this](https://github.com/splewis/get5/blob/14359de35ab2ff897d1981b6e4cae983c399aaaf/scripting/get5.sp#L1072)). If that code I linked is the cause, it's probably a good idea to change the overtime detection to something like checking the gamerules value ``m_bInOvertime`` or ``m_nOvertimePlaying``.

**Comment by EAbychkov** [comment]
yes , mp_maxrounds = 10 
Maybe if I will add "mp_halftime 1" it fix the issue?

**Comment by miped** [comment]
So you have halftime set to 0, meaning there's no countdown at halftime at all?

**Comment by EAbychkov** [comment]
As I understand mp_halftime 1 mean that of the middle of the match teams will change their sides. But despite using this the winner team have to be specified correctly. 
When I tested this I had mp_halftime 0.(not sides changes) and I got wrong winner team. I just assumed if teams will switch their sides winner team supposedly can become correct.

**Comment by miped** [comment]
Ah yeah i see the problem. I guess since you're doing aimmaps, you're not concerned about switching sides as most of them are symmetrical.

What happens is that you hit this condition: https://github.com/splewis/get5/blob/14359de35ab2ff897d1981b6e4cae983c399aaaf/scripting/get5.sp#L1066, which triggers this: https://github.com/splewis/get5/blob/14359de35ab2ff897d1981b6e4cae983c399aaaf/scripting/get5.sp#L960, in turn triggering this: https://github.com/splewis/get5/blob/14359de35ab2ff897d1981b6e4cae983c399aaaf/scripting/get5.sp#L1083

That function then swaps get5's internal bookkeeping of scores, but since there wasn't actually a side swap event, it's now wrong.

@splewis I think we just need at add a check for mp_halftime being 0 in the `Event_RoundEnd` handler, right?

**Comment by splewis** [comment]
Yes... not having halftime is going to break things. That would have been very useful reproduction info.

@miped Exactly. Ideally the teamswap logic would be smarter - but I never managed to find another reliable event for checking when teams swapped (I see [halftime_start](https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#start_halftime) now, I don't know if I've tried that or not). Your suggestion is fine for now, at least.

**Comment by miped** [comment]
hmm... i'll try and investigate the halftime_start event. It might be the case that setting the halftime to 0 seconds will make that not work either. Ideally we'd use whatever is the most correct one.

In the meantime, i suggest @EAbychkov to set `mp_halftime 1`, and set a very low number for `mp_halftime_duration`.

Also, considering the issue, this shouldn't only happen on !swap usage. I think it happens regardless.

**Comment by EAbychkov** [comment]
Thanks, mp_halftime 1 and game_mode 1 fixed the problem.

**Comment by splewis** [comment]
https://github.com/splewis/get5/commit/cc00ba4a4ad15b4de68eb88f0aee3d3bec50037a should've fixed the bug here. I think this is resolved.
