### ISSUE TITLE
get5_loadmatch does not work as a parameter

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#131]
### Expected behavior
Add '+get5_loadmatch match.json' as a parameter to my .bat starting file and it will load match.json file on the start. 
I also tried to put this command to autoexec.cfg and server.cfg - no result

### Actual behavior
You have to execute get5_loadmatch match.json command by hands. 

Plugin version: 0.5.1
Sourcemod version: 1.8 build 5977

**Comment by Technoblazed** [comment]
Fairly certain this is intended, but probably worth the issue anyway, in which situation would you want this as a launch option though?

**Comment by TandelK** [comment]
I think he better uses get5-web of Splewis. Also config files can be made easily in just 2 mins just need to execute them properly

**Comment by EAbychkov** [comment]
I would like to run multiple servers with different match.json files as a parameters automatically, using my self-written software. Is it possible to fix? Or I have to find some workaround?

**Comment by splewis** [comment]
This won't work because:
- get5_loadmatch is a command, not a cvar, so it won't work (as far as I know only cvars can be used this way)
- more importantly, when those command line args are executed sourcemod (and the plugin) hasn't  loaded

You should set the ``get5_autoload_config`` cvar in ``cfg/sourcemod/get5.cfg`` instead.

**Comment by EAbychkov** [comment]
Yes, this works, but not in my case. What if I want to start 10 srcds.exe instances for 10 servers with a different match.cfg files. How can I solve this?

**Comment by Technoblazed** [comment]
10 different match.cfg files:

match1.cfg
match2.cfg

Etc.

**Comment by EAbychkov** [comment]
Yes, but I can not use get5_autoload_config in this case. Anyway thanks, I already wrote some workaround.

**Comment by Technoblazed** [comment]
@EAbychkov, why can't you use it? That's EXACTLY why its there?

**Comment by EAbychkov** [comment]
But I can use only one  \csgo\cfg\sourcemod\get5.cfg file, therefore, I can specify only one get5_autoload_config command, but what if I want to run 10 games at the same time with different match.cfg
Do I miss something?

**Comment by Technoblazed** [comment]
Oh you're using the same instance, I see. 

The options for that would either be:

- Multiple sourcemod forks (Not Recommended)
- Manually executing the get5_loadmatch command
- Using get5-web
- Whatever work around you used

**Comment by EAbychkov** [comment]
Yes, the same instance, exactly. I already wrote some simple automation, so the problem is solved. Anyway thanks a lot for your effort.

**Comment by splewis** [comment]
I don't think there's anything get5 can do to make this easier then. Closing.

**Comment by algoth** [comment]
@EAbychkov Can you share more details about the workaround you used to run multiple instances on the same server? I am trying to do the same thing but cant find a way.

**Comment by saintplay** [comment]
@algoth I guess I'm trying to do the same thing...


I have multiple servers running, what I do is:

- use `rcon get5_endmatch` to end a match of one server
- create a `new_match.cfg`, I do this programmatically with my custom web app
- use `rcon get5_loadmatch new_match.cfg` on a "**free**" server
- use `rcon get5_endmatch` or wait the match to end
- and on and on
