### ISSUE TITLE
Wrong winner team in case of equal score. 

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#132]
### Expected behavior
In case of equal score, players will play until some team will win two rounds in a row.
### Actual behavior
In case of equal score, the winner is always Team2.

- Plugin version:  0.5.1
- Sourcemod version: 1.8 build 5977

**Comment by splewis** [comment]
This has been fixed for the next version: https://github.com/splewis/get5/commit/738f75975e11523fcf6d62e89c835cc98b4cf5e8 and https://github.com/splewis/get5/commit/f2a083bb04ab8100beb60cc22d9d219fcb29cff2.

**Comment by EAbychkov** [comment]
Just tested with the latest version, 
Got this logs:

03/28/2017 - 13:32:05: get5_event: {
    "params": {
        "map_name": "de_dust2",
        "winner_side": "CT",
        "map_number": 0,
        "team1_score": 5,
        "winner": "team1",
        "team2_score": 5
    },
    "matchid": "123",
    "event": "round_end"
}

03/28/2017 - 13:32:05: Game Over: casual mg_active de_dust2 score 5:5 after 5 mi
n

03/28/2017 - 13:32:05: get5_event: {
    "params": {
        "map_name": "de_dust2",
        "map_number": 1,
        "team1_score": 5,
        "winner": "none",
        "team2_score": 5
    },
    "matchid": "123",
    "event": "map_end"
}

![wrongwinnertied](https://cloud.githubusercontent.com/assets/1067550/24401270/5e0fd7a2-13bc-11e7-8d43-d02d0dcda773.png)

**Comment by EAbychkov** [comment]
Please check this out, is it possible to disable "tied" as a result of the match?

**Comment by Technoblazed** [comment]
Yeah, don't let the match tie. Add overtime.

**Comment by EAbychkov** [comment]
Sorry, but how add this? Just googled for it without any result ((

**Comment by EAbychkov** [comment]
Just found this
mp_overtime_enable 1
mp_overtime_maxrounds 6
mp_overtime_startmoney 10000
Thanks for your help, I hope this will work as expected.

**Comment by EAbychkov** [comment]
Lol, sorry for a lot of messages, but when I wanted to add this commands in my live.cfg I found they already been there. So obviously they do not work. Do I need some additional plugin to make them work?

**Comment by splewis** [comment]
No. You likely have some other installation issue - another set of cvars being executed, another plugin running, etc.

From your screenshot it looks like the server is launched in casual mode as well (game_mode 0 instead of 1), which might make weird things happen.

**Comment by EAbychkov** [comment]
Problem solved by settings game_mode 1 
Thanks a lot
