### ISSUE TITLE
"series_start" event never occurs

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#133]
### Expected behavior
"series_start" event raised at the beginning of the match (for instance when the first player connected)
### Actual behavior
"series_start" event never occurs

### Steps to reproduce
- Plugin version: latest (build #315 (24.03.2017 0:28:06))
- Sourcemod version: latest

**Comment by splewis** [comment]
I can't reproduce this, the event fired in my test; it fires when the match config is loaded: https://github.com/splewis/get5/blob/3c2b5e6d3c9617c04be8aed31475544e78c73dbf/scripting/get5/matchconfig.sp#L110

**Comment by EAbychkov** [comment]
Ohh sorry, my bad, am I understand this correctly, "series_end" will fire when the match is over, no matter how many maps I have (BO1, BO2 ...) it will fire **only one time** at the end just before kick all the players?

**Comment by miped** [comment]
Yes that's correct.

**Comment by splewis** [comment]
I think this is settled then.
