### ISSUE TITLE
Help needed: knife round not start after !ready

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#134]
I'll not say that this is a bug because there's a huge chance that the problem is something that I'm doing wrong. There's a few things about my game server. First, there are many errors on console when I run srcds_run that I don't know how to fix or if they are "normal" or "common" errors.

Some errors on srcds_run: https://pastebin.com/CFcm6Gmb
Then, after several logs of setting cvars, these errors are shown too: https://pastebin.com/xajwh57e

Just to notice, I've followed the SCRDS Steam Tutorial to create a Dedicated CS:GO server (https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers) - basically I've ran `./steamcmd.sh +login anonymous +force_install_dir ../server +app_update 740  validate +quit` - after it installed, I've followed your Step by step installation guide tutorial (https://github.com/splewis/get5/wiki/Step-by-step-installation-guide) and I'm on a Ubuntu 16.04, 64bit.

I really don't know if there's some connection between these errors and my actual issue. What happens to me is that, even if I set `"min_players_to_ready": 2` and `"side_type": "always_knife"` on `match.json`, the knife round never starts after all players (one on CT and other on TR - two players total) typed `!ready` on chat. I've tried to run the `get5_forceready` command, that shows a console message like "Some admin has readied all players/teams" but it did not work.

My match.json config file is: https://pastebin.com/bHwkyvHr

I have some other questions that, if you want, I can create another issue(s). But I'll listing here in case they are easily answered.

- If I create a server.cfg file on the `csgo/cfg` path with some cvars, they will be replaced by all the cvars on `match.json` section?
- What about all other configs that are on gamemodes configs (`gamemode_casual.cfg`, `gamemode_competitive.cfg`, etc). They are too replaced by the cvars `match.json` section?
- There's some option to force all players to be ready (for the knife round and for live) at the server start by default?

Sorry my bad english, feel free to correct me. :)
This is a awesome job that you're doing. You guys are the best! Thank you!

**Comment by Technoblazed** [comment]
- server.cfg file should contain your basic server information, hostname, rcon passwd etc.
- You should NOT edit `gamemode_competitive.cfg`, instead you should create a `gamemode_competitive_server.cfg`. Otherwise the file will wipe whenever there is a game update.
- You have 7 maps in your match.json, but have skip veto enabled, not even sure if that will work.

**Comment by gabrielfgularte** [comment]
Thank you @Technoblazed!

> server.cfg file should contain your basic server information, hostname, rcon passwd etc.
But if I put some cvars with different values on 

> You should NOT edit gamemode_competitive.cfg, instead you should create a gamemode_competitive_server.cfg. Otherwise the file will wipe whenever there is a game update.

**Comment by gabrielfgularte** [comment]
Thank you @Technoblazed!

> server.cfg file should contain your basic server information, hostname, rcon passwd etc.

But if I put some cvars with different values on `match.json` they will replace server.cfg cvars?

> You should NOT edit gamemode_competitive.cfg, instead you should create a gamemode_competitive_server.cfg. Otherwise the file will wipe whenever there is a game update.

Alright, thank you! I miss that. But the same question here. If I put some cvars with different values on `match.json` they will replace these `gamemode_competitive.cfg` cvars?

**Comment by Technoblazed** [comment]
> But if I put some cvars with different values on match.json they will replace server.cfg cvars?
For good practice, you shouldn't be using any cvars in your match.json as are defined in your server.cfg, your server.cfg is mainly for CORE server information such as hostnames and rates. Use the `gamemode_competitive_server.cfg` for your information instead.

> You should NOT edit gamemode_competitive.cfg, instead you should create a gamemode_competitive_server.cfg. Otherwise the file will wipe whenever there is a game update.

Yes, match.json will override.

**Comment by gabrielfgularte** [comment]
> Yes, match.json will override.

Thank you!

> I'll try let only one map in this section and make a test. Thank you!

That does not have worked =(

**Comment by gabrielfgularte** [comment]
> For good practice, you shouldn't be using any cvars in your match.json as are defined in your server.cfg, your server.cfg is mainly for CORE server information such as hostnames and rates. Use the gamemode_competitive_server.cfg for your information instead.

This was just a question in my head. I actually have no `server.cfg` and no `gamemode_competitive_server.cfg`. Just the raw srcds installation with get5 step by step installation tutorial. But thank you, anyway to advise me of that! =D

**Comment by Technoblazed** [comment]
If you're using linux, I'd recommend using Linux Game Server Manager as it's a hell of a lot easier to use:

https://gameservermanagers.com/lgsm/csgoserver/

**Comment by miped** [comment]
Your issue is that `min_players_to_ready` is players per team. Set it to 1 and you should be good.

**Comment by miped** [comment]
And i'll actually recommend something else than Linux Game Server Manager :-). Personally i like to start `srcds_linux` (not `srcds_run`) straight from a SystemD or Runit service. Proper service management and log handling basically for free. But that's mostly a matter of personal taste.

**Comment by Technoblazed** [comment]
@miped For someone starting new, LGSM is a great place to start. It's simple to use and straight forward if you configure it correctly through the csgoserver file :^)

**Comment by gabrielfgularte** [comment]
@Technoblazed 
> If you're using linux, I'd recommend using Linux Game Server Manager as it's a hell of a lot easier to use:

I was using it until last week, but I think I want more raw control over my resources. The LGSM is great for beginners (and I'm a beginner) but I really want to achieve the maximum of the game server with no abstractions. Thank you anyway.

@miped 
> Your issue is that min_players_to_ready is players per team. Set it to 1 and you should be good.

This was exactly my issue. Thank you very much. I'm talking with Vegim and he told me that you are friends. Glad to meet you.

I still have one question about get5, can you guys help me to answer it?

- There's some option to force all players to be ready (for the knife round and for live) at the server start by default?
- Can I change `!swap` command to use `!switch` instead? It's just for a convenience of my product. My clients already use `!switch` and make them learn a new commando may become a pain.

Also, do you guys have take a look onto my errors? There's something wrong or all of them are acceptable?

Thank you again! You guys rocks!

**Comment by Technoblazed** [comment]
> I really want to achieve the maximum of the game server with no abstractions

Could you elaborate?

**Comment by gabrielfgularte** [comment]
@Technoblazed Yes! Of course!

The LGSM adds a abstraction layer above the game server. This abstraction layer was very good on the very beginning. But with time, we found ourselves lost on files that we did not know if are created by Steam, by the CSGO installation or by LGSM.

So, to simplify all things and reach the limits of a raw srcds installation, we decide to put LGSM away for a while. If we reach some edge of functionality or any other limit, we will use it again.

To resume it, we want need it to use it. While we don't need it, we think we're cool with the raw installation resources.

**Comment by gabrielfgularte** [comment]
@Technoblazed 

> Edit get5.sp and duplicate https://github.com/splewis/get5/blob/master/scripting/get5.sp#L317 , duplicating that entire string, then change swap to switch.

Thank you!

**Comment by gabrielfgularte** [comment]
@Technoblazed There's no need to rebuild the plugin to generate a new `.smx`?

**Comment by Technoblazed** [comment]
You have to recompile the plugin if you edit the .sp, is it just the !switch change that you wanted?

**Comment by gabrielfgularte** [comment]
No. I need to make players automatic ready for knife and live. It's an easy change or demand heavy work?

**Comment by Technoblazed** [comment]
`rcon get5_forceready` ?

**Comment by gabrielfgularte** [comment]
There's a way to force it when ten server starts?

**Comment by Technoblazed** [comment]
May I ask what you're actually using this plugin for? Are you using it for PUGs, scrims, or matches ...

**Comment by gabrielfgularte** [comment]
I'm using it for PUGs. I'm building a service like Faceit. :)

**Comment by gabrielfgularte** [comment]
@Technoblazed 

> You have to recompile the plugin if you edit the .sp, is it just the !switch change that you wanted?

For now this will solve my bigger problem. The others are minor changes. I can do it later. :)

**Comment by Technoblazed** [comment]
For a service like faceit, you'd be better off leaving the ready system enabled. There's a feature within the plugin that forces the match to end if the teams do not join within the allotted time. You'd be better off taking advantage of that.

**Comment by gabrielfgularte** [comment]
Yeah, the "force ready" thing is not really important. But the "switch" is. Thank you!

**Comment by miped** [comment]
@gabrielfgularte I'd agree with @Technoblazed here. I recently did a bit of an overhaul of the ready system, and it's a very central part of the plugin. If you want to disable it completely, you're probably better off forking and stripping down get5 for your specific purposes.

Another possible solution is that you listen to the logs that srcds can send over udp (or query the server say every 5-10 seconds, issuing a `get5_status` and looking at how many players are connected from each team), and once you have the right number of players, you issue a `get5_forceready` command over rcon. There are ready to use rcon libraries out there, and it's fairly easy to implement your own as well.

**Comment by gabrielfgularte** [comment]
Alright! Thank you!!!

**Comment by splewis** [comment]
> You have 7 maps in your match.json, but have skip veto enabled, not even sure if that will work.

It should work just fine. Most of my manual testing involves that scenario.

As for the ready stuff, I'd note that the README does specifically state:
> No, it is not recommended for your new matchmaking service. It is intended for competitive play, not pickup games.

So supporting this type of use case isn't really important to me. That said, my guess is that it's probably not *that* hard to have a cvar/matchconfig variable that could disable it. I'd be fine with that being added if the code changes were minor, but it's not something I ever planned on adding.

**Comment by gabrielfgularte** [comment]
Thank you! So, I will duplicate swap line to make a switch command. This is my main issue by now. Can I ask you how I can rebuild get5 without have to reinstall it?

**Comment by Technoblazed** [comment]
https://wiki.alliedmods.net/Compiling_SourceMod_Plugins

**Comment by gabrielfgularte** [comment]
I just need to drag `get5.sp` to the `sourcemod/scripting` folder and run `compile.sh`. Is that right?

**Comment by Technoblazed** [comment]
If you're using linux, move the get5.sp into the folder, including ALL includes that are required with the plugin, then run the compile script.

**Comment by gabrielfgularte** [comment]
If I have a fork (and I have). How can I build the plugin locally (in Linux, of course)?

**Comment by gabrielfgularte** [comment]
> If you're using linux, move the get5.sp into the folder, including ALL includes that are required with the plugin, then run the compile script.

I've tried it but it shows a message saying that it haven't found `system2`. I don't know where to find this `system2` and put it on the include folder. =/

**Comment by Technoblazed** [comment]
It's usually easier to compile it on your computer using windows before uploading it, but that's my preference. Alternatively, the sourcemod post listed before should clearly explain it :^)

**Comment by gabrielfgularte** [comment]
Thank you @Technoblazed. You guys are amazing! Thank you all for your support. I'm closing this issue. =D
