### ISSUE TITLE
Server is configured to load a map but client says it is loading another

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#139]
I've set my server to load "de_cache" but some clients shows "de_dust" on "Loading World Page". At the end of loading, it loads the right map (de_cache).

I don't know if it is a get5 bug, but I'd never seen this before using it.

Maybe is something that I'm doing wrong?

**Comment by splewis** [comment]
This happens often when the server changes map while the client is still connecting, although I suspect it can happen in some other circumstances.

Can you reproduce this? How are you loading the configs?

**Comment by gabrielfgularte** [comment]
> Can you reproduce this? How are you loading the configs?
Yep. this is happening all the time that I start the server. Umm... I have server.cfg, gamemode_competitive_server.cfg and four get5 configs (get5.cfg, live.cfg, warmup.cfg and knife.cfg). Do you want to see them?

**Comment by Technoblazed** [comment]
Quick question, are you using workshop by chance?

**Comment by gabrielfgularte** [comment]
> Quick question, are you using workshop by chance?

Yes. I'm using workshop. Well, at least, I think I'm using. All that I've done was installed it as your "Step by Step guide" suggests. :)

**Comment by Technoblazed** [comment]
The step by step guide doesn't use workshop by default, can you confirm in which ways you would think you are using the workshop?

**Comment by gabrielfgularte** [comment]
Sorry, I'm not using Workshop. I'm using Steamworks, as the step by step guide optionally says. I have no idea if I'm using workshop and I haven't modified any cvar related to it.

Thank you and sorry. :)

**Comment by splewis** [comment]
The more info the better. All those configs would be nice. My testing would likely just be copying them all, then removing them with the default config 1 at a time seeing if the issue persists.

Users using workshop collections would be using the launch options described in https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators

**Comment by TandelK** [comment]
Can you put your start line here without Auth of IP and other Things like sv_setsteamaccount and i can help you out with also console.log which will be way better

**Comment by gabrielfgularte** [comment]
Hi guys, ok.

> Can you put your start line here without Auth of IP and other Things like sv_setsteamaccount and i can help you out with also console.log which will be way better

Of course, here is it:
`./srcds_run -console -game csgo -usercon -strictportbind -ip 0.0.0.0 -port 27015 +clientport 27005 +tv_port 27020 +sv_setsteamaccount XXXXXX -tickrate 128 +game_mode 1 +game_type 0 +host_workshop_collection +workshop_start_map -authkey`

**Comment by Technoblazed** [comment]
`+host_workshop_collection +workshop_start_map -authkey` isnt required if you're not specifying any variables for them.

**Comment by gabrielfgularte** [comment]
> +host_workshop_collection +workshop_start_map -authkey isnt required if you're not specifying any variables for them.

Thank you. I'll remove those params.

**Comment by gabrielfgularte** [comment]
> My testing would likely just be copying them all, then removing them with the default config 1 at a time seeing if the issue persists.

I'll try that. It can be a client issue or some client cache? I've figured out that only one machine is having this problem...

**Comment by gabrielfgularte** [comment]
Anyway, these are my configs:

https://pastebin.com/sFbEgF01 (match.json)
https://pastebin.com/RSrQGLde (gamemode_competitive_server.cfg)
https://pastebin.com/xYZZ30WK (server.cfg)
https://pastebin.com/Pmc6Jzut (get5.cfg)
https://pastebin.com/MxyV7kRf (knife.cfg)
https://pastebin.com/zA9SasV1 (warmup.cfg)
https://pastebin.com/iJeGgg2Z (live.cfg)

**Comment by Technoblazed** [comment]
I assume you removed all of the team auths from the match.json?

**Comment by gabrielfgularte** [comment]
> I assume you removed all of the team auths from the match.json?

Is that about `get5_check_auths` config that you are asking for? If so, it's 0. Because everyday people come here to test things and login with different accounts...

**Comment by gabrielfgularte** [comment]
I've found the real problem! The problem occurs only with the first client that connect on server.

Any ideas?

**Comment by TandelK** [comment]
Basically the workshop loads map in different way. I am also having a Surf Server with Workshop Collection and Start Map from Workshop also. As soon as you load the first round, it say it will load de_dust because it will not find the real map which you have defined in Start Up Line inside maps folder instead it will run once the Dust Map and try to read your maps directory with workshop folder in it. I have been using Steam Workshop Collection from last couple of years and the same things happen with all the servers .

**Comment by Technoblazed** [comment]
@tandelk, that would be the case, but he's not using the workshop.

**Comment by TandelK** [comment]
I dont know how is he defining start map than ?  Because there are no start up map mentioned in command line after removing workshop collection id and workshop start map 

I did to my Competitive Server like this 
+mapgroup mg_active [Modified Version in Gamemode_server.txt] and +map name it loads all the things properly if they are in Maps folder including Workshop Maps but the Maps has to be in FastDL site in order the clients to get the downloads. Even if the map is in Workshop folder it wont still verify it.

**Comment by Technoblazed** [comment]
The other option is just adding 'map mapname' in your autoexec

**Comment by gabrielfgularte** [comment]
> The other option is just adding 'map mapname' in your autoexec

I''try to force my first map (matchin the first map on `match.json`) running `+map mapname` with my start command and see whats happens.

Thank you!

**Comment by gabrielfgularte** [comment]
I've found out that I have to set the same first map both on match.json and srcds_run command. That has solved the issue for me. So I'm closing it.

Thank you!
