### ISSUE TITLE
Configurable demo save directory?

### ISSUE THREAD

**Issue by WatsonWeb** [splewis/get5#14]
Is it possible to change the directory where demos are saved after being automatically recorded?

Would be nice to have this as a parameter in the config for setups where you need to store the demos outside of the default directory.

**Comment by splewis** [comment]
You could change ``get5_demo_name_format`` to something like ``"demos/{MATCHID}_map{MAPNUMBER}_{MAPNAME}"``, which should work, as long as the demos directory already exists.

**Comment by WatsonWeb** [comment]
Possible to write the demos to a separate drive altogether?

**Comment by splewis** [comment]
I don't know. All the plugin does is issue a tv_record command.
