### ISSUE TITLE
Reload SteamID - enhancement

### ISSUE THREAD

**Issue by Fastmancz** [splewis/get5#140]
Hello,
In the new version, you can add the function to restore the SteamID, which are authorized to go on the server.
ex. **get5_reloadsteamid**
Thanks.

**Comment by splewis** [comment]
I think it's pretty unlikely this is added. Conceptually, you're asking for a reload of a very specific section of the match config data, while there already exists [commands](https://github.com/splewis/get5#serveradmin-commands-meant-to-be-used-by-admins-in-console) and [natives](https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L111) to add and remove players.

**Comment by splewis** [comment]
Closing since there's no response to why this is useful.
