### ISSUE TITLE
Auto readiness confirm

### ISSUE THREAD

**Issue by Pupsick** [splewis/get5#142]
What do you think about auto readiness confirmation in case all players connected (instead of forfeiting the match)?

**Comment by Technoblazed** [comment]
Seems pointless, just join the server in time and play the game as scheduled.

**Comment by Pupsick** [comment]
Nah, i mean sometimes last player connecting at the end of the warmup time(like last 10 seconds) and he have no time to confirm readiness. 
so, i mean if all of the players already connected - would be great to set their readiness automatically
sure, it's my own opinion, so if you're not agree with me - just close the issue.
regards :)

**Comment by Technoblazed** [comment]
So this question is just phrased weirdly, you're asking for a method to disable the ready system, and just have it instantly ready up players on connect? Like a cvar for it?

**Comment by Pupsick** [comment]
i'm asking for some algorithm that will mark all players as ready when warmup times up(in case all of the players connected).
So, if all players connected and warmup times up - dont forfeit the match at this point, just force start it.
p.s. sorry for bad sentences

**Comment by splewis** [comment]
I don't have any plans to add this. To support something like this, it would probably need to disable the ready system entirely which is something I don't want to do right now.
