### ISSUE TITLE
Wrong team tag

### ISSUE THREAD

**Issue by PopiCSGO** [splewis/get5#143]
In the scrim config, I tried to set the team tag to "Infinity". In game however, the team tag is just "inf". Any solutions to this? Here is our scrim config: https://pastebin.com/AxsjyLx4
Also if needed, I can upload a match demo with the bug.

SourceMod Version: 1.8.0.5982
Get5 Version: 0.5.1

**Comment by Technoblazed** [comment]
To confirm:

- That is definitely the config being used.
- Your team tag that it's being replaced with, is a lower case "inf"

**Comment by PopiCSGO** [comment]
Yes, that config is pulled straight from the server, just right after the game.

And yes again, it is replaced with a lowercase "inf".

**Comment by Technoblazed** [comment]
That's really odd, I'm using that version on my server as well and am unable to replicate this, could you try changing the team tag to another one quickly and see what happens then?

**Comment by PopiCSGO** [comment]
I tried it with "Testing123" and it worked perfectly. This is really weird.

**Comment by splewis** [comment]
I just tried "Infinity" as a tag and it worked as expected. It's likely a problem with the game and may be out of my control. Do you have a case that can be reproduced with 1 person? (your original config link is expired anyway.)

**Comment by PopiCSGO** [comment]
Now it works, so it was most likely just the game. Closing since this is solved now.
