### ISSUE TITLE
Investigate a way to override player steam profile pictures

### ISSUE THREAD

**Issue by splewis** [splewis/get5#145]
This would be useful in addition to player name forcing: https://github.com/splewis/get5/issues/106.

**Comment by PopiCSGO** [comment]
This alongside with the player name forcing would be so cool to see in the future!

**Comment by Technoblazed** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=765964792

**Comment by splewis** [comment]
Yeah, I guess this is client side only.
