### ISSUE TITLE
infinite warmup

### ISSUE THREAD

**Issue by Pupsick** [splewis/get5#146]
### Expected behavior

game would start after both teams are marked as ready

### Actual behavior

Sometimes(just like once in over 200 games) game stucks on warmup when both teams are marked as ready
ex
https://puu.sh/vEq74/11e6c9d549.png
actually, no idea which info i suppose to give you now ~_~

also, get5_forceready doesnt makes any effect

### Steps to reproduce
- Plugin version: 0.5.1
- Sourcemod version: 1.8.0.5991

no idea why does it happen

**Comment by splewis** [comment]
Can you provide a match config or what is being printed in chat when this occurs?

**Comment by Pupsick** [comment]
`{"matchid":"11740","maps_to_win":1,"bo2_series":false,"skip_veto":true,"side_type":"standard","maplist":["de_dust2_2x2_overpro"],"players_per_team":2,"team1":{"name":"Team 1","matchtext":"","players":["STEAM_1:1:42507141","STEAM_1:0:185042176"]},"team2":{"name":"Team 2","matchtext":"","players":["STEAM_1:0:144711081","STEAM_1:0:80558182"]},"cvars":{"hostname":"Server #1","mp_freezetime":"15","mp_free_armor":"0"}}`

Chat example from another match with the same problem:

https://puu.sh/vFn3K/13e104f628.png

**Comment by Pupsick** [comment]
just for a moment, 90% happens cuz of g_MapChangePending var.
btw Still trying to find the solution

**Comment by splewis** [comment]
If that's the case I'd recommend adding debug logging for the places g_MapChangePending is set. There's only a few, so a simple log message at each would go a long way. 

My guess is that the [changelevel](https://github.com/splewis/get5/blob/master/scripting/get5/maps.sp#L17) probably isn't taking effect.

**Comment by Pupsick** [comment]
Seems like force changelevel after match over - fixed this issue for me.

**Comment by splewis** [comment]
https://github.com/splewis/get5/commit/dfe76430783a80e93326540ff52dce8aa7fcbe8d should have fixed this.
