### ISSUE TITLE
Spectators not allowed in server despite being clearly defined in match config

### ISSUE THREAD

**Issue by dechristopher** [splewis/get5#147]
### Expected behavior

Server should allow spectators onto the server and into the spectator team to spectate the match.

### Actual behavior

Server allows client to retrieve game data and then kicks client from server citing "You are not a player in this match!"

### Steps to reproduce
- Plugin version: 0.5.2
- Sourcemod version: 1.8 build #5992

**Comment by Technoblazed** [comment]
Do you have a copy of the match config you're using?

**Comment by dechristopher** [comment]
https://kiir.us/matches/league/pre-pos-imp.json

I've extensively checked the formatting and followed the structure guidelines for a match config.

**Comment by Technoblazed** [comment]
How odd, could you try it with a different steamid format, i.e. steam64? Not sure that would cause anything different but want to check just in case.

**Comment by dechristopher** [comment]
Will do, we've been meaning to convert them all to 64 but time hasn't been on our side. I'll get back in a few hours.

**Comment by dechristopher** [comment]
Turns out steam64 ids worked properly. I did further testing with regular steamids and even tried using CS:GO IDs (STEAM_1:X:XXX) all to no avail. There may be a regression somewhere but I'm not sure if anyone else has seen this issue yet. Looks like I'm moving to strictly using steam64 ids.

**Comment by Technoblazed** [comment]
You can never go wrong with Steam3 and Steam64, because they don't have the weird universe stuff :D

**Comment by splewis** [comment]
I'm going to reopen this to remind myself to test the steamid conversion function for this input. This is surprising to me.

**Comment by splewis** [comment]
Well, I would've but the given link doesn't work anymore. Please try to post the actual contents of the match config files in the future.

**Comment by dechristopher** [comment]
https://kiir.us/matches/league/pre/pre-pos-imp.json
