### ISSUE TITLE
Bo3 Series does not load with 3 maps in match config file.

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#148]
### Expected behavior
Bo3 should work with only 3 maps configured in the `maplist` section of the match file (match.json).

### Actual behavior
It does not load and says: "There's no match setup". In the log files it says something about "... cannot start a best of 5 series with only 3 maps".

### Steps to reproduce
My match.json:

```
javascript
{
	"matchid": "my_match",
	"maps_to_win": 3,
	"bo2_series": false,
	"players_per_team": 5,
	"skip_veto": true,
	"side_type": "always_knife",
	"min_players_to_ready": 1,
	"min_spectators_to_ready": 0,

	"maplist": [
		"de_cache",
		"de_mirage",
		"de_overpass"
	],

	"team1": {
		"name": "Awesome Get5 Team A",
		"tag": "GETA",
		"flag": "BR"
	},

	"team2": {
		"name": "Awesome Get5 Team B",
		"tag": "GETB",
		"flag": "BR"
	},

	"cvars": {
		"get5_web_api_url": "http://127.0.0.1:5000",
		"get5_web_api_key": "my_own_secret_token"
	}
}

```

- Plugin version: latest (0.5.2)
- Sourcemod version: latest (1.8)

**Comment by splewis** [comment]
> "maps_to_win": 3,

That defines in a Bo5, so this is working as expected. 

I might consider deprecating "maps_to_win" with just a "num_maps" field, though.

**Comment by gabrielfgularte** [comment]
@splewis I haven't noticed that. You're right. If I want a Bo3 I must set `maps_to_win` to 2, right?

**Comment by splewis** [comment]
Yes.

**Comment by gabrielfgularte** [comment]
I'm closing it! :)

Thank you very much!
