### ISSUE TITLE
issue loading a match

### ISSUE THREAD

**Issue by nobe4rd** [splewis/get5#15]
Hey, 

I've followed your example match, and every time I attempt to load a match, I get the following error:

[get5.smx] Failed to load match config: invalid match kv

do you know of anyway to check and see which kv is invalid?

**Comment by nobe4rd** [comment]
I may have answered my own question here by doing a get5_creatematch, double checking the match file I created and doing a proper get5_loadmatch command

**Comment by splewis** [comment]
Error logs can give additional hints to how the match config files are misformatted.
