### ISSUE TITLE
get5_endmatch causes Windows servers to crash

### ISSUE THREAD

**Issue by aLaaah** [splewis/get5#151]
### Expected behavior
Match force-ends as expected.

### Actual behavior
After the yesterday's CSGO update (Upgraded Windows compile toolchain for Windows client and dedicated server binaries) using get5_endmatch in a Windows server results in a shutdown/lock of the server.

get5_endmatch works correctly under Linux environments.

### Steps to reproduce
- Plugin version: 0.5.2 or 0.5.3dev
- Sourcemod version: 1.8 build 5994 or 1.9 build 6086

**Comment by Technoblazed** [comment]
The update yesterday changed windows binaries, the same issue occurs with the pugsetup plugin, I'm gonna give it a poke later today and try and see what the problem is

**Comment by splewis** [comment]
This is sourcemod issue, and requires a gamedata update. You should post in https://forums.alliedmods.net/showthread.php?t=297340 if you continue to have problems.
