### ISSUE TITLE
Game will not start even after players write !ready

### ISSUE THREAD

**Issue by T1MOXA** [splewis/get5#153]
If in the spectators will be the player that the game will not start even after players write !ready
But if the one who in the spectators write !ready the server crashes.
What it could be ?

PLUGIN_VERSION: 0.5.3-dev
SourceMod Version: 1.8.0.5992

**Comment by Technoblazed** [comment]
Please update your sourcemod version to 1.8.0.5994 or later.

**Comment by splewis** [comment]
I'm closing since there's no update on this - it's almost certainly an issue with your sourcemod installation and unrelated to get5 itself.
