### ISSUE TITLE
Is it possible to change [get5] prefix of every message to something else? 

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#154]
### Expected behavior
message: [TheMasterOfTheMatch] Knife round started!!! 

### Actual behavior
message: [get5] Knife round started!!!

**Comment by Technoblazed** [comment]
`/csgo/cfg/sourcemod/get5.cfg` - `get5_message_prefix`

**Comment by EAbychkov** [comment]
I tried to change this line:
`#define DEFAULT_TAG "[{YELLOW}Get5{NORMAL}]"`
To this:
`#define DEFAULT_TAG "TheMasterOfTheMatch"`
But I didn't get expected result =(

**Comment by Technoblazed** [comment]
You don't need to change the plugin for it... there's a cvar made for it.

**Comment by EAbychkov** [comment]
Ohh you right, thanks a lot !!!

**Comment by splewis** [comment]
Updated https://github.com/splewis/get5/wiki/Full-list-of-get5-cvars#miscellaneous
