### ISSUE TITLE
Match backup file generated for scrims has all players under team 1

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#155]
### Expected behavior

The home team comes under team 1, and the away team goes under team 2.

### Actual behavior

All players are under team 1

### Steps to reproduce
- Plugin version: Latest
- Sourcemod version: Latest 1.8

**Comment by splewis** [comment]
Can you post an example match config & the backup generated?

I don't think the away team is expected to go under team2. The match config for get5_scrim can be generated before anyone joins the server - team2 is just defined as "anyone not on team1" when in scrim mode.

**Comment by Technoblazed** [comment]
Actually, this isn't an issue, I just can't count to 13 correctly :^)
