### ISSUE TITLE
Team names include [NOT READY] tag after backup restoration

### ISSUE THREAD

**Issue by jongcs** [splewis/get5#163]
### Expected behavior
[NOT READY] in team name after load the last match backup file (!stop).
If team name in match cfg file is "TEAM NAME".
### Actual behavior
After use !stop command, the team name will be:
[NOT READY] TEAM NAME

### Steps to reproduce
- Plugin version: 0.5.2
- Sourcemod version: 1.8.0.6014

**Comment by splewis** [comment]
Can you give clear steps to reproduce?

If this does happen, it should go away once teams ready up after the stop command. Can you clarify if it does?

**Comment by jongcs** [comment]
Game start. -> Pause the game, because someone disconnected. -> Both team use !stop to reload. -> Both team name change to "[NOT READY] TEAM NAME", but they don't need to !ready. -> Both team !unpause the game. -> Game resume.

This has happened on my match, so I changed mp_teamname manual.

**Comment by Technoblazed** [comment]
Actually, something similar to this happens, the teamname doesn't actually remove the  notready part until after the first round ends, at least from my experience, so your !stop would cause it to load the knife config, which has NOT READY in use.

**Comment by jongcs** [comment]
It wasn't first round.

Before !stop:
![image](https://user-images.githubusercontent.com/21971007/28003307-4bf9eac6-656f-11e7-9971-7804e3e04a0e.png)

After !stop:
![image](https://user-images.githubusercontent.com/21971007/28003317-5b4e7118-656f-11e7-8bac-c454f6455bfd.png)

**Comment by johankh92** [comment]
I confirm. This happens after the round is restored.

**Comment by PhlexPlexico** [comment]
So yeah, I think https://github.com/splewis/get5/pull/652 may have fixed this issue, but I'm not entirely sure. Throughout my testing for various things with backups I didn't run into this anymore. Is anyone able to confirm if this is still happening?

**Comment by PhlexPlexico** [comment]
Had some more testing done and it looks like that PR may have fixed it. People are no longer receiving the team names when doing round restores.
