### ISSUE TITLE
Bo3 with kniferound on every map

### ISSUE THREAD

**Issue by FaNNboii** [splewis/get5#164]
Hey, i wanted to know if its possible to make a Bo3 match and activate kniferound on each map. At the moment on the first map they choose alle 3 maps and select where they want to start. But i need that on every of the 3 maps theres a kniferound and they cant select on the first map which side they want to start. 
Is it possible?

**Comment by Technoblazed** [comment]
Add always_knife as the side type in your match config

**Comment by FaNNboii** [comment]
ok thanks! is it possible to add a checkbox os something on the get5-web for that?

**Comment by FaNNboii** [comment]
would be awesome!

**Comment by splewis** [comment]
Yes, it's possible. The request is in https://github.com/splewis/get5-web/issues/58, but it's unlikely I get around to it anytime soon.

Also: the [this wiki page](https://github.com/splewis/get5/wiki/Map-Vetoes) would have answered this question.

**Comment by Technoblazed** [comment]
I gave him a tiny placeholder that just adds the side type to the /config endpoint.
