### ISSUE TITLE
Always bo3?

### ISSUE THREAD

**Issue by skiletro** [splewis/get5#169]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

set in cfg 
	"num_maps"		"1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

expecting it to be a best of 1

### Actual behavior

its a best of 3 no matter what number i put?

### Steps to reproduce
- Plugin version: latest
- Sourcemod version: latest

**Comment by splewis** [comment]
Can you post steps to reproduce? Like a match config and the command you used to load it?

**Comment by skiletro** [comment]
I used `get5_loadmatch cml.cfg


File: cml.cfg (Located in csgo/)
`"Match"
{
	"matchid"		"cml1"
	"num_maps"		"1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

	"spectators" // players allowed in spectator (e.g., admins) should go here
	{
		"players"
		{
			"STEAM_0:1:178190202"		"" //Skiletro
		}
	}

	"skip_veto"		"0" // If set to 1, the maps will be preset using the first maps in the maplist below.

	"veto_first"	"team1"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.

	"side_type"		"always_knife" // Either "standard", "always_knife", or "never_knife"

	"maplist"
	{
		"de_cache"		""
		"de_cbble"		""
		"de_inferno"		""
		"de_mirage"		""
		"de_nuke"		""
		"de_overpass"		""
		"de_train"		""
	}

	"players_per_team"		"5"
	"min_players_to_ready"	"1"
	"min_spectators_to_ready"	"1"

	// These values wrap mp_teamprediction_pct and mp_teamprediction_txt.
	// You can exclude these if you don't want those cvars set.
	//"favored_percentage_team1"		"65"
	//"favored_percentage_text"		"HLTV Bets"
	"team1"
	{
		"name"		"Guardians of Steel" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
		//"tag"		"One"  // Short tags replace the "clan tag" on the scoreboard. They are optional.
		//"flag"		""
		"logo"		"gos"
		"players"
		{
			"76561198233957920"		""
			"76561198038705505"		""
			"76561198098672593"		""
			"76561198098752937"		""
			"76561198402809286"		""
		}
	}
	"team2"
	{
		"name"		"Kings"
		//"tag"		"Two"
		//"flag"		""
		"logo"		"king"
		"players"
		{
			"76561198103057572"		""
			"76561198366115454"		""
			"76561198031645097"		""
			"76561198050794124"		""
			"76561198297798113"		""
		}
	}
	// These will be executed on each map start or config load.
	// You should not use this as a replacement for the cfg/get5/live.cfg config.
	"cvars"
	{
		"hostname"		"Carnage League | LIVE | Tune in @ twitch.tv/carnageleague"
	}
}
`

**Comment by grenadecx** [comment]
"Latest" is the worst way to describe the version.

Anyways, I had the same problem with the 0.5.2 version way back, then I switched to the latest development build and that solved it.

**Comment by splewis** [comment]
Can you provide a plugin version number? See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help.

**Comment by skiletro** [comment]
i'm  not sure the plugin version  through the game since i couldn't afford to keep the server up but the zip was called `get5_0.5.2.zip` if that could help

**Comment by Technoblazed** [comment]
That's a super old and outdated release :^)

**Comment by skiletro** [comment]
it seems to be only 20 days old? since i downloaded it from stable releases when i made the post

**Comment by Technoblazed** [comment]
I can't replicate it with your match config, and without any further logs (which you no longer have access to), not much I can do \o/

**Comment by grenadecx** [comment]
@skiletro 
While it's the current "stable", that version is since april.
https://github.com/splewis/get5/releases

As I mentioned, I did have the same problem as you with that version. I suggest you try the development version found here: https://ci.splewis.net/job/get5/lastSuccessfulBuild/

**Comment by splewis** [comment]
I think this has been fixed: see https://github.com/splewis/get5/issues/180
