### ISSUE TITLE
Problem with reconnecting

### ISSUE THREAD

**Issue by ax3rs** [splewis/get5#17]
Hi splewis, today I started a match with "get5_creatematch"
All the players were in their teams, when I reconnected and entered the team that I was before, to a 4 man team, the server moved me to coach, when I disabled coaching, the server kicked me.
Is this a bug? if not, is there any way to prevent this?

**Comment by splewis** [comment]
Sounds like a bug, but I can't seem to reproduce it with 2 players so there's not much I can do.

**Comment by ax3rs** [comment]
I will try to reproduce and record it to youtube

**Comment by ax3rs** [comment]
It didn't work, I guess it was just a one-time thing.
Thanks!
