### ISSUE TITLE
Related to Pause Issue

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5#171]
### Expected behavior
Situation 1 : I set  get5_max_pause_time to "300"" in get5.cfg along with get5_fixed_pause_time "0". 

Situation 2: Tried setting get5_fixed_pause_time "1" and get5_maxpause_time "300".

Situation 3 : Tried setting get5_fixed_pause_time "300" and get5_maxpause_time "300" along with get5_max_pauses "3".

### Actual behavior
Situation 1 : The game supposed to unpause once its been 300 seconds after pausing but its not unpausing. 
Situation 2 : The pauses lasts only 1 seconds.

Situation 3 : The fixed pause time is working and players are unable to unpause while get5_max_pause is not at all useful. 

### Steps to reproduce
- Plugin version: 0.5.3-dev+324 
- Sourcemod version: 1.8.0.5995

**Comment by splewis** [comment]
>Situation 3 : The fixed pause time is working and players are unable to unpause while get5_max_pause is not at all useful.

They're not supposed to be able to unpause. Otherwise, it wouldn't be a fixed time pause. Both ``get5_max_pauses`` and ``get5_max_pause_time`` are still supposed to be respected, though.


Can you check your error logs (addons/sourcemod/logs)? 

This behavior almost sound like you're missing translation strings and the plugin is throwing errors.

**Comment by keeradfun** [comment]
hello,
I checked the log files there is no errors 
error Logs on 29th July:

L 07/29/2017 - 23:42:54: SourceMod error session started
L 07/29/2017 - 23:42:54: Info (map "de_mirage") (file "errors_20170729.log")
L 07/29/2017 - 23:42:54: [SM] Parse error(s) detected in file "/home/keera/ds/t$
L 07/29/2017 - 23:42:54: [SM] (Line 0): Error 1 (Stream failed to open)
L 07/29/2017 - 23:42:54: [SM] Detected parse error(s) in file "/home/keera/ds/t$
L 07/29/2017 - 23:42:54: [SM] Line 0: Stream failed to open
L 07/29/2017 - 23:42:54: [SM] Failed to parse language header file: "/home/keer$
L 07/29/2017 - 23:42:54: [SM] Parse error (line 0, column 0): Stream failed to $
L 07/29/2017 - 23:42:54: Server language was set to bad language "en" -- revert$
L 07/29/2017 - 23:42:54: [SM] Fatal error, no languages found! Translation will$
L 07/29/2017 - 23:42:54: [SM] Unable to load extension "clientprefs.ext": Could$
L 07/29/2017 - 23:42:54: [SM] Exception reported: Language phrase "Please selec$
L 07/29/2017 - 23:42:54: [SM] Blaming: basecommands.smx
L 07/29/2017 - 23:42:54: [SM] Call stack trace:
L 07/29/2017 - 23:42:54: [SM]   [0] Menu.SetTitle
L 07/29/2017 - 23:42:54: [SM]   [1] Line 87, /home/builds/sourcemod/linux-1.8/b$
L 07/29/2017 - 23:42:54: [SM] Unable to load plugin "basecommands.smx": Error d$
L 07/29/2017 - 23:42:54: [SM] Exception reported: Language phrase "Please selec$
L 07/29/2017 - 23:42:54: [SM] Blaming: basevotes.smx

Logs on 8th august
L 08/03/2017 - 16:07:49: SourceMod log file session started (file "L20170803.lo$
L 08/03/2017 - 16:07:49: -------- Mapchange to de_mirage --------
L 08/03/2017 - 16:08:27: Log file closed.

**Comment by TandelK** [comment]
Seems you have either Translations Files missing or cannot excute / read them properly by the Linux User.

**Comment by keeradfun** [comment]
If i can know what and all translations is required for get5 pause to work. I would reinstall and check it again.

**Comment by splewis** [comment]
The errors in that log aren't related to get5.

https://github.com/splewis/get5/commit/1424c1c06c783849a8b50a1d2d43e259c9f18f62 should have fixed problem 1.

Problem 2 is a misunderstanding of how get5_fixed_pause_time works. You set the cvar to the length of the pause. You set it to 1, so it will last 1 second.

**Comment by splewis** [comment]
Closing since I believe this is resolved. You can reopen if that's not the case.
