### ISSUE TITLE
BO3 Problem

### ISSUE THREAD

**Issue by PedroJSViveiros** [splewis/get5#172]
### Expected behavior

When I configure a BO3 match it have to change the maps automatically till the end of the series.

### Actual behavior

When the first map it's finished, it stays in the same map and goes to overtime and never change map neither assume a winning team.

### Steps to reproduce

You can see my match config, and GET5 config.

- Plugin version: latest development build (get5-333)
- Sourcemod version: 1.8.0.5995

[configs.zip](https://github.com/splewis/get5/files/1196577/configs.zip)

**Comment by keeradfun** [comment]
Try loading backup from Map 1 round 30 and finish the round, check if its working.

**Comment by PedroJSViveiros** [comment]
Hello,

First of all, thank you for your fast response.

I tried to do what you said, but it's the same. I tried to play all the 30 rounds and nothing, after i get the 30 rounds it goes to overtime. I think that the problem is with the winning conditions but if I configure a BO1 match that doesn't happen.

Don't know what i'm doing wrong.

Thanks for helping me.

**Comment by splewis** [comment]
> When the first map it's finished, it stays in the same map and goes to overtime

get5 doesn't itself do anything with overtime. You probably have some cvars that are getting set wrong - probably from some other config file or another plugin.

Can you also check some cvars when it happens (and mention what the score was when it happened):
```
mp_maxrounds
mp_match_can_clinch
mp_overtime_enable
```

**Comment by PedroJSViveiros** [comment]
Thank you for your help, it was the cvar mp_match_can_clinch. Don't understand why in BO1 it worked and in BO3 not, but it's ok now, I puted the cvar at '1' in the live cfg. Thanks.
