### ISSUE TITLE
How Events works?

### ISSUE THREAD

**Issue by brunopbarrote** [splewis/get5#175]
How can i receive some of those event log? Should i use logaddress_add  at console or so ?

**Comment by splewis** [comment]
https://github.com/splewis/get5/wiki/Event-logs#interfacing-with-events

**Comment by brunopbarrote** [comment]
But i mean, the only way i could integrate to it, is by doing a plugin in python? If i decide to use c# i can't integrate to get5 events?

**Comment by Technoblazed** [comment]
Well there's 2 options here:

- Add a logaddress to an external site and process all of the logs yourself.
- Create a simple plugin, note: sourcemod plugins are not python, they are sourcepawn. This plugin could then perform post requests and various other requests dependant on your needs. What you're asking for is extremely vague.

**Comment by splewis** [comment]
As Technoblazed said, you can do it many ways. I think the wiki describes the options sufficiently.
