### ISSUE TITLE
cmd Pause works during match game.

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#176]
### Expected behavior
cmd Pause does not work during match game.
### Actual behavior
cmd Pause works during match game and any player can pause the game any time he wants and as many time as he wants. 
### Steps to reproduce

1) run game
2) execute "Pause"->"Unpause" command multiple times

- Plugin version: Dev Version Build #334 (12.08.2017 0:44:09)
- Sourcemod version: the latest

**Comment by Technoblazed** [comment]
What is your value for get5_pausing_enabled?

**Comment by EAbychkov** [comment]
Where can I get it? 
I don't have this key in "\csgo\cfg\get5\live.cfg"
Should I add get5_pausing_enabled 0 ?

**Comment by Technoblazed** [comment]
/csgo/cfg/sourcemod/get5.cfg

**Comment by EAbychkov** [comment]
Currently get5_pausing_enabled "1"
If I will change the value to zero can I still use "!pause" command?

**Comment by Technoblazed** [comment]
Nope, it will completely disable it.

**Comment by EAbychkov** [comment]
But what if I need to use "!pause" in chat but not "pause" cmd ?

**Comment by Technoblazed** [comment]
Isn't `pause` an rcon command?

**Comment by EAbychkov** [comment]
Every player can use cmd "pause" and "unpause" as many times as they want. 
this is cs go cvar 
https://developer.valvesoftware.com/wiki/List_of_CS:GO_Cvars

**Comment by Technoblazed** [comment]
I can't replicate this at all, both of the commands are doing nothing on my online servers.

**Comment by EAbychkov** [comment]
ok, I'll try to make some screenshots.

**Comment by splewis** [comment]
get5 has nothing to do with the console "pause" console command. It only
affects the !pause (in chat) or sm_pause console command.

Have you looked to see if you have any error logs?
https://github.com/splewis/get5/wiki/Debugging-help#getting-error-logs

**Comment by Technoblazed** [comment]
This isn't a get5 issue, but could you post any cfg files you're using on your server? You must have enabled a cvar.

**Comment by EAbychkov** [comment]
Please find live.zip in the attachment. 
What cvar should I enable to disable Cmd pause command?

[live.zip](https://github.com/splewis/get5/files/1238901/live.zip)

**Comment by EAbychkov** [comment]
Out of topic but I also need to disable "kill" command, how can I do this?

**Comment by EAbychkov** [comment]
How to get to know if my server is in competitive gamemode?

**Comment by AFreeman94** [comment]
game_mode and game_type defined in your command line for server startup is
the best way to define which mode your server is in, would you like a list
of the options?

**Comment by AFreeman94** [comment]
Mode  game_type  game_mode

Classic Casual 0 0
Classic Competitive 0 1
Arms Race  1 0
Demolition  1 1
Deathmatch 1 2

As for the kill and pause command, the pause command in console 'pause'
only works to completely pause the server if rcon is used (ex. rcon pause /
rcon unpause). If you are experiencing an issue with the chat command
.pause within the get5 plugin then look in your servers
csgo/cfg/sourcemod/get5.cfg to find the following command (get5_max_pauses)
as with this value at 0 (ex. get5_max_pauses = 0 ) means each team has
unlimited pauses.

The 'kill' command is not blocked in any style of game play as it is a
client commmand by default to allow the player to kill themselves in order
to respawn in games such as TF2 or Day of Defeat: Source. If you want that
commmand disabled I can write the plugin for you and post the link as long
as Sean (splewis) is okay with that or I can provide the source to allow it
to be added to get5 permanently.

**Comment by AFreeman94** [comment]
That is most likely because your server already has sv_pausable set to 0

**Comment by Technoblazed** [comment]
I can guarantee you it doesn't.

Also here's the plugin for you:

```
#include <sourcemod>

#pragma semicolon 1
#pragma newdecls required

public Plugin myinfo = {
	name        = "Kill Command Blocker",
	author      = "Techno",
	description = "Blocks players using the \"kill\" command",
	version     = "1.0.0",
	url         = ""
};

public void OnPluginStart()
{
	AddCommandListener(KillCallback, "kill");
}

public Action KillCallback(int client, const char[] command, int argc)
{
    return Plugin_Handled;
}

```

**Comment by EAbychkov** [comment]
@Technoblazed Sorry for a newbie question, but how can I enable this plugin?

**Comment by Technoblazed** [comment]
Copy paste into here: https://www.sourcemod.net/compiler.php

**Comment by EAbychkov** [comment]
Thanks a lot! I think plugin and sv_pausable 0 are solved my issues, I will test it thoroughly when I will get enough people.

**Comment by AFreeman94** [comment]
I would recommend adding a second listener command for 'explode' as the
command kill is an alias for explode and players would still be able to
kill themselves

On Aug 21, 2017 10:37, "Evgeny" <notifications@github.com> wrote:

Thanks a lot! I think plugin and sv_pausable 0 are solved my issues, I will
test it thoroughly when I will get enough people.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/splewis/get5/issues/176#issuecomment-323759463>, or mute
the thread

**Comment by Technoblazed** [comment]
```
public void OnPluginStart()
{
        AddCommandListener(KillCallback, "kill");
	AddCommandListener(KillCallback, "explode");
}
```

**Comment by splewis** [comment]
Ok, as far as I can tell there's no get5 problem here. Closing this.
