### ISSUE TITLE
Halftime Pause configuration or !ready input

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#177]
Is it possible to configure halftime or additional rounds waiting (delay) time? Or force both teams type !ready again? 

### Expected behavior

Modify some cvar or some rcon command? 

### Actual behavior

No pause (delay) before halftime and additional rounds.

### Steps to reproduce

- Plugin version: #334 (12.08.2017 0:44:09)
- Sourcemod version: 1.8 - build 6017

**Comment by Technoblazed** [comment]
`mp_halftime_pausetimer 1` in your live.cfg would cause a requirement to unpause after each half.

**Comment by EAbychkov** [comment]
Great. thanks a lot! =)

**Comment by splewis** [comment]
That cvar is the closes you will get. Someone requested a proper version of this (#64), but it's not likely to happen anytime soon.

**Comment by EAbychkov** [comment]
![image](https://user-images.githubusercontent.com/1067550/29421141-c9a54a9e-837c-11e7-8e0b-05bed25556cd.png)
If I use this command I am getting freeze screen and I can't continue the game.

**Comment by Technoblazed** [comment]
I wrote something for this a while ago, let me try look for it again.

**Comment by EAbychkov** [comment]
Thanks a lot for your immediate help =)

**Comment by Technoblazed** [comment]
Got it, `mp_halftime_pausematch 1`

**Comment by EAbychkov** [comment]
Thanks, I will check it

**Comment by EAbychkov** [comment]
So if I need to have 1-minute delay before halftime and over time I have to do the following? 
mp_halftime_pausematch 1
mp_overtime_halftime_pausetimer 60
mp_halftime_pausetimer 60

**Comment by Technoblazed** [comment]
mp_halftime_pausetimer and mp_overtime_halftime_pausetimer both need to be set to 0, or else you will have the issue before. The one minute delay you're asking for could just be done with a different cvar 

`mp_halftime_duration 60`

**Comment by EAbychkov** [comment]
Is it possible to add over time pause also 60 ?

**Comment by Technoblazed** [comment]
Can you describe EXACTLY what you want?

**Comment by EAbychkov** [comment]
If the count 15-15 I want the game stopped for a 60 sec or request all players type !ready again.

**Comment by Technoblazed** [comment]
### 60 seconds

mp_halftime_duration 60

### !ready

You can't have this without modifying the plugin, but use `mp_halftime_pausematch 1`
