### ISSUE TITLE
Lan tournament - web panel inquiry

### ISSUE THREAD

**Issue by bambarz** [splewis/get5#179]
Hi splewis - very big fan of your CSGO work.

I'm organizing a LAN tournament next month, and plan on using the web panel to manage the servers - for ease of use and simplicity. A couple of questions:

- Do I need every single players steamID added to the team? What happens if players join the created match without their steam IDs added on the webpanel team list?
-What's the simplest way through webpanel to use esl5on5.cfg as the standard match config for all the matches?

**Comment by Technoblazed** [comment]
- You gotta add all the IDs to the team. If a player connects without being added to the team, it'll kick them from the server when they connect. Note that when a match is live, the admin panel for the match allows you to add players to teams.
- Copy the changed items from the esl5on5 config into the live.cfg, be careful and make sure you test as this has been weird in the past. As far as I'm concerned, the live.cfg is the current esl5on5 config.

**Comment by bambarz** [comment]
Thanks Technoblazed - followup questions:
- I am curious about the use of adding players after the match is Live? Shouldnt they all be _in_ the server before it is live? which means they all must be added _before_ the match goes live?
- Will look into the live.cfg - is that automatically created by the plugin?

It may be a bit of a pain to gather all the players steam ID's (possibly 40 players +) - so this should be interesting...

**Comment by Technoblazed** [comment]
- Whenever you create the match, that would run the commands on the server to load various match settings, so the command would then add them to the map cycle, so technically my phrasing was live. Not when live, but when match is created.
- /csgo/cfg/get5/live.cfg, should've been in the files you uploaded when you setup the servers.

**Comment by AFreeman94** [comment]
I've done exactly this several times if you want help streamlining all the
match's feel free to add and message me

**Comment by bambarz** [comment]
@Technoblazed 
Sorry the wording is still a little confusing - So to summarize:

- Before match is created, any player can join the server.
- After match is created, it will kick anyone not on the steam ID player list.
In your opinion, what is the best time to use the admin panel to add players to the teams? Should I wait for them to join the server? Does that make it easier?

@AFreeman94 Awesome - how can I get in touch :)

**Comment by Technoblazed** [comment]
- Assuming `get5_kick_when_no_match_loaded` is set to `1` in your get5.cfg, no players will be able to join the server before the match is created.
- If you're using the admin panel, you're honestly better off just getting all people that are playing to give you their steamids.

**Comment by AFreeman94** [comment]
Email or steam work for you?

**Comment by TandelK** [comment]
Just add all the teams and Steam ID in the panel before the LAN Tournament begins, Just a single click via Panel and you are good to go for the match to be Live with correct Steam IDs . Collect Steam ID of each and every player [On panel section even if you use steamcommunty.com/id/ Link it auto converts to SteamID64 format. So dont worry about converting them always. ]

**Comment by bambarz** [comment]
@AFreeman94 Shall we get in touch on email? Please drop me yours (not sure if it can be messaged here) or send me a 'hello' thingie to k.mousa86@gmail.com
Thanks man!

**Comment by splewis** [comment]
This seems resolved to me.
