### ISSUE TITLE
No data gets inserted to mysql database

### ISSUE THREAD

**Issue by Slekee** [splewis/get5#181]
Hey!

I created a mysql database called get5 and imported https://raw.githubusercontent.com/splewis/get5/master/misc/import_stats.sql to the database.

My addons/sourcemod/configs/database.cfg looks like this:
"Databases"
{
        "driver_default"                "mysql"
        "default"
        {
                "driver"                        "mysql"
                "host"                          "10.0.0.5"
                "database"                      "get5"
                "user"                          "root"
                "pass"                          "*****"
                //"timeout"                     "0"
                "port"                          "27015"
        }
        "get5"
        {
                "driver"                        "mysql"
                "host"                          "10.0.0.5"
                "database"                      "get5"
                "user"                          "root"
                "pass"                          "****"
                //"timeout"                     "0"
                "port"                          "27015"
        }
        "storage-local"
        {
                "driver"                        "sqlite"
                "database"                      "sourcemod-local"
        }
        "clientprefs"
        {
                "driver"                        "sqlite"
                "host"                          "10.0.0.5"
                "database"                      "clientprefs-sqlite"
                "user"                          "root"
                "pass"                          ""
                //"timeout"                     "0"
                //"port"                        "0"				
		}
}

My error_log -file doesn't write anything after I load get5_loadmatch example_match.cfg.
Before loading a match config it says:
L 08/29/2017 - 11:17:03: SourceMod error session started
L 08/29/2017 - 11:17:03: Info (map "de_dust2") (file "errors_20170829.log")
L 08/29/2017 - 11:17:03: [SM] Unable to load extension "dbi.mysql.ext": libz.so.1: cannot open shared object file: No such file or directory
L 08/29/2017 - 11:17:03: [SM] Exception reported: Could not connect to get5 database: Driver "mysql" not found
L 08/29/2017 - 11:17:03: [SM] Blaming: get5_mysqlstats.smx
L 08/29/2017 - 11:17:03: [SM] Call stack trace:
L 08/29/2017 - 11:17:03: [SM]   [0] SetFailState
L 08/29/2017 - 11:17:03: [SM]   [1] Line 61, ./scripting/get5_mysqlstats.sp::OnPluginStart
L 08/29/2017 - 11:17:03: [SM] Unable to load plugin "get5_mysqlstats.smx": Error detected in plugin startup (see error logs)

I'm running a Virtual machine in azure with Ubuntu 17.04.

Can't find out what's wrong so if anyone can help it would be awesome!

- Plugin version: 0.5.2
- Sourcemod version: 1.8.0.6025

**Comment by Technoblazed** [comment]
- Doubt the port should be 27015, the usual MySQL port is 3306.
- Run `sudo apt-get install lib32z1`

**Comment by Slekee** [comment]
Hey!
Thank you Technoblazed!

I had already installed the lib32z1.

The problem was the IP and port of MySQL. I though first that it should have been the specs of the server, but after setting the IP to 127.0.0.1 and the port to 3306 it worked
