### ISSUE TITLE
Regarding Lan Setup

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5#182]
I have loaded a match setup using get5 plugin, in my lan server where sv_lan is set to "1"

### Expected behavior
The steamids i have provided should be able to join the server and able to play.

### Actual behavior

The players are unable to connect to server, and they are getting kicked saying "You are not a player of this match".
In server console, get5 throwing

L 09/07/2017 - 15:23:47: [get5.smx] Failed to get steamid for client Playtonia.com | Keera D Fun<9><STEAM_1:1:58419760><>

I think get5 can't validate steamids when sv_lan is set to "1"

### Steps to reproduce

- Plugin version: 0.5.3-dev+341
- Sourcemod version: sourcemod-1.8.0-git6025-windows

**Comment by splewis** [comment]
If sourcemod's function to get steamids fails there's probably nothing get5 can do to validate steamids. 

Question: if you run ``status`` in console: do steamids show up?

**Comment by keeradfun** [comment]
In status the server shows players steam ids

# userid name uniqueid connected ping loss state rate adr
# 2 "Playtonia TV 1" BOT active 24
#  3 2 "Playtonia | Keera D Fun" STEAM_1:1:58419760 01:20 11 0 active 128000 192.168.10.162:27017
#end

**Comment by keeradfun** [comment]
In the end, i set sv_lan 0 and applied Steam GLST and set +net_public_add to LAN IP, it worked flawlessly... Anyway, thank you for your time.

**Comment by splewis** [comment]
Closing this since I don't think there's anything I can do here.
