### ISSUE TITLE
canonical build releases url

### ISSUE THREAD

**Issue by janstuemmel** [splewis/get5#185]
just an idea. consider removing the version string from the `get5_x.y.zip`.

i automate spinning up servers. its better to define a variable for automated downloading the get5 release.

github let you download binary releases from a cononical url like this: 
`https://github.com/splewis/get5/releases/download/0.5.2/get5_0.5.2.zip`.  

the path after `.../download/` defines the tag/version of the software. A url like `.../releases/download/0.5.2/get5.zip` would be enough

**Comment by splewis** [comment]
I don't think I'm going to do this. All of my sourcemod projects use this convention, and I don't think that use case is compelling enough to change that process.
