### ISSUE TITLE
get5_mysql_force_matchid not working

### ISSUE THREAD

**Issue by grenadecx** [splewis/get5#186]
Using get5 with get5_mysql.

### Expected behavior

I set the get5_mysql_force_matchid in the cvars section of the config file to 100, using json.
I expected matchid stored in the get5_stats_matches in the database to get matchid 100.

### Actual behavior

matchid in the get5_stats_matches still used incremental id.

### Steps to reproduce

I used the following configuration file:

> {  
   "matchid":"fbea3985-2f38-40b2-b676-5ffb83119139",
   "num_maps":1,
   "bo1_series":true,
   "players_per_team":1,
   "min_players_to_ready":2,
   "min_spectators_to_ready":0,
   "skip_veto":true,
   "map_sides":[  
      "knife"
   ],
   "spectators":{  
      "players":[]
   },
   "maplist":[  
      "de_cache"
   ],
   "team1":{  
      "name":"Alpha",
      "tag":"Alpha",
      "flag":"",
      "logo":"",
      "players":[  
         "76561198003517076"
      ]
   },
   "team2":{  
      "name":"Beta",
      "tag":"Beta",
      "flag":"",
      "logo":"",
      "players":[  
         "76561198389039675"
      ]
   },
   "cvars":{  
      "hostname":"fbea3985-2f38-40b2-b676-5ffb83119139",
      "mp_maxrounds":"15",
      "mp_halftime":"1",
      "mp_halftime_duration":"15",
      "sv_coaching_enabled":"0",
      "mp_overtime_enable":"0",
      "get5_mysql_force_matchid":"100"
   }
}

- Plugin version: 0.5.4-dev (latest git as of today)
- Sourcemod version: 1.8.0.6027

**Comment by pistoolero** [comment]
From readme:
"You can also set get5_mysql_force_matchid to 1 to make get5 ignore the matchid in match configs, and instead set it based on the id assigned when the plugin inserts into get5_stats_matches" so if u want matchid 100 get5_mysql_force_matchid should be set to 0 and matchid should be set to 100.

**Comment by splewis** [comment]
Yeah, the docs are wrong about ``get5_mysql_force_matchid``. You would set it to the matchid you want.

>Sourcemod version: 0.5.4-dev (latest git as of today

This will never *not* make me angry.

Can you test with debug logs enabled and post the results? https://github.com/splewis/get5/wiki/Debugging-help#getting-debug-logs

**Comment by grenadecx** [comment]
> This will never not make me angry.

Oops, let's reverse those :)

get5_debuginfo.txt

Time: 09/30/2017 - 11:09:31
Plugin version: 0.5.4-dev
sourcemod_version = 1.8.0.6027
metamod_version = 1.10.7-devV



Global state:
g_GameState = 3 (warmup)
g_MatchID = 2
g_MapsToWin = 1
g_BO2Match = 0
g_LastVetoTeam = 1
g_MapPoolList (length 1) = 
  [0] -> de_cache
g_MapsToPlay (length 1) = 
  [0] -> de_cache
g_MapsLeftInVetoPool (length 1) = 
  [0] -> de_cache
g_MatchTitle = Map {MAPNUMBER} of {MAXMAPS}
g_PlayersPerTeam = 1
g_MinPlayersToReady = 2
g_MinSpectatorsToReady = 0
g_SkipVeto = 1
g_MatchSideType = 0
g_InScrimMode = 0
g_HasKnifeRoundStarted = 0
g_MapChangePending = 0
g_PendingSideSwap = 0
g_WaitingForRoundBackup = 0
g_SavedValveBackup = 0
g_DoingBackupRestoreNow = 0
Team info for team team1 (0):
g_TeamNames = Alpha
g_TeamAuths (length 1) = 
  [0] -> 76561198003517076
g_TeamTags = Alpha
g_FormattedTeamNames = {LIGHT_GREEN}Alpha{NORMAL}
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = CT (3)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 3
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 27
Team info for team team2 (1):
g_TeamNames = Beta
g_TeamAuths (length 1) = 
  [0] -> 76561198389039675
g_TeamTags = Beta
g_FormattedTeamNames = {PINK}Beta{NORMAL}
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = T (2)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 2
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 27
Team info for team spec (2):
g_TeamNames = casters
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = {NORMAL}casters{NORMAL}
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 0
Team info for team none (3):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 0



Interesting cvars:
get5_autoload_config = 
get5_check_auths = 1
get5_fixed_pause_time = 0
get5_kick_when_no_match_loaded = 1
get5_live_cfg = get5/live.cfg
get5_max_pause_time = 300
get5_max_pauses = 0
get5_pausing_enabled = 0
get5_reset_pauses_each_half = 1
mp_freezetime = 5
mp_halftime = 1
mp_halftime_duration = 15
mp_halftime_pausetimer = 0
mp_match_end_restart = 0
mp_maxrounds = 15
mp_maxrounds = 15
mp_overtime_enable = 0
mp_overtime_halftime_pausetimer = 0
mp_overtime_maxrounds = 6
mp_round_restart_delay = 10
mp_timelimit = 0
mp_warmup_pausetimer = 1
mp_warmuptime_all_players_connected = 0
sv_coaching_enabled = 1
tv_delay = 105
tv_enable = 0



Last log info from addons/sourcemod/logs/errors_20170930.log:
L 09/30/2017 - 10:56:19: Error log file session closed.
 L 09/30/2017 - 10:55:56: [get5.smx] Failed to load match config: invalid match json
 L 09/30/2017 - 10:55:56: [get5.smx] Failed to load match config: Missing "team1" section in match json
 L 09/30/2017 - 10:55:56: Info (map "de_dust") (file "errors_20170930.log")
 L 09/30/2017 - 10:55:56: SourceMod error session started
 


Last log info from addons/sourcemod/logs/get5_debuginfo.txt:

**Comment by grenadecx** [comment]
Where is the code located that reads the get5_mysql_force_matchid cvar from the matchconfig into the g_ForceMatchIDCvar?

**Comment by Technoblazed** [comment]
ConVar identification: https://github.com/splewis/get5/blob/master/scripting/get5_mysqlstats.sp#L54

MatchID setting: https://github.com/splewis/get5/blob/master/scripting/get5_mysqlstats.sp#L101

**Comment by splewis** [comment]
Since the ``SELECT LAST_INSERT_ID()`` log statement was in the debug logs, ``get5_mysql_force_matchid`` was 0 when the match stuff (series init) started.

**Comment by grenadecx** [comment]
Right, I understand that, but since get5_mysql_force_matchid was set to 100 under the cvars section in the matchconfig used, that shouldn't been the case.

**Comment by splewis** [comment]
2ac1796f8883d4399c362697ef31555e633535d0 should have fixed this. 

The problem was that the ``cvars`` section wasn't executed yet when that code ran.

I also opened #187 since I don't think this cvar is necessary.
