### ISSUE TITLE
Evaluate if get5_mysql_force_matchid cvar is needed

### ISSUE THREAD

**Issue by splewis** [splewis/get5#187]
I don't actually understand why it's there. The matchid in the config should be sufficient, as far as I can tell.

I intend to remove it unless someone sees the need for it or actively uses it in a scenario where setting the match config isn't viable.

**Comment by grenadecx** [comment]
I agree that it seems kinda redundant to keep using it when matchid from the config could been used just as easily.

**Comment by nickdnk** [comment]
I agree this should be removed. I will attempt a fix at this and fix #673 at the same time. Closing as we're tracking it there.
