### ISSUE TITLE
Proper way to update from one version to another

### ISSUE THREAD

**Issue by boXseven** [splewis/get5#188]
Hey, I wonder what's the best way to update the plugin. Our server uses 0.5.2 and i want to update to 0.5.3 now.
Do i really need to replace all files or only some?
Do i need to delete the get5.cfg, because there is the new command "get5_print_damage 1"?

greets

**Comment by splewis** [comment]
Normally you just override all the files.

The only file in the release that's meant to be configured in configs/get5/scrim_template.cfg, so you might not want to overwrite that if you've changed it.

**Comment by boXseven** [comment]
How else am I supposed to change the settings if not in get5. cfg?

**Comment by splewis** [comment]
You change them in get5.cfg like always.

If a new cvar isn't there, you can add it. Or you can delete the file and let it be re-created. It doesn't matter.

**Comment by boXseven** [comment]
So in my scenario I would have to overwrite all files and just add this one command to my get5. cfg?

**Comment by splewis** [comment]
Yes.
