### ISSUE TITLE
Add support for BO2's

### ISSUE THREAD

**Issue by splewis** [splewis/get5#19]
It'd be nice if there was some way of having a best-of-2 series playable. I have no idea how vetoes work in this situation, though.

**Comment by techlover1** [comment]
The way we do it in our league is: each team bans 2 maps, then each team picks one (ban/ban/pick). Another way of doing it is the same as a bo3, (ban/pick/random) just without the 3rd map

**Comment by splewis** [comment]
This has been added in https://github.com/splewis/get5/commit/5b469f2efb24a90767e7991cbd813cca12038c5a
