### ISSUE TITLE
get5 Web panel does not let us delete teams.

### ISSUE THREAD

**Issue by MakkaraMasa** [splewis/get5#192]
We have no idea why this is happening. It lets create teams and matches but we can't delete any of them. Does anyone have ideas why it does that?

**Comment by MakkaraMasa** [comment]
It gives this error:

**Comment by Technoblazed** [comment]
Pretty sure you can't delete teams that have played matches.

**Comment by MakkaraMasa** [comment]
They were test teams. We didnt actually even join the server.

**Comment by MakkaraMasa** [comment]
Or complete the matches.

**Comment by Technoblazed** [comment]
Probably the fact the matches were made

**Comment by Technoblazed** [comment]
Also just noticed, wrong git, get5-web is over here: https://github.com/splewis/get5-web

**Comment by MakkaraMasa** [comment]
My bad:D
