### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by unknownuser1337** [splewis/get5#195]
Hey, i set up a new Server and only installed Metamod, Sourcemod, Get5 and the Get5-Web Extensions and everytime when i create a get5-web Match it loads successfully. But when i try to join the Server it crashes in 80%.

I installed Accelerator for Crash Dumps:

Uploaded crash dump: Crash ID: ZCE6-AFZS-EOTR
Uploaded crash dump: Crash ID: ZYZF-7R4Z-O6YP
Uploaded crash dump: Crash ID: XVIB-CUTG-ZNK5
Uploaded crash dump: Crash ID: VJ3X-S7FS-IDRF

When Server Crashes in Serverconsole it says:
https://hastebin.com/quraluquqo.scala

Metamod:Source version 1.10.7-dev
         Built from: https://github.com/alliedmodders/metamod-source/commit/4a27e2f
         Build ID: 959:4a27e2f
         Loaded As: Valve Server Plugin
         Compiled on: Jun 21 2017
         Plugin interface version: 15:14
         SourceHook version: 5:5
         http://www.metamodsource.net/

SourceMod Version Information:
             SourceMod Version: 1.8.0.6032
             SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6032)
             SourcePawn API: v1 = 4, v2 = 11
             Compiled on: Oct 22 2017 15:08:14
             Built from: https://github.com/alliedmodders/sourcemod/commit/afcd94a
             Build ID: 6032:afcd94a
             http://www.sourcemod.net/

[SM] Listing 19 plugins:
           01 "Fun Votes" (1.8.0.6032) by AlliedModders LLC
           02 "Anti-Flood" (1.8.0.6032) by AlliedModders LLC
           03 "Get5" (0.5.3) by splewis
           04 "Basic Chat" (1.8.0.6032) by AlliedModders LLC
           05 "Basic Commands" (1.8.0.6032) by AlliedModders LLC
           06 "Basic Ban Commands" (1.8.0.6032) by AlliedModders LLC
           07 "Reserved Slots" (1.8.0.6032) by AlliedModders LLC
           08 "Client Preferences" (1.8.0.6032) by AlliedModders LLC
           09 "Admin Help" (1.8.0.6032) by AlliedModders LLC
           10 "Get5 Web API Integration" (0.5.4-dev+355) by splewis
           11 "Basic Comm Control" (1.8.0.6032) by AlliedModders LLC
           12 "Player Commands" (1.8.0.6032) by AlliedModders LLC
           13 "Admin Menu" (1.8.0.6032) by AlliedModders LLC
           14 "Admin File Reader" (1.8.0.6032) by AlliedModders LLC
           15 "Basic Votes" (1.8.0.6032) by AlliedModders LLC
           16 "Sound Commands" (1.8.0.6032) by AlliedModders LLC
           17 "Basic Info Triggers" (1.8.0.6032) by AlliedModders LLC
           18 "Nextmap" (1.8.0.6032) by AlliedModders LLC
           19 "Fun Commands" (1.8.0.6032) by AlliedModders LLC

**Comment by splewis** [comment]
Based on the crash dumps ((https://crash.limetech.org/zce6afzseotr) it's unlikely this is directly get5's fault. I'd suggest updating sourcemod and testing if it still happens, since the crash happens in sourcemod.

**Comment by splewis** [comment]
Closing since there's been no followup and I don't believe this to be a get5 issue.
