### ISSUE TITLE
ftp upload branch

### ISSUE THREAD

**Issue by grenadecx** [splewis/get5#196]
I'm interested in uploading the demo once it's finished recording.

I see that there is a ftp upload branch that was made and by taking a quick look it seems a great deal of it is in place for it to work. @splewis what's the status on that branch, what's left?

**Comment by splewis** [comment]
I don't remember at all, to be honest. I don't think I'll get around to it, so it's probably up to somebody else to finish up and test.

**Comment by Pupsick** [comment]
@grenadecx 
If you really need it, you can just use get5 together with smth like tEasyFTP like mid solution. :)

**Comment by grenadecx** [comment]
@splewis 
Alright, thanks. I'm gonna dig into it and see what's missing then.

@Pupsick 
Seems like one way to handle it, thanks. I'm quite new to scripting, so I'll see if I can figure it out.

**Comment by Pupsick** [comment]
@grenadecx Guess i can help you, if you need. :)

**Comment by splewis** [comment]
I'm closing this since there's nothing really happening here. I'm still happy to review a pull request that would add ftp support in get5, though.
