### ISSUE TITLE
Option to customize demos path

### ISSUE THREAD

**Issue by Pupsick** [splewis/get5#197]
If i am right, there is no way to change destination of all demos. (Let me now if i'm not, please)
Can you introduce it? 
E.g. The purpose of this introduction is necessity of running web server to share demos and avoidance of clogging in csgo folder
Regards

**Comment by grenadecx** [comment]
If you look at #14 it seems you can change the directory directly from the demo name cvar.

**Comment by Technoblazed** [comment]
You can change the directory relative to your game path, if they're on the same server, consider making a symlink from within the cs:go directory that links to your webserver, then set the cvar appropriately to match the folder.

**Comment by Pupsick** [comment]
@grenadecx thanks, it's correct.

@Technoblazed 
Thanks. Problem solved. :)
