### ISSUE TITLE
Coaches aren't included in the ready system

### ISSUE THREAD

**Issue by ghost** [splewis/get5#201]
So as the title says, coaches aren't included in the ready system and their team tag doesn't show up during the game. If this is not going to be fully implemented, there could be a cvar like in pugsetup to whether include or exclude coaches/spectators from the ready system.

**Comment by JesusWithPants** [comment]
What version ar You using?
Im using the coach mode also on my 5x5 servers, but have no problems with them. Tags appear propperly.

About Ready system - You need to include in the match config: `"min_spectators_to_ready": 0,`, set it to 1 if You have always one coach in server.

**Comment by slawteruk** [comment]
Are you able to confirm if a coach uses a player slot, or a spectator slot? What should a coach be treated as?

**Comment by nickdnk** [comment]
@PhlexPlexico Do we want this? Looking at the code, the new changes to coaches does not seem to consider a coach a "ready player" at all: https://github.com/splewis/get5/blob/master/scripting/get5/readysystem.sp#L85-L103

**Comment by PhlexPlexico** [comment]
I'm not too sure. I'd be interested to see what ESEA does, but my initial thoughts is that they didn't care about coach ready-ups. If that's not the case, I can definitely look into this!

**Comment by PhlexPlexico** [comment]
So I took a look into it and I think ESEA does require the coach to be ready as well. I think get5 is a bit more functional in regards to this as well, so I think we should include coaches in the ready system. Should be something as simple as just removing those `!IsClientCoaching(i)` calls? Will test this and see if it works as intended.

**Comment by nickdnk** [comment]
It looks like we could just remove that coaching filter, yes.

But a thing to consider here: The ready system has the "minimum players ready" (I forget the exact name and I'm on my phone) option. If this is set to 5, and 4 players and a coach ready, the team will be ready without its 5th player.

If we do this, we should probably add a config parameter for it, I.e. `g_CoachesMustReady` and if that is true, override minimum players required for ready and always set it to the length of the player array + length of coach array. How this would work with in scrim-mode I don't really know.

Thoughts?

**Comment by nickdnk** [comment]
We could also just put in the docs that the "minimum players to ready" set to 0 means all players on the team, including coaches.

**Comment by nickdnk** [comment]
This is in preview on the nightly builds for 0.11 now: https://github.com/splewis/get5/releases/tag/v0.11.0-74ed6a8
