### ISSUE TITLE
Warmup with time limit?

### ISSUE THREAD

**Issue by Gagoosh** [splewis/get5#203]
Hey, I know this is off from get5's main goal, but I'd like to know if it is possible to set warmup a limit time and after it ended, if not all players connected to the match, just end the match. Also when all players connected, just reset the warmup time to something like 10 seconds.

I'm not only asking if its possible to do with get5, but also if someone here knows a simple way to do that, with or without get5, 'cause I can't find anything around that.

**Comment by Technoblazed** [comment]
`get5_time_to_start`: Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited"

**Comment by Gagoosh** [comment]
@Technoblazed is it possible to get steamid from players that didn't connect?

**Comment by pistoolero** [comment]
@Gagoosh what about getting list of players wiem time is out and comparing it with list of players in your match config?

**Comment by Gagoosh** [comment]
@pistoolero yeah, I thought that, the thing is, I'm new to csgo plugins and I don't know how to re-compile get5 plugin :(

**Comment by pistoolero** [comment]
cd into addons/sourcemod/scripting/ and type ./compile.sh {pluginname}.sp

**Comment by Gagoosh** [comment]
@pistoolero I feel kinda stupid, thats way easier than I expected, thanks for the help.

**Comment by algoth** [comment]
@Gagoosh how can i get the list of users who joined at time out? Can't find any command.
