### ISSUE TITLE
Getting matchstats after a match has ended without the db

### ISSUE THREAD

**Issue by bryggemesel** [splewis/get5#208]
Is there a way to fetch matchstats files after a game has ended without the db.
Preferably the file: get5_matchstats_{matchid}.cfg

Like the get5_status command JSON formatted, but with matchstats instead.

**Comment by splewis** [comment]
I don't really understand your question, ``get5_matchstats_{matchid}.cfg`` is exactly the way to get match stats, whether it's another process reading the file or another plugin reading the stats through the ``Get5_GetMatchStats`` native.

I don't plan on adding json output for the match stats. I'm not opposed to someone else adding it and making a pull request, but I have no intention of adding it.

**Comment by splewis** [comment]
Since there's no bug/planned feature request here, I'm closing this.
