### ISSUE TITLE
In battle of 3, it only updates one row in get5_stats_maps

### ISSUE THREAD

**Issue by dzinks2009** [splewis/get5#209]
### Expected behavior

When a game starts in BO3, it should create the first row. It should be updating that row untill the map switches, when the map switches, it should create a new row with "mapnumber" = 1, and update "mapnumber" = 1, instead of "mapnumber" = 0,etc.

### Actual behavior

When the map changes, it should update the new row everytime instead of the old one.

### Steps to reproduce

Check where it creates the new row after the map switches, and update the plugin to set the new row id which it should update.

- Plugin version: 0.5.5-dev,
- Sourcemod version: SourceMod 1.8.0.6038.

**Comment by splewis** [comment]
> Plugin version: 0.5.5-dev,

That isn't a version. Can you provide a commit or build number?

I assume you're referring to the get5_mysqlstats plugin and the ``get5_stats_matches`` & ``get5_stats_players`` not being updated correctly, right?

> and update the plugin to set the new row id which it should update.
I'm not sure what that means.

**Comment by dzinks2009** [comment]
That is also a verison but whatever. The "other" version is get5-367.
Yes, I'm referring to the get5_mysqlstats. The thing that's not updating correctly is **get5_stats_maps** because when in a BO3, and we switch to the 2nd map, a new row is created but it still updates the older row.

**Comment by splewis** [comment]
8a0c3649c5c22e2621d55a64e2c4cddf7697e0d5 should have fixed this.

**Comment by dzinks2009** [comment]
I'll test it and let you know.
