### ISSUE TITLE
Add stats ?

### ISSUE THREAD

**Issue by iDentity1337** [splewis/get5#21]
I think you should add atleast common stats (kills, deaths, headshots, assists), with option for local storage and MySQL. But great project anyways, looking forward for great stuff.

**Comment by Vanhecke** [comment]
I would much rather see a stats output in JSON if anything.

**Comment by iDentity1337** [comment]
Yeah, @Vanhecke, that would be good too.

**Comment by splewis** [comment]
I've implemented the stats collection (**only**), which saves the stats into a keyvalue format and is accessible via the ``Get5_GetMatchStats`` native and the ``get5_dumpstats`` command.

I don't know whether I'm going to add any MySQL support or json-formatted stats, but the collection of the stats makes those easier for others.

**Comment by iDentity1337** [comment]
Available in master branch?

**Comment by splewis** [comment]
Yes.

**Comment by splewis** [comment]
Stats should be implemented fully now.

I've described it in https://github.com/splewis/get5/wiki/Stats
