### ISSUE TITLE
GOTV demo gets deleted

### ISSUE THREAD

**Issue by KeT0M** [splewis/get5#210]
### Expected behavior
Demos should be auto recorded and saved.

### Actual behavior
Demos are getting recorded, but then when the match ends, it seems it does not get saved or get flushed. I am not sure if it is a plugin issue or my server config issue.

Completed GOTV demo "manual_map1_de_mirage.dem", recording time 274.8
StopRecording: 13440 frames flushed in 4.95 seconds

L 12/11/2017 - 11:50:53: SourceMod error session started
L 12/11/2017 - 11:50:53: Info (map "de_mirage") (file "errors_20171211.log")
L 12/11/2017 - 11:50:53: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 12/11/2017 - 11:50:53: [SM] Blaming: get5.smx
L 12/11/2017 - 11:50:53: [SM] Call stack trace:
L 12/11/2017 - 11:50:53: [SM]   [0] GetArrayCell
L 12/11/2017 - 11:50:53: [SM]   [1] Line 30, ./scripting/include/restorecvars.inc::RestoreCvars
L 12/11/2017 - 11:50:53: [SM]   [2] Line 978, ./scripting/get5.sp::EndSeries
L 12/11/2017 - 11:50:53: [SM]   [4] Call_Finish
L 12/11/2017 - 11:50:53: [SM]   [5] Line 689, ./scripting/get5/util.sp::_DelayFunctionCallback

### Steps to reproduce
I create match by get5_creatematch, everyone ready up, match gets played and then when it is finished there is no demo file on the server even tho it was being recorded.

- Plugin version: 0.5.5
- Sourcemod version: 1.8.0.6035

**Comment by Technoblazed** [comment]
When the match is live, do you see a demo file in the path where it should be saved to, with a filesize of 0kb?

If you don't see a demo file at all at any point, it's likely it couldn't be recorded due to a permissions issue.

**Comment by splewis** [comment]
All get5 does is issue ``tv_record`` and ``tv_stoprecord`` commands, so there's probably nothing get5 is doing wrong here.

I would double check for the file, see if you have anything else that could  delete it, or have any permissions problems.

**Comment by splewis** [comment]
I'm closing since I don't think this is related to a get5 problem.
