### ISSUE TITLE
GOTV demos into subfolder

### ISSUE THREAD

**Issue by dtnlol** [splewis/get5#211]
I want to save all recorded demos into a subfolder named "demos". I use the cvar:
get5_demo_name_format "demos/{MATCHID}_map{MAPNUMBER}_{MAPNAME}"

### Expected behavior
Demos should be saved into the demos/ folder.

### Actual behavior
The cvar above has no effect and all demos are still saved into the root directory.

Is it at all possible to do what I am trying to do here?

**Comment by splewis** [comment]
You can do that, you just need to make sure the ``demos`` directory already exists.

All get5 does with the demos is issuing ``tv_record`` and ``tv_stoprecord`` commands to the server. I don't think it's worthwhile to add code to parse for a directory name in the ``get5_demo_name_format`` cvar and ensure it exists in this case.

**Comment by dtnlol** [comment]
That's odd, because the directory exists. I'm using one server as the master and duplicate from this, whenever I need to create new servers. The `demos` directory exists in all of these, I checked manually too when a match was ongoing.

However, I could still see in the root directory something along with `432_map1_de_mirage.dem` even though I explicitly put `demos/...` in the cvar. Maybe I should look for an alternative way, as I've struggled with this for too long.

**Comment by splewis** [comment]
I don't know if that's your issue, but it's unrelated to get5 still. I would just test with the tv_record command and see what works.

**Comment by williamweckl** [comment]
Can I set something like this: `get5_demo_name_format "demos/{TEAM1}vs{TEAM2}map{MAPNUMBER}{MAPNAME}"``?
Would this work? Using TEAM1 and TEAM2 variables?

**Comment by williamweckl** [comment]
Just confirmed that it works! Thx
