### ISSUE TITLE
get5_mysqlstats when using get5_scrim // missing stats

### ISSUE THREAD

**Issue by AntonKost** [splewis/get5#212]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

TBH not sure if it is a bug or a feature :X

### Expected behavior
Saving the actual end score (team1_score = 16 and team2_score = 12 for example) in get5_stats_matches

Saving the played map in get5_stats_matches

### Actual behavior
Played map is missing totaly, just mapnumber is added to the get5_stats_players table.
Just showing a 1 or 0 on team1_score and team2_score

### Steps to reproduce
Just start and finish a scrim with a winner

Unfortunately I'm only into PHP and  MySQL, therefore I can't implement that by myself :(

Maybe with a little help I could extend the stats and could contribute things

- Plugin version: 0.5.5
- Sourcemod version: 1.8 - build 6038

**Comment by splewis** [comment]
I ran a test with get5_scrim and all the values in ``get5_stats_maps``, ``get5_stats_matches``, and ``get5_stats_matches`` were correct. I'm going to need to see the actual tables you got and full steps to reproduce, since I can't find any problems.


> Plugin version: 0.0.5

That version doesn't exist. I'd suggest just following https://github.com/splewis/get5/wiki/Debugging-help#getting-a-debug-dump

**Comment by AntonKost** [comment]
Sorry I've mistyped. I mean version plugin version 0.5.5. Corrected it.

Shame on me, I totaly missed overlooked the get_stats_maps table in my db :(
Sorry for wasting your time splewis!

Anyway, is there a way to get into the statistics thing so I could extend the data which is coming into the db? I mean ofc there is a way but could you maybe provide some info as starting point for me as a only PHP developer?

**Comment by splewis** [comment]
> Anyway, is there a way to get into the statistics thing so I could extend the data which is coming into the db? 

I don't know what that means. You can obviously read from the database however you want. If you mean adding other fields, you'd have to fork the [mysqlstats](https://github.com/splewis/get5/blob/master/scripting/get5_mysqlstats.sp) plugin to record and add extra fields. I'm sure you could also read from the server log and write fields into the database php-only (which is essentially how eBot works), but that seems harder, and would be completely unrelated to get5.
