### ISSUE TITLE
Get5_OnSeriesResult is called much later than it could be

### ISSUE THREAD

**Issue by splewis** [splewis/get5#213]
It gets called in EndSeries, which is typically called after the GOTV delay expires. It should be called much earlier so stats can be updated more quickly.

**Comment by burhan-kun** [comment]
Yes, thats right. After i adding GO TV i become that error. How i can fix this?

**Comment by splewis** [comment]
The only 'fix' is a code change to the get5 plugin. Feel free to send a pull request.
