### ISSUE TITLE
Player name forcing using web client?

### ISSUE THREAD

**Issue by KuzyCS** [splewis/get5#215]
I am not sure how I would go around forcing player's names when I am using the web client.  I understand how you do it if you generate a match.cfg using the plug in but I am using the web only.

If anyone can help me it would be greatly appreciated, thanks.

**Comment by splewis** [comment]
You can't. The web panel doesn't generate a match configs that include player names, and I don't have any plans to add that.

If you really needed player names forced you could just run the sv_load_forced_client_names_file command yourself - that would be just doing it outside of get5.
