### ISSUE TITLE
Feedback request: removal of system2 support

### ISSUE THREAD

**Issue by splewis** [splewis/get5#217]
I'm considering removing support for system2 to cleanup the dependencies and simplify the code paths around (https://github.com/splewis/get5/blob/master/scripting/get5/matchconfig.sp#L198).

If anyone has a good reason why Steamworks doesn't work for them - this is your chance to speak up.

**Comment by splewis** [comment]
system2 support is being removed as of 0.6.0.

**Comment by 4ipalino** [comment]
We are trying to load an json config file over https. Is there a way to achive this with Steamworks? As far as i know Steamwokrs dosen't support https but System2 does.
