### ISSUE TITLE
Veto Logs

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5#218]
Is it possible to get logs of map vetoed in a particular game?

**Comment by Technoblazed** [comment]
You’d need to make a short plugin, utilise the event api here: https://github.com/splewis/get5/wiki/Event-logs

**Comment by keeradfun** [comment]
I will try to make one and share here..

**Comment by Technoblazed** [comment]
What is it you want it to do? Store it in an SQL db?

**Comment by keeradfun** [comment]
Actually, i want vetoes map list should be sent to get5 webapi.

**Comment by splewis** [comment]
> Actually, I want vetoed map list in get5 webapi.

I don't understand what your question is, or if this is a feature request. 

The get5_apistats plugin sends api requests to [this](https://github.com/splewis/get5-web) api implementation. I'm not planning on adding any map veto information to that, so it doesn't make sense to add it to the plugin.

Of course, you're free to use a forked version of the get5_apistats plugin that sends whatever requests you want if you're implementing your own web service as well.

**Comment by keeradfun** [comment]
Ok got it. Thanks for the time.
