### ISSUE TITLE
get5_apistats Sending Map finish request 3 times

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5#219]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
In bo1 matches, the get5_apistats supposed to send single request to get5web URL for example "http://get5weburl/match/matchid/map/0/finish/"

### Actual behavior
But its sending 3 requests back to back adding extra map id's
According to logs.
L 12/23/2017 - 19:54:47: [get5_api] Trying to create request to url http://0.0.0.0/match/905/map/0/finish
L 12/23/2017 - 19:54:47: [get5_api] Added param key=7798ZSPSD1Z16BH69V20O7MY to request
L 12/23/2017 - 19:54:47: [get5_api] Added param team1score=9 to request
L 12/23/2017 - 19:54:47: [get5_api] Added param team2score=0 to request
L 12/23/2017 - 19:54:47: [get5_api] Added param winner=team1 to request
L 12/23/2017 - 19:54:52: [get5_api] Trying to create request to url http://0.0.0.0/match/905/map/1/finish
L 12/23/2017 - 19:54:52: [get5_api] Added param key=7798ZSPSD1Z16BH69V20O7MY to request
L 12/23/2017 - 19:54:52: [get5_api] Added param team1score=9 to request
L 12/23/2017 - 19:54:52: [get5_api] Added param team2score=0 to request
L 12/23/2017 - 19:54:52: [get5_api] Added param winner=team1 to request
L 12/23/2017 - 19:54:52: [get5_api] Trying to create request to url http://0.0.0.0/match/905/map/2/finish
L 12/23/2017 - 19:54:52: [get5_api] Added param key=7798ZSPSD1Z16BH69V20O7MY to request
L 12/23/2017 - 19:54:52: [get5_api] Added param team1score=9 to request
L 12/23/2017 - 19:54:52: [get5_api] Added param team2score=0 to request
L 12/23/2017 - 19:54:52: [get5_api] Added param winner=team2 to request
L 12/23/2017 - 19:54:54: [get5_api] Trying to create request to url http://0.0.0.0/match/905/finish
L 12/23/2017 - 19:54:54: [get5_api] Added param key=7798ZSPSD1Z16BH69V20O7MY to request
L 12/23/2017 - 19:54:54: [get5_api] Added param winner=team1 to request
L 12/23/2017 - 19:54:54: [get5_api] Added param forfeit=0 to request
L 12/23/2017 - 19:54:54: [get5_api] get5_web_api_url now set to http://0.0.0.0
L 12/23/2017 - 19:54:54: [get5_api] get5_web_api_url now set to 
L 12/23/2017 - 19:54:59: [get5_api] Trying to create request to url match/905/finish
L 12/23/2017 - 19:54:59: [get5_api] Trying to create request to url match/905/finish
L 12/23/2017 - 19:55:17: [get5_api] Trying to create request to url match/905/finish

### Steps to reproduce
- Plugin version:  get5 0.5.5-Dev
- Sourcemod version: 1.8.0.6039

**Comment by splewis** [comment]
Can you provide steps to reproduce? How was the match configured?

> Plugin version: get5 0.5.5-Dev

Can I get a commit or build number?

**Comment by splewis** [comment]
No steps to repro. Closing.
