### ISSUE TITLE
How would you do a BO5 with a 1-0 advantage?  And is it possible to give somone "Admin" on the webclient?

### ISSUE THREAD

**Issue by KuzyCS** [splewis/get5#221]
Is there a way to give a team 1-0 advantage in a Best of 5 series?  And with this how would you change the map veto for this series?

And is there a way to give steam ids "admin" on the web client so that they can edit matches created by other people.  Also, how do you whitelist specific steam ids to create matches?

Thanks.

**Comment by splewis** [comment]
https://github.com/splewis/get5#team-schema:
- series_score: current score in the series, this can be used to give a team a map advantage or used as a manual backup method, defaults to 0

You edit the admin list in the config:
https://github.com/splewis/get5-web/blob/master/instance/prod_config.py.default#L54

It should look something like
```
ADMIN_IDS = [764135612361626, 7641356123616267, 764135612361628] 
```

(or whatever the steam64 ids you have are)
