### ISSUE TITLE
Game stucks on "going live" state

### ISSUE THREAD

**Issue by Pupsick** [splewis/get5#222]
### Actual behavior
Sometimes game stucks on "going live" state. Players just staying at spawn and cant move at all.

### Steps to reproduce
Unknown

https://pastebin.com/AbEqTDh4 - debuginfo

- Plugin version:  0.5.5
- Sourcemod version: 1.8.0.5991

P.S. Actually meets like 5-10 games per day(of 700-1000) with this bug.

**Comment by splewis** [comment]
Can you tell me what your cvar values are for:
- get5_live_countdown_time
- mp_match_restart_delay

**Comment by Pupsick** [comment]
"mp_match_restart_delay" = "120"
get5_live_countdown_time "5"

Would i try to set mp_match_restart_delay a bit less? like 15.
May it cause any issue if new game is starting when countdown of mp_match_restart_delay is still going on?

**Comment by splewis** [comment]
I asked about those cvars since they're the only ones referenced in https://github.com/splewis/get5/blob/master/scripting/get5/goinglive.sp

I don't think changing them would help (I was mainly looking to see if one of them was 0). I've never seen this happen and I have no idea what would cause this.

**Comment by Pupsick** [comment]
Okay. I will test it by myself and then give you a solution, just in case.

**Comment by Pupsick** [comment]
ah. seems like this was caused by apistats plugin in case website rejecting the request.
i'm still rtesting.

**Comment by Pupsick** [comment]
I'll post some temporary information over here. May be you'll have any ideas what is going on.
Actual behaviour:
1. Warmup timer goes on and stucks on 0:01
2. Players cant move and do anything

Some temp info about debugging:
`L 01/26/2018 - 19:48:35: [get5][27034] StartGoingLive
L 01/26/2018 - 19:48:35: [get5][27034] Timer for 10.000000 created
L 01/26/2018 - 19:48:35: [get5][2703427034] get5_event: {
    "params": {
        "map_name": "aim_map",
        "map_number": 0
    },
    "matchid": "34271",
    "event": "going_live"
}
L 01/26/2018 - 19:48:35: [get5_api][27034] Trying to create request to url http://host/api/match/34271/map/0/start
L 01/26/2018 - 19:48:35: [get5_api][27034] Added param key=a3a581463a6c8e4asdd111cecdd2asd to request
L 01/26/2018 - 19:48:35: [get5_api][27034] Added param mapname=aim_map to request`
Nothing else going after this in logs. 

So may be you know any cases why timer can stuck at 0:01?
Actually seems like the problem not in get5, right here https://github.com/splewis/get5/blob/master/scripting/get5/util.sp
`
stock void EndWarmup(int time = 0) { }
`
Have no idea how to test it now, but i'm still trying.

**Comment by Pupsick** [comment]
Finally, i changed the plugin and enabled the 0 value of g_LiveCountdownTimeCvar.
I've done this to try this part of code: https://github.com/splewis/get5/blob/master/scripting/get5/util.sp#L197
I was wondering like i can disable this warmup timer on live countdown, but seems like all of the csgo timers are broken at this point.
Actually, we clipped that moment.
https://clips.twitch.tv/HelplessRefinedKumquatBibleThump
P.S. Actually game stucks not only on going live state. In case we have knife round - it stucks on it.
At this situation like above - it stucks on "live" state.
P.P.S. At this point i'm out of ideas again.

**Comment by Pupsick** [comment]
Think we can close it.
Seems like issues were caused by overloaded server.
I just freed some memory and reduced cp load - seems okay now.
