### ISSUE TITLE
Event log to file output not JSON

### ISSUE THREAD

**Issue by bluestreek18** [splewis/get5#223]
### Expected behavior
Event log outputs JSON with timestamps as detailed in the documentation

### Actual behavior
^R�1�f^C�+^@�^Lp��?�ԧ��}�����Y^C^@X;˷Z�^B�^F^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^$
^G^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
^Ycash_team_rescued_hostage^R^C600
&
!bot_autodifficulty_threshold_high^R^A0
&
^^cash_team_win_by_defusing_bomb^R^D3500
^N
        game_mode^R^A1
!
^\mp_ggtr_bomb_pts_for_upgrade^R^A2
^N
        bot_quota^R^A0
#
^[ff_damage_reduction_bullets^R^D0.33

Just looking at the .log file created for that match with nano - also the file is very large. ~20mb for a 5-10 min 1v1 match.

### Steps to reproduce
I added get5_event_log_format "{MATCHID}_map{MAPNUMBER}_{MAPNAME}.log" to my get5.cfg inside cfg/sourcemod/

- Plugin version:
0.5.5
- Sourcemod version:
6040

Maybe im missing something really obvious or misunderstanding the documentation. Any help would be great. Thanks

**Comment by splewis** [comment]
I can't reproduce any problems. 

Do you have exact steps to reproduce this (a match config, at least)?

**Comment by bluestreek18** [comment]
I did not properly install SMJansson. Thanks for the help. I should have checked my server log more carefully.
