### ISSUE TITLE
There is no match setup.

### ISSUE THREAD

**Issue by MetalsnakeMC** [splewis/get5#227]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
I think it's supposed to start.

### Actual behavior
There is no match setup.

### Steps to reproduce
We put the match.cfg in the right folder.

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:

**Comment by tAtU87** [comment]
There is no match setup
how can i fix it ? help pls

**Comment by tAtU87** [comment]
i can't  join  the server

**Comment by MikkelDK** [comment]
@tAtU87 

Try read this: https://github.com/splewis/get5/wiki/Full-list-of-get5-cvars
You need to disable this: **get5_kick_when_no_match_loaded**

**Note: these are auto-executed on plugin start by the auto-generated (the 1st time the plugin starts) file cfg/sourcemod/get5.cfg.** (You can find the command on get5.cfg (cfg/sourcemod/get5.cfg)

**Comment by tAtU87** [comment]
thank you bro for help <3
