### ISSUE TITLE
Failed to load match config

### ISSUE THREAD

**Issue by MetalsnakeMC** [splewis/get5#228]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Match is supposed to load.

### Actual behavior
Failed to load match config.
L 02/14/2018 - 01:03:49: rcon from "167.114.174.219:55222": command "get5_loadmatch match.cfg"

Failed to load match config.
L 02/14/2018 - 01:03:49: rcon from "167.114.174.219:55222": command "get5_loadmatch match"

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:

**Comment by MetalsnakeMC** [comment]
Sure. 

![thingy](https://user-images.githubusercontent.com/12903823/36228805-418262a4-11a3-11e8-9c39-475da6e5cc6f.PNG)

https://pastebin.com/920JX7rT

**Comment by Technoblazed** [comment]
Afaik, `get5_loadmatch` reads relative to the root directory, so you'd need to use, `get5_loadmatch "addons/sourcemod/configs/match.cfg"`

**Comment by MetalsnakeMC** [comment]
Ohhh. Wow, such an easy fix that I never would have gotten. Thanks!

**Comment by MetalsnakeMC** [comment]
I lied. It still doesn't seem to be working

**Comment by Technoblazed** [comment]
Whoops missed a folder out:

```
get5_loadmatch "addons/sourcemod/configs/get5/match.cfg"
```

**Comment by ErcouldnT** [comment]
Hello,

Is there any possible way to send match config through rcon command to server? Maybe as JSON?

**Comment by ericstgo87** [comment]
get5_loadmatch_url "https://your-url-here/test_match.json"

**Comment by ErcouldnT** [comment]
@ericstgo87 Oh, I thank you so much!
