### ISSUE TITLE
Unknown commands

### ISSUE THREAD

**Issue by MetalsnakeMC** [splewis/get5#229]
### Expected behavior
When I type 
get5_loadmatch "addons/sourcemod/configs/get5/match.cfg" it was working

### Actual behavior
It was just working, now it's saying unknown command for every get5 command.

### Steps to reproduce

https://pastebin.com/QmpuZdjb

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:

**Comment by splewis** [comment]
Check your error logs: https://github.com/splewis/get5/wiki/Debugging-help#getting-error-logs

**Comment by MetalsnakeMC** [comment]
I can't seem to find any error logs.  This is the only one I can find.
![rip](https://user-images.githubusercontent.com/12903823/36330421-8b83e5fe-1337-11e8-8293-981fa6e146d3.PNG)

**Comment by splewis** [comment]
If you don't have any sourcemod logs (``addons/sourcemod/logs``) then there's probably some seriously wrong file permissions on your server that should be resolved first.

**Comment by MetalsnakeMC** [comment]
Alrighty, well not sure how those are resolved so i just reinstalled the server, and I'll try again tomorrow

**Comment by MetalsnakeMC** [comment]
*not sure how to resolve those

**Comment by splewis** [comment]
I'm closing since there's been no followup. Feel free to reopen if you have issues.
