### ISSUE TITLE
Failed to load. Native System2_DownloadFile was not found

### ISSUE THREAD

**Issue by iDentity1337** [splewis/get5#23]
I reinstalled my server for ip reasons, and now after adding the latest development build, the plugin fails to load. In log I can only catch this:
L 05/14/2016 - 16:54:51: [SM] Unable to load plugin "get5.smx": Native "System2_DownloadFile" was not found

I have System2 extension in my extensions folder, also the include in the scripting/include. What am I missing?

**Comment by splewis** [comment]
Not able to reproduce. Can you post the output of:

``sm plugins list`` 
and
``sm exts``

from console/rcon?

**Comment by iDentity1337** [comment]
I will in a minute, my internet decided to shit on me again.

**Comment by iDentity1337** [comment]
[SM] Displaying 10 extensions:
[01] Automatic Updater (1.7.3-dev+5303): Updates SourceMod gamedata files
[02] Webternet (1.7.3-dev+5303): Extension for interacting with URLs
[03] CS Tools (1.7.3-dev+5303): CS extended functionality
[04] BinTools (1.7.3-dev+5303): Low-level C/C++ Calling API
[05] SDK Tools (1.7.3-dev+5303): Source SDK Tools
[06] Top Menus (1.7.3-dev+5303): Creates sorted nested menus
[07] Client Preferences (1.7.3-dev+5303): Saves client preference settings
[08] SQLite (1.7.3-dev+5303): SQLite Driver
[09] SteamWorks Extension (1.2.1): Exposes SteamWorks functions to Developers
[10] SMJansson (2.3.1/3): JSON parser/writer

[SM] Listing 18 plugins:
  01 "Fun Votes" (1.7.3-dev+5303) by AlliedModders LLC
  02 "Client Preferences" (1.7.3-dev+5303) by AlliedModders LLC
  03 "Basic Comm Control" (1.7.3-dev+5303) by AlliedModders LLC
  04 "Reserved Slots" (1.7.3-dev+5303) by AlliedModders LLC
  05 "Anti-Flood" (1.7.3-dev+5303) by AlliedModders LLC
  06 "Nextmap" (1.7.3-dev+5303) by AlliedModders LLC
  07 "Admin Menu" (1.7.3-dev+5303) by AlliedModders LLC
  08 "Admin Help" (1.7.3-dev+5303) by AlliedModders LLC
  09 "Fun Commands" (1.7.3-dev+5303) by AlliedModders LLC
  10 "Basic Chat" (1.7.3-dev+5303) by AlliedModders LLC
  11 "Basic Votes" (1.7.3-dev+5303) by AlliedModders LLC
  12 "Basic Ban Commands" (1.7.3-dev+5303) by AlliedModders LLC
  13 "Sound Commands" (1.7.3-dev+5303) by AlliedModders LLC
  14 "Player Commands" (1.7.3-dev+5303) by AlliedModders LLC
  15 "Admin File Reader" (1.7.3-dev+5303) by AlliedModders LLC
  16 "Basic Info Triggers" (1.7.3-dev+5303) by AlliedModders LLC
  17 "Basic Commands" (1.7.3-dev+5303) by AlliedModders LLC
  18 <Failed> "Get5" (0.2.0-dev) by splewis

https://gyazo.com/8057aedbcabb8196e2ba6550581d0a4c <- i have these in extensions folder

**Comment by iDentity1337** [comment]
Alright, I somehow got it working without installing any extensions. I will close this for now, but I'll have to re-look those extensions again some day.

**Comment by iDentity1337** [comment]
Okay, so I just found out after recompiling the plugin with a few tweaks this error strikes, only your builds work. Compiling works flawlessly, though. You have any idea what may cause this?

**Comment by splewis** [comment]
Probably using wrong/old versions of the extensions' include files.

[This](https://github.com/splewis/get5/blob/master/.travis.yml#L29) is where they come from for my builds.

**Comment by iDentity1337** [comment]
You are a freaking legend. Thanks so much man ! <3
