### ISSUE TITLE
ADMIN ID, unsure if working, unsure how to change

### ISSUE THREAD

**Issue by BloodyIron** [splewis/get5#230]
I'm setting up for a LAN, and I'm seeing a couple small problems:

1. The ADMIN IDs and WHITELIST IDs don't seem to be honoured.
2. I'm not sure on how to change the STEAM64 IDs used for ADMIN IDs and WHITELIST IDs

Based on the documentation ( https://github.com/splewis/get5-web/blob/master/INSTALL.md ), it seems I need to change to the instance folder and modify prod_config.py, then go down a folder and run "
./manager.py db upgrade", however it _feels_ like this isn't being honoured.

Can I get some direction here? Or maybe it's not working?

I tried to intentionally not list my STEAMID in the list, but still have a valid STAEMID in the list (a friend's), so that my user should be unable to make a team, or stuff like that, but I was able to make a team. This is after running that upgrade string, and also restarting apache2.

So, I'm at a loss as to what I'm doing wrong. Or is this a bug?

**Comment by splewis** [comment]
This issue was moved to splewis/get5-web#84
