### ISSUE TITLE
Add api request on warmup init

### ISSUE THREAD

**Issue by Pupsick** [splewis/get5#232]
It would be great if the server sent a api request on map load/warmup start, since map loading may take unpredictably long. 
In this case it will be possible to know exactly when match is loaded and in other cases is something went wrong during loading(in example match isnt loaded after map change)

**Comment by splewis** [comment]
What do you mean by "api request"?

**Comment by Pupsick** [comment]
I've meant request from gameserver to web_api_url the same way like few others: 
/match/{id}/map/{mapid}/start
/match/{id}/map/{mapid}/finish
and others

**Comment by splewis** [comment]
The get5_apistats makes those, and that plugin is specifically meant only for the https://github.com/splewis/get5-web panel. It's not implementing a general purpose API, just one for that panel (it other words: it's not a public API). 

If you want things like that you should be making your own plugin that sends whatever HTTP requests you want.

**Comment by Pupsick** [comment]
Clearly. :)
