### ISSUE TITLE
Detect Forfeit

### ISSUE THREAD

**Issue by bluestreek18** [splewis/get5#233]
There is no way to know a match was forfeit without detecting for yourself who is ready and is is connect/disconnected.

I would think that the series end event when one player never readies up and then causes a forfeit would 
either say what had happened or at least put the other teams score as 1.

```
{ params: 
  { team1_series_score: 0, team: 'none', team2_series_score: 0 },
     matchid: 'example_match_test',
     event: 'series_end' 
  } 
}
```

Perhaps this is considered an enhancement? Is it possible to make the get5 admin says to show up in the server log as this would also solve the problem for me as get5 does mention the forfeit in game.

EDIT: After digging through the code a bit I can see in some places the match winner is set to the team that did not forfeit and it other places it is set to team none. Definitely looks like a bug/inconsistent behavior.

**Comment by splewis** [comment]
3105989f9027536db2fdba767e56a63a93e8e10b should resolve this.

> EDIT: After digging through the code a bit I can see in some places the match winner is set to the team that did not forfeit and it other places it is set to team none. Definitely looks like a bug/inconsistent behavior.

If you have concrete examples that's the case, then feel free to reopen. The only "forfeit" get5 has is if a  team doesn't ready up in time, and that's the case handled in the commit above, so I'm not sure what other code you're referring to.
