### ISSUE TITLE
WaitingForGOTVBrodcastEndingInfoMessage

### ISSUE THREAD

**Issue by FaNNboii** [splewis/get5#234]
Hey, anyone know how i can disable at Matchend that the Server waits 2min until the Game count as finished?

It says: "The map will change once the GOTV broadcast has ended."

Best Regards,
Nico

**Comment by Technoblazed** [comment]
Disable demos, or set your tv_delay to 0. If you remove it without this the server will crash.

**Comment by FaNNboii** [comment]
Ok, tv_delay 0 in server.cfg?

**Comment by Technoblazed** [comment]
gamemode_competitive_server.cfg

**Comment by FaNNboii** [comment]
Thx :)

**Comment by splewis** [comment]
I'm guessing that probably won't work if you have the default live and warmup configs, which also set tv_delay.

**Comment by FaNNboii** [comment]
ok then i change it in these cfgs too

**Comment by Technoblazed** [comment]
Yeah I wasn't sure if they did or not, change the tv_delay value in your warmup/live configs instead of the _server file
