### ISSUE TITLE
Force pause (sm_pause) doesn't work through rcon or server console

### ISSUE THREAD

**Issue by B00steed** [splewis/get5#236]
### Expected behavior
When running sm_pause through rcon, game should be force-paused by admin and does not count as a tactical pause for one of the teams but as a technical pause with no time limit.

### Actual behavior
Running sm_pause (through rcon or server console) throws an error in the console, I can't write it right because I'm on the train home but it's pretty urgent for a LAN tournament tomorrow.
First line is: client index 0 is invalid

### Steps to reproduce
Just run sm_pause through rcon or server console (when a match is in progress and not already paused.

- Plugin version: 0.5.5
- Sourcemod version: 1.8 - build 6041

**Comment by B00steed** [comment]
Also, unrelated but pretty urgent too, how do I add a coach in a team cfg ? So when connecting he will be automatically assigned to coach of his team ?

**Comment by Technoblazed** [comment]
Original issue: https://github.com/splewis/get5/pull/237

Updated issue: You'd need to add the coach as a regular member of the team, once they join the server, they will manually have to join the coach position, this isn't something that can be forced afaik.

**Comment by B00steed** [comment]
@Technoblazed Ok, first of all, much thanks for the quick reply, it is really important to me to figure out a solution or a workaround till tomorrow. 

Regarding the PR, is it fixed or is there a workaround I can use for now ? Because I don't want the team to waste their tactical pauses on technical issues.

**Comment by Technoblazed** [comment]
Download the source, recompile the code with the changes I made, then retest yourself.

**Comment by B00steed** [comment]
Ok, one more thing, is there a way the players can trigger this ? like by using !tech ?

**Comment by Technoblazed** [comment]
Not currently: https://github.com/splewis/get5/issues/62

**Comment by B00steed** [comment]
I can't thank you enough. Will update tomorrow regarding the force-pause issue.

**Comment by B00steed** [comment]
Hey, just got on my PC, after figuring out how to compile on Windows, I'm pretty sure everything went fine, I get no errors when compiling and the smx file is loaded, but I still get the same error when trying to run sm_pause.

Here's the full log:
] rcon sm_pause
L 03/28/2018 - 00:21:10: [SM] Exception reported: Client index 0 is invalid
L 03/28/2018 - 00:21:10: [SM] Blaming: get5_testpause.smx
L 03/28/2018 - 00:21:10: [SM] Call stack trace:
L 03/28/2018 - 00:21:10: [SM]   [0] GetClientAuthId
L 03/28/2018 - 00:21:10: [SM]   [1] Line 474, get5/util.sp::GetAuth
L 03/28/2018 - 00:21:10: [SM]   [2] Line 176, get5/teamlogic.sp::GetClientMatchTeam
L 03/28/2018 - 00:21:10: [SM]   [3] Line 14, get5/pausing.sp::Command_Pause

Pretty sure I compiled correctly and checked the pausing.sp file as well, I will greatly appreciate it if you could give a look.

**Comment by Technoblazed** [comment]
https://github.com/splewis/get5/pull/238

**Comment by B00steed** [comment]
This fixed it. I can't even explain how much trouble you saved me. Can I just copy the .smx file to the server itself (I compiled on my laptop) and it'll work ? Or do I need to copy the updated .sp files as well ?

Anyway, much thanks.

**Comment by Technoblazed** [comment]
Just the .smx will do, the server doesn't actually use the .sp files at all

**Comment by B00steed** [comment]
Ok, thanks a lot again :)
