### ISSUE TITLE
Command !stop works in 50/50

### ISSUE THREAD

**Issue by NUM1337** [splewis/get5#24]
Hello!
Everything works perfect, but! Today i wanted to test out command "!stop". And this is what happend. Backup was succesfully loaded, match was stopped like it supposed to do, but overall score was 0:0 for a map. I was trying to load round 3,4,5 etc. but it's 0:0 all the time, even if the chat output says it's round 3,4,5. In backup files i noticed this:

`"SaveFile"
{
	"timestamp"		"2016-05-15 11:15:10"
	"team1"		"Prownage.pl"
	"team2"		"AlsenTeam.Female"
	"map"		"de_cbble"
	"round"		"8"
	"FirstHalfScore"
	{
		"team1"		"0"
		"team2"		"0"
	}
`

This bug is because i did something wrong with the configuration server?

Best regards, NUM.

**Comment by splewis** [comment]
Not sure what would cause the game's backup system to not record scores properly. I wonder if launching it as casual vs competitive could be why.

**Comment by NUM1337** [comment]
Yea, You were right.. I don't know how i didn't see that im on casual mode, thanks for help! :)
