### ISSUE TITLE
Request team name limit? 

### ISSUE THREAD

**Issue by MikkelDK** [splewis/get5#242]
Hi, 

Is there some way to limit teamname on get5? As example max 10 texts of teamname.

**Comment by Technoblazed** [comment]
Could you be more specific?

**Comment by MikkelDK** [comment]
Yeah it's because. If im using create match. And it do automatic make teamname as example :

Team_Heckman meaηs cat 〔ง°ﺏ°〕ง where the extra is Bugged up, if i win a round. But not Bugged if another team Winner the round. I dont have a screenshot to show :/

**Comment by Technoblazed** [comment]
Are you talking about ingame team name values, or hostname values?

**Comment by MikkelDK** [comment]
ingame team name values

**Comment by Technoblazed** [comment]
And how are those values being set, just through the scrim command, or are you setting them in a match config?

**Comment by MikkelDK** [comment]
Just scrim command. What i remember its command via !get5

**Comment by Technoblazed** [comment]
If I remember correctly, the team names for scrims is just from the scrim_template file, which means that you need to change the value in there yourself. The "Away" team is always set to be called "Away".

**Comment by MikkelDK** [comment]
I was wrongly with scrim -> it was this command: get5_creatematch - Creates and loads a match using the players currently on the server as a Bo1 
(couldnt remember it. so i did turned my PC ON)

About it was possible to limit the team-name values (as example like this)

team_Heckman meaηs cat 〔ง°ﺏ°〕ง 0 - 0 team_Heckman meaηs cat 〔ง°ﺏ°〕ง
to be as example: team_Heckman - team_HeckmanCat

**Comment by MikkelDK** [comment]
@Technoblazed - Do you have some idea. About it was possible for limit the team_name values > for using get5_creatematch? ^^

If there is no fix for that, you guys is welcome to close this.

**Comment by splewis** [comment]
Sorry, I don't really see the value in limiting team names within get5 itself. 

Alternatives would be:
- restricting the player names themselves via another plugin
- creating match configs / having another plugin create them and load them
