### ISSUE TITLE
[TIP/BUG] idea for !tech

### ISSUE THREAD

**Issue by MikkelDK** [splewis/get5#245]
Hi,

It's a good idea to adding possible for using !unpause if !tech is using.

I have tested the plugin with few players/teams, and they say it's NOT possible to using !unpause as normal if !tech is "in use"

So they need to open console and type: sm_unpause.

So it's good idea to adding command => !unpause to be possible for using if !tech is used.

**Comment by Technoblazed** [comment]
Given how the tech pause actually works, I’m not even sure if this is accurate, both teams should be able to unpause themselves

**Comment by MikkelDK** [comment]
Hmm, i did tested with one player (1on1) > and we did both typo !unpause nothing happened. ;/

**Comment by Technoblazed** [comment]
Ah, do you have fixed pause times enabled?

**Comment by MikkelDK** [comment]
I dont think i did. ;o i mean just it (should) works if i doing "!tech" > and after possible for use !unpause e.g :-)

**Comment by Technoblazed** [comment]
https://github.com/splewis/get5/pull/246

**Comment by MikkelDK** [comment]
Nice! ;)

**Comment by splewis** [comment]
This should be resolved now.
