### ISSUE TITLE
[bug] Match not pausing

### ISSUE THREAD

**Issue by jellever** [splewis/get5#247]
### Expected behavior
Game pausing when using sm_pause command or pausing through web panel.

### Actual behavior
Through web interface, the web interface reports that the match is paused (which it isn't) and the command comes back with the following:
04/07/2018 - 17:02:22: [SM] Exception reported: Client index 0 is invalid
L 04/07/2018 - 17:02:22: [SM] Blaming: get5.smx
L 04/07/2018 - 17:02:22: [SM] Call stack trace:
L 04/07/2018 - 17:02:22: [SM]   [0] GetClientTeam
L 04/07/2018 - 17:02:22: [SM]   [1] Line 162, ./scripting/get5/teamlogic.sp::GetClientMatchTeam
L 04/07/2018 - 17:02:22: [SM]   [2] Line 14, ./scripting/get5/pausing.sp::Command_Pause

### Steps to reproduce
Use sm_pause or web panel pause button/ 

[get5_debuginfo.txt](https://github.com/splewis/get5/files/1887922/get5_debuginfo.txt)

- Plugin version: 0.5.5
- Sourcemod version: 1.8.0.6041

**Comment by splewis** [comment]
This should already be fixed in the next version (the call to ``GetClientMatchTeam`` is done later now). 

You can try a [development build](https://ci.splewis.net/job/get5/lastSuccessfulBuild/) which has the fix included.
