### ISSUE TITLE
chataliases?

### ISSUE THREAD

**Issue by Zcamt** [splewis/get5#250]
Am i able to add "chataliases" as i am in pugsetup with editing the "chataliases.cfg"?

**Comment by Technoblazed** [comment]
Edit here and recompile with whatever changes you make: https://github.com/splewis/get5/blob/2811428b451ea003f6a66402170b0bd2d68e034b/scripting/get5.sp#L336

TLDR: no.

**Comment by Zcamt** [comment]
Doesn't seem to work.

**Comment by Technoblazed** [comment]
Define doesn't work.

- Did you actually edit the source code?
- Did you then recompile the source code?

If yes, show me your code changes.

**Comment by Zcamt** [comment]
I've been using PawnStudio to edit the file.
What i've typed in is this:
AddAliasedCommand("r", Command_Ready, "Marks the client as ready");
AddAliasedCommand("rdy", Command_Ready, "Marks the client as ready");
AddAliasedCommand("nr", Command_NotReady, "Marks the client as not ready");
AddAliasedCommand("ur", Command_NotReady, "Marks the client as not ready");
AddAliasedCommand("urdy", Command_NotReady, "Marks the client as not ready");

And I'm pretty sure I recompiled it, at least when i reopen the file, it's all saved.

**Comment by Technoblazed** [comment]
Saving the file doesn't mean it's compiled.

Read this: https://wiki.alliedmods.net/Compiling_SourceMod_Plugins

Compile updated binaries with your changes.

**Comment by Zcamt** [comment]
It's the .sp file I need to compile right?

**Comment by Zcamt** [comment]
Because that link seems to be only for plugins? Not scripts

**Comment by Technoblazed** [comment]
get5.sp

**Comment by Zcamt** [comment]
If i use this: http://www.sourcemod.net/compiler.php
I get this error 

Your plugin failed to compile! Read the errors below:
SourcePawn Compiler 1.7.1
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2014 AlliedModders LLC

/groups/sourcemod/upload_tmp/textuNgFyG.sp(21) : fatal error 182: cannot read from file: "include/get5.inc"

Compilation aborted.
1 Error.

**Comment by Technoblazed** [comment]
You can't use that, you need to download sourcemod and compile it using the binaries.

**Comment by Zcamt** [comment]
I don't think i fully understand that

**Comment by Zcamt** [comment]
It can't be sourcemod from here? https://www.sourcemod.net/downloads.php

**Comment by splewis** [comment]
Customizing chat aliases isn't supported in get5. It might be someday; but it isn't now and teaching users how to compile sourcemod plugins isn't in the scope of these issues.
