### ISSUE TITLE
Remove steam authentication process completely

### ISSUE THREAD

**Issue by Bearbobs** [splewis/get5#252]
I generally use this plugin for lan scrims but problem is that it keepon showing
because of this my server lags..any fixes?

L 04/29/2018 - 11:52:46: [get5.smx] Failed to get steamid for client ΓùóΓùñBobs<2><STEAM_1:1:197114456><>
L 04/29/2018 - 11:52:46: [get5.smx] Failed to get steamid for client ΓùóΓùñBobs<2><STEAM_1:1:197114456><>
L 04/29/2018 - 11:52:46: [get5.smx] Failed to get steamid for client ΓùóΓùñBobs<2><STEAM_1:1:197114456><>

#help appreciated

**Comment by splewis** [comment]
Did you set ``get5_check_auths`` to 0?

**Comment by Bearbobs** [comment]
ya

**Comment by Bearbobs** [comment]
but still its is checking for steam id idk why

**Comment by Bearbobs** [comment]
/ This file was auto-generated by SourceMod (v1.8.0.6041)
// ConVars for plugin "get5.smx"


// Name of a match config file to automatically load when the server loads
// -
// Default: ""
get5_autoload_config ""

// Whether the get5 backup system is enabled
// -
// Default: "1"
get5_backup_system_enabled "1"

// If set to 0, get5 will not force players to the correct team based on steamid
// -
// Default: "1"
get5_check_auths "0"

// Format of the damage output string. Avaliable tags are in the default, color tags such as {LIGHT_RED} and {GREEN} also work.
// -
// Default: "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"
get5_damageprint_format "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format ""

// Path to use when writing match event logs, use "" to disable
// -
// Default: ""
get5_event_log_format ""

// If set to non-zero, this will be the fixed length of any pause
// -
// Default: "0"
get5_fixed_pause_time "30"

// Whether the plugin kicks new clients when no match is loaded
// -
// Default: "1"
get5_kick_when_no_match_loaded "0"

// Config file to exec when the game goes live
// -
// Default: "get5/live.cfg"
get5_live_cfg "get5/live.cfg"

// Number of seconds used to count down when a match is going live
// -
// Default: "10"
// Minimum: "5.000000"
// Maximum: "60.000000"
get5_live_countdown_time "10"

// Number of seconds before a backup file is automatically deleted, 0 to disable
// -
// Default: "160000"
get5_max_backup_age "160000"

// Maximum number of time the game can spend paused by a team, 0=unlimited
// -
// Default: "300"
get5_max_pause_time "300"

// Maximum number of pauses a team can use, 0=unlimited
// -
// Default: "0"
get5_max_pauses "4"

// The tag applied before plugin messages.
// -
// Default: "[{YELLOW}Get5{NORMAL}]"
get5_message_prefix "[{YELLOW}SCRIM{NORMAL}]"

// Whether pausing is allowed.
// -
// Default: "1"
get5_pausing_enabled "1"

// Whether damage reports are printed on round end.
// -
// Default: "0"
get5_print_damage "0"

// Whether pause limits will be reset each halftime period
// -
// Default: "1"
get5_reset_pauses_each_half "0"

// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "0"

// Where match stats are saved (updated each map end), set to "" to disable
// -
// Default: "get5_matchstats_{MATCHID}.cfg"
get5_stats_path_format "get5_matchstats_{MATCHID}.cfg"

// Whether clients can use the !stop command to restore to the last round
// -
// Default: "1"
get5_stop_command_enabled "1"

// Time format to use when creating file names. Don't tweak this unless you know what you're doing! Avoid using spaces or colons.
// -
// Default: "%Y-%m-%d_%H"
get5_time_format "%Y-%m-%d_%H"

// Time (in seconds) a team has to make a !stay/!swap decision after winning knife round, 0=unlimited
// -
// Default: "60"
get5_time_to_make_knife_decision "60"

// Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited
// -
// Default: "0"
get5_time_to_start "0"

// Time (in seconds) from presenting a veto menu to a selection being made, during which a confirmation will be required, 0 to disable
// -
// Default: "2.0"
get5_veto_confirmation_time "2.0"

// Seconds to countdown before veto process commences. Set to "0" to disable.
// -
// Default: "5"
get5_veto_countdown "5"

// Config file to exec in warmup periods
// -
// Default: "get5/warmup.cfg"
get5_warmup_cfg "get5/warmup.cfg"

**Comment by splewis** [comment]
Having looked at the code, the main use of steamids when that cvar is set to 0 is in the stats-collecting code. It should result in a logged error ever kill or other similar stat, but that shouldn't result in any lag.

> problem is that it keepon showing because of this my server lags..any fixes?

Do you have any evidence this is actually causing issues? If there were thousands of logged entries every second in the log I would believe you, but you only showed 3.

I would also make sure get5_check_auths is set to 0 while on the server. You could be setting it in another config (like a match config / scrim template).

Regardless of that: you should probably still see errors, that cvar is poorly named. All it does is say whether to enforce steamid->team locking. The stats system, for example, will still try to get steamids to record stats. Maybe that should be changed.

**Comment by keeradfun** [comment]
@Bearbobs  Are you trying run lan server without glst?

**Comment by Bearbobs** [comment]
i have to reinvite player for 10 man and recreate the server with get5 again 👎
 I will try to do it but at that time error was similar to mine labeling every player on server that hai steam id cannot be found

**Comment by splewis** [comment]
I only care about how often the error is getting logged. 

Do you not have the sourcemod error logs anymore?

**Comment by Bearbobs** [comment]
L 04/21/2018 - 01:23:30: [SM] Unable to load plugin "multi1v1_challenge.smx": Could not find required plugin "[Multi-1v1] Challenge"
L 04/21/2018 - 01:23:30: [SM] Unable to load plugin "retakes_standardallotor.smx": Could not find required plugin "retakes"
L 04/21/2018 - 01:27:51: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:29:58: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:29:58: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:29:58: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:03: [get5.smx] Failed to load match config: Missing "team1" section in match kv
L 04/21/2018 - 01:31:03: [get5.smx] Failed to load match config: invalid match kv
L 04/21/2018 - 01:31:03: [get5.smx] Could not restore from match config "get5_match_config_backup0.txt"
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:31:14: [get5.smx] Failed to get steamid for client ✪Bobs<3><STEAM_1:1:197114456><>
L 04/21/2018 - 01:36:44: SourceMod error session started
L 04/21/2018 - 01:36:44: Info (map "de_mirage") (file "errors_20180421.log")
L 04/21/2018 - 01:36:44: [SM] Unable to load extension "cleaner.ext": Failed to find signature. Please contact the author.
L 04/21/2018 - 01:36:49: [SM] Unable to load plugin "multi1v1_challenge.smx": Could not find required plugin "[Multi-1v1] Challenge"
L 04/21/2018 - 01:36:49: [SM] Unable to load plugin "retakes_standardallotor.smx": Could not find required plugin "retakes"
L 04/21/2018 - 01:39:09: Error log file session closed.
L 04/21/2018 - 01:42:33: SourceMod error session started
L 04/21/2018 - 01:42:33: Info (map "de_mirage") (file "errors_20180421.log")
L 04/21/2018 - 01:42:33: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:15: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:15: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:15: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:21: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:41: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:41: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>
L 04/21/2018 - 01:44:41: [get5.smx] Failed to get steamid for client ✪Bobs<23><STEAM_1:1:197114456><>

**Comment by Bearbobs** [comment]
i got the file

**Comment by Bearbobs** [comment]
[errors_20180428.log](https://github.com/splewis/get5/files/1973366/errors_20180428.log)

**Comment by Bearbobs** [comment]
these are the logs of that day

**Comment by Bearbobs** [comment]
anything else u need @splewis ?

**Comment by splewis** [comment]
Thanks - I'll look into adding a cvar to disable the stats system and we can see if that helps.

**Comment by Bearbobs** [comment]
ty

**Comment by Bearbobs** [comment]
@keeradfun me using skins plugin also becoz of which my glst will get banned

**Comment by splewis** [comment]
Since there's a pretty easy workaround I don't think I'm going to implement this.

If someone sends a pull request to disable stats, then I'll review it, but I don't see much value in this. I'm not going to do extra work for users breaking Valve's server rules.
