### ISSUE TITLE
Consider switch to pure sourcemod json encoding/decoding

### ISSUE THREAD

**Issue by splewis** [splewis/get5#253]
https://github.com/clugg/sm-json

**Comment by khtsn** [comment]
Are there any pros and cons when changing from SMJansson to this?

**Comment by splewis** [comment]
Not requiring users to install the extension is the benefit.

**Comment by splewis** [comment]
This is in progress in the https://github.com/splewis/get5/tree/json-include branch.

One side effect is that the json is output without indentation or line breaks, but removing the SMJAnsson dependency still seems worthwhile.
