### ISSUE TITLE
Disable get5_SetHostName

### ISSUE THREAD

**Issue by wats0N1** [splewis/get5#256]
Hey there,

I was wondering if there is any way to prevent Get5 from changing the hostname to "Get5: (Team1) vs (Team2)" or something like that, I want the hostname to stay like it was before launching Get5.
Is that possible?

Thanks in advance :)

**Comment by Technoblazed** [comment]
Edit the cvar in get5.cfg to be blank

**Comment by wats0N1** [comment]
/cfg/sourcemod/get5.cfg

there is no cvar there which says "get5_sethostname" or anything alike.
Is it the right folder?

**Comment by Technoblazed** [comment]
get5_hostname_format - You didn’t provide a get5 version so I’m not even sure if it’s in the version you’re using

**Comment by wats0N1** [comment]
That cvar is not there either.
I didn't provide a version since i don't know which one we're using and I neither have a clue where I can look that up :/

**Comment by wats0N1** [comment]
This is how the cfg looks, maybe that can help :)

// This file was auto-generated by SourceMod (v1.8.0.6041)
// ConVars for plugin "get5.smx"


// Name of a match config file to automatically load when the server loads
// -
// Default: ""
get5_autoload_config ""

// Whether the get5 backup system is enabled
// -
// Default: "1"
get5_backup_system_enabled "1"

// If set to 0, get5 will not force players to the correct team based on steamid
// -
// Default: "1"
get5_check_auths "0"

// Format of the damage output string. Avaliable tags are in the default, color tags such as {LIGHT_RED} and {GREEN} also work.
// -
// Default: "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"
get5_damageprint_format "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"

// Path to use when writing match event logs, use "" to disable
// -
// Default: ""
get5_event_log_format ""

// If set to non-zero, this will be the fixed length of any pause
// -
// Default: "0"
get5_fixed_pause_time "0"

// Whether the plugin kicks new clients when no match is loaded
// -
// Default: "1"
get5_kick_when_no_match_loaded "0"

// Config file to exec when the game goes live
// -
// Default: "get5/live.cfg"
get5_live_cfg "get5/live.cfg"

// Number of seconds used to count down when a match is going live
// -
// Default: "10"
// Minimum: "5.000000"
// Maximum: "60.000000"
get5_live_countdown_time "10"

// Number of seconds before a backup file is automatically deleted, 0 to disable
// -
// Default: "160000"
get5_max_backup_age "160000"

// Maximum number of time the game can spend paused by a team, 0=unlimited
// -
// Default: "300"
get5_max_pause_time "300"

// Maximum number of pauses a team can use, 0=unlimited
// -
// Default: "0"
get5_max_pauses "0"

// The tag applied before plugin messages.
// -
// Default: "[{YELLOW}Get5{NORMAL}]"
get5_message_prefix "[{YELLOW}Get5{NORMAL}]"

// Whether pausing is allowed.
// -
// Default: "1"
get5_pausing_enabled "1"

// Whether damage reports are printed on round end.
// -
// Default: "0"
get5_print_damage "0"

// Whether pause limits will be reset each halftime period
// -
// Default: "1"
get5_reset_pauses_each_half "1"

// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "0"

// Where match stats are saved (updated each map end), set to "" to disable
// -
// Default: "get5_matchstats_{MATCHID}.cfg"
get5_stats_path_format "get5_matchstats_{MATCHID}.cfg"

// Whether clients can use the !stop command to restore to the last round
// -
// Default: "1"
get5_stop_command_enabled "1"

// Time format to use when creating file names. Don't tweak this unless you know what you're doing! Avoid using spaces or colons.
// -
// Default: "%Y-%m-%d_%H"
get5_time_format "%Y-%m-%d_%H"

// Time (in seconds) a team has to make a !stay/!swap decision after winning knife round, 0=unlimited
// -
// Default: "60"
get5_time_to_make_knife_decision "60"

// Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited
// -
// Default: "0"
get5_time_to_start "0"

// Time (in seconds) from presenting a veto menu to a selection being made, during which a confirmation will be required, 0 to disable
// -
// Default: "2.0"
get5_veto_confirmation_time "2.0"

// Seconds to countdown before veto process commences. Set to "0" to disable.
// -
// Default: "5"
get5_veto_countdown "5"

// Config file to exec in warmup periods
// -
// Default: "get5/warmup.cfg"
get5_warmup_cfg "get5/warmup.cfg"

**Comment by Technoblazed** [comment]
It was added here: https://github.com/splewis/get5/commit/8821a92b85050e1a54b464957aa4388126b20c49 If you've updated since then, you might need to recreate the config file

**Comment by wats0N1** [comment]
well the scripting/get5.sp and scripting/get5/matchconfig.sp both include those cvars as shown, yet it is still not in the get5.cfg.

Would it work if I just added get5_hostname_format "" to the get5.cfg?

**Comment by wats0N1** [comment]
nevermind, it worked, thanks for your help! :)
