### ISSUE TITLE
Disable [READY] / [NOT READY]  shown with teamnames

### ISSUE THREAD

**Issue by xe1os** [splewis/get5#259]
Hi could you please tell me if we can disable the [READY] / [NOT READY] suffix with teamnames.
Thanks

**Comment by Technoblazed** [comment]
Replace https://github.com/splewis/get5/blob/master/scripting/get5/util.sp#L260-L270 with 

```cpp
if ((g_GameState == GameState_Warmup || g_GameState == GameState_PreVeto) &&
      !g_DoingBackupRestoreNow) {
    MatchTeam matchTeam = CSTeamToMatchTeam(csTeam);
    if (IsTeamReady(matchTeam)) {
      Format(taggedName, sizeof(taggedName), "%T %s", "ReadyTag", LANG_SERVER, name);
    } else {
      Format(taggedName, sizeof(taggedName), "%T %s", "NotReadyTag", LANG_SERVER, name);
    }
  } else {
    strcopy(taggedName, sizeof(taggedName), name);
  }
```

with just 

```cpp
strcopy(taggedName, sizeof(taggedName), name);
```

in utils.sp, and recompile.

**Comment by xe1os** [comment]
@Technoblazed thanks for the help. Like u said, i have replaced `strcopy(taggedName, sizeof(taggedName), name);` in util.sp and started the server.
Still shows Ready/Not ready tags to teamname. How do i recompile?`
