### ISSUE TITLE
Invalid JSON Upon 'loadmatch_url'

### ISSUE THREAD

**Issue by dechristopher** [splewis/get5#26]
Hey Sean,

I'm making an attempt to load a match.json file using the get5_loadmatch_url command. It keeps telling me that there is no "team1" section. I'm using the exact format described in your included example_match.json file and there seem to be no extraneous brackets or missing commas anywhere. I saw you possibly updated the format of the KeyValue match configs and didn't touch the JSON config in the same commit. I don't know if you changed anything with JSON parsing and forgot to update the documentation, but here's the file I'm using for reference: http://pastebin.com/7qkKP9zZ

Thanks in advance for any help you can give me.

### Steps to reproduce
- Plugin version: latest dev
- Sourcemod version: latest dev

**Comment by splewis** [comment]
The get5_loadmatch_url command just fetches the file, saves it to a file ``csgo/remote.json``, then does the same parsing as the regular get5_loadmatch command. You should check to see if that file exists, and what its contents are.

**Comment by dechristopher** [comment]
I suspect this to be an issue with including http(s):// in front of the URL you are passing to the command. I tested this on multiple webservers across the internet that I have access to and the story's the same for all of them. When including http(s):// the plugin responds with:

`Could not resolve host 'http'`

I suspect this to be an issue with the way the plugin parses the URL. You could possibly check for any http(s):// in the URL given and trim it off of the string. Hope this helps. Plugin works flawlessly other than that one thing.

**Comment by splewis** [comment]
There's a limitation in getting command arguments when a : is parsed that tends to terminate the argument string there. Not sure that there is a fix other than not including http:// in urls.

**Comment by dechristopher** [comment]
Gotcha, thanks a lot for the prompt replies.
