### ISSUE TITLE
How do i add more maps to the mappool?

### ISSUE THREAD

**Issue by ChrizHV** [splewis/get5#261]
How can i add more maps to the mappool?

**Comment by Technoblazed** [comment]
Edit your `maplist` section of your match config https://github.com/splewis/get5/blob/master/configs/get5/example_match.cfg#L22-L31

**Comment by ChrizHV** [comment]
@Technoblazed What if i use the Web panel, and the map pool is limited on the website. How do i use the web panel but different maps. Thank you for replying

**Comment by Technoblazed** [comment]
Firstly, https://github.com/splewis/get5-web is the webpanel repository, create issues for that there.

Secondly, https://github.com/splewis/get5-web/blob/master/instance/prod_config.py.default#L25-L35 edit here

**Comment by ChrizHV** [comment]
@Technoblazed My bad, But i'm using the public version that is working https://get5.splewis.net/

Is there anyways to use that, and then use custom maps?

**Comment by Technoblazed** [comment]
You'd need to selfhost if you want to use custom maps, there's an installation guide in the wiki.
