### ISSUE TITLE
Make sure gotv can see calls to Get5_MessageToAll

### ISSUE THREAD

**Issue by splewis** [splewis/get5#263]
Implementation at https://github.com/splewis/get5/blob/master/scripting/get5/natives.sp#L85

**Comment by vilchez521** [comment]
Something like this:

The map will change once the GOTV broadcast has ended.

**Comment by splewis** [comment]
I don't see what that particular Get5_MessageToAll call has to do with this issue at all.

**Comment by vilchez521** [comment]
because when you change map in bo3 if waiting for the tv to finish the broadcast, instead when the mapveto do so in the same way so that casters can see the veto of maps

**Comment by vilchez521** [comment]
You could implement a command that can extract these maps?

**Comment by splewis** [comment]
I'm not sure what you're asking exactly. Map veto info is already in the event logs published: https://github.com/splewis/get5/wiki/Event-logs#series-flow

**Comment by vilchez521** [comment]
I've been able to find it by typing the command get5_status, but in bo3, for example, 2 maps, are just me 3 not

**Comment by splewis** [comment]
Moved to https://github.com/splewis/get5/issues/279

I doubt I ever implement it myself, though.
