### ISSUE TITLE
!tech pause dont work

### ISSUE THREAD

**Issue by vilchez521** [splewis/get5#265]
!tech pause dont work but !pause yes.

**Comment by splewis** [comment]
You need to provide a version number. It's asked for in the default template for a reason.

**Comment by splewis** [comment]
Can you post your match config and check the value of ``get5_allow_technical_pause``?

**Comment by vilchez521** [comment]
`// This file was auto-generated by SourceMod (v1.8.0.6041)
// ConVars for plugin "get5.smx"


// Name of a match config file to automatically load when the server loads
// -
// Default: ""
get5_autoload_config ""

// Whether the get5 backup system is enabled
// -
// Default: "1"
get5_backup_system_enabled "1"

// If set to 0, get5 will not force players to the correct team based on steamid
// -
// Default: "1"
get5_check_auths "1"

// Format of the damage output string. Avaliable tags are in the default, color tags such as {LIGHT_RED} and {GREEN} also work.
// -
// Default: "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"
get5_damageprint_format "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"

// Path to use when writing match event logs, use "" to disable
// -
// Default: ""
get5_event_log_format ""

// If set to non-zero, this will be the fixed length of any pause
// -
// Default: "0"
get5_fixed_pause_time "90"

// Whether the plugin kicks new clients when no match is loaded
// -
// Default: "1"
get5_kick_when_no_match_loaded "1"

// Config file to exec when the game goes live
// -
// Default: "get5/live.cfg"
get5_live_cfg "get5/live.cfg"

// Number of seconds used to count down when a match is going live
// -
// Default: "10"
// Minimum: "5.000000"
// Maximum: "60.000000"
get5_live_countdown_time "10"

// Number of seconds before a backup file is automatically deleted, 0 to disable
// -
// Default: "160000"
get5_max_backup_age "900"

// Maximum number of time the game can spend paused by a team, 0=unlimited
// -
// Default: "300"
get5_max_pause_time "0"

// Maximum number of pauses a team can use, 0=unlimited
// -
// Default: "0"
get5_max_pauses "2"

// The tag applied before plugin messages.
// -
// Default: "[{YELLOW}Get5{NORMAL}]"
get5_message_prefix "[{YELLOW}KOSLEAGUE{NORMAL}]"

// Whether pausing is allowed.
// -
// Default: "1"
get5_pausing_enabled "1"

// Whether damage reports are printed on round end.
// -
// Default: "0"
get5_print_damage "1"

// Whether pause limits will be reset each halftime period
// -
// Default: "1"
get5_reset_pauses_each_half "1"

// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "0"

// Where match stats are saved (updated each map end), set to "" to disable
// -
// Default: "get5_matchstats_{MATCHID}.cfg"
get5_stats_path_format "get5_matchstats_{MATCHID}.cfg"

// Whether clients can use the !stop command to restore to the last round
// -
// Default: "1"
get5_stop_command_enabled "1"

// Time format to use when creating file names. Don't tweak this unless you know what you're doing! Avoid using spaces or colons.
// -
// Default: "%Y-%m-%d_%H"
get5_time_format "%Y-%m-%d_%H"

// Time (in seconds) a team has to make a !stay/!swap decision after winning knife round, 0=unlimited
// -
// Default: "60"
get5_time_to_make_knife_decision "60"

// Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited
// -
// Default: "0"
get5_time_to_start "0"

// Time (in seconds) from presenting a veto menu to a selection being made, during which a confirmation will be required, 0 to disable
// -
// Default: "2.0"
get5_veto_confirmation_time "8.0"

// Seconds to countdown before veto process commences. Set to "0" to disable.
// -
// Default: "5"
get5_veto_countdown "5"

// Config file to exec in warmup periods
// -
// Default: "get5/warmup.cfg"
get5_warmup_cfg "get5/warmup.cfg"
`
My config, but i dont see get5_allow_technical_pause

**Comment by Technoblazed** [comment]
If you updated the plugin on the server, you will need to regenerate the config file, either delete the file and restart to regenerate, or manually add the cvars yourself

**Comment by splewis** [comment]
Can you actually provide steps to reproduce? What commands are you running? Are you using a match config? 

Also I don't particularly care what is in ``get5.cfg`` - you could be setting the cvar elsewhere (like a match config). You should actually look at the value of the cvar on the server when you're testing by doing something like ``sm_cvar get5_allow_technical_pause`` in console.

**Comment by vilchez521** [comment]
If I add it to get5.cfg, still don't have answer put !tech, as if the command !tech wasn't in the list of available commands to interact the players.

One question, is there any way that I can test this I only without having to call to more players?

**Comment by vilchez521** [comment]
But sm_cvar and sm_cvars I do not respond in both leave me unknown command, however, with sm cvars if that answer, but even so is unresponsive when happened sm cvars get5_allow_technical_pause

**Comment by vilchez521** [comment]
Okey, sm cvars get5:

[SM] Listing 30 convars for: Get5
  [Name]                           [Value]
  get5_autoload_config             
  get5_backup_system_enabled       1
  get5_check_auths                 1
  get5_damageprint_format          --> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)
  get5_debug                       0
  get5_demo_name_format            {MATCHID}_map{MAPNUMBER}_{MAPNAME}
  get5_event_log_format            
  get5_fixed_pause_time            90
  get5_game_state                  0
  get5_kick_when_no_match_loaded   1
  get5_last_backup_file            
  get5_live_cfg                    get5/live.cfg
  get5_live_countdown_time         10
  get5_max_backup_age              900
  get5_max_pause_time              0
  get5_max_pauses                  2
  get5_message_prefix              [{YELLOW}KOSLEAGUE{NORMAL}]
  get5_pausing_enabled             1
  get5_print_damage                1
  get5_reset_pauses_each_half      1
  get5_server_id                   0
  get5_stats_path_format           get5_matchstats_{MATCHID}.cfg
  get5_stop_command_enabled        1
  get5_time_format                 %Y-%m-%d_%H
  get5_time_to_make_knife_decisio  60
  get5_time_to_start               0
  get5_version                     0.5.5
  get5_veto_confirmation_time      8.0
  get5_veto_countdown              5
  get5_warmup_cfg                  get5/warmup.cfg

**Comment by Technoblazed** [comment]
`get5_version 0.5.5`

You're not using 0.6.0

**Comment by vilchez521** [comment]
But i update...0.6.0

**Comment by Technoblazed** [comment]
Did you just upload the .sp files, or did you upload the new binaries as well

**Comment by vilchez521** [comment]
All the folder that is in the version 0.6.0

**Comment by Technoblazed** [comment]
The output you just showed to me, clearly displays you're on version 0.5.5, so check again, reupload the new smx files if you have to

**Comment by vilchez521** [comment]
I go back up all the files of the version 0.6.0 then, with this must be solved?

**Comment by Technoblazed** [comment]
Assuming you actually update the plugin, and redo the config as we talked about a while ago, it should be fine

**Comment by vilchez521** [comment]
This afternoon after work I will try again and I will tell you that such.

**Comment by vilchez521** [comment]
Okey, update and work, close pls and thanks!!

**Comment by Technoblazed** [comment]
You close it?

**Comment by vilchez521** [comment]
yes pls, thanks so much!
