### ISSUE TITLE
Clash between practicemode and get5? Money always @ 16k

### ISSUE THREAD

**Issue by secstu** [splewis/get5#266]
### Expected behavior
After entering sm_practicemode_can_be_started 0 to the beginning of the live.cfg money should be 800. 

### Actual behavior
Because practicemode is off the money should change to 800. - it doesn't.
I tried manually entering the command - nothing. Rcon - nothing. Server console - nothing.

### Steps to reproduce
Follow the wiki and download the newest release and install.

- Plugin version: Newest
- Sourcemod version: Newest ( 1.8)

**Comment by Technoblazed** [comment]
- Don't. Use. Newest. As. A. Version. Number.

You're also likely to need to use `sm_exitpractice` to end the practice mode session.

**Comment by secstu** [comment]
Yup that is it!
Thanks
