### ISSUE TITLE
Set the map on the config file

### ISSUE THREAD

**Issue by muc1** [splewis/get5#267]
if there a way to set the map on the json config files?

**Comment by Technoblazed** [comment]
Change `num_maps` to 1, and change the https://github.com/splewis/get5/blob/master/configs/get5/example_match.json#L20-L29 to one map, instead of the full list

**Comment by muc1** [comment]
is that how the get5 web does it?
or i should test?

**Comment by Technoblazed** [comment]
get5-web just generates a match config and has the server access that, so I guess it's now it does it.

**Comment by muc1** [comment]
anything on the api?

**Comment by Technoblazed** [comment]
API stats is for use when you're connecting to a get5-web instance and will be viewable through that interface

**Comment by muc1** [comment]
i want to listen to the api by my self how can i do that?

**Comment by Technoblazed** [comment]
Use get5-web as an example, you'll need to replicate the functionality of that

**Comment by muc1** [comment]
I don't know any python writing in node js. :/

**Comment by Technoblazed** [comment]
I'm "working" on a nodejs port at the minute, but it's on hold whilst I work on other stuff

I'm not going to take you through making it yourself, I don't teach people to code, you'll just need to learn

**Comment by muc1** [comment]
I working on exactly that. Currently listening to the MySQL stats but it's not really efficient so I'm looking for a method to listed to the apistats plugin

**Comment by muc1** [comment]
L 06/22/2018 - 05:22:35: get5_event: {
    "params": {
        "reason": "Cannot play a series of 3 maps with a maplist of 1 maps"
    },
    "matchid": "GQCEHRC8krRJkgb",
    "event": "match_config_load_fail"
}

**Comment by Technoblazed** [comment]
Remove the double quotes around num_maps, looks like you’ve added them to quite a few, refer to the match config example to see which others you need to change

**Comment by muc1** [comment]
around the cvars you must put double quotes and around the config veriables them selves you dont need to.
thanks for help anyway
