### ISSUE TITLE
Some improvement questions

### ISSUE THREAD

**Issue by pupsick** [splewis/get5#269]
Hello!
Few last days i'm working on improving this plugin for me and i finally stucked with two questions, so i will be really thankful if you will answer for some.
1. You announced new feature: 
> Add player_connect and player_disconnect events
So i actually found the handlers implementation of these functions
```
public Action Event_PlayerDisconnect(Event event, const char[] name, bool dontBroadcast) { }
public Action Event_PlayerConnectFull(Event event, const char[] name, bool dontBroadcast) { }
```
Connect event seems work fine but disconnect doesnt.
One thing i realised - there is no hook for disconnect event.
Current list of hooks seems:
  ```
  HookEvent("player_spawn", Event_PlayerSpawn);
  HookEvent("cs_win_panel_match", Event_MatchOver);
  HookEvent("round_prestart", Event_RoundPreStart);
  HookEvent("round_freeze_end", Event_FreezeEnd);
  HookEvent("round_end", Event_RoundEnd);
  HookEvent("server_cvar", Event_CvarChanged, EventHookMode_Pre);
  HookEvent("player_connect_full", Event_PlayerConnectFull);
  HookEvent("player_team", Event_OnPlayerTeam, EventHookMode_Pre);
```
Finally, I guess it's necessary to use something like
`HookEvent("player_disconnect", Event_PlayerDisconnect, EventHookMode_Pre);  `
Am i right?
2. How can i actually handle the moment of warmup start?
My idea is to implement some code on map start and actually match config loaded moment. Sometime(usually after updates) there are some bugs pop after map changem so i want to verify game runs normally.
I tried to verify that at 
`stock void StartWarmup(bool indefiniteWarmup = true, int warmupTime = 60) {`
But it seems to be a bad place to verify that.
Any suggestions?

**Comment by pupsick** [comment]
For the first question solution seems good, but i've also added a check for current gamestate to prevent logging disconnects when there is no any game running, like
`if (g_GameState > Get5State_None) {`
For the second one i did this verification at OnMapStart event.
Just letting you know and still would love to hear your opinion. Probably, i'm missing something so still, waiting.
Thanks. :)

**Comment by splewis** [comment]
1. 
> Am i right? 

Yes. Good catch.

2. 

I'm not actually sure what problem you're trying to solve. Warmup can definitely get in weird states, but with the default live & warmup configs I have never actually had it happen in my usage (the readme also  discourages copy-pasting other ones like the esl one).

**Comment by pupsick** [comment]
Thanks for the quick reply.
2. More simply, the purpose of that idea - i just wanna handle 2 states - when the server recieves get5_loadmatch_url command(that's already done by you) and the second state - when actual match map is loaded. It's mostly needed to notify my clients that server is fully configured to provide their match.
Btw, seems like it works cool at OnMapStarted, so problems are solved. Thanks!
P.S. I also had some questions about forfeit and winner=none params on series end but i feel a bit intrusive already. :)
