### ISSUE TITLE
cmp_warmup_start leading to server crashes

### ISSUE THREAD

**Issue by pupsick** [splewis/get5#272]
Hello again!
I came with some weird issue that occurs on match start and i can't debug it for too long.
### Expected behavior

Server would change the map and start match properly.

### Actual behavior

Something happens and match isnt starting.
Debug log shows like:
```
L 07/05/2018 - 12:55:51: [get5] cleanedUrl (SteamWorks) = website.com/api/164083
L 07/05/2018 - 12:55:51: [get5] Change from state 0 -> 3
L 07/05/2018 - 12:55:51: [get5_api] get5_web_api_url now set to https://website.com/api/
L 07/05/2018 - 12:55:51: [get5] get5_event: {
    "params": {
        "team1_name": "Red Team",
        "team2_name": "Blue Team"
    },
    "matchid": "164083",
    "event": "series_start"
}
```

I've also forked the repo and added more api requests on map loaded, like
```
ge5.sp
public void OnMapStart() {
if (g_GameState == Get5State_Warmup) {
    Call_StartForward(g_OnMapStart);
    Call_PushCell(GetMapNumber());
    Call_Finish();
  }
}

get5_apistats.sp
public void Get5_OnMapStart(int mapNumber) {
		Handle req = CreateRequest(k_EHTTPMethodPOST, "match/%d/map/%d/init", g_MatchID, mapNumber);
		if (req != INVALID_HANDLE) {
			SteamWorks_SendHTTPRequest(req);
		}

		Get5_AddLiveCvar("get5_web_api_key", g_APIKey);
		Get5_AddLiveCvar("get5_web_api_url", g_APIURL);
}
```
So it makes request when map loaded and current gamestate equals to warmup state.
In this case i also receive that request 
`L 07/05/2018 - 12:55:56: [get5_api] Trying to create request to url https://website.com/api/match/164083/map/0/init
`
So that means map is actually loading and at this moment state equals to warmup state.
Then nothing logging for this match and get5_status shows that no match loaded.
So a bit weird issue, not really frequent(for 1k matches occurs 2-3 times) but still annoying.

I'm not sure is this a plugin issue or server, but may be you have any ideas how can i improve logging to catch this.

### Steps to reproduce

Unknown

- Plugin version: 0.7.0-dev
- Sourcemod version: 1.8.0.6040

P.S. Suggest to https://github.com/splewis/get5/blob/master/scripting/get5.sp#L583
Change `g_GameState >= Get5State_Warmup` to `g_GameState > Get5State_Warmup`
P.P.S. I've sent a message to your email @splewis would love to talk with you a bit, if you dont mind. :)

**Comment by splewis** [comment]
Can you comment on why you closed this?

**Comment by pupsick** [comment]
Ehhh, thought it's not get5 related issue.
But now i'm not sure again.
https://crash.limetech.org/qjo5umd22ist
That's crash dump that i've got with accelerator.
Problem occurs 10-20 times per 1000 matches now.
![image](https://user-images.githubusercontent.com/27925161/42734459-f6ae28dc-884c-11e8-8990-10d7b82a4cdc.png)

**Comment by Technoblazed** [comment]
Look's like this issue is also related to the `mp_warmup_start` issue that's in cps

**Comment by pupsick** [comment]
Based on the logs, we can conclude that problem occurs when some command is called.
First of all, i've cleared all of my configs from commands such as "bot_kick" .
The main purpose of this issue - it cant be handled. In case of automatic competition system it's not possible to handle this crashes, so matches are stuck until we reset it.
Regarding seems it's not possible to fix it right now, i'm working on solution just to handle and reset this kind of games when problem occurs.

**Comment by Technoblazed** [comment]
The crash stack you linked is caused around the mp_warmup_start section, same thing is in cps: https://github.com/splewis/csgo-pug-setup/issues/226

**Comment by pupsick** [comment]
Okay. Just wasnt sure what cps means.
`Make sure you have sourcemod 1.9 v6241 or later. If you don't, your server will crash.`
Since i've posted this issue, i've already update my sm to `1.9.0.6241`, so it's still occurs.
Anyway, i'll try the newest build again(6245).

**Comment by pupsick** [comment]
No effect. Still crashing.

**Comment by pupsick** [comment]
So, finally, may be you have any ideas how it can be fixed or just handled somehow?

**Comment by Technoblazed** [comment]
I can’t repro this as it is, and there aren’t really clear steps for it

**Comment by pupsick** [comment]
It seems absolutely random.
Just like i'm re-running the same match config and no error occurs.

**Comment by pupsick** [comment]
Issue seems resolved.
I've reinstalled server and updated both metamod and sourcemod to the latest versions.
Anyway, i've also added a lot of logging stuff. So, next time it will appear - i'll get completely log what's going on. :)
P.S. 

> P.S. Suggest to https://github.com/splewis/get5/blob/master/scripting/get5.sp#L583
Change g_GameState >= Get5State_Warmup to g_GameState > Get5State_Warmup

**Comment by pupsick** [comment]
Just noticing - after few days problem has returned.
The mid solution for me now - is just to reinstall metamod.
After reinstalling metamod everything works fine again.
https://crash.limetech.org/gel4lubniywd

**Comment by pupsick** [comment]
Damn. I'm just pretty done with this. I've tried to dive into binaries, but unfortunately without any success.
I'll keep this open until it fixed.

> The mid solution for me now - is just to reinstall metamod.
Has no effect anymore.

**Comment by pupsick** [comment]
Dont want to be annoying, but... Am i only the one who still stucked with this issue?
https://crash.limetech.org/zl3hvcbzrooo/carburetor
It's still crashing, i'm updating sourcemod like everytime new update coming out and still no effect.

**Comment by splewis** [comment]
That crash dump link doesn't worst (probably set as private?). Generally diagnosing crashes is pretty painful, so there's not much I can do to help.

**Comment by pupsick** [comment]
https://crash.limetech.org/ud7433nac4ys
Problem is still in `cmp_warmup_start` command.

Really sad fact, but servers are crashing too often.

**Comment by nickdnk** [comment]
This still relevant? What is `cmp_warmup_start`? Never hard of that command.
