### ISSUE TITLE
Knife round pauses issue.

### ISSUE THREAD

**Issue by playtonia** [splewis/get5#274]
### Expected behavior
.pause command shouldn't work in knife round and should receive a warning to team that pauses works only when the game is live.

### Actual behavior
1) The message pops up "game will be pause once the game goes to freezetime".
2) Doesn't pause the game but consideres as pause taken and reduces 1 pauses from maximum pause count of the particular team.

### Steps to reproduce

- Plugin version: "0.6.0-dev"
- Source mod version:  1.8.0.6050

**Comment by splewis** [comment]
Pausing working in knife rounds is intended behavior.

**Comment by playtonia** [comment]
Doesn't pause the game but considers as pause taken and reduces 1 pauses from maximum pause count of the particular team.

**Comment by playtonia** [comment]
After doing several tests. This happens only when you try to pause the game on 
WaitingForKnifeRoundDecision
GoingLive.

**Comment by nickdnk** [comment]
Duplicate.
