### ISSUE TITLE
Plugin no longer working.

### ISSUE THREAD

**Issue by deziau** [splewis/get5#278]
Hello, 

So I am not sure what the issue is but since this morning the plugin is not working on the servers and when making a match using the web panel, which gives the "Either get5 or get5_apistats plugin missing" but all of them are installed as it was working fine yesterday on the same server. so i am not sure if this is because of the new cs update but something to look into.

**Comment by splewis** [comment]
https://github.com/splewis/get5/wiki/Debugging-help#getting-a-debug-dump

Check for error logs on your server. 

"the plugin is not working" isn't useful. The default template asks for extra info (like the debug dump described) for a reason.

**Comment by splewis** [comment]
Closing since there's been no useful information given. Feel free to reopen if you can provide the info I asked for.
