### ISSUE TITLE
Display map veto information in more places

### ISSUE THREAD

**Issue by splewis** [splewis/get5#279]
If you're on GOTV, you may not see what happened during the veto. I don't know what can be changed to make that easier.

Clients in spectate (or admins) could have an additional command to expose the veto information. get5_status currently only shows the maps in the series.

**Comment by vilchez521** [comment]
change 

g_MapChangePending = true;
  CreateTimer(10.0, Timer_NextMatchMap);
}

in mapveto.sp and write:

g_MapChangePending = true;
  CreateTimer(90.0, Timer_NextMatchMap);
}

90 second gotv delay and go compile again.

**Comment by splewis** [comment]
I'm fine with a similar change (the number should be based on ``tv_delay`` not a constant), but it should be guarded by a cvar that is disabled by default.

**Comment by vilchez521** [comment]
I've done what I wrote and it has worked perfectly in this way.

**Comment by vilchez521** [comment]
OK, I put in test in a few days.
Thanks!
