### ISSUE TITLE
LO3 is not happening

### ISSUE THREAD

**Issue by ax3rs** [splewis/get5#28]
Hey splewis!
I have updated my server to the latest plugin version (we were on the first version) and now the LO3 is not happening, just a quick restart + text output of "The match will begin in 10 seconds."
Any ideas how to fix? Did you disable it in any version?

**Comment by splewis** [comment]
I removed the lo3 process in favor of a warmup countdown.

**Comment by ax3rs** [comment]
Ah.
Any chance bringing back the old liveon3 include + adding lo3 in the right lines (if needed) will re-enable it? It's kind of a standard to us and we rather do it instead of a normal restart

**Comment by splewis** [comment]
If someone makes a pull request to add it and enabled/disabled through a cvar. Otherwise it's not coming back.

**Comment by ax3rs** [comment]
Ok.
To another question, when there is a match played there is a strange output to the server console:

>  [get5_mysqlstats.smx] Last Connect SQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') VALUES (1, 0, '76561198169357269', 'team1', 23, 'ax3', 8, 15, 0, 0, 0, 5, 1166' at line 1

The map stats gets update, but the player stats don't because of this, pretty sure it's a problem with the MySQL plugin, any fix?

**Comment by splewis** [comment]
Open a separate issue if you think there's a bug. I fixed one recently, but without knowing what version/build you are using and if you have the matching schema I can't help you.
