### ISSUE TITLE
Custom logo without web panel

### ISSUE THREAD

**Issue by STiNG645** [splewis/get5#284]
Can I use a custom logo without a web panel? If possible, please give instructions. And why does not show flag of my country, when I write "UZ" in match config? There is any way to show?

**Comment by splewis** [comment]
You should be able to. It isn't really documented yet. (https://github.com/splewis/get5/issues/158)

 > And why does not show flag of my country, when I write "UZ" in match config? There is any way to show?

Because CS:GO doesn't support a value of "uz" in the mp_teamflag_1 and mp_teamflag_2 cvars. Nothing get5 can do about that.

**Comment by STiNG645** [comment]
> You should be able to. It isn't really documented yet. (#158)

Please, instructions.

**Comment by STiNG645** [comment]
???

**Comment by Technoblazed** [comment]
As you can see in issue 158, it's not done yet.

**Comment by TandelK** [comment]
@STiNG645 are you still looking into this issue ? I think its been ages that this thing might be solved.
