### ISSUE TITLE
forfeit with get5_time_to_start not working properly

### ISSUE THREAD

**Issue by tloesch** [splewis/get5#286]
Bugs appears in combination with the get5-web ui.

### Expected behavior
If the forfeit happens with get5_time_to_start while warmup, the match should be marked as ended.
Getting kicked after the forfeit happens.

### Actual behavior
If the forfeit happens with get5_time_to_start while warmup, the match will not be marked as ended.

**Additional Info:**
- If you press cancel on the get5-web match. You get following message:
`{
"message": "Match already finished"
}`
- You dont get kicked after the forfeit happens (Maybe because i was in an admin account)
- If you try to rejoin the Server the Message "The match has been ended" appears.

### Steps to reproduce

- Set get5_time_to_start to a desired value for example "60".
- Create a Match with the get5-web ui.
- Join the Server and ready up
- Wait till the forfeit happens
- Check the Match Status at the get5-web ui

[get5_debuginfo.txt](https://github.com/splewis/get5/files/2228606/get5_debuginfo.txt)

Let me know if you need some more information.

I reported the issue first at the get5-web repo.
As @Technoblazed mentioned i created a more detailed issue here.

Reference: https://github.com/splewis/get5-web/issues/105

**Comment by splewis** [comment]
> Bugs appears in combination with the get5-web ui.

Have you tried to reproduce it without it? All the UI does is send a match config to the server. It's pretty unlikely I try to reproduce it without having a given match config. 

You can add a "/config" the end of a match url on the get5 web panel to get a config.

**Comment by tloesch** [comment]
I will provide you a match config soon.

**Comment by nickdnk** [comment]
Too old. Reopen if relevant.
