### ISSUE TITLE
Map score shows 0:0 after round restore

### ISSUE THREAD

**Issue by xe1os** [splewis/get5#287]
Hi,

We have noticed a bug after the round backup file is restored from web panel or server console.
Round gets restored but the match score remains 0:0

This happens only when the csgo server is crashed/restarted and if all the players are disconnected from the server.

SourceMod version : 1.9 - build 6248
Get5 Plugin version : 0.6.0
[get5_backup_match12_map0_round14.txt](https://github.com/splewis/get5/files/2280217/get5_backup_match12_map0_round14.txt)

**Comment by splewis** [comment]
Can you provide the backup file you loaded? Without any way to reproduce there's very little chance this will be investigated.

> match score remains 0:0

Do you mean:
- round score in the current map as shown on the scoreboard (I'm guessing you mean this one?)
- series score
- the round score being printed in chat at the end of each round

**Comment by mgjuhler** [comment]
Hi, 
I have had a lot of test matches today and find that some of them store map score and some do not. I didn't think I could find a pattern in which matches it stores the score and which one it does not. I have attached a few from the latest match. I have many more backup files, write if you need more.

Get5 version: 0.7.1
SourceMod Version: 1.9.0.6276
SourcePawn Engine: 1.9.0.6276, jit-x86 (build 1.9.0.6276)
SourcePawn API: v1 = 4, v2 = 12
Compiled on: Mar 28 2019 17:12:25
Build ID: 6276:2bfc349





[get5_backup_files.zip](https://github.com/splewis/get5/files/3113660/get5_backup_files.zip)

**Comment by xe1os** [comment]
@splewis can you please help us.

**Comment by keeradfun** [comment]
Hi,
Found the similar issue as mentioned above, when ever i try to restore the round the match restarts.

    Get5 version: 0.7.1
    SourceMod Version: 1.10.0.6482
    SourcePawn Engine: 1.10.0.6482, jit-x86 (build 1.10.0.6482)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Apr  9 2020 14:58:37
    Built from: https://github.com/alliedmodders/sourcemod/commit/0ac7875
    Build ID: 6482:0ac7875

Recorded the issue - https://youtu.be/IZvBbC7wey8

**Comment by PhlexPlexico** [comment]
I'm fairly certain this was resolved in https://github.com/splewis/get5/pull/652 - so I believe this should be good to close. If you're still running into this issue, feel free to reopen this ticket, or open a new one.

Thanks!
