### ISSUE TITLE
Errors loading a match config

### ISSUE THREAD

**Issue by punkstarharis** [splewis/get5#288]
### Actual behavior
Whenever we try to load get5 match cfg it shows failed to load cfg in console and i found these errors in log file 
https://pastebin.com/xSc1KFT8
my sourcemod is already up to date

### Expected behavior
Match Should start (scrim template is working fine btw)

**Comment by splewis** [comment]
- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

Those are asked for a reason. Your steps to reproduce are the match config you're trying to load.

**Comment by punkstarharis** [comment]
Plugin version : 0.060
Sourcemod version : 6245

Match config : https://pastebin.com/0a3q1BG0a

**Comment by splewis** [comment]
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Attach the file, please (you can drag & drop).

**Comment by punkstarharis** [comment]
its showing we dont that file type
https://pastebin.com/Z2UaWww7

**Comment by punkstarharis** [comment]
at first i tried  team players with steam64id it give same error then i leave it blank and its still giving same error

**Comment by splewis** [comment]
> Aug 11 18:53:03:  KeyValues Error: RecursiveLoadFromBuffer:  got empty keyname in file match_config.txt
Aug 11 18:53:03:  Match, team1, players,
Aug 11 18:53:03:  KeyValues Error: RecursiveLoadFromBuffer:  got empty keyname in file match_config.txt
Aug 11 18:53:03:  Match, team1, (*players*),
Aug 11 18:53:03:  KeyValues Error: RecursiveLoadFromBuffer:  got empty keyname in file match_config.txt
Aug 11 18:53:03:  Match, (*team1*), (*players*),
Aug 11 18:53:03:  Failed to load match config.

You can't use empty strings as keys:
```
		"players"
		{
			// Any of the 3 formats (steam2, steam3, steam64 profile) are acceptable.
			// Note: the "players" section may be skipped if you set get5_check_auths to 0,
			// but that is not recommended. You can also set player names that will be forced here.
			// If you don't want to force player names, just use an empty quote "".
			""		""
			""		""
			""		""
			""		""
			""		""
			""		""
		}
```

**Comment by splewis** [comment]
> at first i tried team players with steam64id it give same error then i leave it blank and its still giving same error

... then post the config?

**Comment by punkstarharis** [comment]
[vicp.txt](https://github.com/splewis/get5/files/2280455/vicp.txt)

**Comment by splewis** [comment]
Closing this since there's been no update.
