### ISSUE TITLE
I can't enter on my server

### ISSUE THREAD

**Issue by Fyatt** [splewis/get5#289]
Well, i don't know why, but i put my steam id on my match archive, and when i start the server, load the match and try to enter in the server, he say "You are not a player in this match". My id isn't wrong, so... help me plz?

```"Match"
{
	"matchid"							"equipe1_vs_equipe2_id0"
	"num_maps"							"3"

	"spectators" 
	{
		"players"
		{
			"STEAM_0:1:438675107"		"Administrador"
			"STEAM_0:0:438609566"		"Espectador"
		}
	}

	"skip_veto"							"1"

	"veto_first"						"team1"

	"side_type"							"standard"

	"maplist"
	{
		"de_cache"						""
		"de_dust2"						""
		"de_inferno"					""
		"de_mirage"						""
		"de_nuke"						""
		"de_overpass"					""
		"de_train"						""
	}

	"players_per_team"					"5"
	"min_players_to_ready"				"1"
	"min_spectators_to_ready"			"0"

	"team1"
	{
		"name"							"Equipe 1"
		"tag"							""
		"flag"							"BR"
		"logo"							""
		"players"
		{
			"STEAM_1:0:99087930"		"Fyat"
		}
	}

	"team2"
	{
		"name"							"Equipe 2"
		"tag"							""
		"flag"							"BR"
		"logo"							""
		"players"
		{
			"STEAM_0:1:438593688"		"Jogador 6"
		}
	}

	"cvars"
	{
		"hostname"						"Teste"
	}
}```

**Comment by Technoblazed** [comment]
Please don't remove the default issue sections. They're there for a reason.

```
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
```

Please add a new comment with the information requested above.

**Comment by splewis** [comment]
> I only want to join my server without disable the "player list" with get5_check_auths 0

Then you shouldn't even bother adding steamids to the match config.

1) How are you setting ``get5_check_auths``?

2) Have you actually checked the value of the ``get5_check_auths`` cvar after being kicked (over rcon or similar)?

**Comment by Fyatt** [comment]
1. get5_check_auths 1
2. yes

**Comment by Fyatt** [comment]
I try in json too, but i have other error in console:

[get5.smx] Failed to load match config: Missing "team1" section in match json
[get5.smx] Failed to load match config: invalid match json

Config in .json:
`{
	"matchid": "teste",
	"num_maps": 1,
	"players_per_team": 1,
	"min_players_to_ready": 1,
	"min_spectators_to_ready": 0,
	"skip_veto": true,
	"veto_first": "team1",
	"side_type": "standard",

	"spectators": {
		"players":
		[
			"STEAM_0:1:438675107" : "Administrador",
			"STEAM_0:0:438609566" : "Espectador"
		]
	},

	"maplist":
	[
	],

	"favored_percentage_team1": 0,
	"favored_percentage_text": "",

	"team1": {
		"name": "Equipe 1",
		"tag": "",
		"flag": "BR",
		"logo": "",
		"players":
		[
			"STEAM_0:0:99087930" : "teste"
		]
	},

	"team2": {
		"name": "Equipe 2",
		"tag": "",
		"flag": "BR",
		"logo": "",
		"players":
		[
			"STEAM_0:0:........" : "teste2"
		]
	},

	"cvars": {
		"hostname": "teste"
	}
}`

**Comment by splewis** [comment]
> How are you setting get5_check_auths?

>1. get5_check_auths 1

That doesn't help. I was expecting something like:
- "in server.cfg"
- "in the match config cvars section"
- "in cfg/sourcemod/get5.cfg"
etc.

Also you told me you were setting it to 0, now to do that you're setting it to 1?

**Comment by splewis** [comment]
That json file you gave is also invalid.
```
		"players":
		[
			"STEAM_0:1:438675107" : "Administrador",
			"STEAM_0:0:438609566" : "Espectador"
		]
```

should be
```
		"players":
		{
			"STEAM_0:1:438675107" : "Administrador",
			"STEAM_0:0:438609566" : "Espectador"
		}
```

Same with the other "players" sections.

**Comment by Fyatt** [comment]
Well, in your example json is wrong...

`{
	"matchid": "example_match",
	"num_maps": 3,
	"players_per_team": 1,
	"min_players_to_ready": 1,
	"min_spectators_to_ready": 0,
	"skip_veto": false,
	"veto_first": "team1",
	"side_type": "standard",

	"spectators": {
		"players":
		[
			"STEAM_1:1:.....",
			"STEAM_1:1:.....",
			"STEAM_1:1:....."
		]
	},

	"maplist":
	[
		"de_cache",
		"de_dust2",
		"de_inferno",
		"de_mirage",
		"de_nuke",
		"de_overpass",
		"de_train"
	],

	"favored_percentage_team1": 65,
	"favored_percentage_text": "HLTV Bets",

	"team1": {
		"name": "EnvyUs",
		"tag": "EnvyUs",
		"flag": "FR",
		"logo": "nv",
		"players":
		{
			"STEAM_0:1:52245092" : "splewis",
			"STEAM_1:1:....." : "",
			"STEAM_1:1:....." : "",
			"STEAM_1:1:....." : "",
			"STEAM_1:1:....." : ""
		}
	},

	"team2": {
		"name": "Fnatic",
		"tag": "Fnatic",
		"flag": "SE",
		"logo": "fntc",
		"players":
		[
			"STEAM_1:1:46796472",
			"STEAM_1:0:78189799",
			"STEAM_1:0:142982",
			"STEAM_1:1:.....",
			"STEAM_1:1:....."
		]
	},

	"cvars": {
		"hostname": "Match server #1"
	}
}
`

**Comment by Fyatt** [comment]
And I've already solved my first problem! Thanks for everything!

**Comment by splewis** [comment]
That example config is also valid. The players section can either be a dictionary of steamid->names or an array of steamids.

What you gave doesn't pass through a JSON linter e.g. https://jsonlint.com/

**Comment by Fyatt** [comment]
Wait, in your example you use [ ]

"spectators": {
	"players":
	[
		"STEAM_1:1:.....",
		"STEAM_1:1:.....",
		"STEAM_1:1:....."
	]

and you say to me change to { }

**Comment by Fyatt** [comment]
Is that i am saying, in your example u use [ ]

**Comment by Fyatt** [comment]
It is because you don't force the user names?

**Comment by splewis** [comment]
Both
```
		{
			"STEAM_0:1:52245092" : "splewis",
			"STEAM_1:1:....." : "",
			"STEAM_1:1:....." : "",
			"STEAM_1:1:....." : "",
			"STEAM_1:1:....." : ""
		}
```

and 

```
		[
			"STEAM_1:1:46796472",
			"STEAM_1:0:78189799",
			"STEAM_1:0:142982",
			"STEAM_1:1:.....",
			"STEAM_1:1:....."
		]
```


are valid (they're both used in the example). The first is a dictionary of steamids to names, and the second is just an array of the steamids. Your first json config was neither of those.

> It is because you don't force the user names?

Yes, you don't have to force them.

**Comment by Fyatt** [comment]
Oh, ok, thx man!
