### ISSUE TITLE
Forceready when all players on server

### ISSUE THREAD

**Issue by nikakhaburzania** [splewis/get5#290]
I was trying to force match to start as soon as all 10 players are on server without them writing .ready, if all of them are on server I want it to go live straight away like on faceit/esea.

I tried "min_players_to_ready"		"0" but it did not work.

any suggestions?

**Comment by splewis** [comment]
There's no support for doing this. The ready system is meant to be used. 

If you want support for starting games with no ready system, you need to make a pull request that makes the necessary changes.

I'd also point out:
>  if all of them are on server I want it to go live straight away like on faceit/esea.

That's true in their matchmaking systems. Not for team-based matches, which is what get5 is concerned with, from the get5 readme:

> No, it is not recommended for your new matchmaking service. It is intended for competitive play, not pickup games.

**Comment by saintplay** [comment]
Hi @splewis, I'm looking into this too. 

> No, it is not recommended for your new matchmaking service. It is intended for competitive play, not pickup games.

So, is this the primary reason why get5 is not recommended for matchmaking use cases? Are there other reasons?

Thanks for your work

**Comment by splewis** [comment]
> So, is this the primary reason why get5 is not recommended for matchmaking use cases? Are there other reasons?

Yes. I have no intention of making or supporting changes or features that are only useful for pickup games/matchmaking systems.

**Comment by splewis** [comment]
As a slight update to what I posted before, I would be willing to merge a pr that disabled the ready system if it was very un-obtrusive to the code and simple. 

I don't know how hard it would be, so I don't know if making it simple enough for my taste is possible.
