### ISSUE TITLE
 Failed to get steamid errors

### ISSUE THREAD

**Issue by Fyatt** [splewis/get5#291]
Whell, when i try to enter in my server, that happen now:

[get5.smx] Failed to get steamid for client _Fyat<2><STEAM_1:0:99087930><>

get5_check_auths was set 1

**Comment by splewis** [comment]
Do you have ``sv_lan`` set to 1?

**Comment by Fyatt** [comment]
I already set to 1 and 0, and above didn't work

**Comment by Fyatt** [comment]
I already set to 1 and 0, and both didn't work

**Comment by splewis** [comment]
Well, then calls to GetSteamAuthId https://github.com/splewis/get5/blob/8ff6312d234a2b78e148313e7f818680297cc5c8/scripting/get5/util.sp#L477 are failing, and I can't tell you why. 

Make sure your server isn't having connection issues, otherwise there's nothing I can do to help.

**Comment by Fyatt** [comment]
oh, ok, thx, i'm going to verify this
