### ISSUE TITLE
Load Match after Server Starts (Help)

### ISSUE THREAD

**Issue by nathanthesnooper** [splewis/get5#292]
If I add `+get5_loadmatch match.json` to my server script, I get `Unknown command "get5_loadmatch"
` because the plugin hasn't loaded yet. Is it possible to do this after the plugin starts? I want to avoid `/cfg/sourcemod/get5.cfg` because I want the match to be variable (ex. get5_loadmatch $match)

**Comment by splewis** [comment]
> Is it possible to do this after the plugin starts?

Sorry, do what? Run the ``get5_loadmatch`` command? You can run it anytime the plugins loaded.

**Comment by nathanthesnooper** [comment]
If I add `get5_loadmatch` to my server script it executes before the plugin loads

**Comment by splewis** [comment]
Yes, so execute the command later. Don't put it in the startup options.

**Comment by nathanthesnooper** [comment]
Would it be possible to configure a match in the startup script and run the match later?

**Comment by splewis** [comment]
Maybe. I don't know what you mean by "startup script", but it sounds like it would be entirely unrelated to get5 itself.

You might be better off just writing a separate plugin that calls [Get5_LoadMatchConfig](https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L100) with the file given by whatever means you want.

**Comment by nathanthesnooper** [comment]
I have found a workaround for the problem. Basically I set an alias in my server start script called "startmatch" with the value of "get5_loadmatch etc"

Then I add "startmatch" to the end of get5.cfg

**Comment by splewis** [comment]
Glad you found a workaround.
