### ISSUE TITLE
Server crashes multiple times

### ISSUE THREAD

**Issue by blauni** [splewis/get5#293]
### Plugins installed
"CS:GO PracticeMode" (1.3.2) by splewis
 "Get5" (0.6.0) by splewis

### Expected behavior
Server shouldn't crash after _"2. Create match with current players"_ or command _"get5_loadmatch match.cfg"_ 

### Actual behavior
Server crashes after loading match configs. Sometimes the first game runs okay after restarting the server, at the end the second game will crash. I just choose "Create match with current players" on the menu or i try the command "get5_loadmatch match.cfg" on the server. Both will crash (1) if i dont restart the server or (2) if im not alone on the server after restart. I attached the error files of source mod and match.cfg. 

[errors_20180821.log](https://github.com/splewis/get5/files/2311378/errors_20180821.log)
[match.txt](https://github.com/splewis/get5/files/2311383/match.txt) (match.cfg)

L 08/22/2018 - 19:31:02: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 08/22/2018 - 19:31:02: [SM] Blaming: get5.smx
L 08/22/2018 - 19:31:02: [SM] Call stack trace:
L 08/22/2018 - 19:31:02: [SM]   [0] GetArrayCell
L 08/22/2018 - 19:31:02: [SM]   [1] Line 30, ./scripting/include/restorecvars.inc::RestoreCvars
L 08/22/2018 - 19:31:02: [SM]   [2] Line 1044, ./scripting/get5.sp::EndSeries
L 08/22/2018 - 19:31:02: [SM]   [4] Call_Finish
L 08/22/2018 - 19:31:02: [SM]   [5] Line 692, ./scripting/get5/util.sp::_DelayFunctionCallback

EDIT: After changelevel map -> Every time the match ends i have to say get5_endmatch or "4. End match" on menu if I dont wait until the server automatically changes the map.

### Steps to reproduce

- Plugin version:  "Get5" (0.6.0) by splewis
- Sourcemod version: SourceMod 1.8.0.6041, by AlliedModders LLC
- Steps to reproduce (please be specific):

1. I stopped the server after installation of the plugin.
2. Activated tv_autorecord 1 and tv_enable 1
3. I started the server.
4. Type get5_loadmatch match.cfg in the console or get5 in chat and choose 2. Create match with current players.
5. Server crashes.
5.1 First game could work fine, a second game (same procedure 1-4) will crash.

**Comment by splewis** [comment]
It may be unrelated, but you should definitely not set tv_autorecord 1.

**Comment by blauni** [comment]
Okay. If i dont set it to 1 i get no replays. The plugin doesnt record the games for me. I know its a bad behavior to have it on 1, but yea.. i got this problem. I think its not important for this bug, but I listed it so you know what I did. 

[get5.txt](https://github.com/splewis/get5/files/2311517/get5.txt)
// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format "\replays\{MATCHID}_map{MAPNUMBER}_{MAPNAME}"

Directory \csgo\replays exists

**Comment by splewis** [comment]
Just noticed:

> Sourcemod version: SourceMod 1.8.0.6041, by AlliedModders LLC

Update to a 1.9 snapshot. SM 1.8 isn't supported on csgo anymore.

**Comment by blauni** [comment]
I will do it. Tomorrow we will try the plugin again.

**Comment by blauni** [comment]
Server didn't crash once with newer version of SourceMod. The plugins still doesnt save any replays.

**Comment by splewis** [comment]
This seems fixed then. If you still have issues with demos, please make a separate issue - keep in mind all get5 does is issue a ``tv_record`` command with the substituted variables from ``get5_demo_name_format ``, though.
