### ISSUE TITLE
Add support to native votes

### ISSUE THREAD

**Issue by pawelxxdd** [splewis/get5#295]
Can you add support to native votes?
**[Plugin Here](https://github.com/BeepFelix/CSGO-MajorVotes)**

**This will use ingame vote system.**

**Comment by splewis** [comment]
I don't plan on adding this.

I might be open to a pull request for it, but I'd need to see what the implementation looks like and what it looks like ingame. Based on what I see in the readme it seems very unstable and prone to issues, so I'd lean toward not adding this.
