### ISSUE TITLE
No get5.smx

### ISSUE THREAD

**Issue by sjicka** [splewis/get5#297]
as title says.... theres not get5.smx in my files

**Comment by MikkelDK** [comment]
Are you sure? 

Try download this: https://github.com/splewis/get5/releases/download/0.6.0/get5_0.6.0.zip

**Comment by Technoblazed** [comment]
Either:

- Compile the source yourself.
- Download a stable build: https://github.com/splewis/get5/releases
- Download a dev build: http://ci.splewis.net/job/get5/lastSuccessfulBuild/

**Comment by sjicka** [comment]
@MikkelDK it's in the one you sent, thanks! I went over my files again though and for some reason isnt there. I tried re-downloading it but to no success. Anyways thank you for helping.

**Comment by Technoblazed** [comment]
@sjicka the green download button on the repo downloads the source.
