### ISSUE TITLE
Changing Prefix

### ISSUE THREAD

**Issue by Michael-GG** [splewis/get5#30]
Problem has been solved

**Comment by dechristopher** [comment]
You'd need to download the source, go into natives.sp in the get5 subfolder and change / remove the prefix in the first line.

**Comment by Michael-GG** [comment]
Thanks for the reply, I've already tried this and it didn't seem to work. Any ideas ? Thanks

**Comment by dechristopher** [comment]
When you edit the source files in the scripting folder (assuming you have the sources installed to a gameserver) you need to run spcomp.exe (or compile.exe I can't remember which) and then a new get5.smx will be compiled and placed in the compiled folder in the scripting directory. You can then grab the new get5.smx and place it into your sourcemod plugins directory and restart the CS server for the changes you made to take effect.

**Comment by Michael-GG** [comment]
When you say "run spcomp.exe". Where do i do this. Sorry for not understanding im new to soucemod plugins.

**Comment by dechristopher** [comment]
If you have SOurceMod installed in a CS:GO server, go to the root folder of the server and navigate to the addons/sourcemod/scripting folder. In there, you'll need to make sure you place all of your edited source files from get5 if they're not already in there and then you'll need to run either compile.exe or spcomp.exe which will both be in that same folder. From there, you'll find the "compiled" folder which will contain a freshly compiled get5.smx which you'll place in your addons/sourcemod/plugins folder. Hope this helps!

**Comment by Michael-GG** [comment]
Thanks for the help :)

**Comment by Michael-GG** [comment]
When i come to compliing it im getting this error : http://prntscr.com/bgh0tn . Im probably doing something stupid. Thanks Again!

**Comment by dechristopher** [comment]
You need to download this file:

https://forums.alliedmods.net/attachment.php?attachmentid=119072&d=1367582350

And place it in the includes folder in the scripting folder. Get5 requires this extension (system2) to compile properly.

**Comment by Michael-GG** [comment]
And now this : http://prntscr.com/bghma5 , I already installed the jansson files. Sorry for all the hassle. Al

**Comment by dechristopher** [comment]
It doesn't seem like you've installed the smjansson includes. Download this:

https://forums.alliedmods.net/attachment.php?s=fb7344680309a98bc7e19df1ec34512c&attachmentid=105506&d=1340554212

Then navigate to the pawn/scripting/include directory in the zip file and extract the smjansson.inc file into the includes folder as well. And don't sweat it.

**Comment by Michael-GG** [comment]
Another error : http://prntscr.com/bghonj

**Comment by ax3rs** [comment]
Update you smjansson include, the one on AlliedModders isn't updated.
Download it from here: https://github.com/thraaawn/SMJansson

**Comment by Michael-GG** [comment]
Changed it. Thanks to All :D
