### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by sjicka** [splewis/get5#300]
Just a bit confused with how to get the demo. Can anyone help?

**Comment by MikkelDK** [comment]
it will often be found under the "csgo" folder called: X_map_.dem what i remember. ;) (ON SERVER!)

**Comment by sjicka** [comment]
> it will often be found under the "csgo" folder called: X_map_.dem what i remember. ;) (ON SERVER!)

The difficulty for me is to start and stop the demo...

**Comment by MikkelDK** [comment]
Well get5 will start demo, so soon the match has [been] started. and after the match has been finished (about it's 16-14 > or OVERTIME) it will automatic stop the demo.

Are you talking about, how to start the demo ingame? > you need to download it down from server > and move to your own csgo (folder) > and using demoui ingame. ^^

**Comment by sjicka** [comment]
Yes, I just don't know how to start it or where it goes on my server. Thank you for helping me though, I'm a noob and it must be tedious.

**Comment by sjicka** [comment]
> Well get5 will start demo, so soon the match has [been] started. and after the match has been finished (about it's 16-14 > or after overtime 15-20 (e.g) it will automatic stop the demo.
> 
> Are you talking about, how to start the demo ingame? > you need to download it down from server > and move to your own csgo (folder) > and using demoui ingame. ^^

For example, what folder does it go to on the server?
and i cant make sense of this: https://github.com/splewis/get5/wiki/Recording-match-demos

**Comment by MikkelDK** [comment]
Demos will always be on csgo folder. On the server via FTP.

**Comment by sjicka** [comment]
> Demos will always be on csgo folder. On the server via FTP.

I was looking for my csgo folder in my server settings though and i couldnt find it

**Comment by TandelK** [comment]
csgo folder is located in main directory of server files where you can find srcds.exe and other Server Start Up files. CSGO folder contains all the game information as well as Addons / CFG which are very well known for installing of Sourcemod and Metamod  which you did before installing Get5

**Comment by TandelK** [comment]
If you have found the demos or no longer required than please @sjicka Close the issue.
