### ISSUE TITLE
Server Name

### ISSUE THREAD

**Issue by RustySpoon1234** [splewis/get5#301]
Hello, My server name is Get5: team_[playername] vs team_[playername]
I would like it to be [My team name] vs. Away. (i.e Team ABC vs. Away)

Is there an easy way to do this?

**Comment by Technoblazed** [comment]
Change `get5_hostname_format` in your `get5.cfg` to 

```
{TEAM1} vs. Away
```

**Comment by splewis** [comment]
Keep in mind if you're using ``get5_creatematch`` command the team name will always be set to ``team_<playername>``. If you expect it to be of the form <team name> vs "away" then you should be using the ``get5_scrim`` command.

**Comment by RustySpoon1234** [comment]
> Keep in mind if you're using `get5_creatematch` command the team name will always be set to `team_<playername>`. If you expect it to be of the form vs "away" then you should be using the `get5_scrim` command.

I have got the away side figured out, but no matter what I do my team still comes up as team_<playername>. I've put in the steamids but its just not working.
