### ISSUE TITLE
get5_mysqlstats dont working

### ISSUE THREAD

**Issue by SennyK22** [splewis/get5#304]
Hello.
Im trying turn on get5_mysqlstats but im have a problem.
In databases.cfg im write:
`"Databases"
{
	"driver_default"		"mysql"
	
	// When specifying "host", you may use an IP address, a hostname, or a socket file path
	
	"default"
	{
		"driver"			"mysql"
		"host"				"localhost"
		"database"			"zsbi"
		"user"				"root"
		"pass"				"password"
		"port"				"3306"
	}

	"get5"
	{
		"driver"			"mysql"
		"host"				"localhost"
		"database"			"zsbi"
		"user"				"root"
		"pass"				"password"
		"port"				"3306"
	}
	
	"storage-local"
	{
		"driver"			"sqlite"
		"database"			"sourcemod-local"
	}

	"clientprefs"
	{
		"driver"			"sqlite"
		"host"				"localhost"
		"database"			"clientprefs-sqlite"
		"user"				"root"
		"pass"				""
		//"timeout"			"0"
		//"port"			"0"
	}
}`

and when Im looking for turned on plugins im see:

```
Errors:
get5_mysqlstats.smx (Get5 MySQL stats): Error detected in plugin startup (see error logs)
```

in logs im have all clear (no one logs files)

Can you help me with it ?Thanks

**Comment by TandelK** [comment]
Are you using same database for all the Plugins i.e. default as well as get5 ?

**Comment by SennyK22** [comment]
I have created tables with this import_stats.sql

**Comment by TandelK** [comment]
> Got the same issue.
> Stats wont get uploaded to the web and the match will be "pending" until i cancel it, even if it's done or not started.
> 
> It's only the get5_mysqlstats.smx that's not working.
> 
> > You ran 100 of 100 tests, 2 failed, 98 passed
> > L 10/03/2018 - 00:21:27: [SM] Exception reported: Could not connect to get5 database: Configuration "get5" not found
> > L 10/03/2018 - 00:21:27: [SM] Blaming: get5_mysqlstats.smx
> > L 10/03/2018 - 00:21:27: [SM] Call stack trace:
> > L 10/03/2018 - 00:21:27: [SM]   [0] SetFailState
> > L 10/03/2018 - 00:21:27: [SM]   [1] Line 61, ./scripting/get5_mysqlstats.sp::OnPluginStart
> > L 10/03/2018 - 00:21:27: [SM] Unable to load plugin "get5_mysqlstats.smx": Error detected in plugin startup (see error logs)
> 
> Line 61 /scripting/get5_mysqlstats.sp
> 
> > ```
> > **SetFailState("Could not connect to get5 database: %s", error);**
> > ```

It clearly says in its Logs that your Database config is not found , Please use databases.cfg  to correct your database settings.

**Comment by TandelK** [comment]
@SennyK22 Do you have condebug command enabled on the server ? If yes , can you run once the server and give me the complete console.log to see the real error causing on the server. Also make sure if you have Linux Server  that the server Sql extension is working properly. Sometimes happen that mysql extension does not work due to dependencies.

**Comment by TandelK** [comment]
Also a small update on Databases.cfg if you have linux Ubuntu specially , change localhost from host to IP which is 127.0.0.1 because as per i remember last time i had issues with Linux Server connecting to localhost host

**Comment by ErcouldnT** [comment]
I have exactly the same error message. Changing both "localhost" to "127.0.0.1" doesn't fix my issue (I have Windows server). Maybe I didn't success about creating database using the import_stats.sql, and I don't know how?

Errors:
get5_mysqlstats.smx (Get5 MySQL stats): Error detected in plugin startup (see error logs)

**Comment by ErcouldnT** [comment]
How can i use "import_stats.sql" to create database? Btw I'm on Windows. Thanks for your help.

**Comment by ErcouldnT** [comment]
How can i use "import_stats.sql" to create database? Thanks for your help.
