### ISSUE TITLE
Pause Issue

### ISSUE THREAD

**Issue by abdulsami34** [splewis/get5#306]
Hello there,
I have set pause time to 50, But its still not working. It's paused for ever.

**Comment by MikkelDK** [comment]
Which command do you have used/set?

**Comment by abdulsami34** [comment]
get5_max_pauses = 4
get5_reset_pauses_each_half = 0
get5_fixed_pause_time = 30
get5_pausing_enabled = 1

What should be the : get5_max_pause_time = ?
I have set that it to 30 as well? Is that correctr?

**Comment by splewis** [comment]
Can you provide a debug dump as described in https://github.com/splewis/get5/wiki/Debugging-help#getting-a-debug-dump?

**Comment by abdulsami34** [comment]
I fixed the issue. But, the tech pause isn't working.
I enabled the tech in cfg as well.

**Comment by splewis** [comment]
> I fixed the issue

How? 

> But, the tech pause isn't working.

As I asked before:  https://github.com/splewis/get5/wiki/Debugging-help#getting-a-debug-dump?

**Comment by splewis** [comment]
Closing since there's not enough of the requested info to diagnose/debug here.
