### ISSUE TITLE
How to enable overtime

### ISSUE THREAD

**Issue by SennyK22** [splewis/get5#307]
Hi guys.. 
Im have problem today..
How I can turn on play-offs when is 15:15?
Thanks

**Comment by jnexlevel** [comment]
mp_overtime_enable 1

**Comment by TandelK** [comment]
Oh my god , guys stop posting non get5 related stuff here. Better you can google it easily.  If it is related to get5 config than you can add this command in cfg/sourcemod/get5/live.cfg 

mp_overtime_enable 1

**Comment by SennyK22** [comment]
Im seraching but im dont know how I can write it. Thanks

**Comment by Technoblazed** [comment]
He literally just told you

**Comment by SennyK22** [comment]
maybe u know how repair scoreboard? when is half and change teams scoreboard is bugging and we must reconnect

**Comment by TandelK** [comment]
@SennyK22 Dont post other stuff in this Question . The Scoreboard has nothing to do with this Mod or Plugin. It is game sided issue or lack of setting cvars properly.

**Comment by splewis** [comment]
>  Can you reference this official Site of CS:GO CVARs inside ReadMe so people dont have to keep on asking silly question https://developer.valvesoftware.com/wiki/List_of_CS:GO_Cvars

Anyone can https://github.com/splewis/get5/pulls :)
