### ISSUE TITLE
First round loss bonus still $1400

### ISSUE THREAD

**Issue by Brian2one0** [splewis/get5#309]
### Expected behavior
Receive $1900 after losing pistol on both sides

### Actual behavior
Only receive $1400 after losing pistol (like before the update)

- Plugin version: 0.6.0
- Sourcemod version: 1.9.0.6256
- Steps to reproduce (please be specific): If you lose pistol you only receive $1400. I changed "mp_starting_losses" to 1 in the bspconvar_whitelist.txt but you still only receive $1400 after losing pistol for the first time.

**Comment by Technoblazed** [comment]
Are you using the provided live.cfg, or a modified one? It's likely you've added something that stops this functionality as I haven't had this issue occur.

**Comment by Brian2one0** [comment]
Yeah it's the provided live.cfg. Do I need to add "mp_starting_losses 1" to that file?

**Comment by Technoblazed** [comment]
Shouldn't need to but you can always give it a go.

**Comment by splewis** [comment]
gamemode_competitive.cfg contains ``mp_starting_losses 1``, so if you launch your server as competitive (``game_type 0; game_mode 1``) the setting should be right.

It should probably also get added to the default live.cfg, though. 

 > bspconvar_whitelist.txt

That file is a whitelist for convars *maps* can set, it's not relevant here.
