### ISSUE TITLE
Can't use default Pausing

### ISSUE THREAD

**Issue by coyotezin** [splewis/get5#314]
### Expected behavior
Use the .pause command and it pauses the match for 300 seconds(5 minutes) and during the pause time it shows the player the time remaining of the pause.

### Actual behavior
Pause gets infinite time and it doesnt show players the time remaining.

### Steps to reproduce
Add this to match config cvars(as mentioned [here](https://github.com/splewis/get5/wiki/Pausing)):

get5_max_pauses = 0
get5_max_pause_time = 300
get5_reset_pauses_each_half = 1
get5_fixed_pause_time = 0
get5_pausing_enabled = 1

- Plugin version: 0.6.0
- Sourcemod version: Stable 1.9.0 6260

**Comment by nickdnk** [comment]
Should be fixed with https://github.com/splewis/get5/pull/547.
