### ISSUE TITLE
Is there a way of adding a set of Steam IDs to be allowed to bypass the whitelist? We use the webpanel and have to manually add 3 steam IDs to the whitelist to every match.

### ISSUE THREAD

**Issue by KuzyCS** [splewis/get5#315]
Just wondering if there's an easier and more efficient way of adding a set of steam IDs to be permanently whitelisted on the server via either the web panel or commands in the server or get5 config.

I'm not sure what github I should assign this to the web panel or the plugin, but I think this issue would most likely to be solved with the plugin rather than the web client.

Thanks in advance.

**Comment by TandelK** [comment]
in cfg/sourcemod/get5.cfg 

// Whether or not admins with the changemap flag will be immune to kicks from "get5_kick_when_no_match_loaded". Set to "0" to disable
// -
// Default: "1"
get5_kick_immunity "1"

This will auto allow admins even when Matches are not loaded .

**Comment by splewis** [comment]
I think the above answer is good - add the users as sourcemod admins and give them immunity from get5.
