### ISSUE TITLE
Possible issue with readysystem after update 5. Nov

### ISSUE THREAD

**Issue by bryggemesel** [splewis/get5#318]
### Expected behavior
Teams type "!ready", -> game starts.

### Actual behavior
Game doesn't start after both teams have written "!ready".

### Steps to reproduce
1. Start 1v1 aim using json:
https://raw.githubusercontent.com/bryggemesel/angrytesti/master/match2.json
2. Have both teams type !ready

- Plugin version: 0.6.0
- Sourcemod version: 1.9

Console.log throws:
L 11/06/2018 - 20:00:24: [SM] Exception reported: Failed to lookup SetClanTag signature.
L 11/06/2018 - 20:00:24: [SM] Blaming: get5.smx
L 11/06/2018 - 20:00:24: [SM] Call stack trace:
L 11/06/2018 - 20:00:24: [SM]   [0] CS_SetClientClanTag
L 11/06/2018 - 20:00:24: [SM]   [1] Line 259, ./scripting/get5/readysystem.sp::UpdateClanTags
L 11/06/2018 - 20:00:24: [SM]   [2] Line 635, ./scripting/get5.sp::Timer_CheckReady

Nothing to note in sourcemod-logfile (addons/sourcemod/logs).

All and any information/suggestions appreciated :)

**Comment by splewis** [comment]
Sourcemod issue.

Wait for https://github.com/alliedmodders/sourcemod/pull/922 to be resolved.
