### ISSUE TITLE
Won't exec Warmup.cfg

### ISSUE THREAD

**Issue by Michael-GG** [splewis/get5#32]
When i load a match config it cannot exec the warmup.cfg and also seems that when the knife round start it doesn't use the knife.cfg becuase players still get pistols and the bomb and the time of the round is only 1:50 instead on 60 minutes. Any help would be great.

Console when exec loadmatch : http://prntscr.com/bgp54u

**Comment by splewis** [comment]
I can't reproduce any issues.

Is there a file called ``warmup.cfg`` in ``csgo/cfg/get5``?

**Comment by Michael-GG** [comment]
Got it to work, Thanks again !
