### ISSUE TITLE
Match End to late

### ISSUE THREAD

**Issue by burhan-kun** [splewis/get5#323]
### Expected behavior
Instant Match End after 16-X. Or in 15 Seconds.

### Actual behavior
On Match End Get5 push the Data 120 Seconds later. Maybe a Server Configuration Variable needed

### Steps to reproduce
Match finishing and waiting for the MYSQL Update

**Comment by TandelK** [comment]
That might be because of GOTV recording  delay . Can you drop your live.cfg and other server.cfg config files in pastebin and share link ?

**Comment by splewis** [comment]
Sounds like the issue in https://github.com/splewis/get5/issues/213.
