### ISSUE TITLE
 Change Remaining Pauses during matches

### ISSUE THREAD

**Issue by superfish-lu** [splewis/get5#324]
I am looking for a way to change the amount of remaining pauses for a team if get5_max_pauses is used.
E.g. when a team is using a pause instead of a !tech.

Is there currently a way where I can see the current amount of pauses left per team and change it if required? Like a SM variable or get5_ command?

If not, is this something that admins would like to be able to do duing a match?

**Comment by TandelK** [comment]
It all depends on the variables you have set them in get5.cfg in cfg/sourcemod/ 

There are several commands of Pauses on starting the server first time. I would really recommend you to read all the description written on them as they give almost 99% info what they are really doing . 

Also !tech command has to be only used by Admins and not Players , if a player request a Technical Pause a Admin on the server should respond and take the technical pause and resolve the issue. 

Also whenever a team uses a Pauses it will say how many pauses are remaining.

**Comment by TandelK** [comment]
Also for finding all the pause related cvars once the server is up i would really recommend you to either use any of the two commands to find all the cvars related to them

1) find pause 
This will find all the cvar related to word pause including the base game cvar and vote allow and other options. This also prints the get5 cvars of pause 
2) find get5_
This will find all the cvars related to Get5 Plugin but will contain all the cvars of get5_ format 

Also for specific CMDs and CVARs there are Sourcemod Commands
sm cvars get5.smx - Prints all the CVars
sm cmds get5.smx - Prints all the Commands of in game that can be used in Console.

**Comment by splewis** [comment]
Generally https://github.com/splewis/get5/wiki/Pausing has most the pause info.

You can change the cvars in a live match; get5 is tracking the pauses used, not how many are left, so changing the max pauses cvar will effectively let each team use more pauses.

Unfortunately there's no command to view the available pauses for each time. I'd be happy to review a pull request that adds it (`get5_status` is a good place to include such information), but I don't plan on adding it myself.
