### ISSUE TITLE
Posting info about team captains before team ready

### ISSUE THREAD

**Issue by NUM1337** [splewis/get5#33]
After a message "Type !ready when ready for voting etc." post message in new line:
**Team captain for {GREEN or teamnameformated}$TEAM_1/2 {NORMAL}is: {GREEN}$TEAM_CAPTAIN_1/2**

If one/two of teams dont have team captain yet, it should post:
**Team captain for $TEAM_1/2 is not selected yet.**

Honestly i think that it will helps a little bit and prevent everyone to writing **!ready** and not knowing how is exacly a team captain, who can vote etc.

This is what i did: I tried to implement this, but i dont know how to request name of the captain from variables (yeah, im stupid)

http://scr.hu/53sa/m65zv - screen

**Comment by NUM1337** [comment]
I tried to implement this, but i dont know how to request name of the captain from variables (yeah, im stupid)

http://scr.hu/53sa/m65zv

**Comment by splewis** [comment]
There are no captains.

**Comment by NUM1337** [comment]
Do i understand it right? First person which join CT or TT have rights to do votes as whole TEAM yes? I wanted to print it out.

**Comment by splewis** [comment]
Anybody on the team can ready them up or !stay/!swap. I don't see enough of an advantage to having explicit captains for something designed for competitive play (I.e. not pugs).

**Comment by NUM1337** [comment]
Hmm.. strange because on my server (i was using old version of plugin and the newest one) only one person can write !ready and its person which joined team 1st. Anyone else can write !ready but without any results.

**Comment by splewis** [comment]
You're right, I had mis-remembered. The "captains" were only meant to be for the veto system, but it looks like I placed it into the ready commands as well: https://github.com/splewis/get5/blob/master/scripting/get5.sp#L513

I'll probably change that.

**Comment by NUM1337** [comment]
Hmm ok, so my idea is no longer worth to implement :P Good that we solved it :)
