### ISSUE TITLE
No access to get5 or practisemode

### ISSUE THREAD

**Issue by LaBishop** [splewis/get5#331]
Hey guys,

I've managed to successfully add the get5! and practisemode to my server, however when i then attempt to access them through the commands, the server responds by telling me I don't have access to these commands. I've made myself and another admins from the step by step but its still not allowing us access.

Could anyone help?

Thanks,

**Comment by splewis** [comment]
You probably messed up how you added the admins. 

If you actually showed what you did to add them someone might be able to help (I'm guessing you edited `addons/sourcemod/configs/admins_simple.ini`?)

**Comment by splewis** [comment]
Without more info I can't really help more here. Feel free to reopen if you have more info.
