### ISSUE TITLE
How do I switch sides in scrim

### ISSUE THREAD

**Issue by ckilian1** [splewis/get5#334]
Whenever I start a scrim it puts everyone on one team how to I change that.

**Comment by splewis** [comment]
Have you read https://github.com/splewis/get5/wiki/Using-get5-for-scrims#adding-your-teams-steamids?

**Comment by splewis** [comment]
Do you have specific questions from that page?

You open configs/get5/scrim_template.cfg and add the steam ids of your players over the placeholders.
