### ISSUE TITLE
Match backups aren't loading

### ISSUE THREAD

**Issue by Lukerayn3r** [splewis/get5#335]
Hi I am just testing out my LAN server before my event and noticed the backup system wasn't working correctly. 

I started a match played 2 rounds so backups were made. I then looked in the csgo dir and found 2 files one was named `get5_backup_matchmatch 1_map0_round2.cfg` and the other was named `backup_round01.txt`. I wasn't sure if there was meant to be 2 files so I just wanted to mention it, when I use the command get5_last_backup_file the file returned is `get5_backup_matchmatch 1_map0_round2.cfg` which didn't seem correct after looking at your examples. I tried to restore this backup anyway using `get5_loadbackup get5_backup_matchMatch 1_map0_round1.cfg` and as expected I got an error saying `failed to find backup file "get5_backup_matchMatch"` the space in the file name is obviously causing an issue but it seems like the whole backup system isn't functioning correctly anyway.

I am using version 0.6.0 which I believe is the latest version. I havent updated the code for about 3 months and I noticed you have made a few commits.

Any help is much appreciated, I am a developer myself so I should understand anything you need me to do.

**Comment by splewis** [comment]
The backup_round01.txt file is from Valve's builtin backup system.

It sounds like you just shouldn't include spaces in your match id. That's probably a fixable bug, but not something I'm going to look into myself (pull requests welcome).

**Comment by Lukerayn3r** [comment]
Oh ok that makes sense so the cfg is your backup file? I will remove the spaces and try again and update but I was also wondering if there was a way to specify which dir the backups are stored in? I am happy to edit some code if you can point me to the file I need to change.

**Comment by splewis** [comment]
https://github.com/splewis/get5/blob/master/scripting/get5.sp#L1095

The reason there's no cvar for the file format like several other get5 cvars (`get5_demo_name_format` & `get5_event_log_format`) is that it needs to support listing all backup files matching the pattern: https://github.com/splewis/get5/blob/master/scripting/get5/backups.sp#L37, so it would take a little extra work to implement correctly.

**Comment by Lukerayn3r** [comment]
I'll just leave it then, If I have time I will start working on it though. Thanks for the help
