### ISSUE TITLE
Dust2 change problem

### ISSUE THREAD

**Issue by sixtt** [splewis/get5#336]
Hello
We are having trouble starting the map dust2.
If we choose dust2 after the map veto does not work.
You lose the connection to the server.

With all other maps it works normally.

Can I have set something wrong?

### Expected behavior
Change the map without interruption after the veto (only problem with dust2).
### Actual behavior
When choosing the dust2 map after the veto, the server loses the connection.
### Steps to reproduce
Starting a game in bo3 mode.

- Plugin version: 0.6.0
- Sourcemod version: 1.9.0.6266
- Steps to reproduce: Starting a game in bo3 mode with veto on.

**Comment by Technoblazed** [comment]
```
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
```

**Comment by TandelK** [comment]
@sixtt Please check csgo/maps folder if you have a map file named de_dust2.bsp and other dust2 files

**Comment by sixtt** [comment]
> @sixtt Please check csgo/maps folder if you have a map file named de_dust2.bsp and other dust2 files

I checked and got the files in the folder. 
Thank you!

**Comment by sixtt** [comment]
> ```
> If making a feature request, you should delete all the pre-filled text here.
> If reporting a bug, fill in the following sections:
> 
> ### Expected behavior
> 
> 
> 
> ### Actual behavior
> 
> 
> 
> ### Steps to reproduce
> 
> Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.
> 
> - Plugin version:
> - Sourcemod version:
> - Steps to reproduce (please be specific):
> ```

I edited my first comment with the information, thank you!

**Comment by splewis** [comment]
Have you tried changing the map to dust2 yourself, without get5 involved?

Providing the actual match config causing your problem may help as well.

**Comment by splewis** [comment]
Closing since there's no follow up here, and unlikely to be get5 related.
