### ISSUE TITLE
Either get5 or get5_apistats plugin missing

### ISSUE THREAD

**Issue by Rottefar** [splewis/get5#337]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Working

### Actual behavior
https://i.imgur.com/8XpprxV.png

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.60
- Sourcemod version: 1.9-6275
- Steps to reproduce (please be specific): Followed the guide u have

**Comment by Technoblazed** [comment]
You are missing the get5 or get5_apistats plugin in the server plugins folder.

Please provide an output of `sm plugins list` in your server console.

**Comment by Rottefar** [comment]
https://i.imgur.com/VxDsqOK.png
here yo go

**Comment by Technoblazed** [comment]
You're missing the smjansson extension.

**Comment by Rottefar** [comment]
where i get this?
