### ISSUE TITLE
How to enable GOTV

### ISSUE THREAD

**Issue by Jargs** [splewis/get5#340]
Tried to enable gotv on the server, dosent seem like gotv is able to join the server

This is what i put in my server.cfg

/////////////////////////////////////////////
// 5on5 esl gotv

sv_hibernate_postgame_delay 180

tv_allow_camera_man 1        	// Auto director allows spectators to become camera man
tv_allow_static_shots 1        	// Auto director uses fixed level cameras for shots
tv_autorecord 1            	// Automatically records all games as GOTV demos.
tv_chatgroupsize 0        	// Set the default chat group size
tv_chattimelimit 8        	// Limits spectators to chat only every n seconds
tv_debug 0                	// GOTV debug info.
tv_delay 90                	// GOTV broadcast delay in seconds
tv_delaymapchange 1        	// Delays map change until broadcast is complete
tv_deltacache 2            	// Enable delta entity bit stream cache
tv_dispatchmode 1            	// Dispatch clients to relay proxies: 0=never, 1=if appropriate, 2=always
tv_enable 1                	// Activates GOTV on server.
tv_maxclients 10            	// Maximum client number on GOTV server.
tv_maxrate 0            	// Max GOTV spectator bandwidth rate allowed, 0 == unlimited
tv_name "DGN - GOTV"    	// GOTV host name
tv_overridemaster 0        	// Overrides the GOTV master root address.
tv_port 27040            	// Host SourceTV port
tv_relaypassword schmetterling 	// GOTV password for relay proxies
tv_relayvoice 0            	// Relay voice data: 0=off, 1=on
tv_snapshotrate 24        	// Snapshots broadcasted per second
tv_timeout 60            	// GOTV connection timeout in seconds.
tv_title "DGN - GOTV"    	// Set title for GOTV spectator UI
tv_transmitall 1            	// Transmit all entities (not only director view)

**Comment by MikkelDK** [comment]
Create a server.cfg
and paste that (gotv configs) in a file (e.g: gotv.cfg)
on the server.cfg - typo:
exec gotv.cfg

problem solved! ;) 
Or you can check my repo(csgoconfigs) how i did make it works. ;)

**Comment by Jargs** [comment]
https://i.imgur.com/Ta6an1O.png

I restarted the server after adding exec gotv.cfg, and i used your gotv.cfg

**Comment by MikkelDK** [comment]
Did you created a server.cfg? - you need to remember, the (csgoserver) need to +exec server.cfg (when you starting/boot the gameserver up) ;)

**Comment by Jargs** [comment]
https://i.imgur.com/JsrC1aI.png

**Comment by Jargs** [comment]
The server is created with tcadmin

**Comment by MikkelDK** [comment]
Did you edit on server.cfg and added exec gotv.cfg (save) and restart? it should work like that. ^^

**Comment by Jargs** [comment]
i dont have a gamemode_competitive_server.cfg, but when i put the gotv settings in gamemode_competitive.cfg it still dosent work

**Comment by splewis** [comment]
How you enable gotv has nothing to do with get5. Most people just set ``tv_enable 1`` in ``server.cfg`` and that's it. If you actually do thing it's related to get5 you should try removing it and see if the issue persists.

**Comment by TandelK** [comment]
The thing is that if you want to watch GOTV on Internet you have to enable Port of it via Start Up Parameters as well as a new CVAR was launched in year 2016 for allowing public to watch on Internet 


tv_advertise_watchable 0 set it 1 

and i can see the config you have shared is way old around of 2014-15 , you can find all the commands in Official CSGO Cvars List 
https://developer.valvesoftware.com/wiki/List_of_CS:GO_Cvars
