### ISSUE TITLE
Demo Recording.

### ISSUE THREAD

**Issue by LaBishop** [splewis/get5#342]
Hello,

I've been setting up my server and last thing I'm struggling with is getting the demo's to save on the server.

I've enabled the tv and followed the wiki, however I'm unaware as to exactly where the "void Get5_OnDemoFinished(const char[] filename)" needs to be placed so that I can allocate the demos to the replay folder on my server.

I hope this makes sense and someone can help me.

Regards,

LaBishop.

**Comment by LaBishop** [comment]
Hello,

Sorry I'm trying to locate where those demos are saved so that I can access them.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by splewis** [comment]
https://github.com/splewis/get5/wiki/Recording-match-demos#where-are-the-demos

**Comment by TandelK** [comment]
They are officialy by stored in CSGO Folder.
