### ISSUE TITLE
BOT joins game 

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5#343]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
BOT should not be in the game

### Actual behavior
Bot joins game in warmup and pistol round

### Steps to reproduce
1. Press M key(teammenu)
2. Press(or spam) your teams key(T:1 CT:2)
3. BOT joins game

- Plugin version: 0.6.0 
- Sourcemod version: 1.9.0.6269

**Comment by splewis** [comment]
> Press M key(teammenu)
Press(or spam) your teams key(T:1 CT:2)
BOT joins game

That's not enough for me to reproduce any issue. Are you loading a specific match config? Did you change the live/warmup cvars, or any other get5 cvars? Running other plugins?

**Comment by FlowingSPDG** [comment]
I'm using get5-webpanel (http://get5.flowing.tokyo/matches).
I changed get5 cvars(about pauses) but others are all default.
SRCDS has only SourceMod's default plugin and get5 plugins.

I suspect that team-lock function isnt working properly.
I'll send you record video once its ready

**Comment by FlowingSPDG** [comment]
after few days,I tried same thing but BOT was kicked out when game starts.
Maybe I have some misunderstanding last time.sorry for taking your time.
I'm closing issue,thanks :)

**Comment by TandelK** [comment]
There are 2-3 Reasons why bots might be joining the server. First of all make sure that you have Competitive Mode enabled instead of Casual, secondly check the gamemode files gamemode_casual.cfg or more

**Comment by FlowingSPDG** [comment]
There's game_mode and game_type cvars in launch options,So it should be fine

**Comment by TandelK** [comment]
not really by default all the gamemode_ files have auto add bots .
