### ISSUE TITLE
Backup file format/directory cvar

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5#344]
Is there's cvar to configure get5's backup file format/directory,it woulbe awesome fore me :)
Currently I'm running SRCDS on AWS,but sharing backup file is not easy for now.
So,I want to save backup files into NFS(EFS for AWS) shared storage.
(e.g. creating "backup" symlink folder)
thanks :) and sorry for poor English skill.

**Comment by splewis** [comment]
If someone wants to implement this, I added some notes at https://github.com/splewis/get5/issues/335#issuecomment-456200592 on the special concerns for it.

**Comment by nickdnk** [comment]
Will be fixed in https://github.com/splewis/get5/pull/793.
