### ISSUE TITLE
!unpause doesn't work after round restore

### ISSUE THREAD

**Issue by xe1os** [splewis/get5#345]
### Expected behavior
Use the !unpause command after the round restore (!stop) and it unpauses the match.

### Actual behavior
!unpause doesn't work. Match doesn't resume. 

### Steps to reproduce
Start a round and use !stop (both teams). Then try to resume the match typing !unpause (both teams).

- Plugin version: 0.7.0
- Sourcemod version: 1.9.0.6275

**Comment by xe1os** [comment]
@splewis please help.

**Comment by makhoder** [comment]
bug confirmed, it needs an admin to unpause by mp_unpause_match

**Comment by vassilidev** [comment]
mp_unpause_match = sm_unpause ?

**Comment by patrickfnielsen** [comment]
I've also hit this bug, the only solution is to get an admin to mp_unpause_match

**Comment by bastianalexispu** [comment]
this happens when a time limit is given to the pause, but if the pause has no time limit the command !unpause works perfect after restoring the round with !stop

**Comment by nickdnk** [comment]
Fixed on master.
