### ISSUE TITLE
player name forcing maps to a wrong name

### ISSUE THREAD

**Issue by gelzis** [splewis/get5#346]
### Expected behavior
Forced names for players are mapped the match config steam ids.

### Actual behavior
Names don't match steamids, get assigned a different name from the list.

### Steps to reproduce
I loaded following test match config with `get5_loadmatch_url`
```
{
  "num_maps": 3,
  "players_per_team": 1,
  "min_players_to_ready": 1,
  "min_spectators_to_ready": 0,
  "skip_veto": false,
  "matchid": "68",
  "spectators": {
    "players": {
      "76561198020860239": "",
      "76561198193600518": "",
      "76561197992432416": "",
      "STEAM_1:1:61031878": "",
      "76561197990917519": ""
    }
  },
  "cvars": {
    "get5_web_api_url": "http://ff2c8ed8.eu.ngrok.io/get5/series/",
    "get5_web_api_key": "dev"
  },
  "team1": {
    "name": "wolsung",
    "tag": "wolsung",
    "flag": "LV",
    "players": {
      "76561198193600518": "gelzis",
      "76561198010082464": "Whiskas",
      "76561198200517929": "hyskeee",
      "76561198201620490": "broky",
      "76561198094219557": "krii",
      "76561198134401925": "YEKINDAR"
    }
  },
  "team2": {
    "name": "SkinLordz",
    "tag": "SkinLordz",
    "flag": "LV",
    "players": {
      "76561198212318784": "discplex",
      "76561198072534862": "CaptaiN",
      "76561198023592349": "raw",
      "76561198033543607": "Flushed",
      "76561198875795145": "skuja",
      "76561197978169057": "udrizw0w"
    }
  }
}
```

When I join with my account (`76561198193600518`) I should be forced by name `gelzis`, I get forced to name `hyskee` instead.
`L 02/10/2019 - 14:14:27: "hyskeee<4><STEAM_1:0:116667395><>" STEAM USERID validated`

And when I join with my test account (`76561198875795145`), I should be forced by name `skuja`, I get forced to name `raw` instead.
```
L 02/10/2019 - 14:17:09: "raw<5><STEAM_1:1:457764708><>" connected, address ""
L 02/10/2019 - 14:17:09: "raw<5><STEAM_1:1:457764708><>" STEAM USERID validated
[Get5] Type !ready when your team is ready to veto.
L 02/10/2019 - 14:17:14: "raw<5><STEAM_1:1:457764708><>" entered the game
```

With the exact same match config, etc. everything works fine when using previous `0.6` version. My guess its somehow connected with the `JSON` parsing changes in `0.7` ? 
Also what I saw on status page, that `maps` object on version `0.6` was:
`"maps":{"map0":"de_inferno","map1":"de_mirage","map2":"de_train"}`
now its:
`"maps":{"map0":"de_inferno","map2":"de_train","map1":"de_mirage"}`
this ordering change is not issue of course, but probably some object parsing in json sequencing change also messes up the steam -> name mapping somewhere in the code.

- Plugin version: 0.7 (tried also latest jenkins build `0.7.0-dev+453` ), same result.
- Sourcemod version: 1.9.0.6275

**Comment by splewis** [comment]
Thanks for the detailed bug report. I've verified this, I'll try to fix it shortly.

**Comment by splewis** [comment]
958d99f25ed5e3d3e857d8f01c41ef1baa516cb9 should fix this. Can you verify it works for you now?

**Comment by gelzis** [comment]
player name forcing now works as expected, thank you!
