### ISSUE TITLE
SteamWorks not running

### ISSUE THREAD

**Issue by tffwh1te** [splewis/get5#349]
I'm getting errors as shown below

```
Errors:
get5_mysqlstats.smx (Get5 MySQL stats): Error detected in plugin startup (see error logs)
get5_apistats.smx (Get5 Web API Integration): Required extension "SteamWorks" file("SteamWorks.ext") not running
```

**Comment by splewis** [comment]
> (see error logs)

Check the error logs then. ``addons/sourcemod/logs``

> Required extension "SteamWorks" file("SteamWorks.ext") not running

Install steamworks: https://github.com/splewis/get5#get5_apistats then.

It doesn't really make sense to be running both of these plugins at the same time, though.

**Comment by splewis** [comment]
Closing since there's no update here. Feel free to reopen if you still have problems/questions.
