### ISSUE TITLE
There is no match setup . i cant join the server

### ISSUE THREAD

**Issue by tAtU87** [splewis/get5#350]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by MikkelDK** [comment]
No reason to open this! - I will answer on your first issue (you did closed)
