### ISSUE TITLE
No match overtime in BO3

### ISSUE THREAD

**Issue by SquidThePrinter** [splewis/get5#352]
When playing a BO3 match, the match fails to go to overtime. Tested on multiple servers, one which previously had matches played on it and did not have the same problem prior to the 3/7/19 CS:GO update. I've included the debuginfo file which contains an exception that may be related. [get5_debuginfo.txt](https://github.com/splewis/get5/files/2950128/get5_debuginfo.txt)

### Expected behavior
Match gets to 15-15, goes into overtime.

### Actual behavior
Match gets to 15-15, hangs at end scoreboard and does not go into overtime. Backup to round 30 is not created. Transferring previous round (14-15) backup file to another server and running from there yields same results.

### Steps to reproduce
1) Create a BO3 with map veto match, start said match
2) Let game run until 15-15

- Plugin version: 0.7.1
- Sourcemod version: 1.9.0.6275

I can provide any additional information needed to track down and resolve this issue upon request, including demos displaying actual behavior or additional log files.

**Comment by splewis** [comment]
> Steps to reproduce (please be specific): 1.10.7-devV

Having your match config/commands to run/live.cfg & warmup.cfg are probably needed.

Regardless, I doubt this is really a get5 issue. It's more likely either a game bug or a consequence of setting some game cvars that cause problems.

**Comment by SquidThePrinter** [comment]
I'll attach all the configs (had to change their file extension to .txt or GitHub wouldn't upload them).

[knife.cfg](https://github.com/splewis/get5/files/2950426/knife.cfg.txt)
[live.cfg](https://github.com/splewis/get5/files/2950427/live.cfg.txt)
[warmup.cfg](https://github.com/splewis/get5/files/2950428/warmup.cfg.txt)

Like I said, there were no issues before the most recent CS:GO update on 3/7. Before that, everything worked perfectly fine.

**Comment by SquidThePrinter** [comment]
@splewis wondering if you've had time to verify this bug or if you need additional info to help narrow down the problem

**Comment by splewis** [comment]
No, I haven't. It's an open source project for a reason, though - anyone, including you, has the ability to investigate it :)

I still doubt it's an issue with get5 though. You could do some basic debugging by removing get5 and just setting all the same halftime duration/overtime-related cvars and seeing it if still happens. My guess it that you're just setting some cvar that causes it, and an update has slightly changed the behavior of it.

**Comment by SquidThePrinter** [comment]
Closing this issue, in case anyone else is experiencing this issue I fixed it by changing the `mp_overtime_halftime_pausetimer` line value to 0 instead of 10 like I had previously set, issue was instantly resolved.
