### ISSUE TITLE
BO3 Issue Changing to second map.

### ISSUE THREAD

**Issue by OlympusAM** [splewis/get5#355]
After the first match. Wait for GOTV to end then switch maps.

I have a BO3 Match Setup. After the first map is over. It waits for the GOTV broadcast to end before the map change like it should. It then displays its changing to the second map. It then kicks everyone giving the error "No Match Setup" when trying to reconnect.
tv_delay = 105 from the default Get5 Config.

### Steps to reproduce

- Plugin version: 0.7.1
- Sourcemod version: 1.9 - build 6275
- Steps to reproduce (please be specific):

Create a BO3 match on the get5 web panel. Bo3 with map vetoes, select the 3 maps.
tv_delay=105 default set by get5.

**Comment by OlympusAM** [comment]
Match Config
https://pastebin.com/KZxY0mzL

Console Logs from before & after the 1st map.
https://pastebin.com/mcH0Sysd

**Comment by williamweckl** [comment]
It does not happen everytime, but most of the time it does. With best of 2 maps too.

**Comment by williamweckl** [comment]
I´m being using the same version 0.7.1 for a very long time and this year this bug started to happen, maybe was some csgo dedicated server update that caused it.

**Comment by adamjermann** [comment]
Exact same thing happened to us in our league final... BO3 setup, veto and first map commenced perfectly, then at map change server dropped all the players, then they could not reconnect with the message "There is no match setup".

**Comment by splewis** [comment]
If someone can consistently reproduce the issue, it would help fix this. Otherwise, I'm not sure what I can do. It's possible the plugin is getting reloaded by your sourcemod installation, for whatever reason.  SM reloads plugins when it detects the file changes by default, the last I remember. Not sure what other reasons could cause it.

**Comment by TandelK** [comment]
@splewis can confirm this issue. It gives error as soon as GOTV Recording is completed and try to load second map.

**Comment by TandelK** [comment]
In order to get all data in our panel back i did one thing is created a map0_round0.cfg backup to map1_round0.cfg and loaded that file on the server so it contains the API key and maintaining the matches. Still it does not have accurate information as after first map that file will be bugged to score update. Had to update Series score and Map scores in map1_round0.cfg file.

**Comment by Gewad** [comment]
I started having exactly the same issues when I enabled GOTV on the server. Maybe it was just coincidence that it didn't happen before but maybe this can point you in the right direction. I will test if the server works fine again when GOTV is disabled but I don't have time to do that today.

**Comment by williamweckl** [comment]
Maybe I've figured out.

The last weekend I've run another tournament using my servers, but this time I reduced the GOTV delay time to 30 seconds. The problem did not happen, not even once, and I ran a lot of md3 matches. 

But here is the funny thing, even lowering the GOTV delay time, the server are still waiting 120 seconds to change the map after the first and second maps, and the message is still the same: "Waiting for GOTV finish broadcasting... " (OR something like that). But GOTV already stopped to broadcast.

My hypothesis here is that the GOTV delay time and change map time are different things and for some reason they are not synced. When GOTV delay is higher than the map change time, GET5 stops the match for some reason. If both times are 120 seconds, there is a chance that one finishes before the other.

Maybe we can prove the hypothesis setting a GOTV delay time higher to 120 seconds.

I don't know GET5 code very well, but maybe someone who knows can tell if this make any sense or not.

**Comment by splewis** [comment]
Seems possible.

Some code snippets around the tv delay and changemap behaviour, that might help debugging:

https://github.com/splewis/get5/blob/96e94e3cfd9e80916f1bfc904d3549025d09fe45/scripting/get5/util.sp#L134-L138

https://github.com/splewis/get5/blob/51fe79d0da8131f7104e4a78551f4364f06be950/scripting/get5.sp#L1048-L1052

https://github.com/splewis/get5/blob/3f793ceb3736d78ba6a92f42631d91cb52f0beb4/scripting/get5/goinglive.sp#L49-L50

https://github.com/splewis/get5/blob/51fe79d0da8131f7104e4a78551f4364f06be950/scripting/get5.sp#L968-L1012

**Comment by TandelK** [comment]
@splewis Is this normal that it shows Map changes in 10 seconds and get stuck on 5 seconds and server crashes. May be that extra 5 seconds are not getting added properly?

**Comment by metalhyoga** [comment]
Hi, I don't know if this could help, but I'm using Get5 as an automatic match setup, in a Ruby on Rails Environment. What I have realized is that when using the 
`get5_end_match_on_empty_server "1"`

If during the map change, a user that is not on the match joins the server, he will be kicked and throw a Player_disconnect event, this will trigger the end_match_on_empty_server, resulting on a series_end event, and finishing the match and configuration.  Maybe this windows caused between gotv and match, gives a longer opportunity to the issue to happen.

**Comment by nickdnk** [comment]
Could this be related to `mp_match_restart_delay` being set to a lower value than GOTV + MATCH_END_DELAY_AFTER_TV ?

**Comment by nickdnk** [comment]
This should be fixed in https://github.com/splewis/get5/pull/821.
