### ISSUE TITLE
no get5.cfg

### ISSUE THREAD

**Issue by Slice272** [splewis/get5#356]
i installt get5 like i should everything is fine but when i try to join the server it says there is no match setup... so i went in my files to look for the get5.cfg to change get5_kick_when_no_match_loaded 0 but there is no get5.cfg like it should....

so i tryed 9hours now to fix it myself i looked in any .sp files if there is something i can work with.

but iam out of ideas now so pls help xD

**Comment by splewis** [comment]
> but there is no get5.cfg like it should....

Then your server is failing to write ``cfg/sourcemod/get5.cfg``. It might be missing write permissions. I can't help you with that. Checking ``addons/sourcemod/logs`` for errors logs might help you (of course, your server might also not having write permissions to that directory either).

You can just make the file yourself and put whatever contents in it you want. You can see all the cvars and their defaults at https://github.com/splewis/get5/blob/master/scripting/get5.sp#L247-L332.

**Comment by Slice272** [comment]
allright thank you
