### ISSUE TITLE
Text In-Game Colors (list)

### ISSUE THREAD

**Issue by kozamonq** [splewis/get5#357]
Hi guys !
When I'm going to my "get5.cfg" file on the directory (csgo/cfg/sourcemod/),
At line 95 we can see : "get5_message_prefix : [{YELLOW}Get5{NORMAL}]"...
But my question is, what are the other colors available ?
Maybe like : {orange}, {lightred}... & more

Thanks for help

**Comment by Technoblazed** [comment]
```
static char _colorNames[][] = {"{NORMAL}", "{DARK_RED}",    "{PINK}",      "{GREEN}",
                               "{YELLOW}", "{LIGHT_GREEN}", "{LIGHT_RED}", "{GRAY}",
                               "{ORANGE}", "{LIGHT_BLUE}",  "{DARK_BLUE}", "{PURPLE}"};
```

**Comment by 66venum** [comment]
Oh thanks you're quick !
but, dor exemple,I tried to put {LIGHT_RED}[ {ORANGE}Get5  {LIGHT_RED}] {GRAY},
one the game, I only see {LIGHT_RED}[ {ORANGE}Get5  {LIGHT_RED}] {GRAY} in plain-text...
What can be the prbolem for you ?
