### ISSUE TITLE
Get5 Can't read the scrim_template.cfg

### ISSUE THREAD

**Issue by CoooPi** [splewis/get5#358]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Starting a scrim

### Actual behavior
Saying "[get5.smx] Failed to load match config: Failed to read scrim template in addons/sourcemod/configs/get5/scrim_template.cfg
L 03/23/2019 - 15:35:46: get5_event: {"matchid`":"","params":{"reason":"Failed to read scrim template in addons\/sourcemod\/configs\/get5\/scrim_template.cfg"},"event":"match_config_load_fail"}
L 03/23/2019 - 15:35:46: rcon from "IP:Port": command "get5_scrim"

### Steps to reproduce
Dowload Get5.smx to yours server and download the "scrim_template.cfg" to the addons/sourcemod/configs folder, reboot the server twice. Then type "rcon get5_scrim" into the console 

- Plugin version: 0.7.1

**Comment by TandelK** [comment]
Check if your scrim_template is actually inside sourcemod/config/get5 folder and not in sourcemod/configs folder

**Comment by splewis** [comment]
Does ``addons/sourcemod/configs/get5/scrim_template.cfg`` exist? If it doesn't, that's your issue.

If it does exist, your server is missing read permissions to the file.

I don't think there's a bug here. The ``get5_scrim`` command works fine for me.

**Comment by splewis** [comment]
Closing since there's no followup here.
