### ISSUE TITLE
Custom cvars in game cfg not loaded if server is empty

### ISSUE THREAD

**Issue by gardc** [splewis/get5#359]
### Expected behavior
I have an empty server where a 5v5 game (veto, knife and live) is taking place. In my get5 match cfg under cvars section, I have listed several cvars i want to change. When the players connect to the server, I expect the cvars to be sat as I've specified in the config.

### Actual behavior
When setting cvars such as **get5_message_prefix** and **get5_time_to_start** via get5 match cfg, they are **not loaded at warmup** when players connect. After veto (map load) and on game live, the custom cvars are then loaded.
If there are players on the server and i load the game config, then all the cvars are loaded instantly as expected.

### Steps to reproduce
- Plugin version: 0.7.1
- Sourcemod version: 1.9.0.6275
- Steps to reproduce (please be specific):

Have an empty server and load a config with cvars (i believe the config has to have veto enabled).
Example cvars:
```
"cvars": {
        "get5_message_prefix": "[blahblah]",
        "get5_time_to_start": 300
	}
```
When you join, you should see that the message prefix is still Get5, and there is no start timer enabled.

If you stay connected to the server and run **get5_endmatch** and load the config again, you should see that the convars are then sat correctly and the message prefix is blahblah and there is a start timer warning.

**Comment by splewis** [comment]
The cvars are probably getting set fine, it's probably a case of them being set again to different values by another config file being executed, probably `cfg/sourcemod/get5.cfg` in this case. 

It might be worth changing get5 re-executing the match ``cvars`` section after the first player joins the server.

**Comment by gardc** [comment]
Yup, editing that config in cfg/sourcemod/ resolved the issue! Thanks!
