### ISSUE TITLE
Warmup doesn't work

### ISSUE THREAD

**Issue by pistoolero** [splewis/get5#36]
When server starting it load warmup.cfg but when I'm connecting it load live.cfg, it looks like get5_autoload_config doesn't work or it is overwritten by get5_live_cfg. I have only 16k money when I should have 65k (when I exec cfg manually it's 65k), it should be 1337 rounds but it's only 30, it shouldn't be roundtime and should be warmup but it is 2min roundtime and no warmup...

- Plugin version: 0.3.0
- Sourcemod version: 1.7.3-dev+5303

#Edit 
On screenshot it is shown. It loads ESL cfg instead of warmup cfg 
![13517861_1083014795068960_82007364_o](https://cloud.githubusercontent.com/assets/13179358/16365337/72b72cf6-3bfd-11e6-87a7-2c88e1ec0358.png)

**Comment by splewis** [comment]
I'm unable to find any issues with warmup or the get5_autoload_config cvar using the default live and warmup configs. Can you reproduce issues using those?

Also, "latest" isn't a very helpful version. Something like "0.3.0" or "0.3.1-dev+183" is much more useful.

**Comment by pistoolero** [comment]
Edited.
Plugin version: 0.3.0
Sourcemod version: 1.7.3-dev+5303

**Comment by pistoolero** [comment]
Here is executing warmup.cfg
```
L 06/27/2016 - 00:42:23: server_cvar: "mp_friendlyfire" "0"
L 06/27/2016 - 00:42:23: server_cvar: "mp_maxrounds" "1337"
L 06/27/2016 - 00:42:23: server_cvar: "mp_freezetime" "0"
L 06/27/2016 - 00:42:23: server_cvar: "mp_roundtime" "1"
Can't use cheat cvar sv_grenade_trajectory in multiplayer, unless the server has sv_cheats set to 1.
L 06/27/2016 - 00:42:23: server_cvar: "sv_alltalk" "1"
L 06/27/2016 - 00:42:23: World triggered "Match_Start" on "de_mirage"
L 06/27/2016 - 00:42:23: eBot triggered "Round_Spawn"
```
And when I connect it exec esl5on5.cfg
```
L 06/27/2016 - 00:42:23: "ratten<3><STEAM_1:0:34120335><>" connected, address ""
Client "ratten" connected (78.88.25.56:27005).
L 06/27/2016 - 00:42:23: World triggered "Restart_Round_(1_second)"
L 06/27/2016 - 00:42:23: Team "CT" scored "0" with "0" players
L 06/27/2016 - 00:42:23: Team "TERRORIST" scored "0" with "0" players
GOTV[0] broadcast active.
L 06/27/2016 - 00:42:23: "ratten<3><STEAM_1:0:34120335><>" STEAM USERID validated
L 06/27/2016 - 00:42:24: World triggered "Match_Start" on "de_mirage"
L 06/27/2016 - 00:42:24: Team playing "CT": Suaby&Gaming
L 06/27/2016 - 00:42:24: Team playing "TERRORIST": Montujemy
L 06/27/2016 - 00:42:24: eBot triggered "Round_Spawn"
L 06/27/2016 - 00:42:26: World triggered "Round_Start"
PutClientInServer: no info_player_start on level
L 06/27/2016 - 00:42:33: "ratten<3><STEAM_1:0:34120335><>" entered the game
L 06/27/2016 - 00:42:33: server_cvar: "mp_c4timer" "40"
L 06/27/2016 - 00:42:33: server_cvar: "mp_freezetime" "12"
L 06/27/2016 - 00:42:33: server_cvar: "mp_friendlyfire" "1"
L 06/27/2016 - 00:42:33: server_cvar: "mp_maxrounds" "30"
L 06/27/2016 - 00:42:33: server_cvar: "mp_roundtime" "1.92"
L 06/27/2016 - 00:42:33: server_cvar: "mp_roundtime_defuse" "1.92"
L 06/27/2016 - 00:42:33: server_cvar: "sv_alltalk" "0"
L 06/27/2016 - 00:42:33: server_cvar: "sv_deadtalk" "0"
--------------------------------------------------------
sv_pure value unchanged (current value is 1).
--------------------------------------------------------
Console: "> ESL CS:GO 3on3/5on5 Ladder Config loaded - 14.01.2016<"
L 06/27/2016 - 00:42:33: "Console<0><Console><Console>" say ""> ESL CS:GO 3on3/5on5 Ladder Config loaded - 14.01.2016<""
```

**Comment by splewis** [comment]
I've made a change to not exec the live config when the first players joins, however:

- You have modified the plugin which means it is too difficult for me to provide support without the changes being open source
-  I don't recommend using the ESL configs. They often set warmup cvars that can cause issues with the plugin.

**Comment by pistoolero** [comment]
I only edited MESSAGE_PREFIX and Get5_Message/Get5_MessageToAll messages in get5.sp, nothing more.
I will try with something different config.

**Comment by pistoolero** [comment]
Ok, it works properly now :) thanks! To close / delete 
![image](https://cloud.githubusercontent.com/assets/13179358/16365558/07848fb2-3c04-11e6-8d0e-2ddc9860e139.png)
