### ISSUE TITLE
Get5 own maps and start a match with the right match config

### ISSUE THREAD

**Issue by akelahvh** [splewis/get5#362]
I want my own maps that is on /csgo/maps file in the tournament and your website doesn't support them? how do I enable the own maps and how do I start a match

**Comment by akelahvh** [comment]
start the match what config is the one I need to change and enable to start a match? Do I need to start it through your website?

**Comment by splewis** [comment]
> start the match what config is the one I need to change and enable to start a match? 

https://github.com/splewis/get5#quickstart

You make a match config. You run get5_loadmatch. You can list whatever maps you want in a match config.

> I want my own maps that is on /csgo/maps file in the tournament and your website doesn't support them? how do I enable the own map

If you're using [get5-web](https://github.com/splewis/get5-web) there's a config file where you can list what maps you want enabled. If you're using my "public" instance (which you absolutely should **not** be using), then you're stuck with whatever maps I have enabled on it.

I strongly recommend just making your own match config files.

**Comment by akelahvh** [comment]
can you add me on discord so it's easiter to communicate? akela#7905

**Comment by akelahvh** [comment]
well I fixed it, but I want to add so they have 1 minute pause so it automatically unpause the pause after 1 minute in the csgo/cfg/sourcemod/get5

**Comment by akelahvh** [comment]
and why do I get defuse kit everytime I respawn? when I haven't bought it :/ it's like autobuy

**Comment by akelahvh** [comment]
I fixed the pause thing but this, defuse kit I have it when I spawn

**Comment by splewis** [comment]
> can you add me on discord so it's easiter to communicate? akela#7905

I don't provide support in non-public places.

> but I want to add so they have 1 minute pause so it automatically unpause the pause after 1 minute in the csgo/cfg/sourcemod/get5

https://github.com/splewis/get5/wiki/Pausing

> and why do I get defuse kit everytime I respawn? when I haven't bought it :/ it's like autobuy

You have `mp_defuser_allocation` set to something other than 0 then. Don't do that. You're probably running the server as casual instead of competitive.

**Comment by akelahvh** [comment]
Where do I find this "mp_defuser_allocation"

**Comment by splewis** [comment]
You can set whatever cvars you want in cfg/get5/live.cfg. If you're asking why it's set to something other than 0 at all - that's not something I can help you with (it's not related to get5). Like I said, if I had to guess you're probably just launching your server as casual.

**Comment by TandelK** [comment]
@akelahvh Can you drop your startup command line here so i can tell you exact reason why you might be facing for the issue.

**Comment by akelahvh** [comment]
this is my live.cfg https://pastebin.com/vpgw1ruC

**Comment by akelahvh** [comment]
and the match.cfg https://pastebin.com/deQxwPYM

**Comment by TandelK** [comment]
@akelahvh Can you drop your start up parameters which is like `srcds.exe -game csgo -console -usercon `

**Comment by Technoblazed** [comment]
Your server is probably set to casual.

**Comment by akelahvh** [comment]
./srcds_run -game csgo -console -usercon +exec server.cfg -port 27230 +sv_pure -1 -maxplayers_override 12 +ip 82.208.17.17 +clientport 28230 -sport 29230 +tv_port 26230 -steamport 31230 +replay_port 30230 +sv_lan 0 -insecure +game_type 0 +game_mode 1 -gamemodes_serverfile gamemodes_server.txt +mapgroup fakaheda_custom +map de_mirage -tickrate 64 -autoupdate -steam_dir /hlserver/27230/steamcmd/ -steamcmd_script /hlserver/27230/steamcmd/csgo.txt +sv_setsteamaccount CA2D52AA99BFBE8A08A5E7C1E52FC04D -norestart

**Comment by splewis** [comment]
You really should not share your sv_setsteamaccount. I'd suggest regenerating a new one to use now.

**Comment by akelahvh** [comment]
okay

**Comment by TandelK** [comment]
Did you create own gamemodes_server.txt  ?  If yes than please execute in competitive mode the file of gamemode_competitive.cfg as well as gamemode_comepetitive_server.cfg and also in your custom map group . You can add me in Discord. It is TandelK#7676

**Comment by akelahvh** [comment]
gamemode_competitive.cfg https://pastebin.com/fLKqS1K4 
gamemode_competitive_server.cfg https://pastebin.com/DZZ0P9BC

**Comment by TandelK** [comment]
Official Reference Guide. 


https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Dedicated_Servers#gamemodes_server.txt
