### ISSUE TITLE
load match json issue

### ISSUE THREAD

**Issue by thboss** [splewis/get5#363]
L 04/08/2019 - 13:37:15: [get5.smx] json_decode: character not identified as object or array at 0
L 04/08/2019 - 13:37:15: [get5.smx] Failed to load match config: invalid match json

**Comment by Technoblazed** [comment]
The issue template is there for a reason, please do NOT delete it.

```
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
```

**Comment by splewis** [comment]
Without a version number and the match config you were using there's really nothing you've given to investigate. Feel free to reopen if you can give those.

**Comment by thboss** [comment]
json and get5 last version
SM 1.10
comfig match : example_match, I didn't change it

**Comment by splewis** [comment]
> get5 latest version

Please give a specific version. 

https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version

**Comment by PhlexPlexico** [comment]
Much like Technoblazed explained, please use the proper submission format so they can get all the information required. As for the load match issue, are you trying to load it from a URL? Are you using the latest (yesterdays) build? Have you tried using the 0.7.1 release on the releases page?

**Comment by thboss** [comment]
"get5_version" = "0.7.1"
