### ISSUE TITLE
!tech not working

### ISSUE THREAD

**Issue by getwh1ted** [splewis/get5#368]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Working !tech command

### Actual behavior

Notworking !tech command

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: 1.9.0.6276
- Steps to reproduce (please be specific): I don't know what put in here

**Comment by PhlexPlexico** [comment]
Would you mind posting your get5.cfg that's located in `csgo/cfg/sourcemod/get5.cfg`?

**Comment by getwh1ted** [comment]
`// This file was auto-generated by SourceMod (v1.9.0.6276)
// ConVars for plugin "get5.smx"


// Whether or not technical pauses are allowed
// -
// Default: "1"
get5_allow_technical_pause "1"

// Name of a match config file to automatically load when the server loads
// -
// Default: ""
get5_autoload_config ""

// Whether the get5 backup system is enabled
// -
// Default: "1"
get5_backup_system_enabled "1"

// If set to 0, get5 will not force players to the correct team based on steamid
// -
// Default: "1"
get5_check_auths "1"

// Format of the damage output string. Avaliable tags are in the default, color tags such as {LIGHT_RED} and {GREEN} also work.
// -
// Default: "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"
get5_damageprint_format "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"

// Whether to wait for map vetos to be printed to GOTV before changing map
// -
// Default: "0"
get5_display_gotv_veto "1"

// Whether to end the match if all players disconnect before ending. No winner is set if this happens.
// -
// Default: "0"
get5_end_match_on_empty_server "0"

// Path to use when writing match event logs, use "" to disable
// -
// Default: ""
get5_event_log_format ""

// If set to non-zero, this will be the fixed length of any pause
// -
// Default: "0"
get5_fixed_pause_time "30"

// Template that the server hostname will follow when a match is live. Leave field blank to disable. Valid parameters are: {MAPNUMBER}, {MATCHID}, {SERVERID}, {MAPNAME}, {TIME}, {TEAM1}, {TEAM2}
// -
// Default: "Get5: {TEAM1} vs {TEAM2}"
get5_hostname_format "GLCS: {TEAM1} vs {TEAM2}"

// Whether or not admins with the changemap flag will be immune to kicks from "get5_kick_when_no_match_loaded". Set to "0" to disable
// -
// Default: "1"
get5_kick_immunity "1"

// Whether the plugin kicks new clients when no match is loaded
// -
// Default: "1"
get5_kick_when_no_match_loaded "1"

// Config file to exec when the game goes live
// -
// Default: "get5/live.cfg"
get5_live_cfg "get5/live.cfg"

// Number of seconds used to count down when a match is going live
// -
// Default: "10"
// Minimum: "5.000000"
// Maximum: "60.000000"
get5_live_countdown_time "10"

// Number of seconds before a backup file is automatically deleted, 0 to disable
// -
// Default: "160000"
get5_max_backup_age "160000"

// Maximum number of time the game can spend paused by a team, 0=unlimited
// -
// Default: "300"
get5_max_pause_time "300"

// Maximum number of pauses a team can use, 0=unlimited
// -
// Default: "0"
get5_max_pauses "4"

// The tag applied before plugin messages.
// -
// Default: "[{YELLOW}Get5{NORMAL}]"
get5_message_prefix "[{GREEN}GLCS{NORMAL}]"

// Whether pausing is allowed.
// -
// Default: "1"
get5_pausing_enabled "1"

// Whether damage reports are printed on round end.
// -
// Default: "0"
get5_print_damage "0"

// Whether pause limits will be reset each halftime period
// -
// Default: "1"
get5_reset_pauses_each_half "0"

// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "0"

// Whether to set client clan tags to player ready status.
// -
// Default: "1"
get5_set_client_clan_tags "1"

// Where match stats are saved (updated each map end), set to "" to disable
// -
// Default: "get5_matchstats_{MATCHID}.cfg"
get5_stats_path_format "get5_matchstats_{MATCHID}.cfg"

// Whether clients can use the !stop command to restore to the last round
// -
// Default: "1"
get5_stop_command_enabled "1"

// Time format to use when creating file names. Don't tweak this unless you know what you're doing! Avoid using spaces or colons.
// -
// Default: "%Y-%m-%d_%H"
get5_time_format "%Y-%m-%d_%H"

// Time (in seconds) a team has to make a !stay/!swap decision after winning knife round, 0=unlimited
// -
// Default: "60"
get5_time_to_make_knife_decision "60"

// Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited
// -
// Default: "0"
get5_time_to_start "0"

// Time (in seconds) from presenting a veto menu to a selection being made, during which a confirmation will be required, 0 to disable
// -
// Default: "2.0"
get5_veto_confirmation_time "2.0"

// Seconds to countdown before veto process commences. Set to "0" to disable.
// -
// Default: "5"
get5_veto_countdown "5"

// Config file to exec in warmup periods
// -
// Default: "get5/warmup.cfg"
get5_warmup_cfg "get5/warmup.cfg"`

**Comment by getwh1ted** [comment]
[get5.cfg.txt](https://github.com/splewis/get5/files/3077748/get5.cfg.txt)

**Comment by PhlexPlexico** [comment]
Thanks! Is there by chance anything from the console that is output when they call a tech timeout? Any stacktrace or something in the logs?

**Comment by getwh1ted** [comment]
Absolutely nothing

**Comment by PhlexPlexico** [comment]
Just tested it too, can agree that !tech is not working on the same version, haha

**Comment by abdulsami34** [comment]
For those, who are looking for a fix!

get5_allow_technical_pause "1" change this to 0

It works fine after changing it to 0.

**Comment by splewis** [comment]
> get5_allow_technical_pause "1" change this to 0

That's a workaround, not a fix.

It looks like the use of g_AllowTechPauseCvar is just inverted here: https://github.com/splewis/get5/blob/master/scripting/get5/pausing.sp#L6

pull requests welcome :)

**Comment by Iwhite67** [comment]
i confirm with last stable version i have this bug, need 0 for tech pause
