### ISSUE TITLE
Is it possible to put automatic forceready when 10 players connect?

### ISSUE THREAD

**Issue by victorscatolon** [splewis/get5#371]
would like to put a forceready when the server is 10 players, so it would not depend on the players to give! Ready or! Forceready

Can someone help me?

**Comment by saintplay** [comment]
This was previously discussed in #290

**Comment by splewis** [comment]
I commented again in #290 - tl;dr, I'm not outright rejecting the idea, but it'll need someone to send a very simple PR to make it happen.
