### ISSUE TITLE
Failed to get steamid for client after update steam client

### ISSUE THREAD

**Issue by suspectykt** [splewis/get5#373]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
The problem when creating a match through the site get 5 webpanel players can not after creating a team to get to the server

### Actual behavior
```
L 04/18/2019 - 22:39:25: [get5.smx] Failed to get steamid for client pekuS<4><STEAM_1:0:440927271><>
L 04/18/2019 - 22:39:36: [get5.smx] Failed to get steamid for client pekuS<5><STEAM_1:0:440927271><>
L 04/18/2019 - 22:39:42: [get5.smx] Failed to get steamid for client ТАБУРЕТКА<6><STEAM_1:0:416728170><>
L 04/18/2019 - 22:39:44: [get5.smx] Failed to get steamid for client 피카추<7><STEAM_1:0:421704078><>
L 04/18/2019 - 22:39:48: [get5.smx] Failed to get steamid for client pekuS<8><STEAM_1:0:440927271><>
L 04/18/2019 - 22:39:55: [get5.smx] Failed to get steamid for client 피카추<9><STEAM_1:0:421704078><>
L 04/18/2019 - 22:40:01: [get5.smx] Failed to get steamid for client pekuS<10><STEAM_1:0:440927271><>
L 04/18/2019 - 22:40:03: [get5.smx] Failed to get steamid for client 피카추<11><STEAM_1:0:421704078><>
L 04/18/2019 - 22:40:16: [get5.smx] Failed to get steamid for client Красотка<12><STEAM_1:0:437245835><>
L 04/18/2019 - 22:40:31: [get5.smx] Failed to get steamid for client ╰_╯<13><STEAM_1:0:425993768><>
L 04/18/2019 - 22:40:36: [get5.smx] Failed to get steamid for client Красотка<14><STEAM_1:0:437245835><>
L 04/18/2019 - 22:40:49: [get5.smx] Failed to get steamid for client pekuS<15><STEAM_1:0:440927271><>
L 04/18/2019 - 22:40:55: [get5.smx] Failed to get steamid for client 피카추<16><STEAM_1:0:421704078><>
L 04/18/2019 - 22:40:57: [get5.smx] Failed to get steamid for client pekuS<17><STEAM_1:0:440927271><>
L 04/18/2019 - 22:41:36: [get5.smx] Failed to get steamid for client comediaN<18><STEAM_1:0:92041114><>
L 04/18/2019 - 22:41:53: [get5.smx] Failed to get steamid for client ТАБУРЕТ<19><STEAM_1:1:114170613><>
L 04/18/2019 - 22:56:03: [get5.smx] Failed to get steamid for client comediaN<25><STEAM_1:0:92041114><>
L 04/18/2019 - 22:56:38: [get5.smx] Failed to get steamid for client ТАБУРЕТКА<26><STEAM_1:0:416728170><>
L 04/18/2019 - 22:56:46: [get5.smx] Failed to get steamid for client ТАБУРЕТ<27><STEAM_1:1:114170613><>
L 04/18/2019 - 22:57:17: [get5.smx] Failed to get steamid for client pekuS<28><STEAM_1:0:440927271><>
L 04/18/2019 - 22:57:22: [get5.smx] Failed to get steamid for client 피카추<29><STEAM_1:0:421704078><>
L 04/18/2019 - 22:57:35: [get5.smx] Failed to get steamid for client ТАБУРЕТ<30><STEAM_1:1:114170613><>
L 04/18/2019 - 22:59:16: [get5.smx] Failed to get steamid for client comediaN<31><STEAM_1:0:92041114><>
L 04/18/2019 - 23:00:28: [get5.smx] Failed to get steamid for client Красотка<32><STEAM_1:0:437245835><>
```

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

```
L 04/19/2019 - 15:13:24: [get5] cleanedUrl (SteamWorks) = http://.............../match/137/config
L 04/19/2019 - 15:13:24: [get5_api] get5_web_api_url now set to 
L 04/19/2019 - 15:13:24: [get5] Change from state 0 -> 1
L 04/19/2019 - 15:13:24: [get5_api] get5_web_api_url now set to http://............/
L 04/19/2019 - 15:13:24: [get5] get5_event: {"matchid`":"137","params":{"team1_name":"Terra","team2_name":"Terra2"},"event":"series_start"}
L 04/19/2019 - 15:13:24: [get5_mysql] Setting up series stats, get5_mysql_force_matchid = 0
L 04/19/2019 - 15:13:24: [get5_mysql] INSERT INTO `get5_stats_matches` (series_type, team1_name, team2_name, start_time) VALUES ('bo1', 'Terra', 'Terra2', NOW())
L 04/19/2019 - 15:13:24: [get5_mysql] SELECT LAST_INSERT_ID()
L 04/19/2019 - 15:14:13: [get5] get5_event: {"matchid`":"129","params":{"client":"none","map_number":0,"map_name":"de_dust2"},"event":"player_disconnect"}
L 04/19/2019 - 15:14:23: [get5_api] Trying to create request to url http://......./match/137/map/-1/finish
L 04/19/2019 - 15:14:23: [get5_api] Added param key=779SFMG4L0TMXXUHPTDYCUDV to request
L 04/19/2019 - 15:14:23: [get5_api] Added param team1score=0 to request
L 04/19/2019 - 15:14:23: [get5_api] Added param team2score=0 to request
L 04/19/2019 - 15:14:23: [get5_api] Added param winner=none to request
L 04/19/2019 - 15:14:23: [get5_mysql] UPDATE `get5_stats_maps` SET winner = 'none', end_time = NOW() WHERE matchid = 129 and mapnumber = -1
L 04/19/2019 - 15:14:23: [get5_mysql] UPDATE `get5_stats_matches` SET team1_score = 0, team2_score = 0 WHERE matchid = 129
L 04/19/2019 - 15:14:23: [get5_api] Trying to create request to url http://............/match/137/finish
L 04/19/2019 - 15:14:23: [get5_api] Added param key=779SFMG4L0TMXXUHXXXXXXXXX to request
L 04/19/2019 - 15:14:23: [get5_api] Added param winner=none to request
L 04/19/2019 - 15:14:23: [get5_api] Added param forfeit=0 to request
L 04/19/2019 - 15:14:23: [get5_api] get5_web_api_url now set to http://....../
L 04/19/2019 - 15:14:23: [get5_mysql] UPDATE `get5_stats_matches` SET winner = 'none', team1_score = 0, team2_score = 0, end_time = NOW() WHERE matchid = 129
L 04/19/2019 - 15:14:23: [get5] Change from state 1 -> 0
L 04/19/2019 - 15:14:23: [get5_api] get5_web_api_url now set to
```

Create Scrim Match
I was thrown from the server
```
SuSpeCT: !get5
[5x5] ╨Ч╨░╨│╤А╤Г╨╢╨╡╨╜ ╨║╨╛╨╜╤Д╨╕╨│ ╨┤╨╗╤П ╨╝╨░╤В╤З╨░.
L 04/19/2019 - 16:32:51: [get5.smx] Setting player auths in the "players" section has no impact with get5_check_auths 0
L 04/19/2019 - 16:32:51: [get5] Change from state 0 -> 3
L 04/19/2019 - 16:32:51: [get5] get5_event: {"matchid`":"scrim","params":{"team1_name":"myteam","team2_name":"Away"},"event":"series_start"}
L 04/19/2019 - 16:32:51: {"matchid`":"scrim","params":{"team1_name":"myteam","team2_name":"Away"},"event":"series_start"}
L 04/19/2019 - 16:32:51: [get5_mysql] Setting up series stats, get5_mysql_force_matchid = 0
L 04/19/2019 - 16:32:51: [get5_mysql] INSERT INTO `get5_stats_matches` (series_type, team1_name, team2_name, start_time) VALUES ('bo1', 'myteam', 'Away', NOW())
L 04/19/2019 - 16:32:51: [get5_mysql] SELECT LAST_INSERT_ID()
L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><>
L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><>
L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><>
L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><>
L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><>
L 04/19/2019 - 16:32:51: [get5] get5_event: {"matchid`":"scrim","params":{"client":"SuSpeCT<3><STEAM_1:0:18656377><>","map_number":0,"map_name":"de_dust2"},"event":"player_disconnect"}
L 04/19/2019 - 16:32:51: {"matchid`":"scrim","params":{"client":"SuSpeCT<3><STEAM_1:0:18656377><>","map_number":0,"map_name":"de_dust2"},"event":"player_disconnect"}
Dropped SuSpeCT from server: ╨в╤Л ╨╜╨╡ ╤П╨▓╨╗╤П╨╡╤И╤М╤Б╤П ╤Г╤З╨░╤Б╤В╨╜╨╕╨║╨╛╨╝ ╤В╨╡╨║╤Г╤Й╨╡╨│╨╛ ╨╝╨░╤В╤З╨░`
```

- Plugin version: 0.7.1  
- Sourcemod version: 1.9.0.6276
- Steps to reproduce (please be specific): 

Created a team and made their steam id (76561ххххххххххххх)in the list, create a match, and at the entrance throws out from the server because you are not a member of this team

**Comment by TandelK** [comment]
Please check your Steam CMD that it is working with Internet. This error only comes when either CSGO Server cannot connect to Steam or with Steam CMD doesnt have access to Internet.

**Comment by suspectykt** [comment]
> 
> 
> Please check your Steam CMD that it is working with Internet. This error only comes when either CSGO Server cannot connect to Steam or with Steam CMD doesnt have access to Internet.
> 
> Also i think you are using both get5_mysql as well as get5_apistats plugin. While using get5_apistats , you have to remove get5_mysql

Prior to this work, removed get 5_mysql the error persists

**Comment by suspectykt** [comment]
> If making a feature request, you should delete all the pre-filled text here.
> If reporting a bug, fill in the following sections:
> ### Expected behavior
> 
> The problem when creating a match through the site get 5 webpanel players can not after creating a team to get to the server
> ### Actual behavior
> 
> ```
> L 04/18/2019 - 22:39:25: [get5.smx] Failed to get steamid for client pekuS<4><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:39:36: [get5.smx] Failed to get steamid for client pekuS<5><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:39:42: [get5.smx] Failed to get steamid for client ТАБУРЕТКА<6><STEAM_1:0:416728170><>
> L 04/18/2019 - 22:39:44: [get5.smx] Failed to get steamid for client 피카추<7><STEAM_1:0:421704078><>
> L 04/18/2019 - 22:39:48: [get5.smx] Failed to get steamid for client pekuS<8><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:39:55: [get5.smx] Failed to get steamid for client 피카추<9><STEAM_1:0:421704078><>
> L 04/18/2019 - 22:40:01: [get5.smx] Failed to get steamid for client pekuS<10><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:40:03: [get5.smx] Failed to get steamid for client 피카추<11><STEAM_1:0:421704078><>
> L 04/18/2019 - 22:40:16: [get5.smx] Failed to get steamid for client Красотка<12><STEAM_1:0:437245835><>
> L 04/18/2019 - 22:40:31: [get5.smx] Failed to get steamid for client ╰_╯<13><STEAM_1:0:425993768><>
> L 04/18/2019 - 22:40:36: [get5.smx] Failed to get steamid for client Красотка<14><STEAM_1:0:437245835><>
> L 04/18/2019 - 22:40:49: [get5.smx] Failed to get steamid for client pekuS<15><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:40:55: [get5.smx] Failed to get steamid for client 피카추<16><STEAM_1:0:421704078><>
> L 04/18/2019 - 22:40:57: [get5.smx] Failed to get steamid for client pekuS<17><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:41:36: [get5.smx] Failed to get steamid for client comediaN<18><STEAM_1:0:92041114><>
> L 04/18/2019 - 22:41:53: [get5.smx] Failed to get steamid for client ТАБУРЕТ<19><STEAM_1:1:114170613><>
> L 04/18/2019 - 22:56:03: [get5.smx] Failed to get steamid for client comediaN<25><STEAM_1:0:92041114><>
> L 04/18/2019 - 22:56:38: [get5.smx] Failed to get steamid for client ТАБУРЕТКА<26><STEAM_1:0:416728170><>
> L 04/18/2019 - 22:56:46: [get5.smx] Failed to get steamid for client ТАБУРЕТ<27><STEAM_1:1:114170613><>
> L 04/18/2019 - 22:57:17: [get5.smx] Failed to get steamid for client pekuS<28><STEAM_1:0:440927271><>
> L 04/18/2019 - 22:57:22: [get5.smx] Failed to get steamid for client 피카추<29><STEAM_1:0:421704078><>
> L 04/18/2019 - 22:57:35: [get5.smx] Failed to get steamid for client ТАБУРЕТ<30><STEAM_1:1:114170613><>
> L 04/18/2019 - 22:59:16: [get5.smx] Failed to get steamid for client comediaN<31><STEAM_1:0:92041114><>
> L 04/18/2019 - 23:00:28: [get5.smx] Failed to get steamid for client Красотка<32><STEAM_1:0:437245835><>
> ```
> 
> ### Steps to reproduce
> 
> Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by `get5_debuginfo` is extremely helpful.
> 
> `L 04/19/2019 - 15:13:24: [get5] cleanedUrl (SteamWorks) = http://.............../match/137/config L 04/19/2019 - 15:13:24: [get5_api] get5_web_api_url now set to L 04/19/2019 - 15:13:24: [get5] Change from state 0 -> 1 L 04/19/2019 - 15:13:24: [get5_api] get5_web_api_url now set to http://............/ L 04/19/2019 - 15:13:24: [get5] get5_event: {"matchid`":"137","params":{"team1_name":"Terra","team2_name":"Terra2"},"event":"series_start"}
> L 04/19/2019 - 15:13:24: [get5_mysql] Setting up series stats, get5_mysql_force_matchid = 0
> L 04/19/2019 - 15:13:24: [get5_mysql] INSERT INTO `get5_stats_matches` (series_type, team1_name, team2_name, start_time) VALUES ('bo1', 'Terra', 'Terra2', NOW())
> L 04/19/2019 - 15:13:24: [get5_mysql] SELECT LAST_INSERT_ID()
> L 04/19/2019 - 15:14:13: [get5] get5_event: {"matchid`":"129","params":{"client":"none","map_number":0,"map_name":"de_dust2"},"event":"player_disconnect"} L 04/19/2019 - 15:14:23: [get5_api] Trying to create request to url http://......./match/137/map/-1/finish L 04/19/2019 - 15:14:23: [get5_api] Added param key=779SFMG4L0TMXXUHPTDYCUDV to request L 04/19/2019 - 15:14:23: [get5_api] Added param team1score=0 to request L 04/19/2019 - 15:14:23: [get5_api] Added param team2score=0 to request L 04/19/2019 - 15:14:23: [get5_api] Added param winner=none to request L 04/19/2019 - 15:14:23: [get5_mysql] UPDATE `get5_stats_maps`SET winner = 'none', end_time = NOW() WHERE matchid = 129 and mapnumber = -1 L 04/19/2019 - 15:14:23: [get5_mysql] UPDATE`get5_stats_matches`SET team1_score = 0, team2_score = 0 WHERE matchid = 129 L 04/19/2019 - 15:14:23: [get5_api] Trying to create request to url http://............/match/137/finish L 04/19/2019 - 15:14:23: [get5_api] Added param key=779SFMG4L0TMXXUHXXXXXXXXX to request L 04/19/2019 - 15:14:23: [get5_api] Added param winner=none to request L 04/19/2019 - 15:14:23: [get5_api] Added param forfeit=0 to request L 04/19/2019 - 15:14:23: [get5_api] get5_web_api_url now set to http://....../ L 04/19/2019 - 15:14:23: [get5_mysql] UPDATE`get5_stats_matches`SET winner = 'none', team1_score = 0, team2_score = 0, end_time = NOW() WHERE matchid = 129 L 04/19/2019 - 15:14:23: [get5] Change from state 1 -> 0 L 04/19/2019 - 15:14:23: [get5_api] get5_web_api_url now set to`
> 
> Create Scrim Match
> I was thrown from the server
> `SuSpeCT: !get5 [�5x5�] ╨Ч╨░╨│╤А╤Г╨╢╨╡╨╜ ╨║╨╛╨╜╤Д╨╕╨│ ╨┤╨╗╤П ╨╝╨░╤В╤З╨░. L 04/19/2019 - 16:32:51: [get5.smx] Setting player auths in the "players" section has no impact with get5_check_auths 0 L 04/19/2019 - 16:32:51: [get5] Change from state 0 -> 3 L 04/19/2019 - 16:32:51: [get5] get5_event: {"matchid`":"scrim","params":{"team1_name":"myteam","team2_name":"Away"},"event":"series_start"}
> L 04/19/2019 - 16:32:51: {"matchid`":"scrim","params":{"team1_name":"myteam","team2_name":"Away"},"event":"series_start"} L 04/19/2019 - 16:32:51: [get5_mysql] Setting up series stats, get5_mysql_force_matchid = 0 L 04/19/2019 - 16:32:51: [get5_mysql] INSERT INTO `get5_stats_matches` (series_type, team1_name, team2_name, start_time) VALUES ('bo1', 'myteam', 'Away', NOW()) L 04/19/2019 - 16:32:51: [get5_mysql] SELECT LAST_INSERT_ID() L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><> L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><> L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><> L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><> L 04/19/2019 - 16:32:51: [get5.smx] Failed to get steamid for client SuSpeCT<3><STEAM_1:0:18656377><> L 04/19/2019 - 16:32:51: [get5] get5_event: {"matchid`":"scrim","params":{"client":"SuSpeCT<3><STEAM_1:0:18656377><>","map_number":0,"map_name":"de_dust2"},"event":"player_disconnect"}
> L 04/19/2019 - 16:32:51: {"matchid`":"scrim","params":{"client":"SuSpeCT<3><STEAM_1:0:18656377><>","map_number":0,"map_name":"de_dust2"},"event":"player_disconnect"} Dropped SuSpeCT from server: ╨в╤Л ╨╜╨╡ ╤П╨▓╨╗╤П╨╡╤И╤М╤Б╤П ╤Г╤З╨░╤Б╤В╨╜╨╕╨║╨╛╨╝ ╤В╨╡╨║╤Г╤Й╨╡╨│╨╛ ╨╝╨░╤В╤З╨░`
> 
>     * Plugin version: 0.7.1
> 
>     * Sourcemod version: 1.9.0.6276
> 
>     * Steps to reproduce (please be specific):
> 
> 
> Created a team and made their steam id (76561ххххххххххххх)in the list, create a match, and at the entrance throws out from the server because you are not a member of this team

**Comment by TandelK** [comment]
Can you please check your Steam Status and also SteamWorks extension status.

**Comment by splewis** [comment]
There's nothing get5 can really do here. That error messages just means it can't get steamids for clients through sourcemod. You probably have some connection issue to steam.

**Comment by atmartorana** [comment]
I have the same issue and I already checked steam status and steamworks extension, with no connection issues.

**Comment by PhlexPlexico** [comment]
Do you have sv_lan set to 0 or 1?

**Comment by atmartorana** [comment]
sv_lan 1

**Comment by JustinBenedick** [comment]
is the fact sv_lan1 going to cause a problem? I am having the same issue.

**Comment by PhlexPlexico** [comment]
`sv_lan 1` is an option set to disallow people from outside the network connecting. I can only assume this prevents calls from the server from going to the internet. Please set it to 0 and give it a try.

**Comment by tloesch** [comment]
I had the same problem 2 years ago.
@PhlexPlexico you are right. sv_lan 1 is causing the problem. With sv_lan 1 the server can't fetch the steamids.

**Comment by JustinBenedick** [comment]
Is there a good way get around this? I am in a situation where I have to prepare for the internet to randomly disconnect. I can't have a tournament stall or get interrupted because the cable went out.

**Comment by PhlexPlexico** [comment]
It depends when you mean the internet randomly disconnecting? You mean external? Even if the server is set to `sv_lan 0` and you have people connect to the LAN IP, they won't have any issues if the network dies, since they're not connecting externally. And since a user would be in the game already, it wouldn't kick them.

I may need someone to confirm that though, as I haven't tested it, but it would make sense since you're not cutting off any LAN access. just external access.

**Comment by splewis** [comment]
Yeah, I'm not sure I understand either. Afaik, using sv_lan 0 has been an acceptable workaround for people.

**Comment by fidel-code** [comment]
I have the same problem.  He does not want to recognize me the steamid.  And the stats are not inserted in the db.  However I check the backups and I can see the steamid as they arrive in steamid32 format.  What can I do?  Lift the Steam with an emulator called Tinserver.  Pork in Cuba there is no internet for this.  slds

**Comment by nickdnk** [comment]
Likely not a get5 problem. Closing due to age.
