### ISSUE TITLE
How to get custom input

### ISSUE THREAD

**Issue by mgjuhler** [splewis/get5#377]
Hi,
I am working on my own sourcemod plugin that uses get5. Even though I am brand new to SourcePawn, it going okay. I would like to add my own custom inputs and values to the match schema, like a team id in the team section. how can i get the info when loading a match config?

config example (only the team part) 

`"team1": {
    "id": "19",
    "name": "team one name",
    "tag": "",
    "flag": "dk",
    "logo": "",
    "players": [
        "76561197961604312"
    ]
},
"team2": {
    "id": "18",
    "name": "team two name",
    "tag": "",
    "flag": "dk",
    "logo": "",
    "players": [
        "76561198017643256"
    ]
},`

**Comment by splewis** [comment]
I'm not really sure what you're trying to do, but you'd have to read the config file & parse it in your other plugin. You're basically adding arbitrary fields to a get5 config file - so get5 can't really expose it directly.

There's a ``Get5_OnPreLoadMatchConfig`` forward that could be used.

**Comment by mgjuhler** [comment]
I got it working by adding "get5_team1Id" and "get5_team2Id" to the cvar section of the config.
