### ISSUE TITLE
Incorrect pausing headers

### ISSUE THREAD

**Issue by abdulsami34** [splewis/get5#378]
If reporting a bug, fill in the following sections:

### Expected behavior

Pausing Header should be working as Counter Terrorist Timeout (0/4) (1/4) and so on

### Actual behavior

Counter Terrorist Timeout (0/4) remain 0/4 even 2 or 3 pauses are used 

### Steps to reproduce

 
Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: 1.9 - build 6276
- Steps to reproduce (please be specific): 

get5_max_pauses = 4
get5_reset_pauses_each_half = 1
get5_fixed_pause_time = 60
get5_pausing_enabled = 1

**Comment by MikkelDK** [comment]
Please. - You need to edit your text, and fill out with this!

Don't delete the text for bugs:

```
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):
```

**Comment by splewis** [comment]
At least give a version number and the pausing cvars you've set. Aka "Steps to reproduce".

**Comment by abdulsami34** [comment]
Updated.

**Comment by nickdnk** [comment]
Should have been resolved after https://github.com/splewis/get5/pull/547. If not, reopen.
