### ISSUE TITLE
plugin: is team1 CT or T?

### ISSUE THREAD

**Issue by mgjuhler** [splewis/get5#379]
i working on my plugin based on get5 and would like to know if there is a way that i can get info on if team1 is CT or T? or on which side both teams are?

**Comment by mgjuhler** [comment]
Closing, used this:

```
 char team1Name[64];
 char team2Name[64];

 char team1NameSz[sizeof(team1Name) * 2 + 1];
 char team2NameSz[sizeof(team2Name) * 2 + 1];

 KeyValues tmpStats = new KeyValues("Stats");

 Get5_GetMatchStats(tmpStats);

 tmpStats.GetString(STAT_SERIES_TEAM1NAME, team1Name, sizeof(team1Name));
 db.Escape(team1Name, team1NameSz, sizeof(team1NameSz));

 tmpStats.GetString(STAT_SERIES_TEAM2NAME, team2Name, sizeof(team2Name));
 db.Escape(team2Name, team2NameSz, sizeof(team2NameSz));
```

**Comment by mgjuhler** [comment]
i thought i had found a way to do it .. but it did not work: (

**Comment by mgjuhler** [comment]
Any help?

**Comment by PhlexPlexico** [comment]
Is `team1` not CT by default when the match is created, if there is a veto? So can you just not check what the current half is?

The reference to `team1` [is here](https://github.com/splewis/get5/blob/aa8ecf49b7ee46cf5e828f081a98bf21785d69a3/scripting/get5.sp#L43) so why not just get what current half it is, then you should be able to deduce who is on what side, right?

**Comment by splewis** [comment]
Can you explain what your use case is?

I wouldn't necessarily be opposed to moving MatchTeamToCSTeam (and its inverse) to a get5 native, but I'd like to know the use case first: https://github.com/splewis/get5/blob/master/scripting/get5/teamlogic.sp#L184-L194

**Comment by mgjuhler** [comment]
In my website I have an "ingame" log of everything that happens in the match: player join, player disconnect, say, kill, bomb etc. These data I get from Get5_OnEvent (). I want some colors on so it's easier to see if the player is T or CT. The json data I get from Get5_OnEvent does not tell if the player is T or CT. If I had data on which team is T and which team is CT already at Get5_OnGoingLive () then that would help a lot.

I am still wery new to sourcespawn and i have been trying to debug
```
// Team navne
char team1Name[64];
char team2Name[64];

char team1NameSz[sizeof(team1Name) * 2 + 1];
char team2NameSz[sizeof(team2Name) * 2 + 1];

KeyValues tmpStats = new KeyValues("Stats");

Get5_GetMatchStats(tmpStats);

tmpStats.GetString(STAT_SERIES_TEAM1NAME, team1Name, sizeof(team1Name));
db.Escape(team1Name, team1NameSz, sizeof(team1NameSz));

tmpStats.GetString(STAT_SERIES_TEAM2NAME, team2Name, sizeof(team2Name));
db.Escape(team2Name, team2NameSz, sizeof(team2NameSz));

LogMessage("---------------------------------------------------------------");
LogMessage("Team 1: %s", team1NameSz);
LogMessage("Team 2: %s", team2NameSz);
LogMessage("---------------------------------------------------------------");
LogMessage("team1Name: %d", team1Name);
LogMessage("team2Name: %d", team2Name);
LogMessage("team1Name: %s", team1Name);
LogMessage("team2Name: %s", team2Name);
LogMessage("---------------------------------------------------------------");

// Team side
g_TeamSide[MatchTeam_Team1] = TEAM1_STARTING_SIDE;
g_TeamSide[MatchTeam_Team2] = TEAM2_STARTING_SIDE;

LogMessage("---------------------------------------------------------------");
LogMessage("Team 1 side: %d", g_TeamSide[MatchTeam_Team1]);
LogMessage("Team 2 side: %d", g_TeamSide[MatchTeam_Team2]);
LogMessage("---------------------------------------------------------------");
LogMessage("MatchTeam_Team1: %d", MatchTeam_Team1);
LogMessage("MatchTeam_Team2: %d", MatchTeam_Team2);
LogMessage("MatchTeam_Team1: %s", MatchTeam_Team1);
LogMessage("MatchTeam_Team2: %s", MatchTeam_Team2);
LogMessage("---------------------------------------------------------------");
LogMessage("2: Terrorists, 3: Counter-Terrorists");
LogMessage("---------------------------------------------------------------");
```

My match config:
team1: TestTeam1
team2: TestTeam2

team1_name allways return TestTeam1
team2_name allways return TestTeam2,

team1_side allways return 3 and team2_side allways return 2

**Comment by splewis** [comment]
Exposing both `MatchTeamToCSTeam` and `CSTeamToMatchTeam` as natives is probably reasonable.

The changes needed are local to include/get5.inc & get5/natives.sp, for example:
- Get5_AddPlayerToTeam: https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L109

- Native_AddPlayerToTeam: https://github.com/splewis/get5/blob/master/scripting/get5/natives.sp#L128-L137

- tie them together: https://github.com/splewis/get5/blob/master/scripting/get5/natives.sp#L10

**Comment by splewis** [comment]
I guess this is resolved? I'd still accept a PR with the things above, though.
