### ISSUE TITLE
Record demoes to a different filename after backup restoration

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#381]
If there is a server crash and we load the last backup file , the Demo recording doesnt work properly as it has already same name file in the directory. There should be a condition for backup loading and demo recording if the backup command is used , it should the new file with _backup.demo in the end making it clear for 2 different demos one before crash and one after backup loaded.

**Comment by nickdnk** [comment]
Just add `{TIME}` to your demo filename. This will be made the default format in a future version.
