### ISSUE TITLE
Question about loading a match from url

### ISSUE THREAD

**Issue by HugoVizcainoSantana** [splewis/get5#382]
First of all, hello here. This mod/plugin is amazing and I´m having a blast working with it.

I´m trying to load a JSON match config from a remote url using the command `get5_loadmatch_url`, but I´m having issues with it.
I can attach here an URL to a sample json i have generated with my API/Interface, and help me debug if down the road we see some issues or bugs in a library or anything.

The url passed to the server through rcon, should offer a download for that JSON? Or only its content as text, so the server plugin can read it? 

Thanks a lot!

**Comment by splewis** [comment]
The plugin issues a HTTP GET request to the url, and parses the response as the json config.

So the url should probably just return the content.
