### ISSUE TITLE
Spectator list ignored

### ISSUE THREAD

**Issue by encg** [splewis/get5#390]
### Expected behavior

Match config loads and automatically moves spectators who are defined in the match file to the spectator team

### Actual behavior

Spectator is kicked from server: "You are not a player in this match."

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: Development build #463 (https://ci.splewis.net/job/get5/463/)
- Sourcemod version: 1.9.0.6281
- Steps to reproduce (please be specific):

New installation of get5 using guide in wiki.
Added my SteamID64 (also tried SteamID & SteamID3) to spectators area of cfg file
Joined server as spectator, executed match config with rcon, kicked from server
I can see that the server is forcing all 11 client names (admin + 10 players) per console
The solutions in other threads with this issue are not working for me

[399_example.txt](https://github.com/splewis/get5/files/3184758/399_example.txt)

**Comment by splewis** [comment]
I'm wasn't able to reproduce the problem. I used the same config (but replacing the steamid with mine) and joined and was forced into spec. 

The only difference is that I didn't use that exact development build or the json library at HEAD like that automatic build used - it's possible changes in that are the issue (also see https://github.com/splewis/get5/issues/364).

You could try the 0.7.1 release to see if it still happens there (it did not have the json issues).

**Comment by encg** [comment]
Thanks. I'll try 0.7.1
