### ISSUE TITLE
Add option for chat-based vetoing instead of menus

### ISSUE THREAD

**Issue by splewis** [splewis/get5#391]
E.g. users type them out:

.ban de_dust2
.ban de_vertigo
.pick de_train

and such. Probably just choosable by cvar.

**Comment by vassilidev** [comment]
better with !veto [MAP] ? and for bo3 !side [SIDE] ?

**Comment by nickdnk** [comment]
@splewis In the PR I have open for this, I made enabling chat veto optional via a Cvar. Based on my limited experience with it (so far), I don't see why anyone would choose menus over the chat option. It's much better. Do you have any opinion on removing the menu logic entirely or whether it should just default to chat?
