### ISSUE TITLE
Pauses by coaches are untimed

### ISSUE THREAD

**Issue by encg** [splewis/get5#396]
### Expected behavior
Pause initiated by coach should last 30 seconds.

### Actual behavior
Pause is untimed (like a tech pause) and not deducted from total number of allotted pauses. The !unpause command from any player does nothing. Need to do rcon mp_unpause_match. 

Pausing from players works as expected (30s timer).

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: Sourcemod version: 1.9.0.6281
- Steps to reproduce (please be specific): 

Coach joins coach role when game goes live and types !pause. Game is paused at halftime without timer. Pause settings:

get5_allow_technical_pause 1
get5_fixed_pause_time 30
get5_max_pause_time 120
get5_max_pauses 4
get5_pausing_enabled 1

**Comment by BubbiBjQrn** [comment]
Can confirm this bug
- Plugin versionBuild #514

get5_allow_technical_pause 1
get5_fixed_pause_time 60
get5_max_pause_time 300
get5_max_pauses 2
get5_pausing_enabled 1
