### ISSUE TITLE
Get Coach Steam ID

### ISSUE THREAD

**Issue by PhlexPlexico** [splewis/get5#398]
Is there anyway to get the steam ID of the coaches? Looking through the repo, it mainly requires the client index, but is there any other way to get the IDs of who is currently coaching?

**Comment by splewis** [comment]
Can you explain what you're trying to do? Is this in another plugin? From reading the stats?

**Comment by PhlexPlexico** [comment]
Specifically I'm trying to add on to the api-stats plugin, and realized that when stats are updated via API call, the coach is included. I know there's a few things I could do on an application end (such as remove user stats where everything is 0), but wanted to see if there was a way for get5 to identify the coach without using ClientID.

Thanks!

**Comment by splewis** [comment]
The real problem sounds like get5 shouldn't be exporting coaches in the stats keyvalue structure at all.

**Comment by PhlexPlexico** [comment]
Okay, I can confirm this in a few days here if that's the case. Would you like me to create a new issue if that's the problem, or just edit the main post with the bug template?

**Comment by PhlexPlexico** [comment]
Okay so here's a match file attached that had a coach included on Top Shelf, you can see the user "Uncharted" is included, even though he is a coach and had no stats recorded.

https://pastebin.com/iu072HV7

So why is the user being recorded, is it because they are technically on the team? Would it be possible to just give them a "coach" KV or something similar to discern and exclude them? Thank you!

**Comment by splewis** [comment]
> So why is the user being recorded, is it because they are technically on the team?

I don't know. I haven't looked.

> Would it be possible to just give them a "coach" KV or something similar to discern and exclude them?

Yes. I'd probably prefer for them to have a "coach" value set.

**Comment by saintplay** [comment]
adding a `!IsClientCoaching(i)` in <https://github.com/splewis/get5/blob/master/scripting/get5/stats.sp#L90>  would do the job, right?

but, is the helper `isClientCoaching()` reliable through all the phases? because I only see it being used in Warmup and Knife Round (to correctly moving the coach)

**Comment by PhlexPlexico** [comment]
Since I've opted to take the get5_apistats and rewrite some of it, I'm actually going to use that by (slowly) looping through the auths and checking if their client number aligns with a coach position. Thanks for pointing out that util call, didn't know it existed! I believe while slower, it should prevent data from being sent.
