### ISSUE TITLE
Team1 error

### ISSUE THREAD

**Issue by GreYzZ** [splewis/get5#4]
[get5.smx] Missing "team1" section in match json
[get5.smx] Failed to load match config from Game.json

How can I fix this?

**Comment by splewis** [comment]
Can you post the match config file you're using (Game.json)?

**Comment by GreYzZ** [comment]
@splewis 
here: http://pastebin.com/dNb5yQ9K

**Comment by splewis** [comment]
There's an extraneous }, at line 31:

get5_loadmatch Game.json
L 02/01/2016 - 13:01:28: [SMJSON] Error in line 31, col 2: string or '}' expected near '}'
L 02/01/2016 - 13:01:28: [get5.smx] Failed to load match config from Game.json
Failed to load match config.
