### ISSUE TITLE
Restoring from backup file does not remove [READY] prefix from team names

### ISSUE THREAD

**Issue by encg** [splewis/get5#400]
### Expected behavior
Both teams .ready after get5_loadbackup file and team names update from "[READY] Team Name" to "Team Name"

### Actual behavior
Team names stay as "[READY] Tean Name" and must manually be updated

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: 1.9.0.6281
- Steps to reproduce (please be specific): Load match config and load backup once a few rounds have passed

**Comment by splewis** [comment]
Looks like the same as #163.
