### ISSUE TITLE
Allow extra team pick for pick/ban in a BOx series

### ISSUE THREAD

**Issue by CrystallineGod** [splewis/get5#401]
Hello,

Just yesterday I played a BO7 with a server that uses Get5, and I noticed if knife round is disabled, the side will be randomized.

As an addition to this system, in pick/ban scenario, allow the team that didn't pick the map choose sides.

Example in a ban/ban/pick/pick/ban/ban/left over scenario, because my wording is atrocious:
Team A bans de_dust2
Team B bans de_vertigo
Team A picks de_mirage
_Team B now has the option to choose what side to start de_mirage on, by typing (!ct or !t)_
Team B picks de_overpass
_Team A can now pick which side they want to start de_overpass on_
Team A bans de_nuke
Team B bans de_inferno
_de_train is left over. It's now up to TO or admins whether to make the choice in sides random or decided through knife round._

**Comment by splewis** [comment]
> and I noticed if knife round is disabled, the side will be randomized.

That's not true (it could be a bug, but that's unlikely imo). The only time randomness is applied is when a knife round is enabled and both teams have equal # of players and a equal total amount of health.

> de_train is left over. It's now up to TO or admins whether to make the choice in sides random or decided through knife round.

In this example, it depends on the configuration. There's no random option supported, but there are ways to force a knife round or force a team into a specific side.

The 'typical' use case is where teams that don't pick the map picks the side, and vice versa. Then the final map is a knife round. That's basically the default configuration. I can't say why your match didn't have that without more information though (e.g. a match config, plugin version, etc.).

**Comment by CrystallineGod** [comment]
I wasn't sure if it was random or the TO was choosing our teams. I doubt it's Get5 that is randomizing teams then.

Our match had knife rounds disabled.

**Comment by splewis** [comment]
It sounds like the match config just disabled knife rounds. If there's a concrete match config with incorrect behavior I can look, but otherwise get5 appears to be working as intended.
