### ISSUE TITLE
Http Error with lan url

### ISSUE THREAD

**Issue by Iwhite67** [splewis/get5#403]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Hi

Windows Serv with Hyper-V with DNS Serv
VM 1 : CSGO
VM 2 : Get5

All with ip from Main Router Network

Csgo : 192.168.10.52
Get5 : 192.168.10.55 with get5.lan

Serv can't load url in local network but only wan network

### Actual behavior

when i create a match from this hostname, a have http error

when i create a hostname from my web dns (ex : coucou.white-gaming.fr) i come from outside of network and is working

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: last release
- Sourcemod version: last stable
- Steps to reproduce (please be specific):
Create match on Webpanel (second VM), Start, i can't with Lan Url (get5.lan) but i can with Wan Url (get5.white-gaming.fr)

**Comment by splewis** [comment]
There isn't much I can really do to help to debug why http requests in the steamer extension fails, unfortunately. The use of get5-web & the get5_apistats plugin isn't intended to be supported, either, so I don't really recommend their use.

**Comment by Iwhite67** [comment]
I thinks is more a problem with steamwork (or maybe m'y Docker container (problem dans)

**Comment by TandelK** [comment]
As far as i know last time we tested the Host modify system and it was working fine. Make sure your CSGO server has modified host file

**Comment by Iwhite67** [comment]
When i ping is good, but maybe Docker not received, i go test outside docker

**Comment by TandelK** [comment]
i am totally out of docker system we did use system with Ubuntu Bash on Windows 10 system and that was working fine

**Comment by Iwhite67** [comment]
ok, i have view on pterodactyl panel who start my csgo container, with a DNS 8.8.8.8

i go try soon to edit this lines with my own dns ip

**Comment by TandelK** [comment]
@Iwhite67 did it work ?

**Comment by Iwhite67** [comment]
No but i bypass

I have on m'y own domain (white-gaming.fr) a entry A get5 with local IP

So i ask panel with wan url, he's taking local IP and he's good

**Comment by TandelK** [comment]
@Iwhite67 if you found a work around please close this issue.

**Comment by Iwhite67** [comment]
Hello, this is fix or not ?

**Comment by Drarig29** [comment]
I'm afraid you are the only one to be able to solve your deployment configuration. This is not a problem of get5.

**Comment by Iwhite67** [comment]
Is a problem on docker side


_________________________

Alexis Zaun
Technicien SAV Nord Est

FOM Industrie FRANCE

***@***.******@***.***>
(+33) 06 40 62 82 45
________________________________

**Comment by Drarig29** [comment]
Not sure about this 😁

**Comment by nickdnk** [comment]
Closed as this has nothing to do with get5 and is also over 2 years old with no new information.
