### ISSUE TITLE
FPS Issues?

### ISSUE THREAD

**Issue by LubricantJam** [splewis/get5#406]
Not sure if this is a CS:GO bug or a Get5 bug. Basically, upon a round start (and only when the round starts) clients FPS drops to around 10-20 constantly until they rejoin. I've checked all server logs, error logs, server FPS, etc and nothing is giving me a clear understanding as to what is happening. 

Any ideas?

**Comment by MikkelDK** [comment]
I can't confirm it.

I don't have problems with csgoservers running Get5.

Did you try running "vanilla" (standard) csgoserver, without sourcemod installed? - about it did lag/fps drops?

**Comment by LubricantJam** [comment]
Mhm, it's odd as it's never really happened in any of my other server instances. I've a slight feeling it might be to do with StealthRevived so I'll see if that's the issue.
