### ISSUE TITLE
[Feature Request] Add some Feature

### ISSUE THREAD

**Issue by Iwhite67** [splewis/get5#407]
Hi, i'm running actualy a lan Event, your plugins is very good and stable.

but he is missing some info for Web panel

Return on SQL Pause + Veto
When i make a backup, all people keep NOT READY

i continue here if i found other feature

**Comment by splewis** [comment]
> but he is missing some info for Web panel

"get5" is a server plugin, not a web panel. This plugin is unrelated to any specific web panel you happen to use.

> Return on SQL Pause + Veto

I don't know what that means.

> When i make a backup, all people keep NOT READY

#163

**Comment by Iwhite67** [comment]
Plugin push on SQL server when the match IS pause

**Comment by splewis** [comment]
> Plugin push on SQL server when the match IS pause and Veto map

Again - get5 doesn't do anything with sql. Other plugins are free to do whatever they want. See https://github.com/splewis/get5#api-for-developers. The get5_apistats & get5_mysqlstats are just functional examples, that happen to work for many people.

> After, he's possible on after bo3/Bo5 veto, to skip the first Map ? (Example for Final of Double Elimination Bracket)

This is already possible with the series_score field in the match config: https://github.com/splewis/get5#team-schema. If you're using a webpanel, it needs to set that field. https://github.com/splewis/get5-web does not have any way for a user to set that field, and probably never will, but that's not related to the plugin.

**Comment by TandelK** [comment]
@Iwhite67 i would recommend you to check out Phlex Get5-Web version which does contains all this required functions, its still in development but still you can try it out.

**Comment by Iwhite67** [comment]
Hi @tandelk do you have link ?

**Comment by Iwhite67** [comment]
Hi, is not closed :)

**Comment by TandelK** [comment]
@Iwhite67 here at https://github.com/PhlexPlexico/get5-web/ 

Checkout the development branch as well we all are in single discord server to test out new function from daily basis . 


You can join us with Phlex himself in the Discord Server at https://discord.gg/dgzUzSB

**Comment by Iwhite67** [comment]
Great ty
