### ISSUE TITLE
[Feature Request] Custom Pausing

### ISSUE THREAD

**Issue by b3none** [splewis/get5#409]
Working with Get5 It'd be nice if we could somehow define a custom pausing method by perhaps setting a forward thus allowing a third party plugin to handle the pausing.

**Comment by TandelK** [comment]
i think running a special 3rd party plugin with get5 will be a bad idea. The more independent and alone plugin is Get5 it is better for Server.

**Comment by splewis** [comment]
Unlikely to happen. If you really want it I'd have to see how it's implemented in a PR, but it seems likely it's too niche.
