### ISSUE TITLE
Failed to Load Match

### ISSUE THREAD

**Issue by klisiana** [splewis/get5#411]
### Expected behavior
after get5_loadmatch the cfg should be loaded

### Actual behavior
Config wont load, but is in the folder
the config or folder is not write-protected
> L 06/13/2019 - 15:32:16: [get5.smx] Failed to load match config: Match kv file doesn't exist: "addons/sourcemod/configs/get5/amd.cfg"
L 06/13/2019 - 15:33:04: [get5.smx] Failed to load match config: Match kv file doesn't exist: "csgo/amd.cfg"
L 06/13/2019 - 15:41:34: [get5.smx] Failed to load match config: Match kv file doesn't exist: "csgo/amd.cfg"
L 06/13/2019 - 15:41:37: [get5.smx] Failed to load match config: Match kv file doesn't exist: "addons/sourcemod/configs/get5/amd.cfg"
L 06/13/2019 - 15:42:02: [get5.smx] Failed to load match config: Match kv file doesn't exist: "csgo/amd.cfg"
L 06/13/2019 - 15:43:24: [get5.smx] Failed to load match config: Match kv file doesn't exist: "amd.cfg"
L 06/13/2019 - 15:43:53: [get5.smx] Failed to load match config: Match kv file doesn't exist: "amd.cfg"
L 06/13/2019 - 15:44:12: [get5.smx] Failed to load match config: Match kv file doesn't exist: "amd.cfg"
L 06/13/2019 - 15:44:52: [get5.smx] Failed to load match config: Match kv file doesn't exist: "csgo/amd.cfg"
L 06/13/2019 - 15:47:24: [get5.smx] Failed to load match config: Match kv file doesn't exist: "addons/sourcemod/configs/get5/live.cfg"
L 06/13/2019 - 15:52:09: [get5.smx] Failed to load match config: Match kv file doesn't exist: "addons/sourcemod/configs/get5/live.cfg"
L 06/13/2019 - 15:52:21: [get5.smx] Failed to load match config: Match kv file doesn't exist: "addons/sourcemod/configs/get5/amd.cfg"
L 06/13/2019 - 15:53:45: [get5.smx] Failed to load match config: Match kv file doesn't exist: "addons/sourcemod/configs/get5/amd.cfg"

### Steps to reproduce
config: https://pastebin.com/zXDYwqhq

Plugin version: 0.7.2-dev+466
sourcemod_version = 1.9.0.6281
metamod_version = 1.10.7-devV
get5 git commit: 849cf3c

**Comment by Technoblazed** [comment]
Triple make sure that the file exists in the correct location location and you don't have any interesting sourcemod configs set that are changing defaults.

**Comment by TandelK** [comment]
Sometime you might get confused with configs folder located in sourcemod instead of that you might have put it in cfg/get5/  or cfg/sourcemod/ folder. Please re-verify your file path properly.

**Comment by splewis** [comment]
https://github.com/splewis/get5/blob/849cf3c76f33869e0b6bdb21ea7fa9e1c9caea82/scripting/get5/matchconfig.sp#L150

get5 is just using the normal sourcemod api to read files, so unfortunately I don't think there's anything we can do to help here. You'd have to debug your file system issues yourself most likely.
