### ISSUE TITLE
Include an Get5_OnMatchPause and Get5_OnMatchUnpause event

### ISSUE THREAD

**Issue by PhlexPlexico** [splewis/get5#412]
Hi!

I'd like to make a suggestion to include a new forward for whenever a match is paused or unpaused within get5. The way I've seen it justified is that if there is a way to detect pauses, a user could create their own plugin to track the forward and store the values/provide feedback on matches that are paused to their own services (i.e. API responses). It could also be led to more data collection on a service that uses get5 to see how many average pauses are taken per match  over a period of games, as an example.

If there is not a way of tracking this already, would this be a good suggestion to look into?

Thanks!

**Comment by splewis** [comment]
There's an existing PR that has unresolved problems: https://github.com/splewis/get5/pull/386

**Comment by vassilidev** [comment]
sm_unpause
