### ISSUE TITLE
Unpause command works while pausing is disabled

### ISSUE THREAD

**Issue by Sn0weyTV** [splewis/get5#413]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
The expected behaviour of this command shouldn't return anything as the get5_pausing is disabled.

### Actual behavior

Returns string "[Get5] Team 1 wants to unpause, waiting for Team 2 to type !unpause" 

The reason this is, I don't believe you are listening for the cvar around the unpause command as the pause command has no issues however the unpause does.

EDIT: Further looking into the issue it looks like whenever mp_pause_match is called it thinks that pausing is enabled when it may not be. The way around this would be to look at the pausing CVar and see if it's 1 if it is then we can execute this command otherwise Plugin_Handled and ignore the state. 

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.2-dev
- Sourcemod version: 1.9.0.6276
- Steps to reproduce (please be specific):

Run the default plugin but just have these values set in your configuration:
get5_pausing_enabled "0"
get5_fixed_pause_time "0"
get5_allow_technical_pause "0"

Then enter "Match paused state". (mp_pause_match)

**Comment by nickdnk** [comment]
Use of `mp_pause_match` directly is unsupported, and admins should call `sm_pause` always.
