### ISSUE TITLE
best of 3 and 5 problem!!!

### ISSUE THREAD

**Issue by Lummppy** [splewis/get5#414]
Hello Sean
There is something i wanted you to know that now a days knife rounds dont happen everthing happens outside the game so saying about the veto thing... as we get info we setup the match config like we know who is team A in t and Team B in ct , in the 1st map the everthing is awesome but when the second maps changes the teams dont change like now Team B should be T and A should be CT and if its a tie like in a best of 3 ,if  score is 1 - 1 in the 3rd map their should be an option that shoul asked knife round or Toss like natural toss same goes in the best of 5 series....

**Comment by TandelK** [comment]
For that you can modify the code as per your  requirement . Basically the thing which you are talking about outside game Veto which can be modified with get5 apistats plugin and run from a website. You will need to make changes on your own

**Comment by TandelK** [comment]
Also think this way where will get5 know which maps are to be selected and which team has picked which map. You will require a API to communicate with your Plugin/Website to tell Get5 which maps and side to used for which rounds. All this things have to been done with your website and get5 apistats plugin which supports sending JSON API calls.

**Comment by Lummppy** [comment]
add me in steam

**Comment by splewis** [comment]
I can't tell if this is a bug report, feature request, or a question about how get5 works. Knife rounds are the default for map 3's of a bo3, and there is no option for random sides yet.

**Comment by Lummppy** [comment]
no i just wanted to know how can i set team sides in that match cfg in a bo3 format

**Comment by TandelK** [comment]
There are 2 ways to do it. If you are trying to use Veto Function than the system has already in built system where Team A selects Map Team B gets Side Selection and after that Team B select Maps and Team A gets Side Selection in Veto itself. This is majorly used format in all major tournaments. 


Option 2 : Predefined Team Settings via Config file . 
Like i gave you the link : https://github.com/splewis/get5/wiki/Map-Vetoes#skipping-the-plugins-veto

It is given as to Skip Veto and manually use Maps selected by your website or other plugin but has to be done via a API Plugin or Config file. 

```
"skip_veto"		"1"
"map_sides"
{
	"team1_ct"		""
	"team2_ct"		""
	"knife"		""
}
"maplist"
{
	"de_cache"		""
	"de_mirage"		""
	"de_overpass"		""
}
```

The above code in your config file will tell server that it has to skip the in Game Veto system and use predefined maps which can be set and Map Sides can be set also but it has to set in correct method

First Map - First Map Side selection it will get executes accordingly. If you are having website to create Veto and create JSON API you can also send that to the server with rcon match config.
