### ISSUE TITLE
[Question] Using No Team Defined in Scrim Template

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#415]
While using Scrim Command scrim_template.cfg is used by default but i want to load matches with both the players are not defined in the teams section . I know only team1 has to be defined for that but is there any way we can use no predefined teams in scrim template not even `team1` ?

**Comment by splewis** [comment]
The only difference when in scrim mode is that anyone not in team1 is implicitly team2. If neither team is specified, I'm not sure what you expect to happen. You might as well set `get5_check_auths` to 0 and let people get on the right team themselves.

**Comment by TandelK** [comment]
Is there any way we can define config for get5_creatematch command ? with `get5_check_auths 0`

**Comment by splewis** [comment]
> Is there any way we can define config for get5_creatematch command

No, you can't customize anything get5_creatematch does. You could have get5_check_auths set elsewhere, or by another plugin, or create a match config otherwise (manually, another plugin, etc).
