### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by splewis** [splewis/get5#42]

**Comment by pistoolero** [comment]
Do you need help with implementation or just with translate phrases?

**Comment by splewis** [comment]
By "translation support" I mean taking most of the English phrases out of the source code and putting them into translations/get5.phrases.txt and using the new translation keys in the source code, not just other languages.

**Comment by NUM1337** [comment]
I would like to do English -> Polish

Best regards, NUM.

**Comment by MikeyUMF** [comment]
I can help English -> Spanish

MikeyUM

**Comment by jfkz** [comment]
I'm working on Russian translation and general translation support.
