### ISSUE TITLE
Cant save stats in mysql

### ISSUE THREAD

**Issue by neltharionorg** [splewis/get5#420]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
should save

### Actual behavior
not saving

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version:1.9 - build 6281
- Steps to reproduce (please be specific):
![Capture](https://user-images.githubusercontent.com/28743090/63340236-9cb21b80-c357-11e9-84f2-dc791c91ee40.PNG)
![23](https://user-images.githubusercontent.com/28743090/63340280-b81d2680-c357-11e9-9d66-89d9f6f8f688.PNG)

**Comment by ttibau** [comment]
@neltharionorg  how do you solved this?
