### ISSUE TITLE
Show damage at end of round

### ISSUE THREAD

**Issue by dwwesley** [splewis/get5#421]
**Splewis all good man?**

- Brother let me ask you a question, yesterday I tested your plugin and I really liked the structure, but some points apparently can be a bug, for example setting the maximum time of a break is 60, which in case would be 1 minute, the game was paused until both teams entered the chat command to undo.

- Another important issue is the damage caused, which is not being shown at the end of each round, even activated in the cfg / sourcemod file.

- Another very important thing, every time you need to enable a competitive match you need to use the command! Get5 or! Scrim, all this could not have an option in the cfg / sourcemod file, to be all automatic, entered the server is already in the mode warm-up, everyone is ready, and so starts the game by going to the round knife, or with the online administrator being able to force everyone to give READY to start faster?

- Apparently your other CSGO PUG SETUP plugin performs better during matches, but with the exception of being manual, would it be possible to activate an automatic option like WARMOD itself?

My contacts:
Email: dwwesley@icloud.com
steam: https://steamcommunity.com/id/spartakuz

########################------------###################------------------------------

If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by TandelK** [comment]
> In CSGO-PUG-SETUP, would you have the option in some configuration file to change the tag [PUGSETUP], to some tag of my own, for example the tag of my clan?

@dwwesley the reason why PUG Setup does not have that function is due to that it can be started with any Random players while Get5 is most likely to be used for Competitive scenario where Teams are fixed by default when they register. If the players are not fixed how can we use Tag Setup with it. PUG and Get5 are complete different level stuff. 


I would like to know if there is a possibility of the plugin starting the competitive with only 2 players writing ready in chat?

Yes you can ofcourse do that with match config file creation if you are using the Get5 properly. It has lot of cvars that you can define them in cfg file . There are example cfg file given in addons/sourcemod/configs/example_match.cfg where you can create a file for each and every match and load the config file on start up or else you can use Get5-Web project which is like a webpanel to communicate between get5 and your panel.

**Comment by splewis** [comment]
> the reason why PUG Setup does not have that function is due to that it can be started with any Random players while Get5 is most likely to be used for Competitive scenario where Teams are fixed by default when they register. If the players are not fixed how can we use Tag Setup with it. PUG and Get5 are complete different level stuff.

Not true:  https://github.com/splewis/csgo-pug-setup/blob/8d480431f0ae744c464ece6842d1022f1f37bb3a/scripting/pugsetup.sp#L284-L286

**Comment by TandelK** [comment]
My bad i didnt read properly i thought Team Tag like in Get5 which we have

**Comment by dwwesley** [comment]
Splewis all good man?

As I had asked, the question of the plugin starting automatically even though it only has 2, 5, 7 players, and looking at the plugin's configs, and this "chataliases.cfg" tool helped me a lot because I created a command .some thing, for cvar "sm_forcestart" and all my problems were solved.

Now anyone on my community server can start MIX.
On the issue of DAMAGE CAUSED IN EACH ROUND.
I would like to know how I can use the color options.

DEFAULT: ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)

I would like the colors to focus only on damage and I will leave it below so that you understand better.

({GREEN}{DMG_TO}{/GREEN}dmg / {HITS_TO} hits) to ({LIGHT_RED}{DMG_FROM}/{LIGHT_RED} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)

This my config above was unsuccessful, and I understand that you should not use colors this way, to use the color system, I can only use one color or I can separate the colors, but which pattern should I follow?

**Comment by TandelK** [comment]
@dwwesley First of all can you move this issue to PUGSetup Github Repo , this is for all for Get5 Plugin .  If you are unable to find PUG Setup Issues go to this link `https://github.com/splewis/csgo-pug-setup`

**Comment by splewis** [comment]
I'm not sure what this issue is even about anymore. If you have pugsetup questions, please put them here: https://github.com/splewis/csgo-pug-setup. These are separate projects, and unrelated.
