### ISSUE TITLE
Get5_GetMatchStats command doesn't work

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#424]
### Expected behavior
Getting some statistics information as a result of the **Get5_GetMatchStats** command execution.

### Actual behavior

Get5_GetMatchStats
**Unknown command**

### Steps to reproduce
Run the match. 
Exec Get5_GetMatchStats in the main srcds.exe window.

- Plugin version: 0.6.0
- Sourcemod version:  1.9.0.6276

**Comment by splewis** [comment]
Get5_GetMatchStats is not a command.  The commands are in https://github.com/splewis/get5/blob/master/README.md#commands

`Get5_GetMatchStats` is a function that get5 makes available for other sourcemod plugins to call: https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L146

**Comment by EAbychkov** [comment]
Thanks for the response. 
Is it possible to make the stats file created automatically (with matchID in the file name) without constantly sending get5_dumpstats command?
