### ISSUE TITLE
Unknown command: get5_creatematch

### ISSUE THREAD

**Issue by cyuf** [splewis/get5#425]
Hi,

I decided to install your plugin to be able to make matches between friends in a competitive way. So I took about an hour to install it properly. But when I type the command: "sm_get5" in the console to be able to create a match, the **error message** "Unknown command: get5_creatematch" appear. It looks like the server/admins commands do not work. :/
Do you have a solution? 

Thanks in advance,
cyuf

**Comment by tech62** [comment]
Sourcemod / Metamod is correctly installed ?
The plugins is correctly loaded ? type sm plugins list and search it in the list.

Secondly, you have to write your steamid in the admins_simple.cfg in sourcemod config folder before starting your server

Try to install your server with LGSM and run ./csgoserver mods-install
Install all theses component : Sourcemod / Metamod / Steamworks / get5

It works for me

**Comment by cyuf** [comment]
> Sourcemod / Metamod is correctly installed ?
> The plugins is correctly loaded ? type sm plugins list and search"get5" in the list.
> 
> Secondly, you have to write your steamid in the admins_simple.cfg in sourcemod config folder before starting your server
> 
> Try to install your server with LGSM and run ./csgoserver mods-install
> Install all theses component : Sourcemod / Metamod / Steamworks / get5
> 
> It works for me

**1.** Yea Sourcemod is correctly installed. (sm_admin commands works)
**2.** The plugins is correctly loaded. Link: https://imgur.com/a/cxPDXZ8
**3.** My steamid is correctly writed. Link: https://imgur.com/a/6OzYNMt

Any other solutions ? D:

**Comment by splewis** [comment]
> 2. The plugins is correctly loaded. Link: https://imgur.com/a/cxPDXZ8

Can you show exactly what you're doing (the commands you're typing) in a screenshot as well?

**Comment by tech62** [comment]
Can you try with the last release ? https://github.com/splewis/get5/releases/tag/0.7.1
Do you have any errors in sourcemod logs ?

I've try to make a server from scratch with LGSM and all works :)

**Comment by cyuf** [comment]
> > 1. The plugins is correctly loaded. Link: https://imgur.com/a/cxPDXZ8
> 
> Can you show exactly what you're doing (the commands you're typing) in a screenshot as well?

Hello splewis ! Thanks for your reply. 

Link: https://imgur.com/xQmMHFb
Here is the error that appears when I use the plugin menu (1). 
Furthermore, here is what appears when I simply use the command "get5_creatematch" in the console (2). :/

> Can you try with the last release ? https://github.com/splewis/get5/releases/tag/0.7.1
> Do you have any errors in sourcemod logs ?
> 
> I've try to make a server from scratch with LGSM and all works :)

I think I'll have to go through this method if I can not find any solution! D:

**Comment by cyuf** [comment]
up! :c

**Comment by splewis** [comment]
>Here is the error that appears when I use the plugin menu (1).

What is "the plugin menu"? I see the menu, but I don't know what you're doing to bring it up still?

I don't see any reason the command wouldn't work. You could try running some of the other commands to see if any work (get5_loadmatch, get5_loadteam, get5_addplayer, etc.).

**Comment by cyuf** [comment]
> > Here is the error that appears when I use the plugin menu (1).
> 
> What is "the plugin menu"? I see the menu, but I don't know what you're doing to bring it up still?
> 
> I don't see any reason the command wouldn't work. You could try running some of the other commands to see if any work (get5_loadmatch, get5_loadteam, get5_addplayer, etc.).

**1.** The "plugin menu" is just the result of the "**sm_get5**" command. 
To create matches with my friends I do not modify all the files to add a player in a team etc. I create a match with the **current players** on the server. (As it is shown in option 2 of the menu)

**2.** I tried with "**get5_loadmatch "addons/sourcemod/configs/get5/match.cfg**"" command, but the same error appears.
Link: https://imgur.com/a/lEBKPQx

**3.** Also, to install your plugin, I deposited all the files of each folder in the corresponding folders on my FTP. 
And the "**get5_0.6.0**" folder is at the root of my csgo folder, as it says on your tutorial.

Did i make a mistake when i extracted your plugin?

**Comment by splewis** [comment]
Can you double check that the file `addons/sourcemod/translations/get5.phrases.txt` exists on your server?

**Comment by cyuf** [comment]
> Can you double check that the file `addons/sourcemod/translations/get5.phrases.txt` exists on your server?

Yup, there it is: https://imgur.com/a/de0dR42

**Comment by cyuf** [comment]
up. :c

**Comment by splewis** [comment]
> And btw, i don't have any errors in sourcemod.

Does that mean you have no files under ``addons/sourcemod/logs/`` beginning with 'errors_' (in the filename), or the `addons/sourcemod/logs`` directory doesn't exist at all? 

The only possible explanations I see are:
- your errors aren't getting logged because of file permission issues
- something else is wrong with your server/client and I can't fix for you

**Comment by cyuf** [comment]
> > And btw, i don't have any errors in sourcemod.
> 
> Does that mean you have no files under `addons/sourcemod/logs/` beginning with 'errors_' (in the filename), or the `addons/sourcemod/logs`` directory doesn't exist at all?
> 
> The only possible explanations I see are:
> 
> * your errors aren't getting logged because of file permission issues
> * something else is wrong with your server/client and I can't fix for you

Thanks for your reply.
So I did not see these log files before. Here's what's in almost every file error. Link: https://imgur.com/a/XYb9LTx

**Comment by saintplay** [comment]
I think you don't have a correct installation of sourcemod + get5.

If you have a linux server try LinuxGSM, they have native support for support sourcemod and get5

**Comment by cyuf** [comment]
> I think you don't have a correct installation of sourcemod + get5.
> 
> If you have a linux server try LinuxGSM, they have native support for support sourcemod and get5

First, I don't think sourcemod installation is the problem because I bought the server by "verygames" website and sourcemod is automatically installed and works very well without the plugin "get5".

Secondly, I wonder what mistakes I could have made. I took each file from each folder of the plugin and then inserted it into the corresponding folders on my ftp.
Is this the mistake I made?

**Comment by saintplay** [comment]
Maybe you can put the output of the tree command to see your csgo server directory

**Comment by cyuf** [comment]
> Maybe you can put the output of the tree command to see your csgo server directory

This? Link: https://imgur.com/a/WDrT75I

**Comment by splewis** [comment]
> So I did not see these log files before. Here's what's in almost every file error. Link: https://imgur.com/a/XYb9LTx


That's the problem. You're missing parts of the translation file (addons/sourcemod/translations/get5.phrases.txt) . Maybe it's old. Maybe it's corrupted. 

> https://imgur.com/a/WDrT75I

Also note that having a directory named `get5_0.6.0` has no impact. The contents of that directory should be unpacked into the `csgo` directory.

**Comment by cyuf** [comment]
> > So I did not see these log files before. Here's what's in almost every file error. Link: https://imgur.com/a/XYb9LTx
> 
> That's the problem. You're missing parts of the translation file (addons/sourcemod/translations/get5.phrases.txt) . Maybe it's old. Maybe it's corrupted.
> 
> > https://imgur.com/a/WDrT75I
> 
> Also note that having a directory named `get5_0.6.0` has no impact. The contents of that directory should be unpacked into the `csgo` directory.

Thanks splewis.

I'll download a new get5.phrases.txt and will try. 

So to install your plugin I just have to extract the content of the plugin directly into the csgo folder? I thought that it was necessary to extract each file from each folder in those corresponding on my ftp. : /

**Comment by splewis** [comment]
The download has 2 folders under it: `addons` and `cfg`. They merge with the current `addons` and `cfg` directories on your server now. Usually people just go to the `csgo` directory and drag those 2 directories into it.

**Comment by cyuf** [comment]
> The download has 2 folders under it: `addons` and `cfg`. They merge with the current `addons` and `cfg` directories on your server now. Usually people just go to the `csgo` directory and drag those 2 directories into it.

Ok I understand! But how am I supposed to do? Because the ftp of my server already contains the addons and cfg folder. I can't erase them. Link: https://imgur.com/a/tsR0Oml

**Comment by cyuf** [comment]
up :c
