### ISSUE TITLE
How to add players to team listing so I don't have to add a ringer every time.

### ISSUE THREAD

**Issue by LaBishop** [splewis/get5#428]
Sorry to bother you here, I just can't find the answer anywhere and I really can't remember how to do this. my apologies.

**Comment by splewis** [comment]
If you're using the scrim functionality: https://github.com/splewis/get5/wiki/Using-get5-for-scrims#adding-your-teams-steamids

Otherwise  https://github.com/splewis/get5#match-schema or

**Comment by LaBishop** [comment]
Hello,

Thank you for the assistance but i still have the same problem as before, I've added the users to the scrim template, but when i start the scrim, it doesn't move me or any of the players into the CT side and sometimes it kicks some of the players saying they aren't players in this match.

I know the steam ID's are correct as they are able to access the practise mode and start the scrim themselves.

**Comment by splewis** [comment]
Please fill out the original issue template, then:
```
### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

```
