### ISSUE TITLE
Missing team1 in JSON

### ISSUE THREAD

**Issue by AFreeman94** [splewis/get5#43]
### Expected behavior

Successfully load the match json config

### Actual behavior

L 07/03/2016 - 23:17:02: [get5.smx] Failed to load match config: Missing "team1" section in match json
L 07/03/2016 - 23:17:02: [get5.smx] Failed to load match config: invalid match json
(Note this is with http://www. infront of the directory and using the example_match.json from here)

### Steps to reproduce
- Plugin version: 0.3.0
- Sourcemod version: 1.8 - build 5916

**Comment by splewis** [comment]
I'm going to assume this is using the get5_loadmatch_url command.

You could try updating the steamworks extension to a more recent build. If that doesn't work you should give the actual URL you were using as the command argument.

**Comment by splewis** [comment]
So you edited the title to change the issue entirely, which makes it kind of hard to help.

Can you give the actual command you're using? You're making me guess at what you actually are doing.

**Comment by splewis** [comment]
Closed due to a lack of information.

**Comment by s1inche** [comment]
Have you found a solution to this problem?

**Comment by TandelK** [comment]
@s1inche it clearly states that Team 1 part is missing from json file , there might be indentation issues with your json file.
