### ISSUE TITLE
Help needed, 6v6

### ISSUE THREAD

**Issue by tapomirbowles** [splewis/get5#433]
Im very sorry to use a bug reporting forum for this, but I dont see any help sections anywhere, so I figured I´d give this place a shot.

I have just rented a CSGO server on dathost.com because we are gonna be playing 2 departments against eachother in our company. We wanna play a match as if it was a real tournament with VETOS and all that jazz. But, we need it to be 6v6, not 5v5. 

I have already installed your plugin on the server, they made that very easy, as you just needed to drag and drop the zip I downloaded here on github into a ftp section they had on their website. So its installed now, but I have no idea how to set it up so that your plugin is always just running and should just start when the server boots up. I also have no idea how to set it so its not 5v5 but 6v6. Could anyone help me with how to go about this?

**Comment by splewis** [comment]
When you create a match config there's a players_per_team field you can just change from 5 to 6: https://github.com/splewis/get5#match-schema. 

For example: https://github.com/splewis/get5/blob/master/configs/get5/example_match.cfg#L33
