### ISSUE TITLE
Required extension "SteamWorks" file("SteamWorks.ext") not running

### ISSUE THREAD

**Issue by AshyzBoyz** [splewis/get5#434]
Required extension "SteamWorks" file("SteamWorks.ext") not running

i installed everything but not working

**Comment by clugg** [comment]
Have you installed the SteamWorks extension?

There are two steps:

1. Save the [`SteamWorks.inc`](https://github.com/KyleSanderson/SteamWorks/blob/master/Pawn/includes/SteamWorks.inc) file to `addons/sourcemod/scripting/include` directory.

2. Find the latest relevant build of the SteamWorks extension [here](https://users.alliedmods.net/~kyles/builds/SteamWorks/). Grab the first file ending with `windows.zip` if your server is running Windows, or the first file ending with `linux.tar.gz` if your server is running Linux. Extract the `SteamWorks.ext.dll`/`SteamWorks.ext.so` (DLL for Windows, SO for Linux) file to `addons/sourcemod/extensions`.

**Comment by splewis** [comment]
You can debug with the ``sm exts`` console command to see if SteamWorks is running. If you have errors there, your issue is with Steamworks.

**Comment by FlowingSPDG** [comment]
Did you check permission setting such as ``chmod 755 addons/sourcemod/extensions/SteamWorks.ext.so`` ?
