### ISSUE TITLE
Steamworks GET request failed 

### ISSUE THREAD

**Issue by bjerrecs** [splewis/get5#435]
### Expected behavior
Get5 pulls the match config from the web server.

### Actual behavior
command "get5_loadmatch_url get5.leagueops.org/match/3/config"
[get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0
get5_event: {"matchid`":"","params":{"reason":"Steamworks GET request failed, HTTP status code = 0"},"event":"match_config_load_fail"}
command "get5_web_api_key XEJEROJRWXXXXXXXXXXXXX"

### Steps to reproduce
b28b5677726e <- web version
[get5_debuginfo.txt](https://github.com/splewis/get5/files/3685570/get5_debuginfo.txt)

Linux system: Ubuntu 16.04
Downloaded Steamworks and installed the .so and inc files.
Get this file when i try to start the match

**Comment by tech62** [comment]
> L 10/03/2019 - 12:12:12: [SM] Exception reported: Could not connect to get5 database: Configuration "get5" not found
 
There is a problem with your DB connection...

**Comment by TandelK** [comment]
@tech62 He is using both the plugins together , API stats as  well as mysql stats one which is never recommended by Get5 . If you are using API stats it means it will connect the Server via API and recieve and Send Data regarding Match Config as well as Stats after every round. You dont need to store them specially in mysqlstats plugin. Would recommend removing it. 


`command "get5_loadmatch_url get5.leagueops.org/match/3/config"`  
If SSL is enabled i would recommend you to use HTTP as currently HTTPS is not supported by SteamWorks.
