### ISSUE TITLE
how to join the the teams match not only my team steam id entered

### ISSUE THREAD

**Issue by mauci80** [splewis/get5#436]
Hi all ,

i want to play internal 5on5, but is not possible to change from ct to t because our steam ids is locked into team 1 settings?

how is possible that we can join different teams on a internal match ?

**Comment by TandelK** [comment]
use cvar 

> get5_check_auth to 0

 but if you have added them directly in scrim template when starting scrim it will automatically move you to that team of yours. Just change team manually when required.

**Comment by splewis** [comment]
Like tandel said, set get5_check_auth or use scrim mode.
