### ISSUE TITLE
mp_free_armor 2 only after first kill

### ISSUE THREAD

**Issue by victorbuttner** [splewis/get5#437]
### Expected behavior

I'm trying to give mp_free_armor 2 to all maps and matches but it works only after the first kill

### Actual behavior
Free armor set only after first kill

### Cvars on match.json
 "cvars": {
                "hostname": "Match server #1",
                "mp_winlimit": "6",
                "mp_timelimit": "10",
                "mp_roundtime": "2",
                "sv_allow_votes": "0",
                "mp_limitteams": 1,
                "mp_round_restart_delay": 2,
                "sv_allowupload": 1,
                "mp_maxrounds": "30",
                "mp_halftime": "1",
                "mp_freezetime": "0",
                "mp_halftime_duration": "8",
                "mp_free_armor": "2",
                "mp_endmatch_votenextmap": 0,
                "mp_endmatch_votenextleveltime": 20,
                "mp_endmatch_votenextmap_keepcurrent": 0,
                "sv_vote_allow_in_warmup": 0,
                "sv_vote_allow_spectators": 0,
                "sv_vote_command_delay": 2,
                "sv_vote_creation_timer": 120,
                "sv_vote_failure_timer": 300,
                "sv_vote_issue_kick_allowed": 1,
                "sv_vote_kick_ban_duration": 30,
                "sv_vote_quorum_ratio": 60,
                "sv_vote_timer_duration": 10,
                "mp_ct_default_primary": "weapon_ak47",
                "mp_t_default_primary": "weapon_ak47",
                "mp_autokick": 0,
                "mp_match_end_restart": 0,
                "bot_kick": 1
            }

**Comment by splewis** [comment]
Are you saying the cvar is no longer set to 2, or that it's still set to 2 but players aren't getting armor (and the cvar itself isn't working)?

**Comment by victorbuttner** [comment]
it works only after the first kill on the match. I set to no knife round, so in the first "kill" the free_armor is not been set.
After the first kill on the match it works correctlty

**Comment by victorbuttner** [comment]
whithout mp_armor
![Captura de tela de 2019-10-17 01-55-46](https://user-images.githubusercontent.com/17817146/66978716-622bdd00-f081-11e9-8313-bf4b92c6fcf8.png)

with mp_armor
![Captura de tela de 2019-10-17 01-56-04](https://user-images.githubusercontent.com/17817146/66978731-7079f900-f081-11e9-9003-f6f880677ddc.png)

**Comment by splewis** [comment]
The map itself is likely taking away or giving armor. 

All get5 does is set the cvars you tell it to. The same issue probably happens if you set those are cvars without get5.

**Comment by victorbuttner** [comment]
how I can overwrite the map config

**Comment by splewis** [comment]
Unfortunately get5 can't help with that; you probably need another plugin, I'd suggest checking out the sourcemod forums for help on that: https://forums.alliedmods.net/forumdisplay.php?f=52
