### ISSUE TITLE
Plugin Compile Error

### ISSUE THREAD

**Issue by AFreeman94** [splewis/get5#439]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Plugin Compiles without error.

### Actual behavior
12 Warnings (warning 241: Array-based enum structs will be removed in 1.11. See https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Enum_Structs)

6 Errors (With https://github.com/clugg/sm-json in the includes)
get5/jsonhelpers.sp(97) : error 105: cannot find method or property JSON_Object.GetIndexString
get5/jsonhelpers.sp(97) : error 92: number of arguements does not match definition
get5/jsonhelpers.sp(119) : error 105: cannot find method or property JSON_Object.GetIndexString
get5/jsonhelpers.sp(119) : error 92: number of arguements does not match definition
get5/matchconfig.sp(527) : error 105: cannot find method or property JSON_Object.GetIndexString
get5/matchconfig.sp(527) : error 92: number of arguements does not match definition

### Steps to reproduce
Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.2-dev
- Sourcemod version: 1.10 - build 6453
- Steps to reproduce (please be specific):

Fresh Folder with current SM build (https://www.sourcemod.net/downloads.php?branch=stable)
Install SteamWorks (https://forums.alliedmods.net/showthread.php?t=229556)
Install sm-json (github.com/clugg/sm-json)

Run compile.exe

**Comment by MikkelDK** [comment]
@AFreeman94 - install this sm-json: https://github.com/clugg/sm-json/archive/v1.2.0.zip - We need to wait until @splewis will update it! ;) since `GetIndexString` is gone, so soon v2 of sm-json will be released! ;)

**Comment by AFreeman94** [comment]
Awesome thank you!

**Comment by splewis** [comment]
The right solution would be to do https://github.com/splewis/get5/issues/393 (pull requests welcome!).

**Comment by splewis** [comment]
#393 is done now, though how you choose to compile may not always work still. The version of sm-json I intended to support is the one linked into the repo now. (it should likely be updated, though)
