### ISSUE TITLE
Mapnumber in mysql_stats not increased after tie

### ISSUE THREAD

**Issue by allanwoer** [splewis/get5#440]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
mysql_stats:
After match tie, mapnumber should be increased, so match stats will be updated correctly.

### Actual behavior
Mapnumer is not increased after a match tie. Data from the previous match is overwritten after a match tie. Seems like mapnumber is calculated by team score, and not matches played.

### Steps to reproduce
- Plugin version: 0.7.1
- Sourcemod version: 1.9.0.6276
- Steps to reproduce (please be specific): End a match with more than one match in the series with "TIE" as result. Note that mapnumber isn't increased.

mysql_stats event: 11/10/2019 - 21:38:32: [get5_mysql] UPDATE `get5_stats_maps` SET team1_score = 1, team2_score = 0 WHERE matchid = 88 and mapnumber = 0

get5_event: 11/10/2019 - 21:38:32: [get5] get5_event: {"matchid`":"88","params":{"reason":1,"winner":"team1","team2_score":0,"map_number":1,"team1_score":1,"map_name":"de_dust2","winner_side":"T"},"event":"round_end"}

note the difference in mapnumber.

**Comment by nickdnk** [comment]
Should be fixed on master.
