### ISSUE TITLE
New releases for SourceMod 1.10.0.6455

### ISSUE THREAD

**Issue by N1ppler** [splewis/get5#443]
After the lattest CSGO Updated (11/18/2019) i must Update Sourcemod to 1.10.0.6455.
Now Get5 & csgo-practice-mode dont work anymore for me.

Would it be possible to get a current version for Sourcemod 1.10.0.6455 ?
For both Plugins Get5 and csgo-practice-mode.

I've tried compiling myself, but it dont work. 

Sry for my bad englisch. I hope i get help.

**Comment by splewis** [comment]
The plugins do not need to be recompiled to continue working. If you have problems, this is not the solution.

**Comment by N1ppler** [comment]
So the new CSGO Updated destroyed something, before everything was fine. 
Could you fix this ?

**Comment by splewis** [comment]
As always, you need to update sourcemod, not the plugin.

**Comment by MikkelDK** [comment]
> So the new CSGO Updated destroyed something, before everything was fine.
> Could you fix this ?

@N1ppler - You need to update to 6456 version of sourcemod. it works here! =)

**Comment by N1ppler** [comment]
I still did that befor i asked thats why i asked.
But i will reinstall the hole server and test it again.

**Comment by N1ppler** [comment]
I've tested it. 
Result with Sourcemod-1.10.0-git6456-linux:
Get5 0.7.1 Dont work
Get5 0.7.2-dev+471 Work
PracticeMode 1.3.3 Dont work
PracticeMode 1.3.4-dev+296 Work

Thanks for Helping

**Comment by splewis** [comment]
I see no reason any of the plugin versions won't work, but glad you fixed your issues.

**Comment by N1ppler** [comment]
Yeah i dont know what happend but it work also with:

Metamod | mmsource-1.10.7-git971-linux
SourceMod | sourcemod-1.10.0-git6456-linux
Get5 | 0.7.1
CS:GO PracticeMode | 1.3.3
