### ISSUE TITLE
[User Help] Understanding Min Players to Ready

### ISSUE THREAD

**Issue by PhlexPlexico** [splewis/get5#445]
### Expected behavior
When creating a match config, I would expect `min_players_to_ready` to be able to control the ready system, regardless of how many players there are per team. For example, if we have `players_per_team` set to 5 (default) and `min_players_to_ready` set to 2, two people should be able to ready up on the team, and then have everyone else be readied, is this correct?

### Actual behavior
If we have the former config options set, all 5 players on the team must ready up in order for vetoes/match to start.

### Steps to reproduce
Create match config with `min_players_to_ready` set to 2 and `players_per_team` to 5, you still need all 5 players to be readied.

- Plugin version: Build #471 from CI.
- Sourcemod version: 1.10

I'm not sure if this would be considered a bug, but more curious if I'm understanding this function correctly. Thank you!

**Comment by vassilidev** [comment]
me too, up

**Comment by Drarig29** [comment]
I have the same problem: 

Even though I set `min_players_to_ready` to 1 and `players_per_team` to 5, when I'm alone in my team and a friend is in the other one, we both have to `!forceready`.

**Comment by splewis** [comment]
> Create match config with min_players_to_ready set to 2 and players_per_team to 5, you still need all 5 players to be readied.

That clearly sounds like a bug, since `min_players_to_ready ` has literally no effect? How could it not be a bug if it has no effect whatsoever? :)

**Comment by Drarig29** [comment]
I think it comes from this `if`:
https://github.com/splewis/get5/blob/34d191a8d551f5238d92d0fdf1f3f9af3d9aab1e/scripting/get5/readysystem.sp#L74

It should be `||` instead of `&&` :)

**Comment by Drarig29** [comment]
After reading your code, I think it's an intended behavior... (this behavior is all [here](https://github.com/splewis/get5/blob/34d191a8d551f5238d92d0fdf1f3f9af3d9aab1e/scripting/get5/readysystem.sp#L56)).

You seem to use `min_players_to_ready` only with `!forceready` ([here](https://github.com/splewis/get5/blob/34d191a8d551f5238d92d0fdf1f3f9af3d9aab1e/scripting/get5/readysystem.sp#L74)).

So, without force readying, the only way for a team to get ready is to have all its players connected and ready ([`playerCount == readyCount`](https://github.com/splewis/get5/blob/34d191a8d551f5238d92d0fdf1f3f9af3d9aab1e/scripting/get5/readysystem.sp#L70)) and to have as many players as set in `players_per_team` ([`playerCount >= minPlayers`](https://github.com/splewis/get5/blob/34d191a8d551f5238d92d0fdf1f3f9af3d9aab1e/scripting/get5/readysystem.sp#L70)). **Regardless of `min_players_to_ready`**.

If that's the behavior you were aiming for, maybe `min_players_to_ready` should have been named `min_players_to_force_ready`...

**Comment by splewis** [comment]
Ah, yes, that's what's up. There should be a message in chat to remind users of it (since it's somewhat confusing clearly): https://github.com/splewis/get5/blob/34d191a8d551f5238d92d0fdf1f3f9af3d9aab1e/scripting/get5/readysystem.sp#L243, https://github.com/splewis/get5/blob/8cbbdb022e5c1ef4504d4e341bf28b7c90b3b9d6/translations/get5.phrases.txt#L173

**Comment by PhlexPlexico** [comment]
Thank you all very much for the clarification! Since it's not a bug and as intended, that's all I need to know.
