### ISSUE TITLE
Feature request : Map freeze on wining series or series clinch

### ISSUE THREAD

**Issue by JustinBenedick** [splewis/get5#449]
I just had a test where a team sweeped a best of 5 series by winning the first 3 rounds. However the plugin went to the 4th map. Could we get a feature were the server pauses after the clinching win instead of going to the 4th map

**Comment by TandelK** [comment]
Well as per the current situation it should never go to 4th Map automatically and saying this Team has won the match but still try to reproduce this issue with just 5 rounds on each map and test it out quickly may be in evening. If you had done any modifications in the code please update it here also.

**Comment by JustinBenedick** [comment]
no code modificaitons, and I have been testing out with bots

**Comment by splewis** [comment]
This is indeed not the default behavior. Do you have a clear steps (plugin version, match config) to reproduce?

**Comment by JustinBenedick** [comment]
I just ran a new test with default settings (except with map votiting disabled) It no longer  goes to the next map but instead new match on the same map. Could it be possible to setup a server pause after a certain period?
