### ISSUE TITLE
Need define path to store backups and stats

### ISSUE THREAD

**Issue by jfkz** [splewis/get5#45]
@splewis 

Need to set up path to store backups and stats (for example `csgo/get5/stats` and `csgo/get5/backups`) that can be configured.

For example, I use `get5_demo_name_format = 'demos/{MATCHID}_map{MAPNUMBER}_{MAPNAME}'` to save all demos in one folder.

If I can add same convars for backups and stats - just reply here and I do this.

**Comment by splewis** [comment]
I'm fine with this. I think I'd also be fine with removing the ``get5_auto_dump_stats`` cvar and just using the new path stats cvar to control whether stats get dumped - if the string is empty then don't output the stats file. Similarly with demos - empty format string could disable it. I'm fine with the stats/demos/backups all being enabled by default.

**Comment by jfkz** [comment]
Thanks. I understand your way and will try to make it.

**Comment by splewis** [comment]
Stats are automatically saved via the ``get5_stats_path_format`` cvar now. Backups don't have a cvar like this yet, though.

**Comment by jfkz** [comment]
Thanks for your job! 

Does it mean that we can't save backups in custom place? If yes I think you can close this issue.

**Comment by splewis** [comment]
I think it's worth keeping a consistent backup file naming scheme for ease of finding them, so I'm closing this and not adding a get5_backup_name_format cvar.

**Comment by jfkz** [comment]
Ok. Thanks.
