### ISSUE TITLE
get5_kick_immunity "1" not working (everyone can join)

### ISSUE THREAD

**Issue by ghost** [splewis/get5#450]
### Expected behavior
Allow only admins to join on server with no match loaded.

### Actual behavior
Everyone can join the server with get5_kick_immunity set to "1"

### Steps to reproduce
- Plugin version: "get5_version" = "0.7.2-dev+474"
- Sourcemod version: 1.10.0.6458
- Steps to reproduce (please be specific):

1. Set get5_kick_immunity "1" and get5_kick_when_no_match_loaded "1"
2. Don't add you as admin in admins_simple.ini 
3. Try to connect to passwordless server without a loaded matchconfig
4. You can join server

Server was rebooted on every config change and SM admin was confirmed with executing multiple SM admin commands. The get5.cfg is on all default values.

I also tried setting get5_kick_immunity "0" and then I don't get access with any user, even the user added as admin.

Did https://github.com/splewis/get5/issues/372 break this when trying to fix it?

**Comment by TandelK** [comment]
Even i had the same issue, we did try to modify the code as per new Boolean but it did not work properly as it should. Would also again look into code for it

**Comment by TandelK** [comment]
@splewis i did some digging and found out that 

CheckCommandAccess() is not all working

https://github.com/splewis/get5/blob/0609e51c40e5eeda30dc0ab4f599ab89054a3916/scripting/get5.sp#L534

Please have a look into it.

**Comment by TandelK** [comment]
@splewis Can you check this out.

**Comment by TandelK** [comment]
@Enghausen-petabit-gg here is a fix for it.

**Comment by TandelK** [comment]
@Enghausen-petabit-gg here its fixed

**Comment by Enghausen-petabit-gg** [comment]
Great work! I will test it later this week! Thanks alot!!
