### ISSUE TITLE
[Question] Multi Scrim Configs?

### ISSUE THREAD

**Issue by ghost** [splewis/get5#452]
Sometimes our teams need to play scrims with other than the default settings in our scrim_template.cfg - Like playing full 30 rounds, map-veto or without "knife for side"

Any chance we can load-up alternative scrim cfgs with another Scrim-setup when we need to? We tried the get5_loadmatch without luck. From my understanding the get5_scrim command do some magic on the scrim template .cfg file before loading it :-)

How do other teams handle this?

**Comment by DennisF10** [comment]
Yeah would be really great if you could add more templates for scrims not just matches (get5_loadmatch) configs.
