### ISSUE TITLE
[BUG] "suicide" value on get5_apistats is not correct

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5#453]
Hi, Im developing my own get5-web by Golang ([get5-web-go](https://github.com/FlowingSPDG/get5-web-go)).
and I found bug while im developing it.
When player killed themself by using HEgrenade/Molotov,it will be counted as "suicide" because killer and victim is equal.
but when player killed by "World"(such as falling,especially vertigo) get5 won't recognize "World" as valid killer so it won't counted as "suicide".
https://github.com/splewis/get5/blob/95e52f5215d6aa6d576a89a1ca3c9064edba0a03/scripting/get5/stats.sp#L198

Thanks for best match plugin btw :)
https://github.com/splewis/get5/blob/95e52f5215d6aa6d576a89a1ca3c9064edba0a03/scripting/get5/stats.sp#L228

https://github.com/FlowingSPDG/get5-web-go/issues/67

**Comment by vassilidev** [comment]
Thx !!

**Comment by FlowingSPDG** [comment]
❤️‍🔥
