### ISSUE TITLE
Get5_OnPlayerConnect forward not firing

### ISSUE THREAD

**Issue by Cyberotic** [splewis/get5#454]
Hello!
I required to print defined value ("Someone has joined") to console when Specific GET5 Event (player_connect) happens.

So I first started with making a plugin looking something like this: (i am totally new to sourcemod)
```
#include <sourcemod>
#include <cstrike>

#include "include/get5.inc"

public Plugin myinfo =
{
	name = "Something",
	author = "Someone",
	description = "Do something",
	version = "1.0",
	url = "http://www.sourcemod.net/"
};
 
public void Get5_OnPluginStart()
{
	PrintToServer("Hello world!");
}

public void Get5_OnEvent(const char[] eventJson)
{
	PrintToServer("EVENT PLUGIN SAYS HI!");
}

public void Get5_OnPlayerConnect(int client)
{
	PrintToServer("SOMEONE GOT CONNECTED!");
}
```

But get5_onplayerconnect doesnt work. Please provide me direction to right path to make this work.

Thanks

**Comment by splewis** [comment]
The `Get5_OnPlayerConnect` forward doesn't exist. The only such 'forwards' are here: https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L40-L84

You might want the [OnClientConnect](https://sm.alliedmods.net/new-api/clients/OnClientConnect) forward from sourcemod itself.

There is also a 'player_connect' event get5 defines, but you probably shouldn't need to use it here: https://github.com/splewis/get5/wiki/Event-logs. OnClientConnect or such should suffice for your needs.
