### ISSUE TITLE
How to import stats for SQLite

### ISSUE THREAD

**Issue by kuper1994** [splewis/get5#455]
Hi, Where I have to put the impor_stats.sql file? how do I need to call it?

I just add it to:
csgo/addons/sourcemod/data/sqlite
with the name 
import_stats.sq3
-----

What I need to change into the 
addons/sourcemod/configs/databases.cfg ?
- what is user? 
- which one do i need to provide? 
- which password? 
- which host is the server IP?

Please advise, thanks.

**Comment by splewis** [comment]
What are you trying to do?

Use the get5_mysqlstats plugin? Get5 has no SQLite support (though that plugin *may* work for SQLite, I've never tested it).
