### ISSUE TITLE
You are not a player in this match.

### ISSUE THREAD

**Issue by VurtulineTuba77** [splewis/get5#456]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Sub/Ringer joins the server with no issue

### Actual behavior
Sub/Ringer gets error saying "You are not a player in this match", is unable to connect

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by TandelK** [comment]
Can you drop your get5 config file that you are executing on the server or if using scrim template also paste the info about Scrim.

**Comment by VurtulineTuba77** [comment]
[get5config.zip](https://github.com/splewis/get5/files/4094816/get5config.zip)

**Comment by VurtulineTuba77** [comment]
[get5config (1).zip](https://github.com/splewis/get5/files/4094858/get5config.1.zip)
ignore that last one, this is the one we're using

**Comment by splewis** [comment]
> Expected behavior
Sub/Ringer joins the server with no issue

The intended get5 behavior is that they get kicked. You have to explicitly add players if you want to authenticate players (the default behavior, disabled bysetting `get5_check_auths 0`). 

Otherwise you can add players after loading a match config with [get5_addplayer](https://github.com/splewis/get5#serveradmin-commands-meant-to-be-used-by-admins-in-console).

**Comment by VurtulineTuba77** [comment]
I played on a different server where anybody could join, and I mean anybody. Will setting get5_check_auths to 0 make it like that or are there other steps I’d have to go through?

**Comment by TandelK** [comment]
@VurtulineTuba77 What kind of config file are you trying to load with Get5. There is a Config file for each and every match unless you use a scrim command. Also if you want to disable player authentication as splewis mentioned use `get5_check_auths "0"` in get5.cfg file . If you are using normal config for match loading it should be located in `addons/sourcemod/configs/get5/example_config.cfg` for example file. Use that file for loading the match. You can use the above cvar of `get5_check_auths 0` in its cvar section for disabling steam id check

**Comment by splewis** [comment]
`get5_check_auths 0` should result in nobody being kicked from the server. Extra players should get forced into coach slots, though not necessarily on the team you want. No authentication takes place.
