### ISSUE TITLE
[Feature Request] Deathmatch (free for all)

### ISSUE THREAD

**Issue by thorpep138** [splewis/get5#457]
Hey @splewis I was wondering how much effort you think it would take to create a deathmatch mode in which instead of two teams it becomes every man for himself (so I guess N teams where N = number of players). I'm imagining this mode would count kills and deaths and declare the person with the highest (kills - deaths) overall the winner. I'd love to work on this as a side project though I am new to source mod. Any thoughts? I considered other plugins that might do the job but I also want the features of this plugin that include whitelisting by steam id, kicking players out with a nice message at the end of the match, etc.

Also curious what you recommend on getting started with sourcemod so I can get up to speed and make meaningful contributions to this repository?

**Comment by saintplay** [comment]
I also had/have a similar idea.
I found this plugin <https://github.com/Maxximou5/csgo-deathmatch>, I figured it out it could be a nice start point.

But I can't use it yet because it doesn't have the steam id whitelisting feature,
@thorpep138 what other features of get5 did you think of?

**Comment by thorpep138** [comment]
@saintplay thanks for the recommendation! I did see that one but as you mentioned it lacks steam id whitelisting. In addition, other important get5 features include the database layer to store all game stats, the ability to start a game by calling a URI that returns a JSON configuration for a game, and all the provided get5 convars for controlling game logisitics such as ready up time, and forcing forfeit if a player fails to connect in a certain time.

**Comment by saintplay** [comment]
I can collaborate on this, email me if you want to team up: <diegojara6@gmail.com>

**Comment by thorpep138** [comment]
Awesome @saintplay I may indeed take you up on that, but first want to heart what @splewis has to say. Just a reminder, I'm totally new to sourcemod so it'll take me a little while to get up to speed.

**Comment by splewis** [comment]
I won't be adding support in get5 directly for this. 

You might be able to build on top of get5 and write another plugin that uses the api features, though: https://github.com/splewis/get5/blob/master/scripting/include/get5.in  (and I'm not opposed to adding new natives/forwards generally, if they are generic enough to be broadly useful).

**Comment by thorpep138** [comment]
Thanks for the input @splewis . Extending get5 in that way does seem likely to be the best way forward.

**Comment by jeaye** [comment]
@thorpep138 or @saintplay, did you guys make any progress on this with a fork or another project?

**Comment by thorpep138** [comment]
@jeaye I decided to work on other things, so no progress from my end.
