### ISSUE TITLE
Get Killed the next round when killing a mate

### ISSUE THREAD

**Issue by vassilidev** [splewis/get5#458]
### Expected behavior
Just get 300$ penality

### Actual behavior
Killed the next round + 300$ penality

### Steps to reproduce
kill a mate during a round

- Plugin version: 0.7.1
- Sourcemod version: 1.10
- Steps to reproduce (please be specific): kill a mate

**Comment by vassilidev** [comment]
> did u check `mp_tkpunish` ?

Yes but how can i remove ? Mp_tkpunish 0 = instant punish and 1 = next round ?

**Comment by splewis** [comment]
This isn't related to get5; you have some cvar (like `mp_tkpunish`) set in your configs somewhere. Often users launch servers with the default "casual" settings instead of "competitive" (the `game_mode` & `game_type` cvars, I forget which one does this), which might cause this.

**Comment by vassilidev** [comment]
Okay, i gonna try and search something like this today, is it better to launch the server on Casual mode and change all option after or is it okay with competitive and delete the tkpunish ?

**Comment by vassilidev** [comment]
Yes ! mp_tkpunish 0 in live.cfg and its okay ! :D
