### ISSUE TITLE
[Question] End match map ?

### ISSUE THREAD

**Issue by vassilidev** [splewis/get5#459]
Hi ! 

I've a question, I am a new CS:GO server admin, i've create a Map Lobby before the map veto etc (Team 1 and Team 2 connect in the lobby and have little instruction)
and I want to load the lobby map after the end of a match (bo1 and bo3)
My server is configurate to load my workshop map at the start (after stop start or a restart)

There is a get5 file for the end ? so i can put nextlevel workshop/ID etc ? 

I find :
nextlevel 
mp_match_end_changelevel 
mp_match_end_restart

**Comment by MikkelDK** [comment]
set: mp_match_end_changelevel 1
set: mp_match_end_restart 0

You could too add "lobby map" to mapcycle.txt

``nextlevel`` is only for "client" =)

**Comment by vassilidev** [comment]
yes i know, changelevel for serv, 

so, i add on server.cfg : 

mp_match_end_changelevel 1
mp_match_end_restart 0

and on my mapcycle i add my workshop map ? 

it does not go well with bo2/3/4/5

**Comment by MikkelDK** [comment]
Well, I don't have tested BO2, BO3, BO7 with the next map. =)

**Comment by vassilidev** [comment]
> Well, I don't have tested BO2, BO3, BO7 with the next map. =)

in bo1 i think gonna work but in bo+1 idk ... i gonna try i think tonight :D

**Comment by TandelK** [comment]
Basically it has to be set in get5 config file which will load or use Web Panel with modified settings. 

For .cfg or .json file you will have to use maplist section as per Maps sequence 

For eg. 

skip veto has to be set to true and maplist has to be set as per Maps loading sequence . Below is example. Map Sides are standard based  specially required for BO2 , BO3 , BO5 and BO7 and for BO1 also if you dont mention it will auto select knife for side selection for BO1. 

Format for .cfg file
```

"skip_veto"		"1"
"map_sides"
{
	"team2_t"		""  //Team 2 Side Selection For BO3 first map de_cache Team 2 side is T Side 
	"team1_t"		"" // Team 1 Side Selection For BO3 second map de_mirage Team 1 side is T Side
	"knife"		""  // Last and final map side on Overpass has to be decided via Knife. 
}
"maplist"
{
	"de_cache"		""  //Map 1
	"de_mirage"		"" // Map2
	"de_overpass"		"" //Map 3
}
```

For more information you can use the Wiki page 
https://github.com/splewis/get5/wiki/Map-Vetoes#skipping-the-plugins-veto

**Comment by splewis** [comment]
> There is a get5 file for the end ? so i can put nextlevel workshop/ID etc ?

Get5 has no special support for this.

You could write your own plugin that uses the [Get5_OnSeriesResult](https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L62) forward to execute arbitrary behavior on series end, though. You'd have to write your own plugin code, though.
