### ISSUE TITLE
Swap team moved players to other team

### ISSUE THREAD

**Issue by jfkz** [splewis/get5#46]
### Expected behavior
When knife round winner type !swap, players from one team moves to another **AND** team name and stats moves too.

### Actual behavior
When knife round winner type !swap, players from one team moves to another **BUT** team name and stats stay on the same sides.

### Steps to reproduce
1. Create match
2. Go to knife round
3. Win knife round
4. Type !swap.

- Plugin version:
0.4.0-dev
- Sourcemod version:
SourceMod v 1.7.3 (build 5302) w/ MetaMod v 1.10.6

**Comment by splewis** [comment]
I can't reproduce this. Team swaps work correctly in my testing, although the scoreboard/ui takes a moment to update after the plugin sets the name/flag/logo cvars.

**Comment by jfkz** [comment]
I found an error and fixed it: https://github.com/jfkz/get5/commit/61656fdbc03556ec199fc32d80dfe7b29361c805#diff-90d002e4b4b9eb90026b90b809ff24a4R100

Problem was: after knife round was ended by win, there are two events to start live match: !swap/!stay typing or action timer.

I fix the situation in that way: when player chose !stay/!swap-way timer will not be executed.
