### ISSUE TITLE
[User Help] creatematch does nothing

### ISSUE THREAD

**Issue by holdzin** [splewis/get5#461]
I was told to put get5_check_auths 0 in sourcemod / get5 if I didn't want to create a match.cfg, I put this in the config but when I run get5_creatematch to create a match nothing happens.

**Comment by FlowingSPDG** [comment]
Did you check Game server logs and that get5-web has public access for game server?

**Comment by splewis** [comment]
If you want help: https://github.com/splewis/get5/wiki/Debugging-help#getting-error-logs
