### ISSUE TITLE
Change map before I can type !ready in chat

### ISSUE THREAD

**Issue by bjarkeh14** [splewis/get5#465]
As soon as I pick a team, the match stoppes. And the server will change map.
This is before the match have been played.

- Plugin version: 0.7.1
- Sourcemod version: 1.10.0.6462
- Steps to reproduce (please be specific):
    1. Connect to the server
    2. Pick a team
    3. Match ends, before I can type !ready in chat

**Comment by bjarkeh14** [comment]
![image](https://user-images.githubusercontent.com/42116042/74886639-fcc26280-5378-11ea-97e4-a78c90828f9a.png)

**Comment by nerf-qh** [comment]
:+1:
