### ISSUE TITLE
Scrim Setup

### ISSUE THREAD

**Issue by suntay44** [splewis/get5#467]
Expected behavior

10 Players (5ct, 5tside)

Actual behavior

all in Tside

**Comment by splewis** [comment]
This may help: https://github.com/splewis/get5/wiki/Using-get5-for-scrims#adding-your-teams-steamids

**Comment by suntay44** [comment]
Hi Splewis. Is there a way to use get5 for pug without my admin help.

**Comment by suntay44** [comment]
even when im offline, when the server has 10 players it will automatically start in kniferound and veto map at the end of match?

**Comment by suntay44** [comment]
and splewis when i downlaod the master there is no .smx file. I need to get it from 7.0.X version

**Comment by splewis** [comment]
> even when im offline, when the server has 10 players it will automatically start in kniferound and veto map at the end of match?

No. Someone must execute the "!scrim" command in chat, or the `get5_scrim` admin command in console. `get5_scrim` is set to map-change permissions by default, which you can change in the sourcemod command overrides system (I don't have an example of this off-hand, sorry).

>  i downlaod the master there is no .smx file.

Don't download the source code. Read https://github.com/splewis/get5#download-and-installation
