### ISSUE TITLE
toornament support? 

### ISSUE THREAD

**Issue by Coffee0297** [splewis/get5#468]
Hello, i am managing a lan with a little over 300 participants. right now we have Ebot to do all the mach stuff and toornament to keep track of the maches.

Do Get5 support import of toornament teams/maches as Ebot do? the reason i wanna switch is that Ebot has not been updated in 3 years and is sometimes buggy....

-Tonny

**Comment by splewis** [comment]
No, get5 has no support of anything toornament-related. 

get5 is only a server plugin anyway; it would probably make more sense for toornament support in an actual match management system as well: e.g. https://github.com/splewis/get5-web (https://github.com/splewis/get5-web/issues/113), but that hasn't made any progress.
