### ISSUE TITLE
Coach moves to spectator after knife round swap

### ISSUE THREAD

**Issue by slawteruk** [splewis/get5#471]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When the Knife round is finished and the winning team hits "!swap", each teams coach is swapped teams but stays in coach mode

### Actual behavior
When the Knife round is finished and the winning team hits "!swap", each teams coach is swapped teams, but are then moved into spectators. The entire time sv_coaching_enabled is correctly set to 1

### Steps to reproduce
Join server with two players and two coaches. Ready up and complete the knife round. Winner of knife round should type the !swap command. Once swapped, both coaches will now be spectators and will need to rejoin the server if they wish to become a coach again. 

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Can you fill out: 

> Plugin version:
Sourcemod version:
Steps to reproduce (please be specific):

And:

Do you have a match config that can be used to reproduce this?

**Comment by slawteruk** [comment]
Get5 Version: 0.7.1
SM Version: 1.10.0 build 6462
MM Version: 1.10 build 971

Steps:
1. Join server with 1 person on each team and 1 person coaching each team (Total 4 connections)
2. Both T and CT ready up and then use !forceready to start - 2 coaches are currently in "coach mode"
3. Knife round begins - 2 coaches still in "coach mode" 
4. End of the knife round, winner selects to swap sides using !swap command - Both coaches are then swapped to spectators 
5. Both coaches then have to leave the server entirely, rejoin and then re-enter the coach command. 

Our config is set up specifically for our API, so I can't put it on here publically. If you have a contact email or a way for us to communicate privately, I'll happily guide you through the process so you can see it for yourself. 

I can be contacted at michael@gameye.com if that helps you.

**Comment by ShibaeO** [comment]
hi thx for your tip, but in config should i add coach steam id in spec or in the team ?
thx for your awnser

**Comment by TandelK** [comment]
Coach Steam IDs have to be added in Teams and when the Coach joins the server he or she has to type !coach to join coach role.

**Comment by ShibaeO** [comment]
thx for your awnser :)

**Comment by kubo6472** [comment]
> Coach Steam IDs have to be added in Teams and when the Coach joins the server he or she has to type !coach to join coach role.

@TandelK 
#705 would be a great solution to this problem.
