### ISSUE TITLE
No creating get5.smx

### ISSUE THREAD

**Issue by Baazyl** [splewis/get5#472]
Hello i have problem with get5.smx

He didn't create on server. Do you have the same problem? Im use 2 version and allways the same

**Comment by MikkelDK** [comment]
You need to compile! =)

**Comment by Baazyl** [comment]
I've got all the stuff from the plug-in on the server and it's just not being created. Maybe I'm throwing a file somewhere wrong

**Comment by MikkelDK** [comment]
What error are you getting, when you are trying to compile the get5.sp ?

**Comment by Baazyl** [comment]
how do you compile get5.sp? When i start server i don't have anything about that

**Comment by MikkelDK** [comment]
When you are downloading "dev" version, you will _need_ to compile the plugin =)

But I can do it for you, and upload .smx file here? :)

**Comment by Baazyl** [comment]
Yep you can if you want :D

**Comment by MikkelDK** [comment]
[get5 (smx only).zip](https://github.com/splewis/get5/files/4246041/get5.smx.only.zip)

There. ^^

**Comment by Baazyl** [comment]
ty <3

**Comment by Badman173** [comment]
Hello @MikkelDK, how do you compile get5.sp
I get the error "get5/jsonhelper.sp".

http://prntscr.com/s68mnu

What files do I need to compile successfully?

**Comment by Drarig29** [comment]
Follow all instructions contained in the `travis.yml` file at the root of the project.
