### ISSUE TITLE
if someone comes out of the server

### ISSUE THREAD

**Issue by eevyy762** [splewis/get5#473]
Hello,if someone comes out of the server, what code can I pull it with?

**Comment by splewis** [comment]
Sorry, but I don't understand your question.

**Comment by eevyy762** [comment]
how can I tell if a player is off the server?

**Comment by TandelK** [comment]
He is asking is there any way we can come to know if the client has got disconnected from the server from the scripting ?

**Comment by eevyy762** [comment]
yes

**Comment by thorpep138** [comment]
@eevyy762 you should call the OnClientDisconnect forward which is documented here: https://sm.alliedmods.net/new-api/clients/OnClientDisconnect

As a courtesy to the community, please review the documentation before asking questions and if you don't find the answer then post where you looked and ask if there is somewhere else you should have looked.

**Comment by eevyy762** [comment]
@thorpep138 can I get ready and start automatically when all the players are in?

**Comment by thorpep138** [comment]
@eevyy762 please close this issue and open a new one for the new question. I recommend you take a look at the full list of cvars at https://github.com/splewis/get5/wiki/Full-list-of-get5-cvars as well as the client/admin commands to force a side to be ready. Using a combination of those you should be able to achieve what you want.
