### ISSUE TITLE
 can I get ready and start automatically when all the players are in?

### ISSUE THREAD

**Issue by eevyy762** [splewis/get5#474]
can I get ready and start automatically when all the players are in?

**Comment by TandelK** [comment]
Currently if each and every player types !ready the game should start automatically. If you want to remove Ready System and automatically start if both teams have the Max Players it should start you will need to do own Scripting modifications.

**Comment by TandelK** [comment]
you can do own scripting change as per your requirements like 

Check condition that all the players are on server after each and every client joins , you can automatically start the match with ready status function, that can easily start the match.

**Comment by splewis** [comment]
> can I get ready and start automatically when all the players are in?

No, the ready-up system is required.
