### ISSUE TITLE
Kniferound bug

### ISSUE THREAD

**Issue by Proksi953** [splewis/get5#480]
### Expected behavior
So that the team that wins kniferound has a choice, and! Stay will not swap teams

### Actual behavior
When a team wins a kniferound, the plugin gives a page to select the team that lost and when that team writes! Stay, the teams swap

- Plugin version: 0.7.1
- Sourcemod version: 1.10 - build 6478
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
> Steps to reproduce (please be specific):

Can you post specific steps (match config, player commands) reproduce this? Nobody else seems to be having this issue, so I don't think it's going to be feasible for me to reproduce it.

**Comment by Proksi953** [comment]
I went through the older posts found here and found that putting ESL config on the server was not a good idea.
