### ISSUE TITLE
Players respawn if they disconnect while dead

### ISSUE THREAD

**Issue by Shaneajm** [splewis/get5#486]
### Expected behavior
When a player disconnects, their alive state should be saved.

### Actual behavior
Player can disconnect when dead and come back alive.

### Steps to reproduce
Die during a match, disconnect during the round and then reconnect. You will come back alive.

- Plugin version: 0.7.2-dev
- Sourcemod version: SourceMod 1.10.0.6458
[get5_debuginfo.txt](https://github.com/splewis/get5/files/4412563/get5_debuginfo.txt)

**Comment by splewis** [comment]
Are you able to confirm this is related to get5? It's very hard for me to imagine it being related. You might just have server config/cvar issues.

**Comment by Shaneajm** [comment]
I can check and let you know.
