### ISSUE TITLE
Allow Admins in-game to select Captains using !capt for specific person for VETO

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#488]
With lot of people getting randomly Veto selection , it will be best if we implement !capt feature like PUG Setup with Get5.  Also to add one more command for resetting Captains if in case there is a timeout of the Captain selected. After everyone is ready , Admins in the game can use !capt command and select Captains. Only this Captains should be allowed to do Veto.

**Comment by nickdnk** [comment]
As mentioned in Discord, we would like to make the player at index 0 on each team captain by default, without any way to change it ingame. That way we won't have to implement any new captain-selection logic at all.

If a captain times out, you can't play the match anyway and would have to restart, so why would you want to be able to select a new captain?

**Comment by JesusWithPants** [comment]
I would agree that it would be extra handy if it was possible to mark a captain on each team who should vote. If not an in-game command, at least a flag that could be set in match .cfg/.json payloads.
For a lot of tournaments this has been a reason get5's veto system cant be properly used as admins have no way to manage as to who gets to vote (and its not always the first person set in team).

**Comment by nickdnk** [comment]
> I would agree that it would be extra handy if it was possible to mark a captain on each team who should vote. If not an in-game command, at least a flag that could be set in match .cfg/.json payloads.
> 
> For a lot of tournaments this has been a reason get5's veto system cant be properly used as admins have no way to manage as to who gets to vote (and its not always the first person set in team).

Why don't you just put the captain at index 0 on the team? That's kind of equivalent to setting it on the match config.

**Comment by JesusWithPants** [comment]
"... admins have no way to manage as to who gets to vote (and its not always the first person set in team)."
If player[0] in team can be made reliably as captain - work for me.

**Comment by nickdnk** [comment]
> "... admins have no way to manage as to who gets to vote (and its not always the first person set in team)." If player[0] in team can be made reliably as captain - work for me.

That's how it works now.

**Comment by JesusWithPants** [comment]
> > "... admins have no way to manage as to who gets to vote (and its not always the first person set in team)." If player[0] in team can be made reliably as captain - work for me.
> 
> 
> 
> That's how it works now.
> 
> 

As of which version? v0.10?

**Comment by nickdnk** [comment]
As of always according to the code. If not, it's a bug and we should open an issue and find a solution for it. I don't use the in-game veto system so I don't have much experience with it.

**Comment by nickdnk** [comment]
@JesusWithPants There was a problem with captain selection when using JSON. This has been fixed and will be released with 0.12. You can download a prerelease here if you want to test: https://github.com/splewis/get5/releases/tag/v0.12.0-353cee5

**Comment by TandelK** [comment]
By default as per code steamid at [0] should be captain but for some reason i dont know it doesnt work. It is random for every game no matter what you do. Instead of all this we can also give players a option in game to select themself as captains using !capt command and also conditional checking if player veto gets disconnect , any other person in line can take over captain .

**Comment by nickdnk** [comment]
> By default as per code steamid at [0] should be captain but for some reason i dont know it doesnt work. It is random for every game no matter what you do. Instead of all this we can also give players a option in game to select themself as captains using !capt command and also conditional checking if player veto gets disconnect , any other person in line can take over captain .  
> 
> 
> 
> For Captain in game selection we can bring different method to achieve it like allow players to themself before Ready Up , team can select up their Captain with using !capt command and override current captain. Also right now if there is any way you can show in Chat that who is current Captain it will be clear for everyone to know who is currently going to Veto and dont make any type of issue while Veto. 
> 
> 

It's fixed in 0.12. Disconnecting captain will stop the veto until the player reconnects.

**Comment by nickdnk** [comment]
@TandelK Do you think only current captain should be able to reassign their captain status? Because of https://github.com/splewis/get5/pull/969, I'm looking into our options here.

**Comment by TandelK** [comment]
Yes. Give teams options to use !captme if current captain by any chance gets disconnected.

**Comment by nickdnk** [comment]
> Yes. Give teams options to use !captme if current captain by any chance gets disconnected and make the new person captain for the time being. Or may be create a !capt1 or !capt2 for CT / T Captain Selection Menu for Admins.
> 
> The first thing i would recommend to do is Show who is currently Captain of each Team before Warmup ends so everyone know who all are captains and dont create issues later on. Show Hint Message like
> 
> 1. {Team Name} Captain - Captain Steam Name / Custom Name
> 2. {Team Name} Captain - Captain Steam Name/ Custom Name

The disconnect issue has already been addressed: A new captain is automatically assigned. I specifically asked if you wanted to let anyone be captain or if only the current captain should be able to reassign _their own_ role. I don't really understand why this feature is necessary at all, which is why I asked. I don't understand what problem we are solving other than "captain is afk".

The PR I linked already announces who is captain in chat when map selection begins.

**Comment by nickdnk** [comment]
I'm working on updating the `!get5` "create match" menu, from within which you can select a captain for each team. Would that be sufficient? It opens up for being able to use `!capt` when still in ready-up phase to become captain, I'm just not sure if we want anyone to just "take" the captain role without confirmation.

**Comment by TandelK** [comment]
> I'm working on updating the `!get5` "create match" menu, from within which you can select a captain for each team. Would that be sufficient? It opens up for being able to use `!capt` when still in ready-up phase to become captain, I'm just not sure if we want anyone to just "take" the captain role without confirmation.

Yea that will be perfect and also can you also make this same option available for scream menu .
