### ISSUE TITLE
Servers are collapsing

### ISSUE THREAD

**Issue by eevyy762** [splewis/get5#492]
sometimes the data goes to the server and the server crashes.

- Plugin version:Latest Version
- Sourcemod version:1.10.0.6455
- Steps to reproduce (please be specific):sometimes the data goes to the server and the server crashes.

**Comment by TandelK** [comment]
can you upload your Server Logs , error logs somewhere and give us the link ? Use something like pastebin to upload your logs and share it as privately and also remove sensitive information like IP addresses.

**Comment by eevyy762** [comment]
where can I find the server logs?

**Comment by eevyy762** [comment]
https://ibb.co/pZfcm2P

**Comment by TandelK** [comment]
it is custom map i can see that but can you verify properly is the Map file loading properly without get5 ?

**Comment by eevyy762** [comment]
I've tried so many times loading without a problem.

**Comment by splewis** [comment]
If you have server crashing issues, you should install [accelerator](https://forums.alliedmods.net/showthread.php?t=277703). Diagnosing a crash is often impossible without it.

**Comment by splewis** [comment]
Can't help without more information.
