### ISSUE TITLE
how to disable Casters

### ISSUE THREAD

**Issue by knightVeer** [splewis/get5#493]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Match start when all 10 players !ready

### Actual behavior

match doesn't start and says Waiting for casters to type !ready to begin.

### Steps to reproduce

how can i disable casters please?
Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by TandelK** [comment]
It is kept as intentionally for live status because Caster should be also ready to Cast the Match.  If there are no casters or spectators defined it should be fine it should directly go through and start the match and if it is like this then it is a bug.

**Comment by splewis** [comment]
If you are reporting bug, please fill out the form. It's there for a reason. I can't help with no information. Note that there is the `min_spectators_to_ready` field the match schema, but it defaults to 0.

**Comment by TandelK** [comment]
@splewis is it intended to use this cvar after VETO has completed and match is ready to begin and than it is bugged . Because when all players are in the server including casters before veto if you have `min_spectators_to_ready  0 ` it will work but after the first map is loaded and in its warmup everyone including Spectators have to ready up.

**Comment by splewis** [comment]
There doesn't appear to be enough information here to help.
