### ISSUE TITLE
Add halftime pause/re-ready up

### ISSUE THREAD

**Issue by ndstudios-admin** [splewis/get5#494]
It will be cool for tournament organizers if you add match admins, so the game will start after two teams, (optional) casters and admin are ready. And for casters very needed feature is the halftime pause timer (mp_halftime_pausematch), which only can be removed after admin is ready.

**Comment by nickdnk** [comment]
You can set `mp_halftime_pausematch` to 1, and the game will pause at halftime. Admin can unpause using `sm_unpause`: http://localhost:63342/get5/documentation/site/pausing/#administrative
