### ISSUE TITLE
Add player score to recorded stats

### ISSUE THREAD

**Issue by ringvold** [splewis/get5#495]
Thanks for this project! It makes it much easier to run tournaments, even just the casual ones we do every week! 😄 

I cant find anything in the stats file that looks like the player score you can see at right end of the in-game score table  when holding tab. 
The stats file have a lot of other stats but we would like to record the player score to see the performance over time (also the official ranks don't always tell the whole truth). Right now we are taking screenshots and adding it manually to a spreadsheet but since stats are already being written for the matches it would be nice have that score available.

Are there any reason this score is not included or cant it be produces from the stats that are currently being written in the stats files?

**Comment by splewis** [comment]
No reason it's not there (other than me just not caring about the stat at the time), it'd be quite easy to add a new stat. PRs welcome.

**Comment by ringvold** [comment]
I have never done this kind of programming but I'll give it a try. :) Do you have any pointers on where to look? Do you know if it is available to just pull out from the game or if it needs to be calculated?

**Comment by ringvold** [comment]
After some poking around I think this might be the one I'm looking for: https://sm.alliedmods.net/new-api/cstrike/CS_GetClientContributionScore

**Comment by splewis** [comment]
Yup, that should be it. Many of the stats get calculated from hooks (e.g. `player_death` has a callback fired each death, which updates the stats), but that for score it's probably better to just do it on round-end, which you could add to this loop doing some other stats: https://github.com/splewis/get5/blob/master/scripting/get5/stats.sp#L91
