### ISSUE TITLE
Force ending match throws error: Menu handle is invalid (error 1)

### ISSUE THREAD

**Issue by Skurkur** [splewis/get5#496]
Doesn't seem to cause any harm, but is still an error.

Mods are auto installed by LinuxGSM (so i'm assuming most linuxgsm servers have the same setup)
Plugin version: 0.7.2-dev+481
sourcemod_version = 1.10.0.6482
metamod_version = 1.10.7-devV
get5 git commit: ed23e8a

Last log info from addons/sourcemod/logs/errors_20200412.log:
L 04/12/2020 - 01:57:07: [SM]   [4] Line 44, ./scripting/get5/get5menu.sp::AdminMenuHandler
 L 04/12/2020 - 01:57:07: [SM]   [3] FakeClientCommand
 L 04/12/2020 - 01:57:07: [SM]   [1] Line 792, ./scripting/get5.sp::Command_EndMatch
 L 04/12/2020 - 01:57:07: [SM]   [0] Menu.Cancel
 L 04/12/2020 - 01:57:07: [SM] Call stack trace:
 L 04/12/2020 - 01:57:07: [SM] Blaming: get5.smx
 L 04/12/2020 - 01:57:07: [SM] Exception reported: Menu handle 1aa00f4 is invalid (error 1)
 L 04/12/2020 - 01:57:07: Info (map "de_mirage") (file "/home/csgo-league/serverfiles/csgo/addons/sourcemod/logs/errors_20200412.log")
 L 04/12/2020 - 01:57:07: SourceMod error session started

- Steps to reproduce (please be specific):
Start a match, force end the match (through !get5 ingame or web panel)

**Comment by TandelK** [comment]
Currently due to Sourcemod 1.10 version update there are lot of code changes that causes error and will require a bit of rewrite soon. Try as much as possible to run the plugin in Sourcemod 1.09 . Even if you skip this error there will be more coming

**Comment by PhlexPlexico** [comment]
Is this issue still happening? I don't think I've ran into this issue whenever I've been doing testing in the past few months with sourcemod 1.10.
