### ISSUE TITLE
Select Team Name from players on Team like the Scrim command does but for a match config?

### ISSUE THREAD

**Issue by Walks2000** [splewis/get5#50]
I was looking through the .sp's for a way to do this but I'm not so sure it's possible, would love to have it picked like the scrim command but I prefer using a match config to set up the game when playing with friends and auto picking a name would just help it look better.

**Comment by splewis** [comment]
Are you referring to the team_{player name} style of team names?

If so, I can imagine those getting auto set by the plugin on player connect if a team name wasn't specified in the matches config. I thought was the current behavior, but I'd have to check.

**Comment by Walks2000** [comment]
Yeah that's exactly what I meant but I'm certain it just defaults to "Team1" and "Team2" if no name is specified in the match cfg

**Comment by splewis** [comment]
You were right, it defaulted to "Team1" / "Team2". I've changed that now to fallback to use a player name when they join.
