### ISSUE TITLE
automatic dust2 switching on

### ISSUE THREAD

**Issue by eevyy762** [splewis/get5#500]
hi, sometimes dust2 automatically opens on our servers.

**Comment by splewis** [comment]
Do you have reason to think this is related to get5? The [sourcemod forums](https://forums.alliedmods.net/forumdisplay.php?f=130) may be a better place for general server help.

**Comment by eevyy762** [comment]
when get5 is not installed, the map goes towards the server, but sometimes dust2 opens on the server when get5 is installed.

**Comment by splewis** [comment]
I'd suggest asking on the sourcemod forums.
