### ISSUE TITLE
Scoreboard bug at half

### ISSUE THREAD

**Issue by ShibaeO** [splewis/get5#503]
### Expected behavior

normal game at half : switch and play

### Actual behavior

at half the socreboard cant be remove by player during the round

### Steps to reproduce

- Plugin version: 0.7.1
- Sourcemod version: 1.10.0.6482
- Steps to reproduce (please be specific): at the half

[get5_debuginfo.txt](https://github.com/splewis/get5/files/4504571/get5_debuginfo.txt)

**Comment by ShibaeO** [comment]
i think i found the solution but if you still have tip tell me
mp_win_panel_display_time 15 ->> mp_win_panel_display_time 3

**Comment by ShibaeO** [comment]
ok its not working ...

**Comment by TandelK** [comment]
Scoreboard at the half time cannot be removed as it is Game function and not plugin one.

**Comment by ShibaeO** [comment]
Thx for your anwser but the problem is not to remove it, its all player has it stuck on there screen and have to re-connect to make it gone

**Comment by lukasz922** [comment]
hello
I have problem its solved edit command 
mp_halftime_duration 8
mp_win_panel_display_time 8
This command Worked tested for me.

**Comment by MoritzLoewenstein** [comment]
`mp_win_panel_display_time 15` is confirmed to be the cause of this, just set it to 3. This issue can be closed.
