### ISSUE TITLE
Freeze Players during Veto

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#504]
Lot of time people are just moving around in Warmup. If we could implement Freeze Players function during Veto selections. With this random people getting Veto would focus on Veto rather than by mistake picking up map for Weapon Selection.

**Comment by Drarig29** [comment]
Maybe you already know how to do it, but I found a way [here](https://forums.alliedmods.net/showthread.php?p=2438705) with his command `sm_speed`:

From his source file:

```
SetEntPropFloat(entity, Prop_Data, "m_flLaggedMovementValue", value);
```

**Comment by splewis** [comment]
I'd accept a PR for this.

> SetEntPropFloat(entity, Prop_Data, "m_flLaggedMovementValue", value);

I think using the builtin pausing or freezetime functionality of the game is a vastly better way to implement this. Awkwardly freezing players would probably not be something I'd accept.

**Comment by TandelK** [comment]
@Drarig29 Try to integrate this feature that as soon as Veto is called upon all the players gets freeze.

**Comment by Drarig29** [comment]
I don't have time currently. Maybe in the next weeks.

**Comment by TandelK** [comment]
As this is integrated now , Closing this issue.
