### ISSUE TITLE
[BUG] Loops not working properly after sm-json v3.0 implementation in config files.

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#505]
### Expected behavior
Normal Veto should show us 7 Maps for veto
Players for match should be as per config file

### Actual behavior
Veto are showing 22 Maps for Veto. 

### Steps to reproduce

get5_debuginfo - https://pastebin.com/dsyiiPvP
Match Config file - https://pastebin.com/PbV5AyTE

- Plugin version: get5 0.7.2-dev+488
- Sourcemod version: 1.10.0.6484
- Steps to reproduce (please be specific):

Use the latest Get5 version with SM 1.10 and run config file given. It was made using example_match.json file . You will be able to see clearly that json loop is not working properly for config. It is creating many duplicates for Maps , Players also.

**Comment by TandelK** [comment]
@MoritzLoewenstein Please check this issue.

**Comment by MoritzLoewenstein** [comment]
sry, i will look into it.

**Comment by TandelK** [comment]
@MoritzLoewenstein any updates on them ? It only causes error for Array Structure specially Players Tab and Map List.

**Comment by MoritzLoewenstein** [comment]
Found the bug, pr coming soon.
