### ISSUE TITLE
Append-only player stats table for avoiding data loss

### ISSUE THREAD

**Issue by redismx** [splewis/get5#508]
### Expected behavior

The player stats are always incremented and never overwritten.

### Actual behavior

The player stats are being overwritten, which may incur data loss in case something wrong happens.

### Steps to reproduce

- Plugin version: development build 489
- Sourcemod version: 1.10 - build 6484
- Steps to reproduce:

So, I'm not quite sure if this was really the problem, but between the first and second map I run `get5_loadteam team1` and `get5_loadteam team2` because I wanted to change the clantag of the players that was wrong. At the end of the series, I noticed that the data from map0 had been overridden with the second map data—somehow the second map also was interpreted to be map0. The match ended 2x0, but the server still thought that we were going to the second map and executed `changelevel` again for the same map that the players had just finished playing.

My point with this report is not necessarily around the `get5_loadteam` thing which may be a bug or perhaps expected behavior as it shouldn't be run in the middle of the match, but I'm more concerned with the stats table in the database. I lost all the data related to the first map due to this, and even if this bug had happened (or any other thing) and I still had the player stats there, I could fix the other tables and tweak the score. In other words: I'm proposing that the get5_stats_players to be append-only (insert-only, instead of replace into).

**Comment by nickdnk** [comment]
@redismx Can you clarify; are you only reporting that you want data to not be overwritten, or do you want to find the cause of the map logic? I have no problem changing the MySQL statements to `INSERT INTO` without a `ON DUPLICATE KEY UPDATE`.

It is no longer using `REPLACE INTO`, just FYI. It was changed: https://github.com/splewis/get5/pull/608/files#diff-c4154d12ae064f557e3b359f5861f53f7f998ea3945efa06c75eda81429af374R267-R281

**Comment by nickdnk** [comment]
You cannot run `get5_loadteam` after a map has finished, as it resets the team's score, leading to probably this issue you had: https://github.com/splewis/get5/blob/734e485cfb1c45649147a25f99c17506be1aa2b1/scripting/get5/matchconfig.sp#L639

We have no plans to rewrite that stats system to append, but you an take advantage of all the new forwards (http://localhost:63342/get5/documentation/site/events_and_forwards/) and save the data yourself.
