### ISSUE TITLE
[Feature request] match title variable for hostname format

### ISSUE THREAD

**Issue by topjor** [splewis/get5#510]
I would like to request a feature so the `match_title` matchconfig variable can be used inside the `get5_hostname_format`
e.g. `{MATCHTITLE}` would resolve to the match title

As an addition the default hostname format could be changed to `{MATCHTITLE}: {TEAM1} vs {TEAM2}`
or `Get5 {MATCHTITLE}: {TEAM1} vs {TEAM2}`

**Comment by MikkelDK** [comment]
You can edit on the source-code and do "PR" =)

**Comment by Drarig29** [comment]
@topjor I don't think we need to update the default value for `get5_hostname_format`.

> `match_title`: wrapper on the `mp_teammatchstat_txt` cvar, but can use {MAPNUMBER} and {MAXMAPS} as variables that get replaced with their integer values. In a BoX series, you probably don't want to set this since get5 automatically sets mp_teamscore cvars for the current series score, and take the place of the mp_teammatchstat cvars.

`match_title` has a complex behavior according to the paragraph above. Its default value is:

https://github.com/splewis/get5/blob/7318ef013d5fcb38cc05a97cd569dda407fdb0c5/scripting/get5/matchconfig.sp#L5

Maybe some people need/prefer a constant hostname for the entire match.

However, you would be able to use your own custom `get5_hostname_format` set to `{MATCHTITLE}: {TEAM1} vs {TEAM2}` with my pull request (PR).

**Comment by topjor** [comment]
Ah okay, I never looked match_title, I am overwriting it with my panel anyway to the name of the match given in there and like to also use it now in the hostname format. for the default this would not make any sense. As for the PR thank you, you beat me to it. I would probably have done it myself in the comming week or in half a year when we need it again for our yearly lan party.

**Comment by topjor** [comment]
Closing as #511 is merged
