### ISSUE TITLE
BO2 process changes

### ISSUE THREAD

**Issue by ThiagoBento2019** [splewis/get5#516]
Hello, I was wondering how or in what part of the code, you can change the choice and ban sequence, precede the veto. 

### Sequence: BAN, BAN, PICK, PICK (No more veto)

Thank you for your help!

**Comment by MikkelDK** [comment]
https://github.com/splewis/get5/wiki/Map-Vetoes#bo2-veto

> Each team alternatives vetoing, vetoing 2 maps each. After those vetoes, 3 maps are left. Each team picks a map, letting the other team choose side on it. The last map left will not be used in the series.
> 
> tldr: ban/ban/ban/ban/pick map 1/pick map 2/last map unused

**Comment by ThiagoBento2019** [comment]
this line??

  // This is also a bit hacky.
  // The purpose is to force the veto process to take a
  // ban/ban/ban/ban/pick/pick/last map unused process for BO2's.
  bool bo2_hack = false;
  if (g_BO2Match && (mapsLeft == 2 || mapsLeft == 2)) {
    bo2_hack = true;
  }

  if (sidesSet < mapsPicked) {
    if (g_MatchSideType == MatchSideType_Standard) {
      GiveSidePickMenu(client);

**Comment by MikkelDK** [comment]
Yep. =)

**Comment by ThiagoBento2019** [comment]
then it would be (mapsLeft == 2 || mapsLeft == 4) to create the sequence: ban, ban, pick, pick?

**Comment by MikkelDK** [comment]
You can try, and compile it, and test. =D

**Comment by ThiagoBento2019** [comment]
okay, great! thanks!

**Comment by splewis** [comment]
I'd be okay with this change, though I'm not sure if it should be a match config field or a new cvar. PRs welcome, either way.

**Comment by ThiagoBento2019** [comment]
Hey bro, i use your plugin for my  page tournaments, and i wanted change the veto system style, because each league, have a different veto style, do you understand? that is why wanted change your code

**Comment by ThiagoBento2019** [comment]
It would be cool if you could let a sequence of vetoes be customized, you know what I mean?

**Comment by nickdnk** [comment]
Tracked in https://github.com/splewis/get5/issues/643.
