### ISSUE TITLE
Score Stats Per Half

### ISSUE THREAD

**Issue by bgilbert6** [splewis/get5#518]
I noticed the end game stats CFG doesn't include any per half information. How hard would this be to add?
Such as
"team1"
{
 "firsthalf"        "t"
 "firsthalfscore "8"
}

"team2"
{
 "firsthalf"        "ct"
 "firsthalfscore "7"
}

Thoughts?

**Comment by ZenOfWolf** [comment]
I haven't tried writing in SourcePawn so I don't know how hard it would be to implement, but half time scores are already stored in backups if you have them enabled. 
Though I would think that it would be possible to fetch them through the plugin, or simply store the score when round 16 begins.

**Comment by bgilbert6** [comment]
I actually have it about 90% done since Get5 already had a "halftime" hook. Not sure if they want me to pull request.

Although overall I'm not sure I'll use it since I'd rather have per round info for all players stats which is much more complicated.

**Comment by splewis** [comment]
It'd be easy to add additional fields under the 'team' level of stats: https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L166. They're set here: https://github.com/splewis/get5/blob/master/scripting/get5/stats.sp#L80-L86. PRs welcome.
