### ISSUE TITLE
Add bot when some players missing

### ISSUE THREAD

**Issue by ferru97** [splewis/get5#52]
Hi
First of all thanks for this mod, it is very useful! :)

I'd like to know if there is a way to lets bots join the game when some players missing

Thanks for support!

**Comment by splewis** [comment]
You can just not set ``bot_quota 0`` in the live/warmup configs.

Otherwise there will be no special support for bots. The plugin is intended for team competitive matches - where there are no bots.

**Comment by ferru97** [comment]
ok thanks for information

Also, how can i set the match id with RCON?
have i to set it before or after get5_loadmatch?

Thanks

**Comment by ferru97** [comment]
For mysql tables

**Comment by splewis** [comment]
You can set it anytime before teams ready up by ``get5_mysql_force_matchid``. If you don't set it, it is set automatically via a ``SELECT LAST_INSERT_ID()`` query.

**Comment by ferru97** [comment]
What is the correct sintax?
I tried with RCON command "get5_mysql_force_matchid = 55"

**Comment by ferru97** [comment]
ok solved without using "="
