### ISSUE TITLE
Can't add custom logos in the server

### ISSUE THREAD

**Issue by DroneN1456** [splewis/get5#521]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Custom logos working in the game

### Actual behavior
Custom logos not working in the game

### Steps to reproduce
custom logo in \csgo\resource\flash\econ\tournaments\teams (server directory)
also a cfg file with the same name as the image .png and the same name inside the cfg file
and using the logo plugin that i forget the name
my game download the logo when i joined the server, but isnt showing

- Plugin version: 0.7.1
- Sourcemod version:  1.10.0.6488
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
> Steps to reproduce (please be specific):

Why is this empty?

Did you set team logos in a match config?

> using the logo plugin that i forget the name

You're not supposed to need any other plugin.

**Comment by DroneN1456** [comment]
o tried again and it worked now, i dont know what exatcly was the problem, put placing the png file (or vector) in the logos folder and seting in the match config should work well
