### ISSUE TITLE
Remove KnifeRound for: Create match with current players?

### ISSUE THREAD

**Issue by MikkelDK** [splewis/get5#523]
Hi,

Is it possible to remove "knife round" for: "Create match with current players"

It seems I can't find a method to remove knife round. =) or do I need to modify get5.sp first?

**Comment by ZenOfWolf** [comment]
It looks like the match config for "Create match with current players" is generated when selecting the option. 
You could probably fix it by adding `kv.SetString("matchid", "never_knife");` to matchconfig.sp at around line 862. Thats where the config is setup.

**Comment by MikkelDK** [comment]
I will wish, it was possible to make "modified" custom.

So it's possible on the "Create match with current players" so the 10 players can vote: Yes/No for the kniferound! =)

**Comment by splewis** [comment]
> I will wish, it was possible to make a "modified" custom.

So it's possible on the "Create match with current players" so the 10 players can vote: Yes/No for the knife round! =)

That type of behavior is a bit too far out from get5's designed use case: tournament/league play.

I'd suggest writing another plugin for whatever custom behavior you want that generates a match config as you like, then calling [Get5_LoadMatchConfig](https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L102) from that plugin.
