### ISSUE TITLE
starting side keyvalue in match config?

### ISSUE THREAD

**Issue by realRapSi** [splewis/get5#525]
I was searching for a keyvalue to set a specific team to start on a specific side on a specifig map.

Ex. I want to set team1 to start on CT side on the first map (bo3)

The veto is done before the server is even started and I want to preset this.

Obviously I set "skip_veto" to zero and "side_type" to "never_knife". But I forgot the command to assign a team to ct or t.

Could anyone please help me out :) Thanks a lot

**Comment by ZenOfWolf** [comment]
In the readme under the heading match schema, it says that "never_knife" sets team1 to ct.
There doesn't seem to be a keyvalue for it.

**Comment by splewis** [comment]
The only supported way to do this is to use `never_knife` for `side_type`, then you could flip which team is team1 and which is team2. I'd probably be okay with a new config option to make it easier - PRs welcome on that.
