### ISSUE TITLE
[User help]Question with max_players

### ISSUE THREAD

**Issue by ndstudios-admin** [splewis/get5#526]
Hi! I have 1 question. I will host a showmatch next week, and 1 team registered 6 players (5 active and 1 reserve, not a coach). So, what happens, if I set players_per_team 6, but min_players_to_ready 5 and we going 5v5? Or what I have to do?

**Comment by ZenOfWolf** [comment]
You don't have to set players_per_team 6, as that value is for max players on a team.
You can set more than 5 players on a team, but if the 6th person joins when the team already has 5 players, the 6th players is kicked.

I'm guessing you're wanting to let the team change players in halftime/maps. The default settings should allow you to do this, just set the 6 steamids under players for that team.

**Comment by ndstudios-admin** [comment]
> You don't have to set players_per_team 6, as that value is for max players on a team.
> You can set more than 5 players on a team, but if the 6th person joins when the team already has 5 players, the 6th players is kicked.
> 
> I'm guessing you're wanting to let the team change players in halftime/maps. The default settings should allow you to do this, just set the 6 steamids under players for that team.

Yep. Thanks! Will be a good option that will make possible change players during freezetime or when match is paused. Like by typing .change or sth like this to chat.

**Comment by splewis** [comment]
> Yep. Thanks! Will be a good option that will make possible change players during freezetime or when match is paused. Like by typing .change or sth like this to chat.

Why is that preferrable? Is there something wrong with the process of:
- a player leaving, then a new player joining? 

What's the value added by a new command?
