### ISSUE TITLE
[Feature Request] Ability to change from MR15 to MR12

### ISSUE THREAD

**Issue by ImperiumProjects** [splewis/get5#527]
I've done some research server-side to see what I'd need to modify to have Get5 run a Bo1 or Bo3 series with MR12 games instead of MR15 and it's quite involved and requires to be manually modified before each match.

There's a lot of talk in the pro community at the moment about possibly switching back to MR12 and I think a cvar in the match config file to specify MR15 / MR12 would be a great way to test MR12 and how viable it is.

**Comment by ZenOfWolf** [comment]
Can't you set `mp_maxrounds 24` in the cvars section of the match cfg?

**Comment by splewis** [comment]
Yes, I don't see why you think this requires anything from get5. You can use whatever game cvars you like, including mp_maxrounds.
