### ISSUE TITLE
Documentation on the JSON returned by get5_status

### ISSUE THREAD

**Issue by alcjzk** [splewis/get5#529]
Hey,

would it be possible to get proper documentation on the match state JSON returned by the `get5_status` command?

**Comment by Drarig29** [comment]
Don't be afraid to look at the code 😊

Just search for `get5_status` in the code. You'll see it runs this method:
https://github.com/splewis/get5/blob/bb64ed8fe06278d1f5aadec1759d7af75728ec59/scripting/get5.sp#L1324

I don't know if you are speaking about the whole response of the `get5_status` command or only a part of it.

But here's some documentation of the whole response.

Here is the **static part**:

- `plugin_version`: Get5's version number.
- `commit`: Only here if `COMMIT_STRING` is defined (probably not your case).
- `gamestate`: A number representing the game's state. (using the [`Get5State` enum](https://github.com/splewis/get5/blob/51fe79d0da8131f7104e4a78551f4364f06be950/scripting/include/get5.inc#L6-L16))
  - **0** - `Get5State_None` = No setup has taken place.
  - **1** - `Get5State_PreVeto` = Warmup, waiting for the veto.
  - **2** - `Get5State_Veto` = Warmup, doing the veto.
  - **3** - `Get5State_Warmup` = Setup done, waiting for players to ready up.
  - **4** - `Get5State_KnifeRound` = In the knife round.
  - **5** - `Get5State_WaitingForKnifeRoundDecision` = Waiting for a !stay or !swap command after the knife.
  - **6** - `Get5State_GoingLive` = In the lo3 process.
  - **7** - `Get5State_Live` = The match is live.
  - **8** - `Get5State_PostGame` = Postgame screen + waiting for GOTV to finish broadcast.

 - `paused`: Is the match paused?
- `gamestate_string`: A human-readable gamestate (generated by [`GameStateString()`](https://github.com/splewis/get5/blob/bb64ed8fe06278d1f5aadec1759d7af75728ec59/scripting/get5/util.sp#L532-L553)) which is a translation of `gamestate`.
  - `"none"`
  - `"waiting for map veto"`
  - `"map veto"`
  - `"warmup"`
  - `"knife round"`
  - `"waiting for knife round decision"`
  - `"going live"`
  - `"live"`
  - `"postgame"`

Now, there may still be **one or two additional parts**.

If current game state is different than `Get5State_None`:
- `matchid`: The current match's id. You can set it in match configs, with the property which has the same name.
- `loaded_config_file`: The name of the loaded config file. If you used `get5_loadmatch <file>`, it's this file's name. If you used `get5_loadmatch_url`, the [pattern of the file](https://github.com/splewis/get5/blob/478710d8c7c0afb3b2f07d70eb3858ca928ab8a2/scripting/get5/matchconfig.sp#L3) is `remote_config%d.json`, where `%d` [is the](https://github.com/splewis/get5/blob/bb64ed8fe06278d1f5aadec1759d7af75728ec59/scripting/get5.sp#L1430-L1432) server's id, which [you can set](https://github.com/splewis/get5/blob/bb64ed8fe06278d1f5aadec1759d7af75728ec59/scripting/get5.sp#L305-L307) with `get5_server_id`.
- `map_number`: The current map number in the series.
- `team1` and `team2`: Two JSON objects which share the same properties.
  - `name`: Name of the team.
  - `series_score`: The score in the series.
  - `ready`: Boolean indicating if the team is ready.
  - `side`: The side on which the team is. [Can be](https://github.com/splewis/get5/blob/96e94e3cfd9e80916f1bfc904d3549025d09fe45/scripting/get5/util.sp#L510-L518) `"CT"`, `"T"` or `"none"`.
  - `connected_clients`: The number of human clients connected in the team.
  - `current_map_score`: The team's score on the current map.

And finally, if current game state is past the `Get5State_Veto`:
- `maps`: A JSON object which contains one property per map.
  - Key: `"map%d"`
  - Value: The name of the map. (Taken from the match config.)

**Comment by alcjzk** [comment]
Thank you for the quick response! And yes I had figured much of this out from the source, but I believe it would be beneficial to many having this posted in the wiki for example?

Definitely would provide ease-of-use for people building anything that fetches get5_status :)

**Comment by splewis** [comment]
Yes - it should be documented, probably in the wiki. Ideally I'd prefer to take the existing wiki into something users can submit PRs for - as far as I know, you cannot submit PRs for the wiki content.

In the meantime (or before I get to moving the docs around), a PR to add `get5_status` documentation to the readme sounds good.

**Comment by PhlexPlexico** [comment]
Closing this as this was completed, and it now exists in the [docs](https://splewis.github.io/get5/developer_api/#static) :)
