### ISSUE TITLE
REMOTE_CONFIG_FILENAME

### ISSUE THREAD

**Issue by PreFix** [splewis/get5#53]
I haven't tried yet, but I can see that #define REMOTE_CONFIG_FILENAME "remote.json" can conflict with other servers runned on the same folder.

**Comment by splewis** [comment]
Yes, you're right that this could cause an issue. The only good news is that the file is only needed there for the duration of the asynchronous file download. But if 2 servers run get_loadmatch_url at the same time problems would be had.

Not sure what the best fix would be.

**Comment by jfkz** [comment]
Sorry for interrupting your conversation. 

As I can understand this is not critical issue. And I see two ways to resolve it:

- Add cvar to determine filename. 
- Generate random name based on server and time. 

As for me I prefer first way. But second is possible too.

**Comment by PreFix** [comment]
I would suggest port based etc remote_27015.json

**Comment by jfkz** [comment]
@PreFix 
That's not a good decision. If I want to create batch configuration script I will use names based on ip/port definitely.

**Comment by splewis** [comment]
Naming by port should be fine. Or by a cvar that just defaults to remote.json, port is probably preferable, though.

**Comment by PreFix** [comment]
@splewis  still ip is might be needed too, because some people use several ip.

**Comment by splewis** [comment]
There is now a ``get5_server_id`` cvar you can set to a unique value per server to prevent conflicts, which is the preferred solution to this.
