### ISSUE TITLE
Map Vote for Loser-Team

### ISSUE THREAD

**Issue by deLuXe83** [splewis/get5#531]
Hi,

do you thing it is possible to add a feature, which lets the loosing team decide what map to play for the next round?

Thank you very much for your help!

**Comment by deLuXe83** [comment]
any ideas?! :) 💯

**Comment by TandelK** [comment]
Well with BO3 it will ask for 2nd Map and 3rd map from start itself.

**Comment by splewis** [comment]
This doesn't really seem like a use case I think it's worth adding, sorry. It's fairly far outside the tournament/league play use-case get5 aims to support.

**Comment by deLuXe83** [comment]
Hey,
thanks for your reply.
Yes that's true regarding real tournament play.
Our use case is kind of a mixture between PUGsetup and get5. We want to play let's say 3-4 maps with mixed teams out of 10-14 people. Teams are changing from matchday to matchday. So we need to setup a cfg in get5 with the teams before we start. This is ok, even if i find the "team voting" system in pugsetup much better for our usecase, but I want the teams to stay locked while mapchanging. So get5 is the better alternative....

And for sure we could set the map pool before, but it would be nicer to let the losing team vote. Workaround is manual mapchange, yes.... But the automatic solution is more impressive ;)

Could you point me in a direction what would need to be changed in the code, so maybe I can try it myself?

thank you very much!
