### ISSUE TITLE
CSGO update broke get5_loadmatch_url

### ISSUE THREAD

**Issue by 39ma** [splewis/get5#532]
get5_loadmatch_url ****
L 05/28/2020 - 17:49:07: [get5.smx] Failed to load match config: Failed to create HTTP GET request
L 05/28/2020 - 17:49:07: get5_event: {"matchid":"","params":{"reason":"Failed to create HTTP GET request"},"event":"match_config_load_fail"}
Failed to load match config.

**Comment by ZenOfWolf** [comment]
It looks like a problem with Steamworks after the newest update. I think we just have to wait for steamworks to be updated.
There is already a post about it on the alliedmodders forum, [here](https://forums.alliedmods.net/showthread.php?t=229556&page=76#post2702746).

**Comment by 39ma** [comment]
Thank you. Yep, we have to wait till SteamWorks will update.
На 28.05.2020 18:23:27, Victor <notifications@github.com> писал:
It looks like a problem with Steamworks after the newest update. I think we just have to wait for steamworks to be updated.
There is already a post about it on the alliedmodders forum, here [https://forums.alliedmods.net/showthread.php?t=229556&amp;page=76#post2702746].

**Comment by tuudik** [comment]
@splewis Can you add new SteamWorks to build scripts?
https://github.com/KyleSanderson/SteamWorks/releases
It works now with new SteamWorks release.

**Comment by splewis** [comment]
It seems like the only change needed is for users to use a newer SteamWorks extension. 

There are no changes to the Steamworks extension's include file still: https://github.com/KyleSanderson/SteamWorks/blob/1.2.3b/Pawn/includes/SteamWorks.inc, so I'm not seeing why the plugin would be incompatible, or what this change does. Isn't the compiled identical still? Or am I missing something?

**Comment by splewis** [comment]
(sorry, I should have commented on #537 instead, but oh well)

**Comment by tuudik** [comment]
Sorry, I just thought having the updated SteamWorks during build is neccessary :) But I am very novice.

**Comment by splewis** [comment]
Np, all the steamworks changes needed are runtime code changes within the SteamWorks extension itself  - the API the extension gives to the get5 plugin remains unaffected, hence not needing any plugin-compile-time changes.

**Comment by tuudik** [comment]
So as I understand only SteamWorks had to be rebuilt due to Steam SDK change:
https://github.com/KyleSanderson/SteamWorks/commit/a5905873cc86bbf3f582fff5db4489c850b3c673
Correct?

And since the function names remained same for SteamWorks, then it doesnt affect get5 during building?

**Comment by hpksoldati** [comment]
It is not working with this update. And I use the command only to run the match.cfg

**Comment by splewis** [comment]
> It is not working with this update. And I use the command only to run the match.cfg

Sorry, but I don't understand your problem. Feel free to file a new issue if you can give more concrete information about your problem.
