### ISSUE TITLE
Setting up coaches

### ISSUE THREAD

**Issue by minim0vz** [splewis/get5#539]
hey, not really an issue, just that all the documentation doesn't really explain how to setup the match config file to support a coach in each team, do i just set the coach steamid on a team roster list or do i set it on the spectators list ?

**Comment by TandelK** [comment]
It is mentioned in Readme which shows in starting page itself of the repo. You have to add them to Team Players Steam ID List where they join in and type !coach with it. Also while using this function make sure they join in first before anyone of their team mates as soon as Player limit is reached it will say that Player Limit has reached so it is better that they join first and type in !coach and they will be sent to their teams section.

**Comment by splewis** [comment]
Yes, you don't explicitly configure coaches. You just add the players on the appropriate teams, and they can use the `.coach` command or will be forced to coach if 5 players already on the team in the server. The documentation could probably make this clearer, though.
