### ISSUE TITLE
Coach slot using !pause command activates !tech pause

### ISSUE THREAD

**Issue by slawteruk** [splewis/get5#544]
### Expected behavior
Coach uses !pause command. Server is then paused based on settings within Get5 config. 

### Actual behavior
Coach uses !pause command. Server then activates a technical pause (!tech) and can not be unpaused by both teams, only the admin via Rcon

### Steps to reproduce
1. Set up teams with 1 player and 1 coach
2. Coach uses !pause command

### Get5 Config:

All 'arg.' variables are used with the Gameye API. 

We place the coach slots within each team so that we can report correct stats per team after knife swap and half time swap. If we do not include the coaches in these slots, they bug out and do not swap teams correctly. 

 "Match"
      {
        "matchid"     "example_match"
        "num_maps"    "1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.
        "spectators" // players allowed in spectator (e.g., admins) should go here
        {
          "players"
          {
            "${arg.spectatorOne}"   ""
            "${arg.spectatorTwo}"   ""
            "${arg.spectatorThree}"   ""
            "${arg.spectatorFour}"   ""
          }
        }
        "skip_veto"   "1" // If set to 1, the maps will be preset using the first maps in the maplist below.
        "skip_veto"   "true"
        "match_title" "${arg.matchTitle}"
        "veto_first"  "team1"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.
        "side_type"   "always_knife" // Either "standard", "always_knife", or "never_knife"
        "maplist"
        {
          "${arg.map}"    ""
        }
        "players_per_team"        "${arg.playersPerTeam}"
        "min_players_to_ready"    "${arg.minPlayersToReady}" // Minimum # of players a team must have to ready
        "min_spectators_to_ready" "${arg.minSpectatorsToReady}" // How many spectators must be ready to begin.
        "team1"
        {
          "name"    "${arg.teamNameOne}" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
          "tag"     "${arg.teamTag1}"  // Short tags replace the "clan tag" on the scoreboard. They are optional.
          "flag"    "${arg.teamFlag1}"
          "logo"    "${arg.teamLogo1}"
          "players"
          {
            // Any of the 3 formats (steam2, steam3, steam64 profile) are acceptable.
            // Note: the "players" section may be skipped if you set get5_check_auths to 0,
            // but that is not recommended. You can also set player names that will be forced here.
            // If you don't want to force player names, just use an empty quote "".
            "${arg.teamOnePlayerOne}" ""
            "${arg.teamOnePlayerTwo}" ""
            "${arg.teamOnePlayerThree}" ""
            "${arg.teamOnePlayerFour}" ""
            "${arg.teamOnePlayerFive}" ""
            "${arg.teamOneCoachOne}" ""
          }
        }
        "team2"
        {
          "name"    "${arg.teamNameTwo}"
          "tag"     "${arg.teamTag2}"
          "flag"    "${arg.teamFlag2}"
          "logo"    "${arg.teamLogo2}"
          "players"
          {
            "${arg.teamTwoPlayerOne}" ""
            "${arg.teamTwoPlayerTwo}" ""
            "${arg.teamTwoPlayerThree}" ""
            "${arg.teamTwoPlayerFour}" ""
            "${arg.teamTwoPlayerFive}" ""
            "${arg.teamTwoCoachOne}" ""
          }
        }
        // These will be executed on each map start or config load.
        // You should not use this as a replacement for the cfg/get5/live.cfg config.
        "cvars"
        {
            hostname "${arg.hostname}"
            mp_maxrounds ${arg.maxRounds}
            mp_halftime_duration ${arg.halftimeDuration}
            get5_demo_name_format _${arg.demfilename}
            get5_check_auths ${arg.steamIdCheck}
        }
      }

- Plugin version: Get5-492
- Sourcemod version: sourcemod-1.10.0-git6462

**Comment by metalhyoga** [comment]
Hi, I'm dealing with this problem too, did you find any solutions?
Regards!

**Comment by nickdnk** [comment]
Should be fixed on master.
