### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by nonhodie** [splewis/get5#546]
### Expected behavior
Game to be played out.

### Actual behavior
The server crashes after a scrim is started. It is not consistent, may crash on the second, on the third, on the 10th, but, at some point, it shuts down.

### Steps to reproduce
I need the server not to crash mid games. The only thing I've changed is setting get5_kick_when_no_match_loaded to 0. Here's the log:

Time: 06/10/2020 - 14:46:22
Plugin version: 0.7.1
sourcemod_version = 1.10.0.6455
metamod_version = 1.10.7-devV

Global state:
g_GameState = 0 (none)
g_MatchID = manual
g_MapsToWin = 1
g_BO2Match = 0
g_LastVetoTeam = 1
g_MapPoolList (length 1) = 
  [0] -> de_inferno
g_MapsToPlay (length 1) = 
  [0] -> de_inferno
g_MapsLeftInVetoPool (length 1) = 
  [0] -> de_inferno
g_MatchTitle = Map {MAPNUMBER} of {MAXMAPS}
g_PlayersPerTeam = 5
g_MinPlayersToReady = 0
g_MinSpectatorsToReady = 0
g_SkipVeto = 1
g_MatchSideType = 0
g_InScrimMode = 0
g_HasKnifeRoundStarted = 0
g_MapChangePending = 0
g_PendingSideSwap = 0
g_WaitingForRoundBackup = 0
g_SavedValveBackup = 0
g_DoingBackupRestoreNow = 0
Team info for team team1 (0):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = {LIGHT_GREEN}{NORMAL}
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = CT (3)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 3
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 0
Team info for team team2 (1):
g_TeamNames = team_?hodie
g_TeamAuths (length 1) = 
  [0] -> 76561198272983771
g_TeamTags = 
g_FormattedTeamNames = {PINK}team_?hodie{NORMAL}
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = T (2)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 2
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 0
Team info for team spec (2):
g_TeamNames = casters
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = {NORMAL}casters{NORMAL}
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 0
Team info for team none (3):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
g_ReadyTimeWaitingUsed = 0

Interesting cvars:
get5_allow_technical_pause = 1
get5_autoload_config = 
get5_check_auths = 1
get5_fixed_pause_time = 0
get5_kick_when_no_match_loaded = 0
get5_live_cfg = get5/live.cfg
get5_max_pause_time = 300
get5_max_pauses = 0
get5_mysql_force_matchid = NULL CVAR
get5_pausing_enabled = 1
get5_reset_pauses_each_half = 1
get5_web_api_url = NULL CVAR
mp_freezetime = 15
mp_halftime = 1
mp_halftime_duration = 15.0
mp_halftime_pausetimer = 0
mp_match_end_restart = 0
mp_maxrounds = 30
mp_overtime_enable = 0
mp_overtime_halftime_pausetimer = 0
mp_overtime_maxrounds = 6
mp_round_restart_delay = 7.0
mp_timelimit = 0
mp_warmup_pausetimer = 1
mp_warmuptime_all_players_connected = 0
sv_coaching_enabled = 1
tv_delay = 105
tv_enable = 0

sm plugins list:
admin-flatfile.smx: Admin File Reader by AlliedModders LLC: Reads admin files (1.10.0.6455, http://www.sourcemod.net/)
get5.smx: Get5 by splewis:  (0.7.1, https://github.com/splewis/get5)
basechat.smx: Basic Chat by AlliedModders LLC: Basic Communication Commands (1.10.0.6455, http://www.sourcemod.net/)
adminmenu.smx: Admin Menu by AlliedModders LLC: Administration Menu (1.10.0.6455, http://www.sourcemod.net/)
basevotes.smx: Basic Votes by AlliedModders LLC: Basic Vote Commands (1.10.0.6455, http://www.sourcemod.net/)
nextmap.smx: Nextmap by AlliedModders LLC: Provides nextmap and sm_nextmap (1.10.0.6455, http://www.sourcemod.net/)
basecommands.smx: Basic Commands by AlliedModders LLC: Basic Admin Commands (1.10.0.6455, http://www.sourcemod.net/)
reservedslots.smx: Reserved Slots by AlliedModders LLC: Provides basic reserved slots (1.10.0.6455, http://www.sourcemod.net/)
adminhelp.smx: Admin Help by AlliedModders LLC: Display command information (1.10.0.6455, http://www.sourcemod.net/)
playercommands.smx: Player Commands by AlliedModders LLC: Misc. Player Commands (1.10.0.6455, http://www.sourcemod.net/)
funvotes.smx: Fun Votes by AlliedModders LLC: Fun Vote Commands (1.10.0.6455, http://www.sourcemod.net/)
clientprefs.smx: Client Preferences by AlliedModders LLC: Client peferences and settings menu (1.10.0.6455, http://www.sourcemod.net/)
sounds.smx: Sound Commands by AlliedModders LLC: Sound Commands (1.10.0.6455, http://www.sourcemod.net/)
basecomm.smx: Basic Comm Control by AlliedModders LLC: Provides methods of controlling communication. (1.10.0.6455, http://www.sourcemod.net/)
funcommands.smx: Fun Commands by AlliedModders LLC: Fun Commands (1.10.0.6455, http://www.sourcemod.net/)
basetriggers.smx: Basic Info Triggers by AlliedModders LLC: Adds ff, timeleft, thetime, and others. (1.10.0.6455, http://www.sourcemod.net/)
antiflood.smx: Anti-Flood by AlliedModders LLC: Protects against chat flooding (1.10.0.6455, http://www.sourcemod.net/)
basebans.smx: Basic Ban Commands by AlliedModders LLC: Basic Banning Commands (1.10.0.6455, http://www.sourcemod.net/)

**Comment by tuudik** [comment]
In addition to SM logs, did you check the server console and etc logs?

**Comment by nonhodie** [comment]
I'll try to re-install everything and see if it still crashes

**Comment by nonhodie** [comment]
This turned out to be a host problem. Our host forced the server hostname change and it crashed everytime due to it. Fixed now :)
