### ISSUE TITLE
AddStringParams not adding params to request url

### ISSUE THREAD

**Issue by maharjanraj** [splewis/get5#548]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

This may be related to SteamWorks extension but I don't know where to open this issue. I am not getting params and couldn't debug either. Is this happening to me only?
got true from AddStringParam(req, 'key', 'value') but params doesn't appear in url.
I think SetHTTPRequestGetOrPostParameter is not working, or may be I did something wrong.

### Expected behavior
/match/5/map/1/finish?team1Score=10&team2Score=16&...

### Actual behavior
/match/5/map/1/finish

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.2-dev+495
- Sourcemod version: 1.10 - build 6490:
- Steamworks version: 1.2.3b lin
- Steps to reproduce (please be specific):
On every event like match start, round end, match end, etc.

**Comment by MypowerHD** [comment]
Did you check the Body of the Post?
