### ISSUE TITLE
Demos are recording very inconsistently 

### ISSUE THREAD

**Issue by ehrenos** [splewis/get5#550]
It seems like only one demo each day is being recorded from the scrims we play. I haven't changed anything with the get5 configs except setup our team with steam ids and enable gotv on the dathost advanced settings. Any issues similar to this that have been solved?

**Comment by PhlexPlexico** [comment]
May be an issue in regards to https://github.com/splewis/get5/issues/762. So you'll just need to follow the solution there and it should work.

If you need anymore help with configuring the file names, feel free to drop by the [Discord](https://discord.gg/zmqEa4keCk) and we'll be able to help you further.
