### ISSUE TITLE
Show teammates money in the round start

### ISSUE THREAD

**Issue by DroneN1456** [splewis/get5#551]
i dont know if this already a feature, but will be very cool to see this option in the plugin and a template for it, like
"{NAME} ---> {MONEY}", showing the balance of the whole team in the chat

**Comment by splewis** [comment]
I don't intend to add this - the idea for get5 is that it doesn't replace builtin game functionality, and is un-obtrusive as possible. Other plugins could, of course, add this in if you want it.
