### ISSUE TITLE
[BUG] SQL Query Didn't Work

### ISSUE THREAD

**Issue by BlackYuzia** [splewis/get5#552]
### Note

I didn't post here any info about versionn of plugin, sm or metamod because this is trouble in only SQL Query.

### Description

I was try import https://github.com/splewis/get5/blob/master/misc/import_stats.sql database to my own.
When I try do this, I get ONLY ONE table (actualy **get5_stats_maps**) but buggy.

When I try do the same by SQL Query I get error message (check screenshot).

> If you need some translate tell it. GUI is on **ru** lang but some messages on **english** lang. 

Because this error I can't use **get5_mysqlstats** plugin.

### Steps to reproduce:

1. Download SQL Query.
2. Try import or send query.
3. Get error!

### Screenshot

![image](https://user-images.githubusercontent.com/25010528/89267139-7efcc580-d63f-11ea-88c4-9e7f2b99f201.png)

**Comment by Drarig29** [comment]
Did you try replacing `SET FOREIGN_KEY_CHECKS = ON;` by `SET FOREIGN_KEY_CHECKS = 1;`?

http://sqlines.com/mysql/set_foreign_key_checks

**Comment by BlackYuzia** [comment]
@Drarig29 I was try do it. I get the same error (all the same)
( I use PMA and get this error again)

**I resove this trouble by using: **HeidiSQL****
But, in **PMA** this didn't work.

**Comment by Drarig29** [comment]
Okay. Then you can close the issue 😉
