### ISSUE TITLE
[BUG] Pause Didn't Work If Fixed Time is True

### ISSUE THREAD

**Issue by BlackYuzia** [splewis/get5#555]
### Description

I was setup cvar `get5_fixed_pause_time` to `1` value.
When players call `!pause`, after that left 3 pause (4 max)
**But pause didn't start.**

When cvar `get5_fixed_pause_time` is `0` value.
`!pause` is work but pause length is **UNLIMITED**.

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin Version: 0.7.2-dev+495
- SM: 1.10.0.6492

How to repeat bug:
1. Install latest release of plugin.
2. Change cvar get5_fixed_pause_time` to `1` value.
3. Start match.
4. Call pause by `!pause` or `sm_pause` command.
5. PROFIT (You didn't have pause)

**Comment by TandelK** [comment]
`get5_fixed_pause_time` you will have to use seconds , currently it is set to just 1 seconds so as soon as you pause the match it again gets un-paused as currently there is only 1 second as a pause time.

**Comment by BlackYuzia** [comment]
Oh. lol. THX! :d
