### ISSUE TITLE
get5 mysql_force_matchid STILL not working

### ISSUE THREAD

**Issue by lmz2k** [splewis/get5#556]
### Expected behavior

I'm trying to use the plugin get5_mysqlstats to save the match stats and save the matchid with id that I send on json file that create the match after running the command get5_loadmatch match.json, but tha matchid is always being created with value 0, even if i set get5_mysql_force_matchid to use my own id.

I tried to solve this problem by reading problem #186, but I was unsuccessful

- Plugin version: Build 495 of get5
- Sourcemod version: 1.10

**Comment by splewis** [comment]
Any steps to reproduce? Ideally the match config file & commands you used & the debug logs mentioned at https://github.com/splewis/get5/wiki/Debugging-help#getting-debug-logs

**Comment by lmz2k** [comment]
### match.json

this is the json file example that I used.
and running the command get5_loadmatch match.json

{
   "matchid":"4369804",
   "num_maps":1,
   "players_per_team":5,
   "min_players_to_ready":1,
   "min_spectators_to_ready":0,
   "skip_veto":true,
   "side_type":"standard",
   "maplist":[
      "de_overpass"
   ],
   "team1":{
      "name":"teste2",
      "tag":"teste2",
      "flag":"BR",
      "players":{
         "76561198065528690":"gLima.sad"
      }
   },
   "team2":{
      "name":"teste1",
      "tag":"teste1",
      "flag":"BR",
      "players":{
         "76561198450222705":"Liminha"
      }
   },
   "cvars":{
      "hostname":"FastTap - Takgota® Oficial BETA"
   }
}

observation: I also tried to send the matchid as number, not as string, but the error persists

## LOGS

L 08/20/2020 - 18:03:52: [get5_mysqlstats.smx] Failed match creation query, error = Duplicate entry '0' for key 'PRIMARY'
L 08/20/2020 - 18:03:56: Error log file session closed.


## MORE INFOS

As you can see, always trying to create a match on database with id 0, but id 0 already exists on database so the match is never been created on database , what I realy want  to do, is to the plugin get the id that was send on the match.json, and use the same id to create a new row on our database.

here is a printscreen of our database, there is just one row, to save new matchs, e need to delete to save a new one: https://prnt.sc/u33plf

**Comment by Drarig29** [comment]
When you say "even if i set get5_mysql_force_matchid to use my own id", where do you do it?

Via the rcon or do you add it in the config file `cvars` section?

**Comment by lmz2k** [comment]
your question made me question whether I was doing it right or not, so I i tried to send the get5_mysql_force_matchid in the json file and worked.


it hadn't been clear to me before how to use the plugin, now I understand.
if someone else is confused how it works like I was, just add this line on your match.json file and will solve the problem:

"cvars":{
"get_5_mysql_force_matchid": "DESIRED_ID"
}

Thanks guys, and congratulations for the plugin xD
