### ISSUE TITLE
Random Error:  Can't init func_areaportal bla...bla

### ISSUE THREAD

**Issue by nakinthorn** [splewis/get5#559]
5 of 10 when i ran my CSGO Server (Dedicated Server)
with Get5 config (match.json)
i got this error
Can't init func_areaportal
Can't init func_areaportal
Can't init func_areaportal
Can't init prop_physics_multiplayer
Can't init func_clip_vphysics
Can't init point_worldtext
Can't init func_areaportal
Can't init func_areaportal
Can't init func_occluder
Can't init light
Can't init light
Can't init light
Can't init func_occluder
Can't init func_occluder
...
....

Pls. help , how to fixed it
it 50% happen
and when it was happen i must reboot server to solve it

thank

**Comment by nakinthorn** [comment]
![Screen Shot 2563-08-27 at 15 28 08](https://user-images.githubusercontent.com/19216345/91416720-fe199e00-e879-11ea-8524-2755478436f0.png)

**Comment by nakinthorn** [comment]
5 of 10 happen how i can do

**Comment by Drarig29** [comment]
It doesn't come from get5.

Apparently, it's because of your configuration:

https://forums.alliedmods.net/showthread.php?p=2240101

**Comment by nakinthorn** [comment]
i Fixed it already, not of my configuration
it was Get5 warmup.cfg bug when first person come to server
like this : []((https://github.com/splewis/get5/issues/320))
btw, fixed

**Comment by BubbiBjQrn** [comment]
@nakinthorn - Iøm currently experiencing same issue 50% of all matches makes server crash. how exactly did you fix this issue?
