### ISSUE TITLE
How to execute Get5 command if server run background

### ISSUE THREAD

**Issue by nakinthorn** [splewis/get5#560]
Now am run server with bash file using call start.sh by pm2 
So, it running in background

how i can run some get5 command in this situation ?

**Comment by Drarig29** [comment]
Isn't pm2 made for Node.js?

Maybe you could prefer running the server in a [screen](https://linuxize.com/post/how-to-use-linux-screen/) and reattach it when you need to run a get5 command.

Otherwise you can use whatever rcon client to send commands via rcon.
