### ISSUE TITLE
.r instead of !ready

### ISSUE THREAD

**Issue by D3K0** [splewis/get5#561]
I have seen that in most servers you just have to type **.r** instead of typing **!ready** to start the match.

any one knows how to add this ".r" command to the get5 plugin?

att,

Gustavo

**Comment by Drarig29** [comment]
You can try console aliases. 

https://csgoconsole.com/commands/console-aliases.html

**Comment by MikkelDK** [comment]
You need to modified get5.sp I think before it's possible.

https://github.com/splewis/get5/blob/master/scripting/get5.sp#L355
Like the example below:
`  AddAliasedCommand("ready", Command_Ready, "Marks the client as ready");`

You can add newline under that and add:
`  AddAliasedCommand("r", Command_Ready, "Marks the client as ready");`

**Comment by D3K0** [comment]
> You need to modified get5.sp I think before it's possible.
> 
> https://github.com/splewis/get5/blob/master/scripting/get5.sp#L355
> Like the example below:
> ` AddAliasedCommand("ready", Command_Ready, "Marks the client as ready");`
> 
> You can add newline under that and add:
> ` AddAliasedCommand("r", Command_Ready, "Marks the client as ready");`

already tried it, but it`s not that simple. also i have to compile .sp to .smx and I dont know how.

**Comment by Drarig29** [comment]
No coding skills are required but you better need a linux system to be able to follow the instructions in the `travis.yml` file...

You can use WSL on windows.

https://www.github.com/splewis/get5/tree/master/.travis.yml

**Comment by D3K0** [comment]
> No coding skills are required but you better need a linux system to be able to follow the instructions in the `travis.yml` file.
> 
> You can use WSL on Windows.
> 
> https://www.github.com/splewis/get5/tree/master/.travis.yml

u just told me how to compile .sp to .smx. but how to add the command **.r**?

i tried to compile it on Windows, but i have this error
**fatal error 183: cannot read from file: "include/get5.inc"**

**Comment by Drarig29** [comment]
As said before, this line should work. 

`AddAliasedCommand("r", Command_Ready, "Marks the client as ready");`

How did you try to compile exactly? Did you follow the instructions in the Travis file?

**Comment by Drarig29** [comment]
By the way, you need to download the full repository. I think you are missing include files...

Download it as a zip file and follow the instructions in the Travis yml file. You need `spcomp`, sourcemod, etc.

**Comment by D3K0** [comment]
I tried it with a `compile.exe` & `spcomp.exe` file that comes among with sourcemod adddon.

I just need to copy/paste the blue lines into the linux terminal? otherwise I would need a step-by-step tutorial. I'm not very good with Linux.   

thanks anyways.

**Comment by D3K0** [comment]
> By the way, you need to download the full repository. I think you are missing include files...
> 
> Download it as a zip file and follow the instructions in the Travis yml file. You need `spcomp`, sourcemod, etc.

I tried it with a `compile.exe` & `spcomp.exe` file that comes among with sourcemod adddon.

I just need to copy/paste the blue lines into the linux terminal? otherwise I would need a step-by-step tutorial. I'm not very good with Linux.

thanks anyways.

**Comment by Drarig29** [comment]
Yes, that's the beauty of the Travis file 😁

First, install WSL on Windows if you don't have it (it's basically a linux integrated in Windows) : [tutorial](https://www.computerhope.com/issues/ch001879.htm) (prefer installing Ubuntu)

Then follow the instructions in the Travis file:

As the first lines say, you must install the prerequisites: `sudo apt install lib32stdc++6`

Install git (`sudo apt install git`) and clone the current repository : `git clone https://github.com/splewis/get5.git`

Now you can run exactly every command  in the `before_script` section to install everything. Beware of the environment variable that you won't have `SMVERSION`, so you can hardcode it in the line which uses it: `SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=1.10"`

Once all is done, hopefully without problem, you can run the command `smbuilder` in the root directory and it will compile in a subdirectory. (I don't remember which one.)

You can then replace the resulting files in your server directory. Mostly the `.smx` file I think.

**Comment by D3K0** [comment]
I follow the steps to install wsl and it keeps showing me this when I start Ubuntu from start menu:

The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Press any key to continue...

**Comment by D3K0** [comment]
> Yes, that's the beauty of the Travis file 😁
> 
> First, install WSL on Windows if you don't have it (it's basically a linux integrated in Windows): [tutorial](https://www.computerhope.com/issues/ch001879.htm) (prefer installing Ubuntu)
> 
> Then follow the instructions in the Travis file:
> 
> As the first lines say, you must install the prerequisites:
> 
> ```shell
> sudo apt install lib32stdc++6
> ```
> 
> Install git (`sudo apt install git`) and clone the current repository:
> 
> ```shell
> git clone https://github.com/splewis/get5.git
> ```
> 
> Now you can run exactly every command in the `before_script` section to install everything.
> 
> Beware of the environment variable `SMVERSION` that you won't have, so you can hardcode it in the line which uses it:
> 
> ```shell
> SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=1.10"
> ```
> 
> Once all is done you can run the command `smbuilder` in the root directory and it will compile in a subdirectory (of which I don't remember the name).
> 
> You can then replace the resulting files in your server directory. Mostly the `.smx` file, I think.

I follow the steps to install wsl and it keeps showing me this when I start Ubuntu from start menu:

The Windows Subsystem for Linux optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Press any key to continue...

**Comment by Drarig29** [comment]
Did you enable the feature?

```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```

**Comment by D3K0** [comment]
> Did you enable the feature?
> 
> ```
> dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
> ```

yes... i dont understand. I'll install ubuntu on a virtual machine.

**Comment by splewis** [comment]
I just merged https://github.com/splewis/get5/commit/ffae6c9642ec7344a621b93fcc58b92158346941 in to support this.
