### ISSUE TITLE
How to set timer to warmup and end the match

### ISSUE THREAD

**Issue by bboychris168** [splewis/get5#566]
I am currently trying to end match after warmup has finished. Currently i have the current set get5_time_to_start "300" but it only says the teams have forfeit but doesn't end the match and kick the players. Is there a way to kick players after warmup of 5min?

I have also tried mp_warmuptime 300 in warmup.cfg and still shows unlimited warmup in the live match.

**Comment by TandelK** [comment]
Well someone can surely do a PR about this with new CVAR saying kick players on forfeit to 1 or 0

**Comment by bboychris168** [comment]
@TandelK would you know if there is any other way to setting a timer on warmup?

**Comment by TandelK** [comment]
@bboychris168 If the team 1 does all !ready and no one joins in other team it should automatically work

**Comment by bboychris168** [comment]
Ok i would have to test it out. But if there is a way to put a timer for 5min and kick everyone out that would be better for my usage. Thanks for your insight!

**Comment by PhlexPlexico** [comment]
I believe the other config option you're looking for is `get5_kick_when_no_match_loaded` set to `1`. If this is set, after a match forfeits it will be set to no match, and kick all the players. Closing this as this is more configuration-based user help.

Should you need anymore help, please join the [Discord](https://discord.gg/zmqEa4keCk) and we'll be able to assist you.
