### ISSUE TITLE
get5_mysqlstats.smx plugin not working

### ISSUE THREAD

**Issue by Zeligon2** [splewis/get5#57]
When i run in console the following command : 
rcon sm plugins load disabled/get5_mysqlstats.smx

i get the following error : 

09/08/2016 - 14:02:12: [SM] Exception reported: Could not connect to get5 database: Configuration "get5" not found
L 09/08/2016 - 14:02:12: [SM] Blaming: disabled/get5_mysqlstats.smx()
L 09/08/2016 - 14:02:12: [SM] Call stack trace:
L 09/08/2016 - 14:02:12: [SM]   [0] SetFailState
L 09/08/2016 - 14:02:12: [SM]   [1] Line 34, ./scripting/get5_mysqlstats.sp::OnPluginStart()
[SM] Plugin disabled/get5_mysqlstats.smx failed to load: Error detected in plugin startup (see error logs).

my databases.cfg is ok with all the info.

any help?

thank you,

### Steps to reproduce
- Plugin version: 0.3.1
- Sourcemod version: 1.8.0.5928

**Comment by splewis** [comment]
Are you *really* sure there is a section called ``"get5"`` in your databases.cfg file? The error pretty strongly indicates it can't be found. Might need a server restart to re-read that file.

**Comment by Zeligon2** [comment]
Thank you for the quick replay, 
now after i changed the name in the databases.cfg to "get5" i get the following error : 

rcon sm plugins load disabled/get5_mysqlstats.smx
L 09/09/2016 - 05:48:44: [SM] Exception reported: Could not connect to get5 database: Driver "mysql" not found
L 09/09/2016 - 05:48:44: [SM] Blaming: disabled/get5_mysqlstats.smx()
L 09/09/2016 - 05:48:44: [SM] Call stack trace:
L 09/09/2016 - 05:48:44: [SM]   [0] SetFailState
L 09/09/2016 - 05:48:44: [SM]   [1] Line 34, ./scripting/get5_mysqlstats.sp::OnPluginStart()
[SM] Plugin disabled/get5_mysqlstats.smx failed to load: Error detected in plugin startup (see error logs).


thank you,

**Comment by ayushgarg39** [comment]
It updates everything instantly during the game in the MySQL database.

**Comment by Zeligon2** [comment]
its not working, 

here is my databases.cfg : 

```
"Databases"
{
    "driver_default"        "mysql"

    // When specifying "host", you may use an IP address, a hostname, or a socket file path

    "default"
    {
        "driver"            "mysql"
        "host"                "localhost"
        "database"            "get5"
        "user"                "root"
        "pass"                "*****"
        //"timeout"            "0"
        //"port"            "3306"
    }

    "get5"
    {
        "driver"            "mysql"
        "host"                "127.0.0.1"
        "database"            "get5"
        "user"                "root"
        "pass"                "********"
        //"timeout"            "0"
        "port"            "3306"
    }


    "storage-local"
    {
        "driver"            "sqlite"
        "database"            "sourcemod-local"
    }

    "clientprefs"
    {
        "driver"            "sqlite"
        "host"                "localhost"
        "database"            "clientprefs-sqlite"
        "user"                "root"
        "pass"                ""
        //"timeout"            "0"
        //"port"            "0"
    }
```

thank you,

**Comment by splewis** [comment]
Have you looked at the error logs? (addons/sourcemod/logs)

**Comment by splewis** [comment]
Closing since there hasn't been any new information. You can reopen if needed.
