### ISSUE TITLE
get5_backup_system_enabled and other undocumented cvars

### ISSUE THREAD

**Issue by nickdnk** [splewis/get5#571]
It seems the `get5_backup_system_enabled` cvar is not part of the wiki, which instead says the timer should be set to 0 to disable the system: https://github.com/splewis/get5/wiki/Full-list-of-get5-cvars - so which one is it?

Also, these cvars are missing from the wiki as well.
`get5_display_gotv_veto`
`get5_pretty_print_json`
`get5_server_id`
`get5_set_client_clan_tags`
`get5_veto_confirmation_time`

I can create a PR to add them based on the get5.cfg file if you want.

**Comment by splewis** [comment]
The source of truth for what the defaults are / what the behavior is would be the code: https://github.com/splewis/get5/blob/master/scripting/get5.sp#L251-L338


The problem with github wiki sis that it can't accept PRs. Feel free to copypaste the new contents and I'll update the page, though. I had wanted to move the wiki content to internal markdown files so they could accept PRs, but I didn't get around to that.

**Comment by nickdnk** [comment]
> The source of truth for what the defaults are / what the behavior is would be the code: https://github.com/splewis/get5/blob/master/scripting/get5.sp#L251-L338

While that's true it kind of defeats the purpose of having documentation in the first place. Heh.

I haven't worked with Github wikis, but I'd support having the docs as part of the repo to make sure merged changes always include updated documentation as well. I can do that.

**Comment by splewis** [comment]
>While that's true it kind of defeats the purpose of having documentation in the first place. Heh. 

Agreed! I was just mentioning as the best way to answer any question on cvar defaults/behavior authoritatively.

**Comment by PhlexPlexico** [comment]
Linking the docs PR to this as this should make it so users can contribute freely to documentation and have it automatically updated upon merge.
