### ISSUE TITLE
Issues help?

### ISSUE THREAD

**Issue by Kjerne** [splewis/get5#576]
!tech doesnt work?
Backups dont save team scores, it saves weapons/money etc, not the team scores.

Warmup: If i dont set mp_ignore_round_win_conditions from default 0 to 1, it just loops restarting match and after switching to a new map. when using web https://get5.splewis.net/ 

Knife: If i dont put mp_restartgame 1, in the knife.cfg, it wont restart the match before knife round, it just starts from your current position.

Using default cfgs, i tried latest release files and after tried master branch. same issues.

**Comment by MikkelDK** [comment]
Do you have tried installed a dev version of get5-plugin?

**Comment by splewis** [comment]
Can you add any error logs you see? https://github.com/splewis/get5/wiki/Debugging-help#getting-error-logs

**Comment by Kjerne** [comment]
> Do you have tried installed a dev version of get5-plugin?

"Using default cfgs, i tried latest release files and after tried master branch. same issues."

**Comment by splewis** [comment]
Without error logs or clear steps to reproduce there's  not much that can happen here.
