### ISSUE TITLE
Only 3 Players Per Team

### ISSUE THREAD

**Issue by HerzGegenFame** [splewis/get5#577]
### Expected behavior
5 Player Teams

### Actual behavior
3Player Teams

### Steps to reproduce

- Plugin version: 0.7.1
- Sourcemod version: 110 Build 6497
- Steps to reproduce (please be specific):

I installed get 5 on my linux machine with only sourcemod and metamod installed.
All the Cvars have been set to 10 Players and 5 per team.
The server starts up with only 6 Players allowed on teams.

This does not change when a match or Scrim is enabled.

**Comment by TandelK** [comment]
Check your config of CSGO server Maxplayers allowed here are 6 in one team including Coaches so its not a issue of  Get5 . Also make sure to check the No of players cvar in Get5 Config. 

Drop your CSGO server.cfg on pastebin 
remove your CSGO Server Name , Password and RCON password and also get5 config used to load the match. Make sure to remove sensitive data first

**Comment by HerzGegenFame** [comment]
Got The Issue Fixed.

Could be that it was not the cause but i switched my Kernel and now it is working as intended. Ty for your help.
