### ISSUE TITLE
Add details in get5_listbackups

### ISSUE THREAD

**Issue by Drarig29** [splewis/get5#578]
Currently, the command `get5_listbackups` just lists the filename of all backup files but there is no more information.

The filename of a backup file is `get5_backup_match%s_map%d_round%d.cfg` or `get5_backup_match%s_map%d_prelive.cfg`, so we only have the match id, the map number and the round number. But it's pretty good like this, so I think it should stay as is.

The problem is that in a LAN with 16 servers (my case), it's quite hard to determine which backup file to choose when a team comes to your desk to ask to load the backup for "the round with a score of 14-12 in the match Team A vs. Team B".

On our private fork of get5, we changed `Command_ListBackups()` to output the following information:
- If there is no Valve backup in the file: `filename date team1_name team2_name`
- Otherwise: `filename date team1_name team2_name map_name team1_score team2_score`

It's done by reading wanted information in each backup file.

If we don't want to change the behavior of the existing command, we could add an optional argument to it (just like `ls` has `ls -l`) or create another command.

I already have the code so I can make a PR.

**Comment by splewis** [comment]
This sounds good to me.

I like the idea of adding an additional command for it, how about `get5_listbackupinfo`?

**Comment by Drarig29** [comment]
Okay, I'll go for this!

**Comment by Drarig29** [comment]
Do you prefer `get5_listbackupinfo` or `get5_listbackupsinfo`?

**Comment by splewis** [comment]
Hah, yeah, it's kind of an awkward situation w.r.t. the naming and pluralness of the command name.

Thinking about it more - I would also be okay with just adding to `get5_listbackups`, nothing that things get a little sad w.r.t. backwards compatibility. But I've strayed away from a strict version 1.0 for a reason :) 

How about we just add to `get5_listbackups` for now? In general adding *less* commands is a good thing, IMO.

**Comment by Drarig29** [comment]
As you wish. It's not a big deal anyway, I think.
