### ISSUE TITLE
Add optionally-set captains

### ISSUE THREAD

**Issue by splewis** [splewis/get5#58]
They would:
- be the only player on each team allowed to do vetoes
- (maybe) be the only player on each team allowed to ready the team up
- (maybe) be allowed allowed to set the team name

**Comment by dragonblade62** [comment]
If this feature gets implemented (which I hope it does), then I think the captain should also be the only person on the team able to initiate pauses. This could be adjusted by a convar such as
get5_captain_only_pause 
or something like that

**Comment by ayushgarg39** [comment]
@dragonblade62  That can also become a problem if the captain timed out (for xyz reasons) and the team won't be able to pause for him since only he is the only one with access to !pause.
On the other side the captains are required in the tournaments as there can be only veto sessions too where only one captain from both teams join the server only to veto and then they can wait out for the whole team to join and knife directly without a delay.

**Comment by dragonblade62** [comment]
@ayushgarg39
This would be solved by a technical pause implementation. The other players on the team can call a technical pause if the captain disconnects.

Anyways, this would probably be a cvar, so it could be modified to ones wants and meeds

**Comment by dragonblade62** [comment]
Needs *

**Comment by royysz** [comment]
Adding this will be great.

**Comment by Technoblazed** [comment]
It's not that hard to add tbh.

**Comment by royysz** [comment]
@Technoblazed the part of "(maybe) be the only player on each team allowed to ready the team up" and captain pausing.

**Comment by Technoblazed** [comment]
@royysz, so that would be the .forceready feature then? Captain pausing is difficult in case the captain disconnects

**Comment by royysz** [comment]
@Technoblazed captain pausing is not so important, captain only ready is.

**Comment by Technoblazed** [comment]
So that would be the .forceready then yes?

**Comment by royysz** [comment]
something like that, but not on scrim, on a normal match.
@Technoblazed

**Comment by Technoblazed** [comment]
.forceready is on both, having captain only .ready is pointless because it was recently changed to per client.

**Comment by royysz** [comment]
I have it on my version?  0.4.1-dev+239

**Comment by splewis** [comment]
I don't think I'm going to ever add this.
