### ISSUE TITLE
Using Get5 in a scrimming service

### ISSUE THREAD

**Issue by n9986** [splewis/get5#581]
I understand that this is not a get5 bug but I was not able to locate an alternate appropriate place I could ask about this. 

I am currently attempting to build a scrimming service, very similar to PopFlash, for my country (we do not have a great ecosystem for this and would like to bring something to players here that gives them a good platform to play on 128 tick servers with their friends). I was initially going to automate this using a bunch of plugins and RCON. However, Get5 turned out to be a game changer and found it to be a very amazing for setting up automated matches (exactly as the what the project description says). 

However, before using it, I would like to ask the author(s) about the statement in the README:

> **No, it is not recommended for your new matchmaking service. It is intended for competitive play, not pickup games.**

I wanted to make sure if this is not to discourage developers like me using Get5 in their commercial projects. Would it be inappropriate to use this even if full credit to the plugin was given along appropriate links and documentation? Lastly, does this project have a roadmap for donation based contributions?

I apologize if this was an inappropriate question. I simply did not want to go ahead and integrate something into my project against the original author(s) wishes. And thank you for the great effort and a great plugin.

**Comment by splewis** [comment]
What you described is a pretty reasonable use of get5 (giving credit isn't strictly necessary either - but  it's appreciated :) ). 

>  Lastly, does this project have a roadmap for donation based contributions?

Unfortunately, no. But the community has gotten more active with contributions in the last year or so (probably related to the decline in # of my own contributions!)

**Comment by n9986** [comment]
Thank you so much for your reply! Coming from an open source background, credit is a must where credit is due.

I will keep the Get5 community updated about my service's progress (if I do succeed in making it) and look for other ways to contribute (documentation/code). Cheers!

**Comment by saintplay** [comment]
@n9986 I did this in my country for the same reason, and I'm running ~1000 monthly 128ticks 5vs5 matches without problems thanks to get5 (literally zero bugs reported from plugin)!
Thanks @splewis !

Although I had to write other plugins, backend, services to make the scrim service fully automatic (demos, stats, discord integration, admin panel, etc)

If you need any help, you can email me. I will be glad to help!

**Comment by n9986** [comment]
@saintplay That is wonderful to know! And also very encouraging to push me further to complete this work. :)

And many thank you for the offer to help. Is there a discord channel you have that I can hang around in?

**Comment by saintplay** [comment]
Not really, but this is my discord `SaintPlay#3267`
