### ISSUE TITLE
How to change other team name when using the default schema

### ISSUE THREAD

**Issue by minim0vz** [splewis/get5#582]
Hello, i use get5 for team practice and the team practice at least against 4 different teams a day and we don't have time or energy to be doing team file for everyone of them, is there a way i can change the name of the other scrims teams on the fly, they are always tagged as Away, the usual csgo cvar for changing team names doesn't change the name on the plugin, when the score shows in the chat at the end of the round it remains as Away.

**Comment by TandelK** [comment]
@minim0vz  Are the teams exactly same always ? 
If yes you can create a predefined CFG/JSON file for it and add the path of those Team JSON path from loadfile option in server config. Just require to change Team File Names. It is exactly defined here. 
https://github.com/splewis/get5/wiki/Managing-match-configs

In this you would be clearly able to see that it has predefined teams cfg pre created so just need to edit 1 or 2 characters in config file

**Comment by VictorABoye** [comment]
It sounds like you're using the !scrim command. In which case it's pretty easy to configure away team name. 

The !scrim command can take two arguments: !scrim (away team name) (map) 

Example: !scrim Astralis de_mirage
This would set the map to mirage and Away team name to Astralis.

More settings for scrims can be found in the wiki under 'using get5 for scrims'

**Comment by splewis** [comment]
@VictorABoye  is correct. https://github.com/splewis/get5/wiki/Using-get5-for-scrims#starting-the-match mentions the optional arguments for the `get5_scrim` command.
