### ISSUE TITLE
Add serverid & ip:port into mysqlstats data

### ISSUE THREAD

**Issue by RuneNyhuus** [splewis/get5#584]
Hey

Is it possible to somehow make it type the IP / Hostname into the Mysql_stats?
Im runninng multiple servers, but i have no way to identify what server is making the stats.
Would be nice if it could write IP or Hostname into the table in the mysql.

I know many would say make different databases for each server, and yes i could do that.
But im deploying alot of servers all the time, so if i could deploy all with the same sql settings.

I see this options in the get5.cfg
// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "0"

But it do not write that server_id into the sql

Or maybe there is another way for this?

**Comment by emil6156** [comment]
+1..
Im struggling with exact the same thing.

**Comment by the-jomper** [comment]
Me to.

**Comment by VictorABoye** [comment]
I've been looking into this, though I haven't used sourcepawn before. But I have a question for you guys before I continue: 
Would it be preferred to have IP, Hostname or the get5_server_id?

Also just a note, it looks like the max amount of arguments have been reached for the get5_stats_players table, atleast in the sql plugin file. I think it would be better if someone more adept at SourcePawn would look at that. 
Therefore, I would only be able to add identifiers to get5_stats_maps and get5_stats_matches. Which I am looking into adding.

**Comment by RuneNyhuus** [comment]
> I've been looking into this, though I haven't used sourcepawn before. But I have a question for you guys before I continue:
> Would it be preferred to have IP, Hostname or the get5_server_id?
> 
> Also just a note, it looks like the max amount of arguments have been reached for the get5_stats_players table, atleast in the sql plugin file. I think it would be better if someone more adept at SourcePawn would look at that.
> Therefore, I would only be able to add identifiers to get5_stats_maps and get5_stats_matches. Which I am looking into adding.

IP or get5_server_id would be preferred.
If its possible to get get5_server_id into get5_stats_maps or get5_stats_matches, it would be totally fine for me.

**Comment by splewis** [comment]
I'm fine with adding both `get5_server_id` and a 'host:ip' into the `get5_stats_matches` table. PRs welcome. I don't think it's worthwhile to add it to the other tables, so the max-arg limit shouldn't be an issue.

**Comment by RuneNyhuus** [comment]
Hey @splewis can you write here when the feature is added... Looking forward to it!! 👍

**Comment by nickdnk** [comment]
Getting the server IP or hostname seems to be a little complicated and/or unreliable. Why? Because the hostname can be many things and unless explicitly defined for the srcds process it might be wrong (if it's a reverse lookup for instance). The same goes for IP, unless there's an API from SourceMod that reliably returns the WAN IP and not just the interface the process is bound to (which may be 0.0.0.0) or the local IP. I can't find documentation for that though.

Adding the `get5_server_id` parameter, however, is easy though and I can make a PR for that in no time. What say ye, @RuneNyhuus ?

**Comment by RuneNyhuus** [comment]
> Getting the server IP or hostname seems to be a little complicated and/or unreliable. Why? Because the hostname can be many things and unless explicitly defined for the srcds process it might be wrong (if it's a reverse lookup for instance). The same goes for IP, unless there's an API from SourceMod that reliably returns the WAN IP and not just the interface the process is bound to (which may be 0.0.0.0) or the local IP. I can't find documentation for that though.
> 
> 
> 
> Adding the `get5_server_id` parameter, however, is easy enough and I can make a PR for that in no time. What say ye, @RuneNyhuus ?

Get5_server_id would be awesome too.. Iam setting the serverid in get5 config anyway so thats good!
And thank you.

**Comment by nickdnk** [comment]
Should work, but according to https://github.com/splewis/get5/issues/673 it does not. Closing and will track there.
