### ISSUE TITLE
Suggest using gitbook.com has a documentation management tool

### ISSUE THREAD

**Issue by ericstgo87** [splewis/get5#586]
Hi guys, 

I've seen it's quite a struggle to maintain the documentation using the github Wiki functionality as it is not possible to send pull request. 
There is a solution to this issue, it would be to create a separate github repository containing all the documentation and then link the repository to the gitbook.com free solution. 

Hope this makes sense ;)

Have a good day

**Comment by nickdnk** [comment]
I just discussed this with splewis and agree that a better solution for documentation is required.

**Comment by Drarig29** [comment]
Mkdocs could be a nice idea too, in this repo or another one (maybe `get5-docs`). This can be hosted on GitHub Pages.

Here is a documentation I'm making right now (it's still under construction). It uses the Material theme for mkdocs: https://drarig29.github.io/brackets-docs/

**Comment by nickdnk** [comment]
@ericstgo87 Couldn't we have the docs be part of *this* repo and just set up a GitHub webhook to deploy it on some free service? I would prefer that PRs have documentation changes in them.
