### ISSUE TITLE
[bug] map wont change on config load if match canceled

### ISSUE THREAD

**Issue by penalte** [splewis/get5#588]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Allways change the map to the one in config

### Actual behavior
If a match is canceled mid game the server stays on that canceled match then when new match config is loaded the server wont change to the map in config, it needs a manual change.

### Steps to reproduce

start a match from a config after the config is loaded and map has changed cancel the match and load a new match config with a diferent map, it will load the new match config but not change to the new map.

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.2-dev+505
- Sourcemod version: 1.10 - build 6499:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
> Steps to reproduce (please be specific):

Can you provide specific commands/configs for this?

**Comment by penalte** [comment]
Sorry splewis i forgot to update this, it was steamworks and a cache bug.
