### ISSUE TITLE
Add a command to add the last player that was kicked

### ISSUE THREAD

**Issue by Drarig29** [splewis/get5#589]
As an admin, sometimes I need to add players with `get5_addplayer`.

I can run RCON commands from my webpanel but I need to look at the server logs to find the last player that was kicked with reason "You are not a player in this match" and copy paste his SteamID and his name.

It would be cool to have a command `get5_addkickedplayer <team1|team2|spec>`.

I don't think a command `get5_lastkickedplayer` would be useful because we would still need to copy paste the result and use it with `get5_addplayer`.

I think this should be implemented in get5 because it's the only plugin to know *why* the player is being kicked (not a player in this match) and get5 could easily remember the SteamID and the name of the last kicked player.

I would make a PR on this.

**Comment by splewis** [comment]
That's a great idea, a PR for that would be great.
