### ISSUE TITLE
Requestion of natives: Get all offline players, force change GameState

### ISSUE THREAD

**Issue by PreFix** [splewis/get5#59]
Requestion of natives: offline players , force change GameState

**Comment by splewis** [comment]
Force changing game state probably won't be happening. 

Adding a native to get all the info loaded for a team is more likely than anything that specific, i.e. something like
```
native void Get5_GetTeamInfo(
    MatchTeam team, 
    char[] name, int nameLength, 
    char[] flag, int flagLength, 
    char[] logo, int logoLength,
    ArrayList players);
```

and you'd be able to do a normal check of whether they are in-game or not for the players.

**Comment by ayushgarg39** [comment]
is it possible to add a command "team_status" for this ? like it shows the players status of the team as online/online.

**Comment by PreFix** [comment]
I need these because I want to make like competive, if players don't get shown up in specific time they all get kicked out and game is "finished"

**Comment by PreFix** [comment]
#60

**Comment by jfkz** [comment]
@PreFix 

> I need these because I want to make like competive, if players don't get shown up in specific time (warmup round) they all get kicked out and game is "finished".

Could `get5_time_to_start` var help you?

**Comment by PreFix** [comment]
Quite strange it doesn't work like this
![image](https://cloud.githubusercontent.com/assets/1775218/18607531/5f3c1cfc-7cd7-11e6-84df-cf62b5e0f941.png)

**Comment by jfkz** [comment]
This code works for me (on the latest version of plugin):
```
"cvars":{  
      "hostname":"Match #1",
      "get5_live_cfg":"esl5on5.cfg",
      "get5_autoload_config":"get5/warmup.cfg",
      "get5_warmup_cfg":"get5/warmup.cfg",
      "get5_time_to_start":300
}
```

**Comment by PreFix** [comment]
@jfkz You are using WEB Api or something else?

**Comment by jfkz** [comment]
@PreFix 
Yeah, I use SteamWorks plugin to get remote json. (command is `get5_loadmatch_url myserver.com/path_to_json`)

**Comment by PreFix** [comment]
I have it like this. http://pastebin.com/EMr4ZCpB 
But still

> find et5_time_to_start
"get5_time_to_start" = "0"

**Comment by jfkz** [comment]
@PreFix
Same. Try to update plugin. It was realised about 1.5 month ago.

**Comment by PreFix** [comment]
@jfkz It's definetly latest version.

**Comment by jfkz** [comment]
@PreFix
Well, I have no idea )

**Comment by splewis** [comment]
If there's an issue with cvars not being executed you can file a bug for that. There was one in the past. As always, an actual version is much more useful than "latest version".

> I need these because I want to make like competive, if players don't get shown up in specific time (warmup round) they all get kicked out and game is "finished". Idk what kind of alternatives u have. API means you should allow people to extend it without modifying core plugins... I don't really low to modify core plugin to get it properly working.

By "competitive", you mean a matchmaking system. Right now, this plugin isn't designed for this kind of use and may be unsuitable. I'm not opposed to that use, but it's not a priority for me.

**Comment by splewis** [comment]
Closing since there's been no followup and the original request wasn't given any motivation.
