### ISSUE TITLE
Demo won't record first game

### ISSUE THREAD

**Issue by agrais** [splewis/get5#594]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Every scrim is recorded.

### Actual behavior
The first scrim after loading/reloading a map won't record a demo. I am 100% sure it has nothing to do with overwriting due to demos having the same name.

### Steps to reproduce
Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: 1.10.0.6499
- Steps to reproduce (please be specific):

Step 1: I write ".map <mapname>" in chat, to change or reload the map.
Step 2: I write "get5_scrim" in console to create a scrim.
Step 3: I write "get5_forceready" in console to start the scrim.
Step 4: I check if a demo is recording - it is **NOT recording** at this point.
Step 5: I write "get5_endmatch" in console to end the current scrim.
Step 6: I write "get5_scrim" in console to create a new scrim.
Step 7: I write "get5_forceready" in console to start the new scrim.
Step 8: I check if a demo is recording - this time it **IS recording**.

At this point I can repeat step 5-8 as many times as I want and as long as I don't repeat step 1, it will record a demo of every single scrim.

### Existing issue
I realize someone else has already created a similar issue to this one, but it is from back in July and the above section wasn't filled out.

Link to the existing issue: https://github.com/splewis/get5/issues/550

**Comment by MikkelDK** [comment]
Do you have GOTV enabled?

I don't have seen this error before. ;/

**Comment by agrais** [comment]
> Do you have GOTV enabled?
> 
> I don't have seen this error before. ;/
> 
> Get5 will first start recording (via GOTV), so soon match is started.

I do have GOTV enabled. As I documented, demos are recorded succesfully as long as it isn't the first scrim after loading a map. Does it make sense?

**Comment by agrais** [comment]
I just did some more testing and I found out the issue was tv_autorecord was enabled.

I guess the reason is that get5_scrim can't record a demo when one is already being recorded. get5_endmatch will end the current demo and then the 2nd time I issue get5_scrim it will be allowed to start a new demo.
