### ISSUE TITLE
FAILED TO LOAD MATCH CONFIG CANT CREATE MATCH ON GET5 WEB

### ISSUE THREAD

**Issue by elayscs** [splewis/get5#595]
cant create match on get5 web
failed to load match config

help me pls

[get5.smx] Failed to load match config: Failed to create HTTP GET request
Failed to load match config.

**Comment by MikkelDK** [comment]
Did you enable get5-apistats file?

**Comment by elayscs** [comment]
> Did you enable get5-apistats file?

![image](https://user-images.githubusercontent.com/74987492/100144736-6996fa00-2ec1-11eb-8c5d-9b25e1c8b51c.png)

**Comment by Drarig29** [comment]
Did you install SteamWorks ?

**Comment by elayscs** [comment]
> Вы установили SteamWorks?

[SM] Listing 21 plugins:
  01 "Sound Commands" (1.10.0.6499) by AlliedModders LLC
  02 "Fun Votes" (1.10.0.6499) by AlliedModders LLC
  03 "Basic Ban Commands" (1.10.0.6499) by AlliedModders LLC
  04 "Admin Help" (1.10.0.6499) by AlliedModders LLC
  05 "Fun Commands" (1.10.0.6499) by AlliedModders LLC
  06 "Admin Menu" (1.10.0.6499) by AlliedModders LLC
  07 "Get5 Web API Integration" (0.7.2-dev+505) by splewis
  08 "Basic Commands" (1.10.0.6499) by AlliedModders LLC
  09 "Player Commands" (1.10.0.6499) by AlliedModders LLC
  10 "Client Preferences" (1.10.0.6499) by AlliedModders LLC
  11 "Basic Info Triggers" (1.10.0.6499) by AlliedModders LLC
  12 "Get5" (0.7.1) by splewis
  13 "Gloves" (1.0.3) by kgns | oyunhost.net
  14 "Nextmap" (1.10.0.6499) by AlliedModders LLC
  15 "Reserved Slots" (1.10.0.6499) by AlliedModders LLC
  16 "Basic Chat" (1.10.0.6499) by AlliedModders LLC
  17 "Admin File Reader" (1.10.0.6499) by AlliedModders LLC
  18 "Basic Comm Control" (1.10.0.6499) by AlliedModders LLC
  19 "Weapons & Knives" (1.7.0) by kgns | oyunhost.net
  20 "Basic Votes" (1.10.0.6499) by AlliedModders LLC
  21 "Anti-Flood" (1.10.0.6499) by AlliedModders LLC
yes i install steamwork

**Comment by elayscs** [comment]
do i need to use apistats and mysqlstats or i need only one of this?

**Comment by Drarig29** [comment]
From the webpanel documentation :

> Note: when using this web panel, the CS:GO game servers must be have both the core get5 plugin and the get5_apistats plugin. They are released together. This means the server must also be running the Steamworks and SMJansson extensions.

So, yes, apistats is needed, while mysqlstats is not.

**Comment by elayscs** [comment]
i dont have smjansson
i will download it now

**Comment by elayscs** [comment]
i downloaded smjansson
but i still have this error
![image](https://user-images.githubusercontent.com/74987492/100147856-1f644780-2ec6-11eb-823f-4af97186427c.png)

**Comment by elayscs** [comment]
@splewis

**Comment by elayscs** [comment]
@Drarig29 can u help me bro? : D

**Comment by MikkelDK** [comment]
No reason to tagging people.

Btw.
what site are you using to create a match?

**Comment by Drarig29** [comment]
Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc

In this folder : `addons/sourcemod/scripting/include`

**Comment by elayscs** [comment]
> No reason to tagging people.
> 
> Btw.
> what site are you using to create a match?

ok bro :D

**Comment by elayscs** [comment]
![image](https://user-images.githubusercontent.com/74987492/100149638-b3371300-2ec8-11eb-9d38-3a57b498e2fe.png)


> Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
> 
> In this folder : `addons/sourcemod/scripting/include`

**Comment by elayscs** [comment]
> No reason to tagging people.
> 
> Btw.
> what site are you using to create a match?

https://get5.splewis.net/match/create

**Comment by Drarig29** [comment]
Maybe the website doesn't work... find the ID of your match and go to this URL :

`https://get5.splewis.net/match/<matchid>/config`

Check that the page contains the JSON config.

**Comment by elayscs** [comment]
> https://get5.splewis.net/match/<matchid>/config

![image](https://user-images.githubusercontent.com/74987492/100150362-aebf2a00-2ec9-11eb-84e5-5d12ff166c16.png)

**Comment by Apfelwurm** [comment]
How does your get5_loadmatch_url command looks? Did you call it with http:// or https:// in front? if thats the case you have to put it in quotation marks like get5_loadmatch_url "https://get5.splewis.net/match/config"

**Comment by elayscs** [comment]
> Как выглядит ваша команда get5_loadmatch_url? Вы вызывали его с http: // или https: // впереди? если это так, вы должны заключить его в кавычки, например get5_loadmatch_url " https://test.test.net/testconfig "

i dont understand bro

**Comment by Drarig29** [comment]
Actually, I think he's using the webpanel to load the config, and the code is removing `http://` and `https://` :

https://github.com/splewis/get5-web/blob/8c1012c9563583353b9486a6590227855547e275/get5/models.py#L349-L353

**Comment by Drarig29** [comment]
Are you using the webpanel to load the config too ? Or are you trying to do `get5_loadmatch_url` manually via the RCON?

**Comment by elayscs** [comment]
> Are you using the webpanel to load the config too ? Or are you trying to do `get5_loadmatch_url` manually via the RCON?

i just added server to webpanel and trying to create match

**Comment by elayscs** [comment]
![image](https://user-images.githubusercontent.com/74987492/100151398-483b0b80-2ecb-11eb-876f-a5b9e937ef63.png)
i tried console

**Comment by Apfelwurm** [comment]
> Actually, I think he's using the webpanel to load the config, and the code is removing `http://` and `https://` :
> 
> https://github.com/splewis/get5-web/blob/8c1012c9563583353b9486a6590227855547e275/get5/models.py#L349-L353

oh, i have never used it, so i didnt knew it supports direct rcon usage :D okay, if its removing the http(s) it should be not be our addition which breaks the whole thing.

**Comment by Apfelwurm** [comment]
> ![image](https://user-images.githubusercontent.com/74987492/100151398-483b0b80-2ecb-11eb-876f-a5b9e937ef63.png)
> i tried console

can you enable debugging please with 

get5_debug 32

https://github.com/splewis/get5/wiki/Debugging-help

**Comment by Drarig29** [comment]
Yes, I knew you were thinking about your addition, but actually, he's using the latest release. So there isn't our changes yet 😉

**Comment by Drarig29** [comment]
I would try a clean install of your servers. Maybe they are not up to date and SteamWorks isn't working fine.

The error you are getting comes from these lines:

https://github.com/splewis/get5/blob/8bfb326fae1822ddae80a4844808d42c5ea826b3/scripting/get5/matchconfig.sp#L216-L220

Clearly, the problem comes from SteamWorks. Maybe you have a conflict somewhere too.

**Comment by elayscs** [comment]
> > ![образ](https://user-images.githubusercontent.com/74987492/100151398-483b0b80-2ecb-11eb-876f-a5b9e937ef63.png)
> > я попробовал консоль
> 
> Можете ли вы включить отладку с помощью
> 
> get5_debug 32
> 
> https://github.com/splewis/get5/wiki/Debugging-help

![image](https://user-images.githubusercontent.com/74987492/100151813-e929c680-2ecb-11eb-9dbe-bf55a7e0b275.png)
i tried but i think it doesnt worked

**Comment by elayscs** [comment]
> I would try a clean install of your CS:GO server. Maybe it's not up to date and SteamWorks isn't working fine.
> 
> The error you are getting comes from these lines:
> 
> https://github.com/splewis/get5/blob/8bfb326fae1822ddae80a4844808d42c5ea826b3/scripting/get5/matchconfig.sp#L216-L220
> 
> Clearly, the problem comes from SteamWorks. Maybe you have a conflict somewhere too.

what could it be?

**Comment by Drarig29** [comment]
> i tried but i think it doesnt worked

It should have made it work but now we have logs.

Could you please dump your `addons/sourcemod/logs/get5_debuginfo.txt` file?

**Comment by Apfelwurm** [comment]
> Yes, I knew you were thinking about your addition, but actually, he's using the latest release. So there isn't our changes yet

oh, didnt saw that version. 



> > I would try a clean install of your CS:GO server. Maybe it's not up to date and SteamWorks isn't working fine.
> > The error you are getting comes from these lines:
> > https://github.com/splewis/get5/blob/8bfb326fae1822ddae80a4844808d42c5ea826b3/scripting/get5/matchconfig.sp#L216-L220
> > 
> > Clearly, the problem comes from SteamWorks. Maybe you have a conflict somewhere too.
> 
> what could it be?

Please post the content of the Log file please.

You can also try to use the recent developer Version of get5 (http://ci.splewis.net/job/get5/lastSuccessfulBuild/)

**Comment by elayscs** [comment]
> > я пробовал, но думаю, что это не сработало
> 
> Это не должно было заставить его работать, но теперь у нас есть логи.
> 
> Не могли бы вы сбросить свой `addons/sourcemod/logs/get5_debuginfo.txt`файл?

[get5_debuginfo.txt](https://github.com/splewis/get5/files/5592789/get5_debuginfo.txt)

**Comment by Apfelwurm** [comment]
first, please move the get5_mysqlstats.smx to the disabled Plugins

**Comment by elayscs** [comment]
> сначала переместите get5_mysqlstats.smx в отключенные плагины

already

**Comment by Apfelwurm** [comment]
then please delete your addons/sourcemod/logs/get5_debuginfo.txt, restart the cs server, issue the 
get5_debug 32
once again, test it once again and post the log content again

**Comment by Apfelwurm** [comment]
since your error is "Failed to create HTTP GET request"
there should be at least an log entry with 
"cleanedUrl (SteamWorks) = *"
if the debugging is enabled, which i can`t see at the Moment

**Comment by elayscs** [comment]
> затем удалите свои addons / sourcemod / logs / get5_debuginfo.txt, перезапустите сервер cs, снова выполните
> get5_debug 32
> , проверьте его еще раз и снова опубликуйте содержимое журнала

i delete my get5_Debuginfo and he is not creating again and tried to create match on get5 web panel
and it write in my console
![image](https://user-images.githubusercontent.com/74987492/100154872-7ff88200-2ed0-11eb-8e63-83b42dd9a78f.png)

**Comment by Apfelwurm** [comment]
really strange...
which archive of SteamWorks do you have used? is it possible you used the Windows version on a Linux Server or the other way around?
whats in your addons/sourcemod/extensions Folder?
which OS does your Server run?

**Comment by elayscs** [comment]
> really strange...
> which archive of SteamWorks do you have used? is it possible you used the Windows version on a Linux Server or the other way around?
> whats in your addons/sourcemod/extensions Folder?
> which OS does your Server run?

linux

**Comment by Apfelwurm** [comment]
Please show your addons/sourcemod/extensions Folder.
Is it a hosted gameserver or do you self host on a v/root/dedicated server?

**Comment by Drarig29** [comment]
> Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
> 
> In this folder : `addons/sourcemod/scripting/include`

Did you download **exactly** this file? Or did you just say you have a file of this name on your server?

**Comment by elayscs** [comment]
> > Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
> > In this folder : `addons/sourcemod/scripting/include`
> 
> Did you download **exactly** this file? Or did you just say you have a file of this name on your server?

yes exactly
 ill try to setup windows steamwork now

**Comment by Apfelwurm** [comment]
> > Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
> > In this folder : `addons/sourcemod/scripting/include`
> 
> Did you download **exactly** this file? Or did you just say you have a file of this name on your server?

correct me if i'm wrong but i thougt only that file is not enough because you also need the .so/.dll of steamworks?



> > > Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
> > > In this folder : `addons/sourcemod/scripting/include`
> > 
> > 
> > Did you download **exactly** this file? Or did you just say you have a file of this name on your server?
> 
> yes exactly
> ill try to setup windows steamwork now

Please Answer the questions... 
it makes no sense if you have a Linux server to setup the windows steamworks...

**Comment by elayscs** [comment]
> > Are you sure you have this file : https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
> > In this folder : `addons/sourcemod/scripting/include`
> 
> Did you download **exactly** this file? Or did you just say you have a file of this name on your server?

oh no i didnt download ur file i just have this file
and now i cant open ur link

**Comment by Drarig29** [comment]
> > Did you download **exactly** this file? Or did you just say you have a file of this name on your server?
> 
> correct me if i'm wrong but i thougt only that file is not enough because you also need the .so/.dll of steamworks?

Oh yes, actually you're right! This is only to build the plugin.

So, @elayscs please follow this instructions :

https://github.com/splewis/get5/wiki/Step-by-step-installation-guide#4-install-steamworks-optional

**Comment by Apfelwurm** [comment]
Yes and please make sure you know what type of Server you are running (Windows or Linux !) and choose the right package!

**Comment by elayscs** [comment]
> Yes and please make sure you know what type of Server you are running (Windows or Linux !) and choose the right package!

linux

**Comment by elayscs** [comment]
> > > Did you download **exactly** this file? Or did you just say you have a file of this name on your server?
> > 
> > 
> > correct me if i'm wrong but i thougt only that file is not enough because you also need the .so/.dll of steamworks?
> 
> Oh yes, actually you're right! This is only to build the plugin.
> 
> So, @elayscs please follow these instructions :
> 
> https://github.com/splewis/get5/wiki/Step-by-step-installation-guide#4-install-steamworks-optional
> 
> (If you haven't done it already.)

yes i do this already

**Comment by elayscs** [comment]
i have a question can i add steam id of players without web get panel?

**Comment by Drarig29** [comment]
You can with `get5_addplayer`. Please read the documentation and open an other issue if you have other questions.

**Comment by splewis** [comment]
I can't follow this thread. Please read the READMe file and open a specific issue if you have a specific problem - and please don't spam with all-caps titles.
