### ISSUE TITLE
Dead players can see enemies.

### ISSUE THREAD

**Issue by Tenderenden** [splewis/get5#598]
In "Live" phase of a match, dead players can see all the remaining players by default (probably "_mp_forcecamera_" is set to 0?).
Manually setting up the "_mp_forcecamera_" to 1 seems to resolve issue for the rest of the match.
I wonder if it's caused by wrong setup of configuration files or is it some kind of bug.

**Comment by MikkelDK** [comment]
I think it's because it's has been **set** to "mp_forcecamera 0", so you need to edit **live.cfg** and change it to: "mp_forcecamera 1"

**Comment by splewis** [comment]
There's nothing in get5 that touches that cvar by default, so you have another config file setting it. 

It's possible the default "casual" settings use `mp_forcecamera 0`, but I don't know for sure.

**Comment by sF0rman** [comment]
Doesn't the practice mod include some cvar for show all players on radar?

I had some issues with startmoney/respawning in live games if I forgot to switch off practice mode, and it could be you have other plugins that effect that (those) settings.

**Comment by nickdnk** [comment]
This is not related to get5 unless you modified your live server config.
