### ISSUE TITLE
Is it possible to add custom logo without web panel?

### ISSUE THREAD

**Issue by shayenek** [splewis/get5#599]
Hello!

I've tried everything, I've put my logo in both panorama and resources folders, made it 64x64, even installed an additional plugin - nothing works, can't get custom logos to work. Any idea on what I might be doing wrong?

Edit. I also wanted to ask if it's possible to add more stats or is the limit of 32 still a thing.

**Comment by lukasz922** [comment]
Hi 

You did it https://steamcommunity.com/sharedfiles/filedetails/?id=765964792

 i see you from Poland Me to maybe priv in help you

**Comment by splewis** [comment]
All get5 does is set the `mp_teamlogo_1` and `mp_teamlogo_2` cvars. Have you tried debugging by just setting those manually? 

> Edit. I also wanted to ask if it's possible to add more stats or is the limit of 32 still a thing.

The mysql stats plugin is limited to 32 at this point. The core get5 plugin can handle plenty more stats.

**Comment by nickdnk** [comment]
> All get5 does is set the `mp_teamlogo_1` and `mp_teamlogo_2` cvars. Have you tried debugging by just setting those manually?
> 
> > Edit. I also wanted to ask if it's possible to add more stats or is the limit of 32 still a thing.
> 
> The mysql stats plugin is limited to 32 at this point. The core get5 plugin can handle plenty more stats.

@shayenek As discussed in my PR here, the limit for MySQL-stats is now 127: https://github.com/splewis/get5/pull/609

**Comment by nickdnk** [comment]
Likely not a get5 issue.
