### ISSUE TITLE
Let min_spectators_to_ready ignore spectators

### ISSUE THREAD

**Issue by Drarig29** [splewis/get5#600]
Currently, there is no way to ignore the ready status of the spectators. According to #127, this is the intended behavior.

https://github.com/splewis/get5/blob/1fc81566b045cad2ab0fc82fa2c7fa185ea9c371/scripting/get5/readysystem.sp#L70

This condition wants every player in the spectators team to be ready.

But I think it would be cool to be able to ignore readying from spectators. Sometimes we would like to be almost AFK as an admin spectator and let the actual players handle their readying.

There could be two possibilities to handle that:
- `min_spectators_to_ready 0` would ignore spectators because to my mind, "to need 0 players" means that we don't need any of them to ready up.
- `min_spectators_to_ready -1` would be better for emphasis and retrocompatibility because 0 is the default value.

As alwalys, I can do a PR.

**Comment by Drarig29** [comment]
What do you think about that @splewis?

Do you prefer 0 or  -1?

**Comment by splewis** [comment]
Thanks for elaborating on the 2 possibilities.  I'd vote for `min_spectators_to_ready 0`, because despite the backwards compatibility concern the behavior seems somewhat confusing otherwise. (The next version's changelog will call out the behavior change here, and hopefully be labelled 1.0.0...)
