### ISSUE TITLE
URGENT: Anonymous access on Jenkins dashboard

### ISSUE THREAD

**Issue by PiterPentester** [splewis/get5#605]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Can you elaborate on this? Anonymous *read* access is intentional - what specifically is the extra access? (feel free to email me at: sean at splewis . net)

**Comment by PiterPentester** [comment]
I can't find clear text passwords and you can use anonymous mode if you want but for better security practice you need to remove anonymous access.
For this project - you can leave this open)
