### ISSUE TITLE
Feature Request: Pausing Convars

### ISSUE THREAD

**Issue by dragonblade62** [splewis/get5#61]
I think that you should add pausing convars, such as 
1. Requiring both teams to confirm a pause to make it happen 
2. Pause duration
3. Pause limit per half

If this is already in there, then I just wasted about 2 minutes of my life typing this. 

Thanks

**Comment by splewis** [comment]
https://github.com/splewis/get5#convars

get5_max_pauses: maximum number of pauses a team can use, 0=unlimited
get5_max_pause_time: maximum number of time the game can spend paused by a team, 0=unlimited
get5_reset_pauses_each_half: whether pause limits are reset each halftime period (default 1)

Requiring both teams to start a pause isn't available, and doesn't really make sense to me.
