### ISSUE TITLE
Trade-kill time

### ISSUE THREAD

**Issue by nickdnk** [splewis/get5#610]
Hello

I've gathered some data over time with the MySQL-plugin, which works fine. However, the "trade-kill" stat seems to trigger _very_ infrequently, and looking at the code it appears a trade-kill can only happen within 1.5 seconds. People who have played around 15 matches have an average trade-kill stat of only 1-2 per game. That seems way too low to me to accurately represent how often players get trade-killed.

Should we increment this? It's currently shorter than the reload-time of all weapons, and a trade-kill could easily happen within 2-3 seconds in my opinion. Is 1.5 seconds a tried-and-true value? How did you arrive at this? I'm not blaming here at all, just asking for the reasoning behind it.

I only created an issue since the value is defined as a constant and not a variable: Declaring it as a variable so people can set their own would also be an easy solution.

https://github.com/splewis/get5/blob/013519d35135a750c157e9f5919232a538873c79/scripting/get5/stats.sp#L1

Cheers

**Comment by splewis** [comment]
It's a pretty arbitrary value. I'd be curious if there's a value used to detect in any other stats system (e.g. HLTV's 2.0 rating). I wasn't able to find one from a quick search.

I might be willing to increase it, but I'm not exactly sure how much. 3 seconds feels way too high, in my opinion. That's plenty of time for a player to reset their aim and take another 'fresh' engagement, hardly making it a trade.

> People who have played around 15 matches have an average trade-kill stat of only 1-2 per game.

What level of game are these from? It's my opinion there are actually very few trades in any random pug style game. I'm mostly interested in a stats system that makes sense for teamplay, where I would expect the # of trades to be higher. I'm open to being proven wrong here, though.

>  It's currently shorter than the reload-time of all weapons

I'd argue if you have to reload, it's not a "trade kill" in the sense with any immediacy of helping a teammate.

>  Declaring it as a variable so people can set their own would also be an easy solution.

I'd actually prefer to not make this a cvar for consistency reasons across different tournaments/events/etc. as much as possible.

**Comment by nickdnk** [comment]
> What level of game are these from? It's my opinion there are actually very few trades in any random pug style game. I'm mostly interested in a stats system that makes sense for teamplay, where I would expect the # of trades to be higher. I'm open to being proven wrong here, though.

Somewhere between MG and Global Elite in MM ranks. I think this might come down to the definition of a trade-kill as well.
> 
> > It's currently shorter than the reload-time of all weapons
> 
> I'd argue if you have to reload, it's not a "trade kill" in the sense with any immediacy of helping a teammate.

The point here being that if you reload because of a fight and someone pops out and kills you while the cutoff is less than the reload-time, you've been traded. No? Adding another 500ms would still keep it under that duration.

I just Google a bit and I can't find any definition of trade-kill duration, which does make sense as it _is_ difficult to define.

I agree that 3 seconds is high, but I don't think 2 is.

**Comment by sF0rman** [comment]
mentor.gg is a website that specifically tracks trade-kills and missed trade-kills. I believe scope.gg does the same. Could check what numbers they use.
