### ISSUE TITLE
Joining server when match is loaded

### ISSUE THREAD

**Issue by ErcouldnT** [splewis/get5#616]
Hello,

I want to players can join when there is already match setup on server. Is this possible?

**Comment by sF0rman** [comment]
I think you can just use this: 

get5_kick_when_no_match_loaded 0

**Comment by splewis** [comment]
This actually seems like a very common question for new users - so I'm considering flipping the default to 0 for that cvar. If anyone disagrees, let me know.

**Comment by Drarig29** [comment]
I'm OK with this 😁

**Comment by VictorABoye** [comment]
> I want to players can join when there is already match setup on server. Is this possible?

Assuming this isn't fixed by setting "get5_kick_when_no_match_loaded" to 0, since a match is loaded...
Have you set "get5_check_auths" to 0?

**Comment by sF0rman** [comment]
> This actually seems like a very common question for new users - so I'm considering flipping the default to 0 for that cvar. If anyone disagrees, let me know.

This sounds sensible. default to 0 is better for new users and anyone using it for leagues, online matchmaking services or whatnot would be expected to know more and able to read wiki/docs to configure. (Anyone should be able to read docs, but you know. Tech savvy people are more likely to read carefully)

**Comment by Apfelwurm** [comment]
I also think this change would make sense. If someone runs a productive get5 installation its most likely that the config is never the less explicitly set to the settings that are needed instead of relying on defaults that might change or might not.
