### ISSUE TITLE
Knife round in BO3 series on each map

### ISSUE THREAD

**Issue by ndstudios-admin** [splewis/get5#618]
### Expected behavior

On the first and second maps, teams get sides they chose on map veto

### Actual behavior

Knife round on each map

### Steps to reproduce

"Match"
{

	"maps_to_win"		"2"
	"skip_veto"		"1"
	"side_type"		"standard"
	"players_per_team"		"1"
	"matchid"   "001"
	
	"spectators" 
	{
		"players"
		{
		}
	}

"map_sides"
{
  "map1" "team1_ct"
  "map2" "team1_ct"
  "map3" "knife"
}
"maps"
{
  "de_mirage" ""
  "de_inferno" ""
  "de_vertigo" ""
}

	"players_per_team"		"1"
	"min_players_to_ready"		"1"
	"min_spectators_to_ready"		"0"

	"team1"
	{
		"fromfile"		"addons/sourcemod/configs/get5/team_nikitosoz8.cfg"
	}

	"team2"
	{
		"fromfile"		"addons/sourcemod/configs/get5/team_radygadash.cfg"
	}
	}

I've recorded that. https://youtu.be/ku8Wg4WNTgo

- Plugin version: developer get5-514
- Sourcemod version: 1.10.0.6502
- Steps to reproduce (please be specific): Run get5 on a server.

**Comment by VictorABoye** [comment]
Have you tried changing 'side-type' to 'always_knife' instead of standard?

**Comment by ndstudios-admin** [comment]
> Have you tried changing 'side-type' to 'always_knife' instead of standard?

But I don't need always knife. And the bot is not starting the game. I've recorded that

**Comment by VictorABoye** [comment]
Sorry, must've switched around the expected and actual behavior when reading:sweat_smile:

**Comment by ndstudios-admin** [comment]
L 01/19/2021 - 23:24:09: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:24:09: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:24:09: [SM]   [2] Line 208, ./scripting/get5/eventlogger.sp::EventLogger_ClientSay
L 01/19/2021 - 23:24:09: [SM]   [3] Line 593, ./scripting/get5.sp::OnClientSayCommand_Post
L 01/19/2021 - 23:24:21: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"
L 01/19/2021 - 23:24:21: [SM] Blaming: get5.smx
L 01/19/2021 - 23:24:21: [SM] Call stack trace:
L 01/19/2021 - 23:24:21: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:24:21: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:24:21: [SM]   [2] Line 112, ./scripting/get5/eventlogger.sp::EventLogger_KnifeStart
L 01/19/2021 - 23:24:21: [SM]   [3] Line 22, ./scripting/get5/kniferounds.sp::Timer_AnnounceKnife
L 01/19/2021 - 23:24:26: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"
L 01/19/2021 - 23:24:26: [SM] Blaming: get5.smx
L 01/19/2021 - 23:24:26: [SM] Call stack trace:
L 01/19/2021 - 23:24:26: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:24:26: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:24:26: [SM]   [2] Line 208, ./scripting/get5/eventlogger.sp::EventLogger_ClientSay
L 01/19/2021 - 23:24:26: [SM]   [3] Line 593, ./scripting/get5.sp::OnClientSayCommand_Post
L 01/19/2021 - 23:24:30: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"
L 01/19/2021 - 23:24:30: [SM] Blaming: get5.smx
L 01/19/2021 - 23:24:30: [SM] Call stack trace:
L 01/19/2021 - 23:24:30: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:24:30: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:24:30: [SM]   [2] Line 208, ./scripting/get5/eventlogger.sp::EventLogger_ClientSay
L 01/19/2021 - 23:24:30: [SM]   [3] Line 593, ./scripting/get5.sp::OnClientSayCommand_Post
L 01/19/2021 - 23:24:54: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"
L 01/19/2021 - 23:24:54: [SM] Blaming: get5.smx
L 01/19/2021 - 23:24:54: [SM] Call stack trace:
L 01/19/2021 - 23:24:54: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:24:54: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:24:54: [SM]   [2] Line 208, ./scripting/get5/eventlogger.sp::EventLogger_ClientSay
L 01/19/2021 - 23:24:54: [SM]   [3] Line 593, ./scripting/get5.sp::OnClientSayCommand_Post
L 01/19/2021 - 23:26:23: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"
L 01/19/2021 - 23:26:23: [SM] Blaming: get5.smx
L 01/19/2021 - 23:26:23: [SM] Call stack trace:
L 01/19/2021 - 23:26:23: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:26:23: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:26:23: [SM]   [2] Line 120, ./scripting/get5/eventlogger.sp::EventLogger_KnifeWon
L 01/19/2021 - 23:26:23: [SM]   [3] Line 57, ./scripting/get5/kniferounds.sp::EndKnifeRound
L 01/19/2021 - 23:26:23: [SM]   [4] Line 71, ./scripting/get5/kniferounds.sp::Command_Stay
L 01/19/2021 - 23:26:23: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"
L 01/19/2021 - 23:26:23: [SM] Blaming: get5.smx
L 01/19/2021 - 23:26:23: [SM] Call stack trace:
L 01/19/2021 - 23:26:23: [SM]   [0] LogToFileEx
L 01/19/2021 - 23:26:23: [SM]   [1] Line 25, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
L 01/19/2021 - 23:26:23: [SM]   [2] Line 208, ./scripting/get5/eventlogger.sp::EventLogger_ClientSay
L 01/19/2021 - 23:26:23: [SM]   [3] Line 593, ./scripting/get5.sp::OnClientSayCommand_Post
L 01/19/2021 - 23:26:40: [SM] Exception reported: Could not open file "/home/server2540/game/csgo//"

**Comment by splewis** [comment]
The root cause is your logging configuration. From the errors:
> Could not open file "/home/server2540/game/csgo//"

Get5 calls `LogToFileEx` for event logging, which will throw an exception on failures, and thus cancel the execution of the ongoing callback (e.g. client say, player death, map end, etc.).

For your case, you should disable event logging or fix the log path (`get5_event_log_format`).

A nice change to prevent this would to either:
- Sourcemod provides a better form of `LogToFileEx` that can return an error instead of an exception on IO errors. (preferred)
- Change event logging to use [WriteFileLine](https://sm.alliedmods.net/new-api/files/WriteFileLine), which won't throw exceptions on IO errors (2nd preferred option, the formatting should not change though).
- Change all get5 callers to run event logging *after* critical work is done. This is somewhat tricky to do in some of the callsites, and would be rather error prone.
