### ISSUE TITLE
want to spectate as admin but cant join the match

### ISSUE THREAD

**Issue by GTAmama16** [splewis/get5#619]
hey there so i was trying to join as Admin to spectate the match but it will just pop out say that "you are not a player in this match"
is there anyway to keep the current setting and join as admin to spectate the match ?

thanks !

**Comment by lukasz922** [comment]
Good Questions  I have same problems

**Comment by GTAmama16** [comment]
yeah btw im using the webpanel to create teams and starting the match

**Comment by Drarig29** [comment]
You can add yourself as a spectator with:

```
get5_addplayer "spec" "your_name" "your_steamid"
```

If you don't want to search for your steamid, you can use this **after being kicked**:

```
get5_addkickedplayer "spec" "your_name"
```

**Comment by GTAmama16** [comment]
thanks for the help guys !
