### ISSUE TITLE
Feature request: Technical Pause vs. tactical pause

### ISSUE THREAD

**Issue by dragonblade62** [splewis/get5#62]
I think a way to specify a technical pause and a tactical pause would be of immense value. For example, if someone suddenly disconnects on a team, and that team has already used its pause that half, then there is no way for either team to pause the game.

The command could be something like !Tpause or !TacPause or something else.
Convars could include:

get5_allow_technical_pause (Self explanatory)
get5_admin_confirm_technical_pause (Sets if a technical pause has to be confirmed by an admin)

Also, if a captain feature gets added to the game, and only captains are allowed to initiate pauses, another convar could be something like

get5_captain_initiate_technical_pause 

so anyone on a team can initiate a technical pause. 

In order to unpause the technical pause, I think the same !unpause command should be used to avoid further confusion.

**Comment by dragonblade62** [comment]
Splewis, what do you think on this matter?

**Comment by splewis** [comment]
Sounds fine to me.

**Comment by Technoblazed** [comment]
https://github.com/splewis/get5/pull/241

**Comment by Technoblazed** [comment]
Yay ┗(- _-)┛

**Comment by splewis** [comment]
Should've closed this when the above was merged.

Technical pauses via !tech are merged in now, controlled by the get5_allow_technical_pause cvar. See also: https://github.com/splewis/get5/wiki/Pausing
