### ISSUE TITLE
Anyway to record the demo in 64/128 ticks ?

### ISSUE THREAD

**Issue by GTAmama16** [splewis/get5#620]
hey guys so im just wondering is there anyway to record that demo in 64/128 ticks instead of 32 ticks ?
running my server on 128 ticks 

thanks for the help

**Comment by MikkelDK** [comment]
You need to add this to your gotv config.

`tv_snapshotrate 128` - this will record 128tick

**Comment by GTAmama16** [comment]
> You need to add this to your gotv config.
> 
> `tv_snapshotrate 128` - this will record 128tick

so i will just have to put this command in the server.cfg？

**Comment by MikkelDK** [comment]
> > You need to add this to your gotv config.
> > `tv_snapshotrate 128` - this will record 128tick
> 
> so i will just have to put this command in the server.cfg？

Example the way. - Yep.

**Comment by GTAmama16** [comment]
> > > You need to add this to your gotv config.
> > > `tv_snapshotrate 128` - this will record 128tick
> > 
> > 
> > so i will just have to put this command in the server.cfg？
> 
> Example the way. - Yep.

thanks man it work!!
