### ISSUE TITLE
Steam ID

### ISSUE THREAD

**Issue by xPatrykPlayX** [splewis/get5#628]
How to disable steam ID checking?

**Comment by Drarig29** [comment]
get5_check_auths 0

**Comment by ErcouldnT** [comment]
Is this a solution for players can connect while in match?

**Comment by Drarig29** [comment]
By default, you must specify each player's steamid who you want to be able to join.

You can disable that with `get5_check_auths 0`, and everyone will be able to join.

If you need to allow only specific players, you can use `get5_addplayer`.

**Comment by ErcouldnT** [comment]
get5_check_auths 0, and everyone will be able to join during the match is loaded?
