### ISSUE TITLE
Feature Request: A more advanced rating system (Such as the HLTV rating system)

### ISSUE THREAD

**Issue by dragonblade62** [splewis/get5#63]
While I think that this would be an interesting idea during the late stages of the plugin development, I do not think that this should be a priority. 
I think that the RWS system is not that advantageous because players can simply hunt for kills in situations that would put them as a disadvantage round-wise just because they want to increase their RWS.
Here is the page describing the HLTV rating system: http://www.hltv.org/?pageid=242

**Comment by splewis** [comment]
I don't plan on putting these stats in get5. HLTV rating can be computed from the counters the stats system already provides: https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L160

In fact, the hltv rating is already displayed on the get5-web interface: http://get5.splewis.net/match/3
