### ISSUE TITLE
Either get5 or get5_apistats plugin missing

### ISSUE THREAD

**Issue by FejkysS** [splewis/get5#631]
Hello,

I cant create match - Either get5 or get5_apistats plugin missing (This problem)

https://ctrlv.cz/shots/2021/02/09/nDfc.png

Sm Plugins list clear

https://ctrlv.cz/shots/2021/02/09/b3T6.png

**Comment by MikkelDK** [comment]
Did you install get5_apistats.smx? - it needs to be installed before it will work.

**Comment by FejkysS** [comment]
> Did you install get5_apistats.smx? - it needs to be installed before it will work.

It is not in Full plugin ?

**Comment by MikkelDK** [comment]
> It is not in Full plugin ?

It is on the "disabled" folder =)

**Comment by FejkysS** [comment]
> It is on the "disabled" folder =)

Cant finde.

**Comment by MikkelDK** [comment]
@FejkysS if you got it solved. remember to close the issue!

**Comment by FejkysS** [comment]
Sill not.
