### ISSUE TITLE
Damage Print isnt showing at the end of round.

### ISSUE THREAD

**Issue by bboychris168** [splewis/get5#632]
Damage print is currently set within the cvars to "1". But not showing anything within the match?. 
I am currently using the get5-520 latest build.

https://ci.splewis.net/job/get5/

**Comment by bboychris168** [comment]
Thanks to @MiguelNdeCarvalho as stated above the convar had to be set manually in the console to fix this issue.

**Comment by splewis** [comment]
> Thanks to @MiguelNdeCarvalho as stated above the convar had to be set manually in the console to fix this issue.

If that's true, it's a bug with the plugin. However, I really don't see any reason why this would be true, unless configured incorrectly.

**Comment by bboychris168** [comment]
Turns out the discord bot that we use to send the JSON to the game server was missing a quotation on the integer. So yeah it could most likely be on our end that caused this issue.
