### ISSUE TITLE
coach dead talk plugin

### ISSUE THREAD

**Issue by Flucky2** [splewis/get5#633]
I was wondering if I could have the link to the coach dead talk plugin

**Comment by splewis** [comment]
https://github.com/splewis/sm-misc/blob/master/scripting/csgo_hearcoach.sp. You could get a compiled version from https://ci.splewis.net/job/sm-misc/lastSuccessfulBuild/ (`addons/sourcemo/plugins/csgo_hearcoach.smx`).
