### ISSUE TITLE
DEMO VOICE CHATS

### ISSUE THREAD

**Issue by leeord** [splewis/get5#634]
Hello guys, 
I have noticed that the demos do not have audio communication between teams. How to change so that the audio is captured at the match? in PUGSETUP the demos have voice chat. I would like to do the same way

**Comment by MikkelDK** [comment]
It's gotv you need to check which commands.

**Comment by leeord** [comment]
I use 2 plugins to run the competition. The gotv configuration is in server.cfg ... in pugsetup.cfg you only have the option to record the demo or not. In get5, cfg shows the recording option but there is nowhere to set audio options. and what would these commands be?

**Comment by MikkelDK** [comment]
```
tv_relayvoice <0|1>
If enabled, allow player voice chat if broadcasted (master only)
```

**Comment by leeord** [comment]
i have found it on warmup.cfg. thanks very much for the help

**Comment by MikkelDK** [comment]
> i have found it on warmup.cfg. thanks very much for the help

@leeord remember to close the issue. ;)
