### ISSUE TITLE
Map Veto

### ISSUE THREAD

**Issue by realRapSi** [splewis/get5#635]
Hey splewis, just a quick question.
Is there a way to change the map veto order in the Best-of-Two system? We are running a different scheme and would need to change it.
Thanks and have a nice day

**Comment by splewis** [comment]
It's not configurable. Only the format at https://github.com/splewis/get5/wiki/Map-Vetoes#bo2-veto is supported.

What order do you want? It might be easy enough to add a config option to allow it.

**Comment by realRapSi** [comment]
new order would be: Team 1 bans 1 map, Team 2 bans 2 maps, Team 1 bans 1 map, Team 2 picks 1. map and Team 1 picks 2nd map. 
Basically A-B-B-A bans and B-A picks.

**Comment by lehmanner** [comment]
That'd actually be great :D  aaaaand hi @realRapSi ;)

**Comment by nickdnk** [comment]
Duplicate of https://github.com/splewis/get5/issues/643
