### ISSUE TITLE
Load Match From URL

### ISSUE THREAD

**Issue by MypowerHD** [splewis/get5#636]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
via the command get5_loadmatch_url, specify url plugin starts automatically

### Actual behavior
after enter the command per rcon, i become only the correct plugin output.
`

] get5_loadmatch_url https://10er.beast-vision.de/match/loadmatch/7210b752-9cf1-48b1-aa15-1b59a43fbd95
[get5] cleanedUrl (SteamWorks) = http://https:
Match config loading initialized.
L 02/25/2021 - 07:44:28: rcon from "178.202.210.229:59343": command "get5_loadmatch_url https://10er.beast-vision.de/match/loadmatch/7210b752-9cf1-48b1-aa15-1b59a43fbd95"

`

### Steps to reproduce
-Plugin version: 0.7.2-dev+520
-sourcemod_version = 1.10.0.6502
-metamod_version = 1.10.7-devV
-get5 git commit: 358a67a

- Steps to reproduce (please be specific):
you can easy use following command "get5_loadmatch_url https://10er.beast-vision.de/match/loadmatch/7210b752-9cf1-48b1-aa15-1b59a43fbd95"

**Comment by Drarig29** [comment]
I think if you surround your URL with quotation marks it will work.

Example : `get5_loadmatch_url "https://10er.beast-vision.de/match/loadmatch/7210b752-9cf1-48b1-aa15-1b59a43fbd95"`

**Comment by MypowerHD** [comment]
> I think if you surround your URL with quotation marks it will work.
> 
> Example : `get5_loadmatch_url "https://10er.beast-vision.de/match/loadmatch/7210b752-9cf1-48b1-aa15-1b59a43fbd95"`

oh wow 👍  worked
