### ISSUE TITLE
Feature Request: Additional Warmup on Team Switch

### ISSUE THREAD

**Issue by dragonblade62** [splewis/get5#64]
Forgive me if I am wrong, but I don't think this is implemented in get5 as of right now. 
This would be similar to something like the CEVO plugin.

**Comment by splewis** [comment]
Most likely not going to happen.

Letting it be frozen at the halftime screen until a 2nd ready up might (there's a cvar for it, I don't remember it off the top of my head), but not resetting back to a warmup period and restoring.

**Comment by Technoblazed** [comment]
`mp_halftime_pausetimer`
Set to 1 to stay in halftime indefinitely. Set to 0 to resume the timer.

**Comment by splewis** [comment]
Closing this, I don't expect this to ever be added.
