### ISSUE TITLE
[Feature Request] Veto Setup

### ISSUE THREAD

**Issue by BlackYuzia** [splewis/get5#643]
Hi there.
I saw #635 and I think what if we create setup for veto steps?

Like:

```jsonc
{
    "veto_settings": [
        "ban_team_A",  // first ban from A team...
        "ban_team_B",  // first ban from B team...
        "ban_team_B",
        "ban_team_A",
        "pick_team_A", // first pick from A team...
        "pick_team_B", // first pick from B team...
        "ban_team_A",
        "ban_team_B",
        "last_map"     // should play latest (random) map
    ],
    "veto_mode": "bo3" // custom mode for bo3
}
```

**Comment by Drarig29** [comment]
Good idea!

What would be the purpose of `veto_mode`? There is already `num_maps` in case you didn't know (which is an odd number or 2).

And good luck trying this, personally I gave up when I saw the number of "hacks" in the veto controller 😂
Also, don't forget the size of the map pool isn't static and it is always odd. This was my two cents.

**Comment by BlackYuzia** [comment]
> What would be the purpose of veto_mode? There is already num_maps in case you didn't know (which is an odd number or 2).

This is if you setup in match config `bo3` and create custom `veto_settings`, plugin should use your custom setup. But, if this is possible, we can create `veto_settings` for a few count of maps. Like: For 6 maps, 7 maps, 9 maps etc.

**Comment by Drarig29** [comment]
Why not just check if `veto_settings` is defined, and use it if it is?

**Comment by BlackYuzia** [comment]
> Why not just check if veto_settings is defined, and use it if it is?

What if you want create a few settings? Like, one for bo3, one for bo5 and etc...

**Comment by Drarig29** [comment]
Yes, you are perfectly right, but I just don't see what additional information it gives... 

I think everything you need is given with the combination of `num_maps` and `veto_settings` 😊

**Comment by BlackYuzia** [comment]
I repeat. What if you want a few templates? :eyes: 
You can change them by one line.

**Comment by Drarig29** [comment]
Ok. Let's wait for @splewis's opinion 😁

**Comment by lehmanner** [comment]
I'd actually apreciate a feature like this too :D

**Comment by splewis** [comment]
I'd be very open to supporting more generic veto formats, as long as it's backwards compatible (i.e. not specifying these values keeps existing behavior).

You'd probably end up rewriting most of the veto code, but it's not very clean code anyway, so I wouldn't be intimidated by it. It's a relatively small section of code.

**Comment by nickdnk** [comment]
I'll rewrite the veto code the be fully dynamic (as suggested in this original issue). It will then be up to the player to provide a valid set of pick/ban options based on the the number maps in the series, clinch configuration and maps in the pool. If it's invalid, it just won't load.

**Comment by nickdnk** [comment]
Check this out: https://github.com/splewis/get5/pull/962
