### ISSUE TITLE
[Bug] Pausing During Warmup Countdown To Knife

### ISSUE THREAD

**Issue by PhlexPlexico** [splewis/get5#647]
### Expected behavior
When you're calling a timeout during the warmup countdown after both teams `!ready`, it should either not subtract total timeouts, or queue a timeout going into the next state.

### Actual behavior
As soon as the warmup countdown starts (and gamestate changes right before the countdown), if any team calls a `!pause`, it will subtract from their total pauses they have for the half/game, but will not pause the game. 

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.2-dev-358a67a
- Sourcemod version: 1.10
- Steps to reproduce (please be specific):
    - Create a match, get both teams to ready up. Have a predetermined set time for pause, as well as a total amount of pauses.
    - During the warmup countdown once everyone is ready, have a team type `!pause`.
    - Their total pauses will be subtracted by one, but no timeout will occur in the next gamestate.

**Comment by nickdnk** [comment]
@PhlexPlexico Could we not just disable pause during countdown? You can just !pause in the freezetime right after.

**Comment by PhlexPlexico** [comment]
Yup! That is definitely a viable fix for this. Another check that could fix it is to adjust the function here - 

https://github.com/splewis/get5/blob/8ffecad946c8206494fdd3ca856d37d1394f1757/scripting/get5/pausing.sp#L1-L3

But just disabling pausing during countdown from warmup works just as well IMO, I forgot I had reported this haha

**Comment by PhlexPlexico** [comment]
So I was looking at previous tickets here to see if there's anything that can be fixed easily - and ran into this https://github.com/splewis/get5/issues/274

So I guess this is a duplicate issue, and it appears pausing during knife round is intended. But we need to do an additional check I think to see if  maybe something as simple as checking if we are currently in Get5State_GoingLive and making sure we don't fire off the pause events to avoid this bug.

**Comment by nickdnk** [comment]
I think we should just disable pausing during this stage and people can just do it in the freezetime on round one. There's no reason to add complexity to the pausing system when this can be solved by just telling people to wait for the game to start.
