### ISSUE TITLE
Able to test a match without filling players

### ISSUE THREAD

**Issue by williamweckl** [splewis/get5#655]
Is there a way to test a match without filling all 10 players? I'm asking because I'm constantly changing some get5, other plugins and server configurations and would be nice to test it before run any real match.

Today when I need to test something, I usually ask for some friends to help me, but is not so easy to join 9 friends together that have the patience to help me with what I need.

I've tried to fill the server with bots, but for some reason, when I join the server, all the bots goes to the opposite team. I was tryng to fill the server with 9 bots + me and force ready. It didn't work.

**Comment by MikkelDK** [comment]
I mean there is a forcestart command. Did you try that out?

And yeah forceready will not work, if there is only bots eg.

**Comment by ericstgo87** [comment]
You can set "min_players_to_ready”: 1 in the match config file.

**Comment by williamweckl** [comment]
I have already set `min_players_to_ready` to 1 at match config.

@MikkelDK is there a force start command? I knew only force ready...

**Comment by MikkelDK** [comment]
> @MikkelDK is there a force start command? I knew only force ready...

Yes should be: ``.forcestart`` or rcon get5_forcestart

**Comment by splewis** [comment]
`.forcestart` is how I've manually tested the plugin in the past, it should work.
