### ISSUE TITLE
auto load config after match/scim ends

### ISSUE THREAD

**Issue by sebastian-wichmann** [splewis/get5#658]
Hello there,

is there any way to load a config after a match ended?
In my case I got the progbelm, or more a wish, to auto load another config e.g. Deathmatch after a match ended.

At the moment my game "freezes". You can't move, you can't shoot, you can't do anything. It would be fun that u are at least able to move around the map.

Im fairly sure that the devs already added this feature, but I'm realy to stupid to find it <.<

**Comment by warf-git** [comment]
did you ever figure this out?
