### ISSUE TITLE
Separate CT and T stats

### ISSUE THREAD

**Issue by redismx** [splewis/get5#659]
I realize that this would make the table a little more verbose (basically duplicate all columns), but it would be extremely valuable to measure players' impacts on each side, because playing as T is generally harder than CT at a high level.

**Comment by nickdnk** [comment]
Based on my reply to https://github.com/splewis/get5/issues/508, this is not likely to happen. As mentioned on there, you can read from the forwards and have a custom plugin save all the data you want, where splitting it into sides is quite easy.
