### ISSUE TITLE
Request on matchid in the loadmatch <match.json>

### ISSUE THREAD

**Issue by NikolajRasch** [splewis/get5#66]
I would like to suggest or make a request to make it possible to set the matchid in the config and save that as the database key or a new column.

in the config.json file there is something named: `"matchid": "example_match"`, but i'm not quite sure of it's uses.
if this is already possible i would like to know how to set it without doing it in the script, otherwise i'm sorry for the troubles and keep up the awesome good work.

**Comment by Technoblazed** [comment]
If you create the matches using the webpanel, this is already done :D

**Comment by splewis** [comment]
You can use it however you want. get5 itself has no database connection. It's up to a user or another piece of software to decide what is done with it.

The get5_mysqlstats will fetch a matchid from its backing MySQL table and set the matchid to that, ignoring what's in the match config (unless ``get5_mysql_force_matchid`` is set).

The get5 web panel generates a config where the matchid already is the primary key in its database.

**Comment by splewis** [comment]
Closing since there's no followup on this.
