### ISSUE TITLE
First kills should be per round, not per team

### ISSUE THREAD

**Issue by redismx** [splewis/get5#660]
The current stats of first kills measure it by team, which means that each round can have 2 first kills (one for each team), which is not quite what tournament organizers or platforms like HLTV use. Instead, the first kill is per round, i.e if it's 5v5 and team A kills someone from team B, if team B kills someone from team A it should not count a first kill for team A.

This might be a breaking change for those that are relying on it working this way, especially considering that this was [introduced almost 5 years ago](https://github.com/splewis/get5/commit/3023774efb4ab03fb8abab515b173d923ffd7920#diff-8a43906bc6558fd89ebcd5158c13c0764277c3ab6a207ee7a8aefb02fc0935d8R173), so perhaps instead of replacing how the first kills work, we could introduce a new stat called opening kills, that can only be attributed once for a round.

**Comment by splewis** [comment]
I agree with you, this should be changed.

As far as being a breaking change: I'm okay with breaking here, and will make sure it's documented in the release changelog.
