### ISSUE TITLE
Team names and flags not showing

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#661]
### Expected behavior
Team names and flags should appear on top of the screen. The expected HUD should be something like:

![no_team_names_shown_expected](https://user-images.githubusercontent.com/1307137/115156788-62cd7700-a05c-11eb-85d8-a6690ae991a3.png)

### Actual behavior
Neither team names or flags are showing up, although team names are shown normally on score panel (tab)
![no_team_names_shown1](https://user-images.githubusercontent.com/1307137/115156823-9c9e7d80-a05c-11eb-97a6-a19c5884f9f4.jpg)

![no_team_names_shown2](https://user-images.githubusercontent.com/1307137/115156828-9f996e00-a05c-11eb-83f3-087c3fff3e08.jpg)

### Steps to reproduce

- Plugin version: 0.7.2-dev
- Sourcemod version: 1.10.0.6502
- Steps to reproduce (please be specific):

1. Follow all steps on https://github.com/splewis/get5/wiki/Step-by-step-installation-guide
2. Load match json config file using `get5_loadmatchurl`
3. Connect using game console

Match config file json:
```
{
    "matchid": "273",
    "num_maps": 1,
    "skip_veto": true,
    "min_players_to_ready": 2,
    "players_per_team": 2,
    "maplist": ["de_mirage"],
    "team1": {
        "name": "bgt2016",
        "tag": "BGT",
        "flag": "BR",
        "players": {
            "76561198331422509": "<0> bgt2016",
            "76561198391936114": "<0> Camilotaxp"
        }
    },
    "team2": {
        "name": "gabrielkst",
        "tag": "GAB",
        "flag": "BR",
        "players": {
            "76561198075990604": "<0> gabrielkst",
            "76561198071764407": "<0> Charanko"
        }
    },
    "cvars": {
        "hostname": "My Custom Match"
    }
}
```

**Comment by nikitosoz8** [comment]
Is this a bug actually? Afaik they should appear only in GOTV. And expected behavior is also a gotv screenshot.

**Comment by gabrielfgularte** [comment]
I really don't know. Can you confirm this? If so, you can close this issue. I was expecting that teamnames and logos would appear ingame for players, didn't know if it was only for GOTV.

**Comment by nickdnk** [comment]
> > Is this a bug actually? Afaik they should appear only in GOTV. And expected behavior is also a gotv screenshot.
> 
> I really don't know. Can you confirm this? If so, you can close this issue. I was expecting that teamnames and logos would appear ingame for players, didn't know that was only for GOTV.

Team names and flags are visible for spectating players, not only GOTV. It works for me. The screenshots you posted are from a player who is alive.

**Comment by splewis** [comment]
IIRC, the flags and names used to show on the scoreboard (and while dead) to players, but I'm guessing the panorama UI changes changed that behavior.

**Comment by nickdnk** [comment]
Not a get5 issue. This is working as intended and what your screenshots show is normal behavior.
