### ISSUE TITLE
 Cannot play a series of 3 maps with a maplist of 1 maps Error

### ISSUE THREAD

**Issue by adam2003sanchez** [splewis/get5#662]
Hi, i have a problem when i try to load a match config what have's map vetos. 

" Cannot play a series of 3 maps with a maplist of 1 maps"

This is my match config:

`  
"Match"
{
	"matchid"		"example_match"
	"num_maps"		"3" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

	"spectators" // players allowed in spectator (e.g., admins) should go here
	{
		"players"
		{
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	"skip_veto"		"0" // If set to 1, the maps will be preset using the first maps in the maplist below.

	"veto_first"	"team1"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.

	"side_type"		"standard" // Either "standard", "always_knife", or "never_knife"

	"maplist"
	{
		"de_dust2"		"1"
		"de_inferno"		"1"
		"de_mirage"		"1"
		"de_nuke"		"1"
		"de_overpass"		"1"
		"de_train"		"1"
		"de_vertigo"		"1"
	}

	"players_per_team"		"5"
	"min_players_to_ready"		"1" // Minimum # of players a team must have to ready
	"min_spectators_to_ready"		"0" // How many spectators must be ready to begin.

	// These values wrap mp_teamprediction_pct and mp_teamprediction_txt.
	// You can exclude these if you don't want those cvars set.
	"favored_percentage_team1"		"65"
	"favored_percentage_text"		"HLTV Bets"
	"team1"
	{
		"name"		"EnvyUs" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
		"tag"		"EnvyUs"  // Short tags replace the "clan tag" on the scoreboard. They are optional.
		"flag"		"FR"
		"logo"		"nv"
		"players"
		{
			// Any of the 3 formats (steam2, steam3, steam64 profile) are acceptable.
			// Note: the "players" section may be skipped if you set get5_check_auths to 0,
			// but that is not recommended. You can also set player names that will be forced here.
			// If you don't want to force player names, just use an empty quote "".
			"STEAM_0:1:68421707"		""
			"[U:1:104490185]"		""
			"76561198064755913"		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	"team2"
	{
		"name"		"Fnatic"
		"tag"		"fnatic"
		"flag"		"SE"
		"logo"		"fntc"
		"players"
		{
			"STEAM_1:1:46796472"		""
			"STEAM_1:0:78189799"		""
			"STEAM_1:0:142982"		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	// These will be executed on each map start or config load.
	// You should not use this as a replacement for the cfg/get5/live.cfg config.
	"cvars"
	{
		"hostname"		"Match server #1"
	}
}`

THNX

**Comment by enerbewow** [comment]
at
"maplist"
{
	"de_dust2"		"1"
	"de_inferno"		"1"
	"de_mirage"		"1"
	"de_nuke"		"1"
	"de_overpass"		"1"
	"de_train"		"1"
	"de_vertigo"		"1"
}

try delete these "1" afther maps and keep it ""

**Comment by nickdnk** [comment]
@adam2003sanchez According to the documentation you should do as @enerbewow says. See: https://github.com/splewis/get5/blob/master/configs/get5/example_match.cfg
