### ISSUE TITLE
Players can't join as spectator after games(scrim) starts

### ISSUE THREAD

**Issue by RafaelMRG** [splewis/get5#667]
### Expected behavior

Player can join the server mid scrim and change to spec or coach

### Actual behavior

Player joins after scrim warmup ends (game starts) and can't join spec or use coach t (or ct) and !coach

### Steps to reproduce

[Debug google docs file](https://docs.google.com/document/d/1T5oH-ia7K-1AeiYim__z2U6GjYqDflBZ8zdbkTOpy1c/edit?usp=sharing)

- Plugin version: "Get5" (0.7.2-dev+492) by splewis
- Sourcemod version: SourceMod Version: 1.10.0.6503
- Steps to reproduce (please be specific):Start a scrim > force ready > after game starts any player that joins can't go to spectator or go !coach or coach t (ct), being in the team or not, being added as a scrim ringer or not.

**Comment by RafaelMRG** [comment]
Testing around i came to conclusion that there might be a bad interaction with [MoveCommands from bara](https://github.com/Bara/MoveCommands) , if anyone else has this problem, be aware of this interaction.

**Comment by splewis** [comment]
Thanks for posting that followup info, very useful to future readers.

**Comment by leonardopessoa** [comment]
Same issue here. But how to fix it if I have MoveCommands?

**Comment by nickdnk** [comment]
> Same issue here. But how to fix it if I have MoveCommands?

Please use the latest version and define spectators in your match configuration. See https://splewis.github.io/get5/latest/match_schema/

**Comment by leonardopessoa** [comment]
Thanks for the answer. It was actually easier than that and not related to the plugins, apparently. Had the match created in "casual" mode. Setting the right game_mode in the srcds launch options did it.
