### ISSUE TITLE
Add de_ancient to the map pool

### ISSUE THREAD

**Issue by chevlor** [splewis/get5#668]
### Expected behavior
Following the map pool modification by Valve, it would be nice to add de_ancient to the map pool on the public web panel (https://get5.splewis.net/) when creating a match.

### Actual behavior
de_ancient is not in the map pool on the public web panel (https://get5.splewis.net/).

![image](https://user-images.githubusercontent.com/54267151/119059805-5036bc80-b9d1-11eb-91b5-8732426bcbcb.png)

### Steps to reproduce
- Plugin version:  "Get5" (0.7.2-dev+492) by splewis
- Sourcemod version: SourceMod Version: 1.10.0.6503
- Steps to reproduce (please be specific):

1. Go on the public web panel (https://get5.splewis.net/).
2. Create a match.
3. Choose the map pool.

**Comment by TandelK** [comment]
This is not a Get5 Plugin issue but more kind of Get5-Web Repo Issue. There was a update today so you can check and use it accordingly.

**Comment by splewis** [comment]
The map pool is updated in both get5 & the web ui.

The get5.splewis.net site may get updated eventually, but I'll continue to remind people: please don't rely on it. It can be shut down any moment.
