### ISSUE TITLE
Feature Request: Add Server Ip to MySQL when the match is start

### ISSUE THREAD

**Issue by Zeligon2** [splewis/get5#67]
### Expected behavior

When you start a match with the plugin it input the match info in MySQL on the tabel `get5_stats_matches` with the server ip and like that i can see witch server is active and not active, beacuse i have alot of servers.

in my case i dont user the get5-web , only the mod.
### Actual behavior

its only put the match info in the MySQL without the server ip in the `get5_stats_matches` table.
### Steps to reproduce
- Plugin version: get5-219
- Sourcemod version: 1.8

**Comment by Technoblazed** [comment]
Would require steamworks to be forced to be used, the normal "hostname" command is unreliable.

**Comment by splewis** [comment]
Sorry, I don't plan on adding this. Part of the goal of having the natives/forwards is so users can adjust behavior like this themselves. So you can change the get5_mysql stats plugin to do whatever you need - it's largely provided as an example.
