### ISSUE TITLE
get5_stats_player (not responding)

### ISSUE THREAD

**Issue by xhuunteR** [splewis/get5#671]
Hello everyone,

Im using get5 plugin with MySQL server for my stats database.

Everything is working fine, except for my player table informations.

I have create all my tables on phpMy Admin following the steps indicated by the link:
https://github.com/splewis/get5/blob...port_stats.sql

Btw, here are my database.cfg configurations, wich is working fine, as Matches and Maps tables on MySQL are loading data.

"default"
{
"driver" "mysql"
"host" " (server IP) "
"database" "sql16551"
"user" "sql16551"
"pass" ""
"timeout" "10"
"port" "3306"
}

"storage-local"
{
"driver" "sqlite"
"database" "sourcemod-local"
}

"clientprefs"
{
"driver" "sqlite"
"host" "localhost"
"database" "clientprefs-sqlite"
"user" "root"
"pass" ""
//"timeout" "0"
//"port" "0"
}

"get5"
{
"driver" "mysql"
"host" " (server IP) "
"database" "sql16551"
"user" "sql16551"
"pass" ""
"timeout" "10"
"port" "3306"
}

Any ideas?
Thanks!
![image](https://user-images.githubusercontent.com/85462395/120942413-24b90f00-c6ff-11eb-9f4e-e4d3acaa8c3c.png)
![image](https://user-images.githubusercontent.com/85462395/120942423-31d5fe00-c6ff-11eb-9121-bf0a0e598a57.png)
![image](https://user-images.githubusercontent.com/85462395/120942431-3ef2ed00-c6ff-11eb-9a33-82fcc52de332.png)

**Comment by astutejoe** [comment]
I just got the issue on the logs:
L 06/06/2021 - 22:59:26: [get5_mysqlstats.smx] Last Connect SQL Error: Field 'tradekill' doesn't have a default value

**Comment by astutejoe** [comment]
Seems that the field `tradekill` was removed but they forgot to update the schema creation SQL, I'm gonna try deleting this field from the table to see if that helps

**Comment by astutejoe** [comment]
No dice, now "L 06/06/2021 - 23:13:17: [get5_mysqlstats.smx] Last Connect SQL Error: Field 'kast' doesn't have a default value"

**Comment by astutejoe** [comment]
The same went for  `contribution_score` and `mvp`. After setting all those fields with default '0', it works, with that in mind this is what I did to fix the issue:
```
ALTER TABLE `get5`.`get5_stats_players`
ALTER `tradekill` SET DEFAULT '0';

ALTER TABLE `get5`.`get5_stats_players`
ALTER `kast` SET DEFAULT '0';

ALTER TABLE `get5`.`get5_stats_players`
ALTER `contribution_score` SET DEFAULT '0';

ALTER TABLE `get5`.`get5_stats_players`
ALTER `mvp` SET DEFAULT '0';
```

**Comment by xhuunteR** [comment]
> The same went for `contribution_score` and `mvp`. After setting all those fields with default '0', it works, with that in mind this is what I did to fix the issue:
> 
> ```sql
> ALTER TABLE `get5`.`get5_stats_players`
> ALTER `tradekill` SET DEFAULT '0';
> 
> ALTER TABLE `get5`.`get5_stats_players`
> ALTER `kast` SET DEFAULT '0';
> 
> ALTER TABLE `get5`.`get5_stats_players`
> ALTER `contribution_score` SET DEFAULT '0';
> 
> ALTER TABLE `get5`.`get5_stats_players`
> ALTER `mvp` SET DEFAULT '0';
> ```

thanks astutejoe
its working now :D
