### ISSUE TITLE
Can someone explain how are players forced to actual teams?

### ISSUE THREAD

**Issue by Rezga12** [splewis/get5#678]
Hi, I was looking through the code but was unable to find out how are players forced to teams exactly? (I.E assigning team CT to a specific player when he joins the server)

I would like to extend the plugin and make automatic team assignment (bypassing the team menu) but am unable to analyze how are teams assigned to players right now.

**Comment by TandelK** [comment]
@Rezga12 Currently the Team based auths are done via Config Files or Web Panel Teams section. The Get5 System is made for Tournament where Team based auths are required. If you want to change the way it is most probably you can check pugsetup plugin by splewis itself.

**Comment by splewis** [comment]
The 'teamjoin' command is hooked: https://github.com/splewis/get5/blob/master/scripting/get5.sp#L454; see https://github.com/splewis/get5/blob/master/scripting/get5/teamlogic.sp#L29.


Forcing players onto teams by skipping the team menu entirely has always been my goal, hence this TODO: https://github.com/splewis/get5/blob/master/scripting/get5/teamlogic.sp#L1-L12. If you can get it to work reliability, it would be gladly accepted into get5.
