### ISSUE TITLE
Disabling knife round - is it possible?

### ISSUE THREAD

**Issue by nonhodie** [splewis/get5#679]
Hi there :) 

I'm just wondering if there's a way of disabling the knife round after readying-up and force the pistol to start immediately. 
I've tried looking around on .cfg files but couldn't find anything related to this.

Is there a way I could make this happen?

Thank you!

**Comment by splewis** [comment]
From the docs for `side_type`: https://github.com/splewis/get5/blob/master/scripting/get5/teamlogic.sp#L1-L12

> side_type: either "standard", "never_knife", or "always_knife"; standard means the team that doesn't pick a map gets the side choice, never_knife means team1 is always on CT first, and always knife means there is always a knife round

You probably want "never_knife", then make sure "team1" is the team that belongs on CT.
