### ISSUE TITLE
!stop during halftime

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#68]
### Expected behavior
!stop should not be able  to be used during halftime.

### Actual behavior
!stop using halftime causes game to hang on halftime loading screen.

### Steps to reproduce
- Plugin version: Latest sourcecode as of this time.
- Sourcemod version: Latest sourcemod 1.8 as of this time.
- Run !stop during halftime.

**Comment by splewis** [comment]
Good catch. Any backup restore commands should probably be ignored during the halftime phases.

**Comment by Technoblazed** [comment]
Just hooking "announce_phase_end" to block the stop command :D

**Comment by Technoblazed** [comment]
PR: https://github.com/splewis/get5/pull/75
