### ISSUE TITLE
Current release (0.7.1) is zipped with elevated permissions

### ISSUE THREAD

**Issue by theo-brown** [splewis/get5#680]
Unzipping the current release results in a directory tree with restricted permissions
```
$ wget https://github.com/splewis/get5/releases/download/0.7.1/get5_0.7.1.zip
$ unzip get5_0.7.1.zip
$ ls -l
total 308
d--------- 3 user user   4096 Feb 16  2019 addons
d--------- 3 user user   4096 Feb 16  2019 cfg
-rw-rw-r-- 1 user user 251415 Feb 16  2019 get5_0.7.1.zip
---------- 1 user user  35141 Nov 20  2018 LICENSE
---------- 1 user user  14558 Dec 20  2018 README.md
```
This is solvable by unzipping and then running `chmod`, but this is a bit of pain as it means you can't easily unzip straight to `csgo/addons`.

Would it be possible to rezip the release with non-restricted permissions? Or alternatively to modify the README to notify people of this.

**Comment by MikkelDK** [comment]
Yeah seems the "chmod" on folders/files are: ``0000`` - I mean they should be 0644 (I'm not 100% sure)

**Comment by splewis** [comment]
https://github.com/splewis/get5/releases/tag/0.7.2 is created, and should have fixed the permissions.
