### ISSUE TITLE
Failed to get matchid from match init query

### ISSUE THREAD

**Issue by nikitosoz8** [splewis/get5#685]
### Expected behavior

Match ID gets from the json file. Data saved in db.

### Actual behavior

L 07/15/2021 - 10:24:45: [get5.smx] Failed to read input auth id "", inputId
L 07/15/2021 - 10:24:45: [get5_mysqlstats.smx] Failed to get matchid from match init query

### Steps to reproduce

Here is match config:
`{
"matchid": "6373",
"num_maps": 5,
"players_per_team": 1,
"min_players_to_ready": 1,
"min_spectators_to_ready": 0,
"side_type": "never_knife",
"skip_veto": true,
"maplist":["aim_9h_ak","aim_ak47_v2","aim_map2_go","aim_map_cl","aim_map"],
"spectators":{"players":[""]},
"team1":{
"name":"mjk134","players":{"STEAM_0:0:531076147":"mjk134"}},
"team2":{"name":"nikitosoz8","players":{"STEAM_0:1:175436101":"nikitosoz8"}}
}`

Insert the config in a json file, load it on the server and start the match. 

- Plugin version: 0.7.3-dev+529
- Sourcemod version: 1.10.0.6502

**Comment by nickdnk** [comment]
Will be fixed with #673.
