### ISSUE TITLE
Not Ending The Match And Not reseting the hostname to default

### ISSUE THREAD

**Issue by Owaisarfeen15** [splewis/get5#687]
When Ever  The  Match End get5 doesnt end the match it just start that match again without warmup or anything and the names are also the same which are in configs it doesnt reset the name to default and it doesnt load the default config which is in server.cfg and gamemode_competative.cfg  after the match ends is there any way to fix this issue need help, 
Thanks

**Comment by warf-git** [comment]
did you ever figure out how to reset the match when the match ends?

**Comment by PhlexPlexico** [comment]
I would make sure that `get5_autoload_config` is set in your config files. After the match delay (if gotv is enabled, this can be as long as two minutes, if not more), it should finalize the match and reload the config specified by the aforementioned option. Let me know if this doesn't work and I'll look further into it. Thanks!

**Comment by nickdnk** [comment]
Closing this as 0.10 should definitely end the match properly and we'll track the hostname issue here: https://github.com/splewis/get5/issues/438
