### ISSUE TITLE
Team names contain [NOT READY] on match backup load

### ISSUE THREAD

**Issue by syn7hgg** [splewis/get5#689]
### Expected behavior
Either both teams have to **!ready** up to resume the match or/and there should not be any **[NOT READY]** tags added to team names when a match backup is loaded.

### Actual behavior
**[NOT READY]** is added before team names when a match backup is loaded.

### Steps to reproduce
Create a match and play normally. Then, either use the **!get5** command to bring up the menu and load the latest backup or use the **get5_loadbackup <backup file>** console command to restore the match status from a backup. You will notice both team names will have **[NOT READY]** appended before the actual names.

- Plugin version: 0.7.2-dev+526
- Sourcemod version: 1.10.0.6504

[get5_debuginfo.txt](https://github.com/splewis/get5/files/6964421/get5_debuginfo.txt)

**Comment by splewis** [comment]
Long-standing issue, alas: #163
