### ISSUE TITLE
How to send get5 status json output as request to my Node.js backend api endpoint?

### ISSUE THREAD

**Issue by ErcouldnT** [splewis/get5#690]
Hi guys,

I have Node.js express api endpoint which is listening for json requests to get get5 events to take actions.

How am i able to send reqs (GET or POST) from my csgo_server (Steamworks installed)?

Erkut

**Comment by Drarig29** [comment]
Personally, I forked a webpanel project and it was already set up to send RCON commands, so I'm constantly sending `get5_status` to the server as an healthcheck (to see if the server is still up). And I use the result of this healthcheck as relevant information.

That's the project I (privately) forked: https://github.com/glenndehaan/csgo-rcon-nodejs

But if you don't want to do this, you could use this plugin instead: https://github.com/yannickgloster/get5_eventapi

And setup the necessary endpoint in your backend.

According to the code (https://github.com/yannickgloster/get5_eventapi/blob/v1.0.0/scripting/get5_eventapi.sp), you need a single POST `/event` route. All the information will be in the body as JSON.

**Comment by ErcouldnT** [comment]
Oh, I thank you so much, sir. All I want is csgo_server makes request to an endpoint on event changes. As I understood, your project make this at opposite way that I don't want it but I will look into your project as well.

get5_eventapi project looks cool, I will give it a try! Thanks for amazing detailed answer.

Have a good day,

Erkut

**Comment by ErcouldnT** [comment]
Hi again, 

Do you have any idea about getting matchstats.cfg (end of match file includes scores and player statistics) and recorded demo same way?

I have just found this topic in get5 wiki: https://github.com/splewis/get5/wiki/Recording-match-demos#uploading-match-demo-on-game-end

Maybe I need to create new issue but I wonder your opinion as well.

Erkut

**Comment by Drarig29** [comment]
No... For this one, we always wait for the end of the LAN party and we have to [`scp`](https://linuxhandbook.com/scp-command/) (a Linux command to copy files from machine to machine remotely) our 5 Gb of demos and `matchstats.cfg` to generate the stats of the tournament... 

That's the only thing which isn't automated yet.

**Comment by ErcouldnT** [comment]
I have just started [this project](https://github.com/ErcouldnT/Get5-Match-Stats-API) and made a roadmap. I'm working on it.

**Comment by splewis** [comment]
Nice projects, I was hoping such things would be created :) 

If any of you (or others) is interested, I'd be willing to add links to them from the get5 README -- let me know.

**Comment by nickdnk** [comment]
Closing as this is a discusson and not a get5 issue. Refer to Discord for this kind of conversation. See the readme.
