### ISSUE TITLE
[Feature Request] Add all Individual Player Weapon Information , API to Web Panel or MySQL Stats plugin. 

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#695]
We should store all the individual player weapon kills information for brief information . We can create core inside the Get5 Plugin but can access for storing via API Panel and MySQL Stats plugin. 

Every individual weapon kills can be stored for brief data and can be used via API Panel or MySQL Plugin which can show data using 3rd party web app.

**Comment by nickdnk** [comment]
I'm adding some forwards soon that will allow people to get this information.

**Comment by nickdnk** [comment]
This should be possible with https://github.com/splewis/get5/pull/736. Please try it out.
