### ISSUE TITLE
Change structure of release zip

### ISSUE THREAD

**Issue by ringvold** [splewis/get5#697]
Would you consider changing the structure of the release zip to no have the root-folder `get5` but just have the `addons` and other folders on root in the zip?

The get5 release zip would then be on the same format as your other plugins (retake, practice, pugsetup) and would make it easier to automate installing it.

My spesific case is that I want to add it to a csgo docker image that already installs sourcemod plugins but get5 can not be easily added to that setup as the zip has a differet structure than all the other plugins.

**Comment by splewis** [comment]
This is likely an oversight; I'll try to get around to fixing it soon.

**Comment by splewis** [comment]
Fixed
