### ISSUE TITLE
Get5 - Server Crash - MovePlayerCT failed, leaving player in list

### ISSUE THREAD

**Issue by kENN1N** [splewis/get5#698]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When we use scrim template to launch the match the server shouldn't crash.

### Actual behavior
When we load scrim template and put in our coaches and start the game the server crashes with the error in the title.
^^^^^^^^^^ im pretty sure its due to the new 1v1 warmup thing

### Steps to reproduce
Launch scrim template
fill up server
2 ct coaches 1 t coach
start game and it crash
![Skærmbillede 2021-08-31 195650](https://user-images.githubusercontent.com/49256531/131580310-c8e2151b-8899-473b-8697-b44ece74f469.png)

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by lukasz922** [comment]
Apparently the solution is to remove bot_kick .I have the same problem when using eBot

**Comment by kENN1N** [comment]
> 
> 
> Apparently the solution is to remove bot_kick .I have the same problem when using eBot

Thanks! i tried to remove it from live and warmup config, gonna check tomorrow when team arrives, if it works or not :)

**Comment by warf-git** [comment]
> 
> 
> Apparently the solution is to remove bot_kick .I have the same problem when using eBot

I tried removing bot_kick from all my files, it doesn't fix it. I also have -nobots in my command line and that didn't change anything.

**Comment by lukasz922** [comment]
There is supposedly a second method, but I haven't tested it. You should delete the warmup folder from csgo \ scripts \ vscripts 
 
Disabled miniarena 1vs1

**Comment by warf-git** [comment]
> 
> 
> > Apparently the solution is to remove bot_kick .I have the same problem when using eBot
> 
> I tried removing bot_kick from all my files, it doesn't fix it. I also have -nobots in my command line and that didn't change anything.

I fixed it using this thread: https://forums.alliedmods.net/showthread.php?t=329045
if you don't want to disable warmup then you can do what I did which is instead of setting "COMPMATCH == false" I replaced "WINGMAN == true" with "COMPMATCH == true". Keep in mind that you probably can't run anything over a 5v5 doing this, but this isn't a problem for the server I'm running.

**Comment by kENN1N** [comment]
> 
> 
> There is supposedly a second method, but I haven't tested it. You should delete the warmup folder from csgo \ scripts \ vscripts
> 
> Disabled miniarena 1vs1

Have you tested this second method?

**Comment by lukasz922** [comment]
> 
> 
> > There is supposedly a second method, but I haven't tested it. You should delete the warmup folder from csgo \ scripts \ vscripts
> > Disabled miniarena 1vs1
> 
> Have you tested this second method?

Not yet

**Comment by kENN1N** [comment]
Aaaaaaaaaaaallright guys, i found a solution - its not perfect but its honest work and it doesnt crash anymore.
So, i've been googling for days and i came up with this plugin.

// https://github.com/Ilusion9/csgo-fix-warmup-sm //
It removes logic scrips related to warmup - so there is still warmup mode but no more 1v1 and i havent had a crash since.

You'll need to compile the plugin from .SP to .SMX, this page is made for that use the link below
// https://www.sourcemod.net/compiler.php // 

When it's done compiling, download and put it in your plugins folder and restart the server.
Enjoy!
