### ISSUE TITLE
Missing team 1 section in match kv

### ISSUE THREAD

**Issue by leeb2k** [splewis/get5#701]
### Expected behavior

load match.cfg

### Actual behavior

failed to load match.cfg

### Steps to reproduce

I followed the strategy explained here: https://github.com/splewis/get5/wiki/Managing-match-configs#managing-team-data-from-separate-files 

join server
type "get5_loadmatch match.cfg"

![serverconsole](https://user-images.githubusercontent.com/81647012/134964248-1aa52c05-0ec5-40ca-ade8-a5843bf1533f.png)

![matchcfg](https://user-images.githubusercontent.com/81647012/134964408-12c62525-9dd5-4799-a7ac-0b0678972b3b.png)

- Plugin version: 533
- Sourcemod version: Preinstalled by dathost
- Steps to reproduce (please be specific):

**Comment by Drarig29** [comment]
It's because of your `/` at the start of the `fromfile`.

Just remove it if the team files are in the same folder.

Otherwise, put the team files in the same folder as in the example of the wiki.

**Comment by leeb2k** [comment]
That didnt fix my issue, i even tried just loading the provided match config with my own players and it still gives me the same error

**Comment by leeb2k** [comment]
never mind, i must've deleted or missed something because i've started from fresh and it works now.
