### ISSUE TITLE
[HELP] - BO5 with 1 map advantage

### ISSUE THREAD

**Issue by JesusWithPants** [splewis/get5#704]
Hi all,

Most likely I just cant read but got a question:
Is it possible to configure get5 match as BO5 with 1 map advantage (so first map is not played)?
Tried setting `series_score` var in team config but seems that it didn't work :/
NOTE: Veto is done outside server and maps/map_sides are set in cfg

**Comment by TandelK** [comment]
@JesusWithPants Can you share your config file you are using for this ?

**Comment by splewis** [comment]
`series_score` should work here.

If not, that's a bug, but we'd need the plugin version / match config to reproduce the issue.
