### ISSUE TITLE
[Feature Request] Add coach command: get5_addcoach <team> <steamid>

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#705]
What about a command that could be implemented in a custom web panel we are using to specify a coach when creating match?
crrf: https://github.com/PhlexPlexico/G5API/issues/96#issuecomment-824394613

**Comment by nickdnk** [comment]
I won't mess around with coaches or backup problems in that version. It's the event system and stat bug fixes only. Maybe in 0.10.

**Comment by kubo6472** [comment]
> I won't mess around with coaches or backup problems in that version. 
It's the event system and stat bug fixes only. Maybe in 0.10.

aight, I get you

**Comment by PhlexPlexico** [comment]
Hey @kubo6472,

I've added in a new function for adding coaches to the game, as a part of tracking coaches for backups/disconnects/reconnects. Would you mind taking the time to test it out and see if it works as intended? Basically all it's doing is adding a player to a team and setting a CVAR if no coach exists for the team already. I think that's mainly the functionality that's needed, right? The build can be found [here](https://github.com/PhlexPlexico/get5/suites/6681223318/artifacts/253269796)

Thanks!

**Comment by kubo6472** [comment]
Thank you! Just replied to the other issue, this may be the right fix for that. I'll test it as soon as I can.
