### ISSUE TITLE
g_BO2Match not resetted after match. BO2 stuck until server reboot.

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#708]
### Expected behavior
After a BO2 a different format can be immediately played on the server

### Actual behavior
After a BO2 the g_BO2Match var is stuck to 1 and therefore any other format has bo2 format.

### Steps to reproduce

- SM error log: https://hastebin.com/rehusovuka.sql
- get5_debuginfo: https://hastebin.com/gupojodozi.yaml
- Crrf: https://github.com/PhlexPlexico/G5API/issues/130#issuecomment-945214440

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/144104183-51f2777b-baaf-497b-ab56-2e08fc3acdd0.png)
BO3 match, BO2 veto

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/144104367-dbdc1131-5630-40b1-b391-a0287a24d4e0.png)
BO3 match after server reboot. BO3 veto

**Comment by PhlexPlexico** [comment]
So I think I may have figured out the issue with this. I was comparing the two variables `g_SkipVeto` and `g_BO2Match`. During a match load from JSON or KV, `g_SkipVeto` does a safe call and returns `false` if `skip_veto` is not present in the match config. However, `g_BO2Match` is a little bit different in that it uses other variables to check for truthiness, which can be seen here as an example:

https://github.com/splewis/get5/blob/3cf1f7d61eda584b725f430070af8b9ecd38f758/scripting/get5/matchconfig.sp#L452-L463

The only problem with this is that once this `g_BO2Match` is set to true, there is no way (aside from a plugin reload or server reboot) that `g_BO2Match` will be set to false. @kubo6472 would you by chance have some time to test the plugin if I were to make a build that has a small patch for this to ensure it's working as intended before I create a PR for this?

Thanks!

**Comment by kubo6472** [comment]
Sure

**Comment by PhlexPlexico** [comment]
[Here](https://github.com/PhlexPlexico/get5/suites/4771054508/artifacts/132801411)  is the link to the artifact for the latest fix I made. If this works then I'll create a PR. 

Thanks!

**Comment by kubo6472** [comment]
Testing just now. I received it in the middle of the night :D

**Comment by kubo6472** [comment]
WORKS!!!

https://phlex.avidgamers.me/match/937

https://phlex.avidgamers.me/match/938
