### ISSUE TITLE
Changing the way admin pauses work.

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#71]
This would involve the creation of two new admin commands, 'get5_forcepause' & 'get5_forceunpause'. These commands will be able to be used by admins ingame similarly to how the webpanel currently uses the mp_pause_match command (something like that). I feel like this command should instead by changed to one of the functions as listed above. This would mean that a message could be added, i.e. 'An admin has paused the match.' or something along the lines of that.

If you okay this as a feature you wouldn't mind having, I'd have no problem coding it in for you, just don't want to do the code before the feature is accepted.

**Comment by splewis** [comment]
sm_pause and sm_unpause should already work for any spectator or via rcon, and be unrestricted (no time limits)

Now that I think about it the web panel probably **should** be sending the ``sm_pause`` command instead of ``mp_pause_match``. (https://github.com/splewis/get5-web/blob/master/get5/match.py#L296)

**Comment by Technoblazed** [comment]
```
L 10/15/2016 - 05:12:41: [SM] Exception reported: Client index 0 is invalid
L 10/15/2016 - 05:12:41: [SM] Blaming: get5.smx
L 10/15/2016 - 05:12:41: [SM] Call stack trace:
L 10/15/2016 - 05:12:41: [SM]   [0] GetClientAuthId
L 10/15/2016 - 05:12:41: [SM]   [1] Line 165, get5/teamlogic.sp::GetClientMatchTeam
L 10/15/2016 - 05:12:41: [SM]   [2] Line 578, C:\..\scripting\get5.sp::Command_Pause
```

Going to work on a fix.

**Comment by Technoblazed** [comment]
PR: https://github.com/splewis/get5/pull/72

**Comment by BloodyIron** [comment]
I'm getting the same error when trying to use pause with the latest build as of today, which is 0.5.5. What's up with that? :(

**Comment by splewis** [comment]
Can you open up a new issue with the output produced by get5_debuginfo then?
