### ISSUE TITLE
Stats wrong: SQL differs from CS GO & backup cfg

### ISSUE THREAD

**Issue by deLuXe83** [splewis/get5#711]
Hey everybody,

I am experiencing strange behavior of get5.

Sometimes the stats recorded in the SQL database differs from scoreboard in CS:GO. Meaning some players (not all, i can see no pattern there) have slightly (like 1-3) more Kills, Deaths or Assists.
**Obvious on Teamkills:** each TK is counted as 1 Kill in get5, while CS:GO as we know subtracts a kill.
This is reproducable, on ever round with a TK, SQL stats are wrong.

But what I cannot reproduce is the following:
When you take a look into the get5_backup_matchxx_xxx.cfg files, which is created after each round. Open the last file of each map. There you have in the upper part detailled stats on each player. Those stats are correct and correlate with score board.
In the lower part of this backup file there is like a summary of the stats. Those are exactly the stats saved also to the SQL database. And those stats differ from the upper stats and score board, meaning they are sometimes wrong.

Anybody having the same issues?

Any thoughts on a solution?
Thank you very much!

**Comment by nickdnk** [comment]
Team kills are not considered kills in get5. It's a separate stat: https://github.com/splewis/get5/blob/3cf1f7d61eda584b725f430070af8b9ecd38f758/scripting/get5/stats.sp#L279

Which version are you using?

**Comment by deLuXe83** [comment]
Thanks for your answer.
Yeah, but they are counted like normal kills ;-)


> Which version are you using?

"get5_version" = "0.8.0-dev+533"

**Comment by nickdnk** [comment]
What do you mean that they are "counted like normal kills"? They're not, teamkills are a separate stat that does not affect your kill count. Please explain.

**Comment by nickdnk** [comment]
Perhaps this is related to incorrect count of suicides? https://github.com/splewis/get5/issues/453

I've had the death count be wrong myself, but never kills or assist.

**Comment by deLuXe83** [comment]
Thanks for your answer.
I tried to explain in my first post :)

Yes ... exactly this is what I am doing!

But shouldn't get5 always and out of the box show the same stats as the ingame scoreboard?

puh, might also be related to #453, yes. Did not check that.

**Comment by nickdnk** [comment]
> Thanks for your answer. I tried to explain in my first post :)

I still don't understand what you mean though.

> But shouldn't get5 always and out of the box show the same stats as the ingame scoreboard?

No. Killing an enemy and then killing a teammate is not the same as not killing anyone. The data can be used for so much more when separated correctly. Personally I present scores for previous matches like:

`(-1) 20 | 5 | 12`

If the person had 20 kills and 1 team kill.

> puh, might also be related to #453, yes. Did not check that.

Yea, but that should only affect your death count, so if you have problems with kills or assists then something else is wrong. I've never had this be wrong myself though. Unless suicides are also meant to subtract one from kills?

**Comment by nickdnk** [comment]
Closed as this will be resolved when we fix #453.
