### ISSUE TITLE
Scrim setup

### ISSUE THREAD

**Issue by MarquesCoding** [splewis/get5#712]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Server starts with config and people can join on either side of the team and are able to ready up using !ready.

### Actual behavior

Server starts with config and people can't join CT...

### Steps to reproduce

Install get5 within no changes and run the scrim

**Comment by splewis** [comment]
This is working as intended, I suggest reading https://github.com/splewis/get5/wiki/Using-get5-for-scrims

* You can add players to the scrim template to configure teams
* Alternatively, use `.ringer` to add players to the "home" team
