### ISSUE TITLE
How can Remove team select menu

### ISSUE THREAD

**Issue by gokos256** [splewis/get5#714]
Hello, I hope everyone is in good health.
The reason I'm opening such a topic is definitely not disrespectful of the work you're doing. But I've found a big problem. In an ongoing match, when a player exits the game and reconnects, and when the Team selection menu appears, I press the "ESC" key, then the "Space" key and simultaneously press the "w-a-s-d" direction keys. I navigate the map as a spectator. So we can watch the players place. This is a big problem.

get5.sp, when I cancel the team selection via sp, I have the following problem. After the players die, it comes alive when it exits the game and enters back. How can we solve this problem, I really need your urgent help.

Thank you and wish you good work.

@splewis

**Comment by gokos256** [comment]
@splewis

**Comment by kubo6472** [comment]
I can't verify. Can you provide the steps to reproduce more clearly?

**Comment by nickdnk** [comment]
Sounds more like a general problem with CS? I mean, is it not obvious to everyone in the game that someone is on the spectator team - or at the very least missing from the game?

**Comment by nickdnk** [comment]
@gokos256 In https://github.com/splewis/get5/pull/736 the players are automatically assigned a team when connecting to the server - or kicked if they are not in the match. This might help. Try that version out.
