### ISSUE TITLE
Randomly moving half a team to coach positions

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#716]
### Expected behavior
Only the person who types in !coach (in this case nobody did) will get moved to the coaching position for that team and this place is limited for 1 player per team.

### Actual behavior
Three of the team players without typing anything got moved to the coaching position until the match was ended and created again.

### Steps to reproduce

The [output file produced by ``get5_debuginfo``](https://paste.sr.ht/blob/de97fae88ea6409d6a66db77a5175b4c66fcd036)

```
get5_version
"get5_version" = "0.7.2" notify singleplayer replicated - Current get5 version
sm version
SourceMod Version Information:
SourceMod Version: 1.10.0.6513
SourcePawn Engine: 1.10.0.6513, jit-x86 (build 1.10.0.6513)
SourcePawn API: v1 = 5, v2 = 12
Compiled on: Sep 22 2021 01:46:49
Built from: https://github.com/alliedmodders/sourcemod/commit/698cc8e
Build ID: 6513:698cc8e
http://www.sourcemod.net/
```
- Steps to reproduce (please be specific):
1. Create a match (BO2 in this case, may be related to #708)
2. Players join and some of them are in spectator positions for the teams they are in (coaches)
3. Console is spammed with (#700) since they are all trying to switch to their team
4. I tell them to stop
5. Force end the match
6. Create it from the scratch

**Comment by TandelK** [comment]
@kubo6472 How many players are set in per team and how many extra players are joining ? By default it will work like Max Players per team is set to 5 and 2 other players of that team join in, they will be auto moved to Coach position. By default CSGO Game has added limitation to Competitive Mode on Server that it will only allow max 5 players per team, so the best way for joining sequence will be first the coach join the server and than he directly types !coach sending him first to coach slot and keeping last 5 slot empty for players.

**Comment by kubo6472** [comment]
Okay, first of all, in this case there were no coaches, so only 5 players joined, but three of them got magically right into the coachslot on join.

**Comment by kubo6472** [comment]
```json
{"match":{"id":85,"user_id":1,"server_id":2,"team1_id":20,"team2_id":7,"winner":null,"team1_score":0,"team2_score":0,"team1_series_score":null,"team2_series_score":null,"team1_string":"Hobovci","team2_string":"Esport TUKE NXT","cancelled":1,"forfeit":0,"start_time":"2021-11-20T11:27:44.000Z","end_time":"2021-11-20T18:22:17.000Z","max_maps":2,"title":"Map {MAPNUMBER} of {MAXMAPS}","skip_veto":0,"api_key":"NSMH6INLR8NCMBIX7AF39HZ7","veto_mappool":"de_inferno de_ancient de_mirage de_nuke de_overpass de_dust2 de_vertigo","veto_first":"team1","side_type":"standard","plugin_version":"unknown","private_match":0,"enforce_teams":1,"min_player_ready":4,"season_id":2,"is_pug":0,"players_per_team":5,"min_spectators_to_ready":0}}
```

**Comment by kubo6472** [comment]
```json
{"matchid":"85","match_title":"Map {MAPNUMBER} of {MAXMAPS}","side_type":"standard","veto_first":"team1","skip_veto":false,"min_players_to_ready":4,"players_per_team":5,"team1":{"name":"Hobovci","tag":"HBV","flag":"SK","players":{"76561198053544786":"Mar9Sal","76561198052369078":"Denis Zachranca 13","76561198231420988":"Nebojácny Jack Hju 23","76561198154519096":"Hobko","76561198056559942":"Miniama","76561198092343285":"Žigov Blafák"}},"team2":{"name":"Esport TUKE NXT","tag":"eTuke N","flag":"SK","players":{"76561199003407221":"❤Gezi❤","76561198151769382":"PE4CE","76561197962110336":"marjen","76561198866394969":"phe0nqx","76561199021130778":"Raklic"}},"cvars":{"get5_web_api_url":"https://cs.jakubdobos.eu/api","get5_check_auths":"1"},"spectators":{"players":[]},"maplist":["de_inferno","de_ancient","de_mirage","de_nuke","de_overpass","de_dust2","de_vertigo"],"min_spectators_to_ready":0,"num_maps":2}
```
Here, sorry, the first one was incorrect. This is the config file.

**Comment by kubo6472** [comment]
> How many players are set in per team

Five
> how many extra players are joining

Extra? Zero. Only the five specified joined.

**Comment by kubo6472** [comment]
> Coaches need to be the 6th player, don't they?
1st question was how many were set, since you can't specify coaches, yet (#705). Then, I was mentioning the situation, where no coaches were suppossed to be on that match, yet two, or rather three players just ended up in coaches, when there were only 5 players per team on the server. Alse @nickdnk 's answer totally contradicts what @TandelK recommends. Anyway, as I mentioned, the best solution is to filter coach position with steamid, no matter how many valid steamids were specified, allow only the first five to play, kick out the rest, except the coach with his steamid.

**Comment by kubo6472** [comment]
I would love to see the get5 add_coach cmnd that would set a boolean isCoach to true and that added steamid is the only one, that can join the server on the coach slot.

**Comment by nickdnk** [comment]
This is already the behavior on 0.10.
