### ISSUE TITLE
Add slack to the repo to enable notifications to slack channel 

### ISSUE THREAD

**Issue by thelitlej** [splewis/get5#717]
I was trying to connect this get5 github repo to my slack channel to enable notifications and saw that slack needed to be added to the repo to make it possible, it would be awsome if it could be added! <3 

Link to add:
https://slack.github.com/github/v2/install/1907286/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiMjc3NjM4MjA5NjUzNS4zNTgyMjQxMDAxODIuNzU5MzAyN2I2ZWQ5MWYyMzdlNzI4MTA0ZGJiMGIxYTYiLCJ0ZWFtSWQiOiJUQUo2TDJZNUMiLCJjbGllbnREb21haW4iOiJzb3VyY2VlbXBpcmUiLCJ1c2VySWQiOiJVMDFQRE1VNkhUNyIsImNoYW5uZWxJZCI6IkMwMlA4VUdRN1NQIiwidHJpZ2dlcmluZ0FwcCI6IkEwMUJQN1I0S05ZIiwicmVwbGF5Q29tbWFuZCI6dHJ1ZSwiaWF0IjoxNjM4NDI4ODA2LCJleHAiOjE2Mzg0MzI0MDZ9.wgJ4nNE8Q6zjwoFYuNcgwqtrdLzE54XJ9H_3g1ZPZKM

**Comment by nickdnk** [comment]
We'll move towards a more consistent release cycle after 0.9 is out. Link is broken.
