### ISSUE TITLE
Match stats JSON file generated at the end of series gets truncated

### ISSUE THREAD

**Issue by TimiSillman** [splewis/get5#722]
### Expected behavior

Match stats JSON file generated at the end of series should be correctly formatted and have all stats

### Actual behavior

JSON gets truncated at the end. Seems to be problem with bo3 games or longer games. This has happened like 6 times in couple days

`"firstdeath_t":3,"firstkill_ct":1,"dama}`

^ this is how the JSON file ends

### Steps to reproduce

Long games like bo3 and bo5 maybe?

I don't know exactly how to reproduce this

- Plugin version: 533
- Sourcemod version: 1.10.0.6524
- Steps to reproduce (please be specific):

**Comment by TimiSillman** [comment]
https://github.com/splewis/get5/blob/43b7f3d86c1e6978c7b01ad20f06247279b1cc9e/scripting/get5/stats.sp#L559

Buffer is way too small?

![image](https://user-images.githubusercontent.com/25002589/145447922-66720294-579b-4a6c-aeda-8edd97eb335d.png)

^ file generated

**Comment by splewis** [comment]
Yes, feel free to send a pull request to update it. I don't have a sense of
what the right value is, but I'm not opposed to 64 KB or such.

**Comment by TimiSillman** [comment]
New error occurs at end of a map

Sourcemod limits plugins heap/stack size to 16kb? 

Adding `#pragma dynamic <size>` might fix but no idea where it goes and what the size should be

Any ideas?

Error:

`L 12/11/2021 - 16:28:50: [SM] Exception reported: Not enough space on the heap
L 12/11/2021 - 16:28:50: [SM] Blaming: get5.smx
L 12/11/2021 - 16:28:50: [SM] Call stack trace:
L 12/11/2021 - 16:28:50: [SM]   [1] Line 142, /var/lib/jenkins/workspace/get5/tmp/addons/sourcemod/scripting/include/json.inc::json_encode
L 12/11/2021 - 16:28:50: [SM]   [2] Line 400, /var/lib/jenkins/workspace/get5/tmp/addons/sourcemod/scripting/include/json/object.inc::JSON_Object.Encode
L 12/11/2021 - 16:28:50: [SM]   [3] Line 560, ./scripting/get5/stats.sp::DumpToJSONFile
L 12/11/2021 - 16:28:50: [SM]   [4] Line 544, ./scripting/get5/stats.sp::DumpToFilePath
L 12/11/2021 - 16:28:50: [SM]   [5] Line 539, ./scripting/get5/stats.sp::DumpToFile
L 12/11/2021 - 16:28:50: [SM]   [6] Line 159, ./scripting/get5/stats.sp::Stats_UpdateMapScore
L 12/11/2021 - 16:28:50: [SM]   [7] Line 972, ./scripting/get5.sp::Event_MatchOver`

Sources:

https://forums.alliedmods.net/showthread.php?t=65592

https://forums.alliedmods.net/showthread.php?p=2620754#post2620754

**Comment by splewis** [comment]
I would suggest:
1) Make the variable static, which should result it in being allocated elsewhere (slightly unsure)
2) If that fails, make it a global variable (still only used in the function), which will definitely allocate the variable elsewhere
