### ISSUE TITLE
Get 5 crashes my server everytime I create a match

### ISSUE THREAD

**Issue by Kado201** [splewis/get5#732]
As the title states anytime I create a match my server auto disconnects and the servers console is flooded with this
https://gyazo.com/83efcee82ce7c424934aa405ad3510de
I have zero idea why this is happening as I've changed nothing in the file explorer

**Comment by nickdnk** [comment]
I get this error often too, but the server does not crash. Can you give more details. Perhaps a match config? Please follow the issue template or come on the Discord server if you have problems that are not a bug.

**Comment by Kado201** [comment]
Could you link me the discord server?

**Comment by nickdnk** [comment]
@Kado201 I think this is related to bots and the warmup area, not actually get5. Look at this thread: https://forums.alliedmods.net/showthread.php?t=328983
