### ISSUE TITLE
[FR] Stop players' ability to un-pause the game when paused by admin

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#737]
When the match is paused by an admin, players shouldn't be able to un-pause the game themselves.

**Comment by nickdnk** [comment]
@kubo6472 Why would you need this? If both teams indicate they are ready, why not continue?

**Comment by kubo6472** [comment]
> @kubo6472 Why would you need this? If both teams indicate they are ready, why not continue?
But if you need to keep the match paused for e.g. GOTV broadcast and livestream production coordination, and the players just keep on unpausing the match when you need to keep it paused.

**Comment by nickdnk** [comment]
Should be solvable with a simple `g_PausedByAdmin` boolean. Set true if admin pauses. If non-admin unpauses and it's true, print a message (needs translation file etc.). 

If a player pauses and the game is not already paused, set the var back to false to ensure it won't remain true in case an admin pauses and then changes the map or something similar.

**Comment by kubo6472** [comment]
Thanks @PhlexPlexico @nickdnk
