### ISSUE TITLE
Failed to get steamid when used in docker

### ISSUE THREAD

**Issue by Gryfenfer97** [splewis/get5#739]
I have a problem with get5 trying to connect even if my steamid is in the list. (works only with docker)

### Expected behavior

Just let me connect to the server

### Actual behavior

I have the following error : 
```
[get5.smx] Failed to get steamid for client Gryf<3><STEAM_1:0:xxxxxxxxx><>
[get5.smx] Failed to get steamid for client Gryf<3><STEAM_1:0:xxxxxxxxx><>
"Gryf<3><STEAM_1:0:xxxxxxxxx><>" disconnected (reason "You are not a player in this match")
```

### Steps to reproduce

Pull the image [cm2network/csgo:sourcemod](https://hub.docker.com/r/cm2network/csgo/). Then run it. I've used a volume so I can edit the server.cfg file where I changed the variable of sv_lan from 0 to 1 (because I use the same pc for the server and the game).
here is my command to run start the container : 
```
docker run -d --net=host \
          -v $(pwd)/csgo-data:/home/steam/csgo-dedicated/ \
          -e SRCDS_PORT="27016" \
          -e SRCDS_TV_PORT="27017" \
          -e SRCDS_IP="0.0.0.0" \
          -e SRCDS_PW=""  \
          -e SRCDS_NET_PUBLIC_ADDRESS="$public_ip" \
          --name=csgo-server \
          cm2network/csgo:sourcemod
```

Then I use a webpanel to create the config and send it to the server but as I tried it outside of docker and it seems to work I don't think the problem come from there.

- Plugin version: 0.7.2
- Sourcemod version: 1.11

**Comment by nickdnk** [comment]
Hello

If it works without Docker, then Docker is the problem. Maybe your networking is not configured properly. Running it in sv_lan could also cause this.

Regardless, this is not a problem we can fix.
