### ISSUE TITLE
About csgo_damageprint.sp, how do i make the damage exceed 100?

### ISSUE THREAD

**Issue by Renrael2022** [splewis/get5#741]
This may be in the wrong repo, but sm-misc doesn't have a issues page.

https://github.com/splewis/sm-misc/blob/8fc2418b533da5a8be8082b121bcec89715e5037/scripting/csgo_damageprint.sp

**Comment by nickdnk** [comment]
Version 0.9 supports excess damage in the chat report. You can use that version once it releases.

https://github.com/splewis/get5/pull/736

**Comment by Renrael2022** [comment]
> Version 0.9 supports excess damage in the chat report. You can use that version once it releases.
Hello

I'm only interested in upgrading only the damageprint, not get5 itself

**Comment by nickdnk** [comment]
Please read my previous response. I highlighted the lines you need to change.

**Comment by Renrael2022** [comment]
> I highlighted the lines you need to change.

Change it with what exactly?

I'm sorry for being annoying but i'm kinda new to source

**Comment by nickdnk** [comment]
Remove the lines I linked.

**Comment by Renrael2022** [comment]
Thanks for being patient with me,
But it sadly didn't work, it's still won't go beyond 100.

**Comment by nickdnk** [comment]
You have to recompile the plug-in if you modify the .sp files. Only the .smx files are read by the game.

**Comment by splewis** [comment]
It would probably be easier to submit a pull request to that repo with the desired changes, and then use the automatically created build.

**Comment by Renrael2022** [comment]
> Recompile the plug-in if you modify the .sp files.

Recompiled it, still didn't work.

On the other hand i tried the 0.9 version, 
damageprint seems to not show up in chat, i enabled it in the cfg file.
Still won't pop up

**Comment by nickdnk** [comment]
Bots are not supported, no. Get5 is not designed to be used with bots. I don't know about the separate damageprint plugin.

**Comment by Renrael2022** [comment]
Guess i'll have to stick to the seperate damage plugin.

**Comment by Renrael2022** [comment]
> You have to recompile the plug-in if you modify the .sp files. Only the .smx files are read by the game.

I manage to make it work, i forgot to look in the compiled folder.
Thank you very much
