### ISSUE TITLE
[Feature Request] Allow players to have their own clan tags.

### ISSUE THREAD

**Issue by anaskiii** [splewis/get5#743]
In the configs, there's always a team tag format that allows you to change the player tag to the specified teams tag. When we changed it to none, the plugin just disabled all clan tags from the players. I was wondering if players could have their own clan tags without forcing it to none or "Name" based. Similar to FACEIT, forcing player's name but not the tags.

**Comment by PhlexPlexico** [comment]
Hey, I think the option is a bit ambiguous, but I believe if you set the config value `get5_set_client_clan_tags` to 0, it shouldn't update the clan tags either. This removes the `[READY]` and `[NOT READY]` tags as well, but it should not remove player tags.
