### ISSUE TITLE
[FR] Include these commands from pugsetup

### ISSUE THREAD

**Issue by Renrael2022** [splewis/get5#745]
Here's the command from pugsetup -

sm_pugsetup_mutual_unpausing (default 1) - Whether an unpause command requires someone from both teams to fully unpause the match.

And here's a command i'd like to be implemented -

// Autoselects a team's !stay/!swap decision after winning knife round.
// 
// Default: "0"
get5_autoselect_knife_decision "1"

**Comment by nickdnk** [comment]
Hello

Sides already default to "!stay" if nobody makes a decision. What exactly do you suggest auto-selection should otherwise do?

**Comment by Renrael2022** [comment]
>Sides already default to "!stay" if nobody makes a decision. What exactly do you suggest auto-selection should otherwise do?

It would autoselect the decision of selecting a team, it only selects !stay. It would great if it selects !swap too.

**Comment by nickdnk** [comment]
> > Sides already default to "!stay" if nobody makes a decision. What exactly do you suggest auto-selection should otherwise do?
> 
> It would autoselect the decision of selecting a team, it only selects !stay. It would great if it selects !swap too.

Why? When would it select swap and when would it select stay? Doesn't make a lot of sense to me.

**Comment by nickdnk** [comment]
I don't see a reason to do that at all.

**Comment by Renrael2022** [comment]
ok

**Comment by Renrael2022** [comment]
Are you going add this command then?

> sm_pugsetup_mutual_unpausing

**Comment by Renrael2022** [comment]
What about this command? [https://forums.alliedmods.net/showthread.php?p=2467665](https://c.tenor.com/uZ0z91UerqEAAAAd/middle-finger-cat.gif/)
