### ISSUE TITLE
[FR] Just two captains required for veto phase

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#751]
Can we get ready for the veto phase when only at least the two captains are present and ready? @proksi953

**Comment by PhlexPlexico** [comment]
Is this not possible with setting the minimum players to ready? I think you should be able to set those to 1, and then call `!forceready` to do this already.

**Comment by kubo6472** [comment]
> Is this not possible with setting the minimum players to ready? I think you should be able to set those to 1, and then call `!forceready` to do this already.

Actually, been using that exactly since.
