### ISSUE TITLE
[Feature Request] Attempt to download a workshop map

### ISSUE THREAD

**Issue by GekasD** [splewis/get5#755]
When a map is being loaded, it should check if the map name is a workshop id (e.x 1729981703) and then run `host_workshop_map <mapid>` instead of `changelevel`, so then it would be possible to pass in workshop map ids in the maplist of a match config.

**Comment by GekasD** [comment]
https://github.com/splewis/get5/blob/master/scripting/get5/maps.sp

Im guessing the check would need to happen on the 2nd function in the file linked above.

**Comment by PhlexPlexico** [comment]
Looks like this is already done in pugsetup - 

https://github.com/splewis/csgo-pug-setup/blob/d03a71cd0251731a13c115aadd19e94def6209db/scripting/pugsetup/maps.sp#L35-L39

So I think this is pretty transferable to this project as well!

**Comment by GekasD** [comment]
Yep looks like exactly what i want, hope this gets implemented soon!

**Comment by PhlexPlexico** [comment]
So yeah, per discord discussions having to implement this may be a bit difficult as well though since we want to avoid as many bugs as possible. A few things that would have to be considered:

- Ensure the server has an API auth key set. Not sure how we can do that but having a check would be better then countless troubleshooting posts.
- Network hiccups which causes a map to not load. There would have to be a way to call a retry if the map hasn't changed. Maybe incorporate a timer function call that checks after X seconds and retry if it hasn't changed?

I think those were the main issues posted in the discord.

**Comment by nickdnk** [comment]
Is there a function that returns the current workshop ID of a map? If not, there is no way to implement retry-logic with a timer.

**Comment by PhlexPlexico** [comment]
I don't have the time to test, but maybe something like [`GetCurrentMap`](https://www.sourcemod.net/new-api/halflife/GetCurrentMap) may work and return a workshop ID instead of the map name?

**Comment by nickdnk** [comment]
No, that returns the name of the map.

**Comment by GekasD** [comment]
What do you mean by current workshop id of a map?, also did you try GetCurrentMap on a workshop map? it returns it in the format workshopid/mapname but i could be wrong

**Comment by PhlexPlexico** [comment]
> What do you mean by current workshop id of a map?, also did you try `GetCurrentMap` on a workshop map? it returns it in the format `workshopid/mapname` or `workshop/workshopid/mapname` but i could be wrong

Basically if the map fails to load, there should still be a periodic check to retry and maybe a global timer and message that will cancel the match if it fails to load the map. And I haven't checked but @nickdnk says it just loads the regular map name with no ID. I can't test so I'm unsure of the behaviour of it.

**Comment by nickdnk** [comment]
> What do you mean by current workshop id of a map?, also did you try `GetCurrentMap` on a workshop map? it returns it in the format `workshopid/mapname` or `workshop/workshopid/mapname` but i could be wrong

GetCurrentMap returns the name of the map, no the ID. So if you've provided an ID as a workshop map and the server attempts to load it, there is no function to call 10 seconds later to determine if that map was actually loaded, as we don't know the name of the map, only it's workshop ID.

**Comment by GekasD** [comment]
you could ping the steam workshop api and get its name that way, also why 10 seconds exactly? it could take longer than that to download a bigger map, i don't think its a good idea to rely on magic numbers like this

**Comment by nickdnk** [comment]
10 seconds was just an example, clearly.

If you can come up with a reliable way to solve this problem, do tell.

**Comment by GekasD** [comment]
Asked some people to get ideas on how to solve the auth key issue.
https://sourcemod.dev/#/commandline/function.GetCommandLine or
https://sourcemod.dev/#/commandline/function.GetCommandLineParam, could be used to get it.
