### ISSUE TITLE
How to disable knife round?

### ISSUE THREAD

**Issue by lugaamn** [splewis/get5#759]
when i use
Create match with current players --->Loaded match config.
Type !ready when you are ready to knife. 

i wanna to play without knife. how to edit and compile this config?

**Comment by Apfelwurm** [comment]
If you load a matchconfig with get5_loadmatch or get5_loadmatch_url you can set::

```
side_type: either "standard", "never_knife", or "always_knife"; standard means the team that doesn't pick a map gets the side choice, never_knife means team1 is always on CT first, and always knife means there is always a knife round
```
(see https://github.com/splewis/get5/blob/master/configs/get5/example_match.json)

But it seems like the function you are using (https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5/matchconfig.sp#L912) currently does not ask for that.

If you want to implement that by default, you should be able to add the line 
``` kv.SetString("side_type", "never_knife");``` 

after https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5/matchconfig.sp#L940.

Or you can add another arg (like in line 922-924) for that case.

**Comment by lugaamn** [comment]
public Action Command_CreateMatch(int client, int args) {
    kv.SetString("side_type", "never_knife");
  if (g_GameState != Get5State_None) {
    ReplyToCommand(client, "Cannot create a match when a match is already loaded");
    return Plugin_Handled;
  }

is it right?

then i compiled get5.cfg?
i got this error 

Compiling get5.sp...
SourcePawn Compiler 1.10.0.6522
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

get5.sp(25) : fatal error 183: cannot read from file: "json"

Compilation aborted.
1 Error.

Can u compile it get5.cfg

**Comment by dreaNN1337** [comment]
> If you load a matchconfig with get5_loadmatch or get5_loadmatch_url you can set::
> 
> ```
> side_type: either "standard", "never_knife", or "always_knife"; standard means the team that doesn't pick a map gets the side choice, never_knife means team1 is always on CT first, and always knife means there is always a knife round
> ```
> 
> (see https://github.com/splewis/get5/blob/master/configs/get5/example_match.json)
> 
> But it seems like the function you are using (
> 
> https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5/matchconfig.sp#L912
> 
> ) currently has no parameter to set that var.
> If you want to implement that by default, you should be able to add the line ` kv.SetString("side_type", "never_knife");`
> 
> after
> 
> https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5/matchconfig.sp#L940
> 
> .
> Or you can add another arg (like in line 922-924) for that case.

Doesnt work for me :(

**Comment by PhlexPlexico** [comment]
> fps6@1st:~/m6/serverfiles/csgo/addons/sourcemod/scripting$ ./compile.sh get5.sp
> 
> Compiling get5.sp... SourcePawn Compiler 1.10.0.6522 Copyright (c) 1997-2006 ITB CompuPhase Copyright (c) 2004-2018 AlliedModders LLC
> 
> get5.sp(25) : fatal error 183: cannot read from file: "json"
> 
> Compilation aborted. 1 Error. fps6@1st:~/m6/serverfiles/csgo/addons/sourcemod/scripting$
> 
> is it right?
> 
> then i compiled get5.cfg? i got this error
> 
> Compiling get5.sp... SourcePawn Compiler 1.10.0.6522 Copyright (c) 1997-2006 ITB CompuPhase Copyright (c) 2004-2018 AlliedModders LLC
> 
> get5.sp(25) : fatal error 183: cannot read from file: "json"
> 
> Compilation aborted. 1 Error.
> 
> Can u compile it get5.cfg

This is also because you're missing dependencies. Take a look at the build actions to see where it clines the `json.inc` folder and places it in the `include`.

**Comment by lugaamn** [comment]
public Action Command_CreateMatch(int client, int args) {
  kv.SetString("side_type", "never_knife");
  if (g_GameState != Get5State_None) {
    ReplyToCommand(client, "Cannot create a match when a match is already loaded");
    return Plugin_Handled;
  }
is it right?

but...
fps6@1st:~/m6/serverfiles/csgo/addons/sourcemod/scripting$ ./compile.sh get5.sp

Compiling get5.sp...
SourcePawn Compiler 1.10.0.6522
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2018 AlliedModders LLC

get5/eventlogger.sp(5) : error 139: could not find type "JSON_Object"
get5/eventlogger.sp(7) : error 139: could not find type "JSON_Object"
get5/eventlogger.sp(7) : error 116: no methodmap or class was found for JSON_Object
get5/eventlogger.sp(8) : error 104: cannot find any methods for int
get5/eventlogger.sp(8) : warning 215: expression has no effect
get5/eventlogger.sp(8) : warning 215: expression has no effect
get5/eventlogger.sp(8) : error 001: expected token: ";", but found ")"
get5/eventlogger.sp(8) : error 029: invalid expression, assumed zero
get5/eventlogger.sp(8) : fatal error 190: too many error messages on one line

Compilation aborted.
7 Errors.

**Comment by lugaamn** [comment]
`"Match"
{
	"matchid"		"LAN#1"
	"num_maps"		"1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

	"spectators" // players allowed in spectator (e.g., admins) should go here
	{
		"players"
		{
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	"skip_veto"		"1" // If set to 1, the maps will be preset using the first maps in the maplist below.

	"veto_first"	""  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.

	"side_type"		"never_knife" // Either "standard", "always_knife", or "never_knife"


	"players_per_team"		"5"
	"min_players_to_ready"		"0" // Minimum # of players a team must have to ready
	"min_spectators_to_ready"		"0" // How many spectators must be ready to begin.

	// These values wrap mp_teamprediction_pct and mp_teamprediction_txt.
	// You can exclude these if you don't want those cvars set.
	"favored_percentage_team1"		"65"
	"favored_percentage_text"		"HLTV Bets"

	"team1"
	{
		"name"		"" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
		"tag"		""  // Short tags replace the "clan tag" on the scoreboard. They are optional.
		"flag"		""
		"logo"		""
		"players"
		{
			// Any of the 3 formats (steam2, steam3, steam64 profile) are acceptable.
			// Note: the "players" section may be skipped if you set get5_check_auths to 0,
			// but that is not recommended. You can also set player names that will be forced here.
			// If you don't want to force player names, just use an empty quote "".
			"STEAM_0:1:52245092"		"splewis"
			"[U:1:104490185]"		""
			"76561198064755913"		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	"team2"
	{
		"name"		""
		"tag"		""
		"flag"		""
		"logo"		""
		"players"
		{
			"STEAM_1:1:46796472"		""
			"STEAM_1:0:78189799"		""
			"STEAM_1:0:142982"		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	// These will be executed on each map start or config load.
	// You should not use this as a replacement for the cfg/get5/live.cfg config.
	"cvars"
	{
		"hostname"		"1sT.MN - Get5 LAN #1"
	}

}`

I can make the knife not work like this, but it doesn't work here. TEAM_NAME1 vs TEAM_NAME2 doesn't work on the hostname.

**Comment by PhlexPlexico** [comment]
If you're using the above template, it's because team1 and team2 name fields are blank. Try adding in a name for each of those teams. If you're having trouble understanding what everything does in the cfg file, please look at the wiki for further information on what specific key value pairs do!

**Comment by lugaamn** [comment]
This is not a server for Tournament or Series, so I thought I would not use cfg.  I understand that it is right to use cfg if I do any competitions.  It's nice to see team names appear on the steam hostname when people just come in and start playing.  So in matchconfig.cfg, I want to make it start with a pistol, not a knife round.  The team name can be seen in the steam hostname with the names of the people on the server to call the create current player.  The problem is: it doesn't make sense to start a knife round again on the next map after playing one Map.

**Comment by lugaamn** [comment]
But I can't help but wonder how to add and compile the pistol round in the create match current player option on matchconfig.cfg.  Can anyone replace it with a get5.smx file?  then I would be very grateful.  Another problem tv_delay 105 seconds + mp_match_end_delay 15 Wait 2 minutes and start the next map a little longer.  Is there no other way to solve it?

**Comment by PhlexPlexico** [comment]
> This is not a server for Tournament or Series, so I thought I would not use cfg. I understand that it is right to use cfg if I do any competitions. It's nice to see team names appear on the steam hostname when people just come in and start playing. So in matchconfig.cfg, I want to make it start with a pistol, not a knife round. The team name can be seen in the steam hostname with the names of the people on the server to call the create current player. The problem is: it doesn't make sense to start a knife round again on the next map after playing one Map.

If it's a server meant for scrimming, then you would use the scrim template and adjust that as needed. I believe you can remove the hostname command and set the team names in the config as well, but it would be static. If you're looking for something to be more dynamic via the get5 menu, I don't think you're going to find what you need. I would suggest using a tool like a webpanel/API integrations to get what you want, as they would be more feature complete by dynamically building match configs. The scope of this project was to manage competitive matches, and just have light support for scrims (mainly via config files).

What you're asking for is (I believe) rather out of scope for the project, and you would be better off using something like pugsetup instead if you want to just have 10 people in a server and play.

And for the delay, either lower the tv delay as that will be your main issue. You can't swap maps without breaking the demo and your demos and anyone watching via gotv would be cut off then from the end of the match. 

If you want to make changes for these, the readme I believe states what dependencies are required in order to build as well.
