### ISSUE TITLE
Recording damage received as well as damage dealt

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#76]
As above, will look into this later.

**Comment by splewis** [comment]
I don't really see the point of adding this stat. Are there any specific conclusions you think this stat allows? I feel deaths covers anything I would imagine "damage received" allows.

**Comment by Technoblazed** [comment]
It'd be nice to be able to record how much damage a player has done per round over the course of the game.

**Comment by splewis** [comment]
Sorry, I was just referring to "damage received".

Damage dealt is already there: https://github.com/splewis/get5/blob/master/scripting/include/get5.inc#L168

**Comment by Technoblazed** [comment]
Cant actually remember to be honest, did this so long ago :(
