### ISSUE TITLE
Compile errors after trying to add new aliases

### ISSUE THREAD

**Issue by W4iv3lt** [splewis/get5#763]
Hello,

I was trying to add new aliases to the get5.sp but when I am compiling the file with the compile.exe, I only get errors.
I have installed:         get5: v0.7.2
                           sm_json: v4.1.0
                      sourcemod: 1.10 - build 6542

----------------------------------------------------------------
Compiler:
get5.sp

get5/jsonhelper.sp(33) : error 105: cannot find method or property JSON_Object.GetKeyType
get5/jsonhelpers.sp(33) : warning 213: tag mismatch
get5/jsonhelpers.sp(131) : error 017: undefined symbol "json_is_meta_key"
get5/matchconfig.sp(545) : error 017: undefined symbol "json_is_meta_key"

3 Errors.

---------------------------------------------------------------

For the beginning, I only added the alias:
AddAliasedCommand("R", Command_Ready, "Marks the client as ready");

Could you explain me what is missing there or how it could be fixed because I want to edit other scripts for other features afterwards, too.
Thanks.

**Comment by PhlexPlexico** [comment]
Do you have the sm_json includes file in your includes directory? This error just means you're missing the includes, usually.

**Comment by W4iv3lt** [comment]
Right now, I am not at the pc but far as I know I added the Json.nic in the include folder as well as the folder json which were also in the include folder of sm_json

**Comment by nickdnk** [comment]
Hello.

Please join the Discord if you need help with stuff like this. GitHuB issues are not the place for this.
