### ISSUE TITLE
[Bug] Team names not switching after halftime

### ISSUE THREAD

**Issue by anon-is-anonymus** [splewis/get5#768]
Currently using plugin version 0.7.2

Hi everyone. Currently experiencing a bug where the team names don't switch sides after half time.

Example:
Round 15: Team A 10 - 4 Team B
Round 16: Team A 4 - 11 Team B
Round 17: Team B 4 - 12 Team A

Was this fixed in later releases?

Thanks for any help!

**Comment by anon-is-anonymus** [comment]
The demo for that specific match is [here](https://drive.google.com/file/d/1aLJEeaZQB5bLNfLRJE36tAU01yJduCtA/view?usp=sharing)

**Comment by nickdnk** [comment]
Please try the latest dev build and report back. There are a lot of bugs in the version you're using.

You can download it here: https://github.com/splewis/get5/suites/7187249388/artifacts/286893038

**Comment by nickdnk** [comment]
Also, make sure you have disabled all other plugins.

**Comment by anon-is-anonymus** [comment]
Will do I'll let you know if its fixed soon

**Comment by anon-is-anonymus** [comment]
Hey just got back from producing the matches and the team names still aren't switching. Any advice? I forgot to enable the debug log unfortunately I'll turn it on for the next match we play on the server

**Comment by nickdnk** [comment]
No idea. It works with that version. I use it myself. Do you have any other plugins or some logs that could be helpful?

**Comment by nickdnk** [comment]
Post your get5 config file and the output of "sm plugins list" from console.

**Comment by anon-is-anonymus** [comment]
get5 config:
// This file was auto-generated by SourceMod (v1.10.0.6540)
// ConVars for plugin "get5.smx"


// Whether or not technical pauses are allowed
// -
// Default: "1"
get5_allow_technical_pause "1"

// Whether to automatically mark players as ready if they kill anyone in the warmup or veto phase.
// -
// Default: "0"
get5_auto_ready_active_players "0"

// Name of a match config file to automatically load when the server loads
// -
// Default: ""
get5_autoload_config ""

// Whether the get5 backup system is enabled
// -
// Default: "1"
get5_backup_system_enabled "1"

// If set to 0, get5 will not force players to the correct team based on steamid
// -
// Default: "1"
get5_check_auths "1"

// Format of the damage output string. Avaliable tags are in the default, color tags such as {LIGHT_RED} and {GREEN} also work.
// -
// Default: "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"
get5_damageprint_format "--> ({DMG_TO} dmg / {HITS_TO} hits) to ({DMG_FROM} dmg / {HITS_FROM} hits) from {NAME} ({HEALTH} HP)"

// Format for demo file names, use "" to disable
// -
// Default: "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"
get5_demo_name_format "{MATCHID}_map{MAPNUMBER}_{MAPNAME}"

// Whether to wait for map vetos to be printed to GOTV before changing map
// -
// Default: "0"
get5_display_gotv_veto "0"

// Whether to end the match if all players disconnect before ending. No winner is set if this happens.
// -
// Default: "0"
get5_end_match_on_empty_server "0"

// Path to use when writing match event logs, use "" to disable
// -
// Default: ""
get5_event_log_format ""

// If set to non-zero, this will be the fixed length of any pause
// -
// Default: "0"
get5_fixed_pause_time "30"

// Template that the server hostname will follow when a match is live. Leave field blank to disable. Valid parameters are: {MAPNUMBER}, {MATCHID}, {SERVERID}, {MAPNAME}, {TIME}, {TEAM1}, {TEAM2}
// -
// Default: "Get5: {TEAM1} vs {TEAM2}"
get5_hostname_format "Get5: {TEAM1} vs {TEAM2}"

// Whether or not admins with the changemap flag will be immune to kicks from "get5_kick_when_no_match_loaded". Set to "0" to disable
// -
// Default: "1"
get5_kick_immunity "1"

// Whether the plugin kicks new clients when no match is loaded
// -
// Default: "0"
get5_kick_when_no_match_loaded "0"

// Config file to exec when the game goes live
// -
// Default: "get5/live.cfg"
get5_live_cfg "get5/live.cfg"

// Number of seconds used to count down when a match is going live
// -
// Default: "10"
// Minimum: "5.000000"
// Maximum: "60.000000"
get5_live_countdown_time "10"

// Number of seconds before a backup file is automatically deleted, 0 to disable
// -
// Default: "160000"
get5_max_backup_age "160000"

// Maximum number of time the game can spend paused by a team, 0=unlimited
// -
// Default: "300"
get5_max_pause_time "300"

// Maximum number of pauses a team can use, 0=unlimited
// -
// Default: "0"
get5_max_pauses "4"

// The tag applied before plugin messages.
// -
// Default: "[{YELLOW}Get5{NORMAL}]"
get5_message_prefix "[{YELLOW}Get5{NORMAL}]"

// Whether pausing is allowed.
// -
// Default: "1"
get5_pausing_enabled "1"

// Whether all JSON output is in pretty-print format.
// -
// Default: "1"
get5_pretty_print_json "1"

// Whether damage reports are printed on round end.
// -
// Default: "0"
get5_print_damage "1"

// Adds [READY] [NOT READY] Tags before Team Names. 0 to disable it.
// -
// Default: "1"
get5_ready_team_tag "1"

// Whether pause limits will be reset each halftime period
// -
// Default: "1"
get5_reset_pauses_each_half "0"

// Integer that identifies your server. This is used in temp files to prevent collisions.
// -
// Default: "0"
get5_server_id "0"

// Whether to set client clan tags to player ready status.
// -
// Default: "1"
get5_set_client_clan_tags "1"

// Where match stats are saved (updated each map end), set to "" to disable
// -
// Default: "get5_matchstats_{MATCHID}.cfg"
get5_stats_path_format "get5_matchstats_{MATCHID}.cfg"

// Whether clients can use the !stop command to restore to the last round
// -
// Default: "1"
get5_stop_command_enabled "1"

// Time format to use when creating file names. Don't tweak this unless you know what you're doing! Avoid using spaces or colons.
// -
// Default: "%Y-%m-%d_%H"
get5_time_format "%Y-%m-%d_%H"

// Time (in seconds) a team has to make a !stay/!swap decision after winning knife round, 0=unlimited
// -
// Default: "60"
get5_time_to_make_knife_decision "60"

// Time (in seconds) teams have to ready up before forfeiting the match, 0=unlimited
// -
// Default: "0"
get5_time_to_start "0"

// Time (in seconds) from presenting a veto menu to a selection being made, during which a confirmation will be required, 0 to disable
// -
// Default: "2.0"
get5_veto_confirmation_time "10.0"

// Seconds to countdown before veto process commences. Set to "0" to disable.
// -
// Default: "5"
get5_veto_countdown "5"

// Config file to exec in warmup periods
// -
// Default: "get5/warmup.cfg"
get5_warmup_cfg "get5/warmup.cfg"

sm plugins list:
[SM] Listing 21 plugins:
  01 "OFL Anti Cheat" (1.3.0) by Online Fighting League
  02 "Admin Menu" (1.11.0.6902) by AlliedModders LLC
  03 "Get5" (0.8.0-dev) by splewis
  04 "Basic Comm Control" (1.11.0.6902) by AlliedModders LLC
  05 "Anti-Flood" (1.11.0.6902) by AlliedModders LLC
  06 "OFL Updater" (1.2.5) by OFL & GoD-Tony
  07 "Sound Commands" (1.11.0.6902) by AlliedModders LLC
  08 "Basic Ban Commands" (1.11.0.6902) by AlliedModders LLC
  09 "Admin File Reader" (1.11.0.6902) by AlliedModders LLC
  10 "Client Preferences" (1.11.0.6902) by AlliedModders LLC
  11 "Basic Info Triggers" (1.11.0.6902) by AlliedModders LLC
  12 "Reserved Slots" (1.11.0.6902) by AlliedModders LLC
  13 "Admin Help" (1.11.0.6902) by AlliedModders LLC
  14 "Basic Votes" (1.11.0.6902) by AlliedModders LLC
  15 "Fun Votes" (1.11.0.6902) by AlliedModders LLC
  16 "Player Commands" (1.11.0.6902) by AlliedModders LLC
  17 "Basic Commands" (1.11.0.6902) by AlliedModders LLC
  18 "Fun Commands" (1.11.0.6902) by AlliedModders LLC
  19 "Basic Chat" (1.11.0.6902) by AlliedModders LLC
  20 "Get5 MySQL stats" (0.7.2) by splewis
  21 "Nextmap" (1.11.0.6902) by AlliedModders LLC

**Comment by PhlexPlexico** [comment]
Quick question as well, how are you setting up the matches? Are you using a match config file, or using the menu and starting scrims?

Thanks!

**Comment by anon-is-anonymus** [comment]
I'm loading the matches through get5_loadmatch_url

The repo with all my configs is [here](https://github.com/anon-is-anonymus/get5-configs) if u wanna look thru em too

**Comment by PhlexPlexico** [comment]
Okay well I notice some of your games have no teams really defined; by any chance is this bug happening when `get5_check_auths` is set to 0?

**Comment by anon-is-anonymus** [comment]
Yea looks like it happens when "get5_check_auths" is set to both 0 and 1. Sent a few examples of wat I mean below

0 (Played on V0.7.2):
![image](https://user-images.githubusercontent.com/68243858/177353195-4d5e8821-88dc-4f41-8bce-7d1d7d5dba08.png)
![image](https://user-images.githubusercontent.com/68243858/177353244-d18a0dd4-5e83-4b3e-9c59-01fcfa17f707.png)

1 (Played on V8.0.0 dev version):
![image](https://user-images.githubusercontent.com/68243858/177353562-5d82a10b-4bf5-4d8f-997e-84ff48f91bf4.png)
![image](https://user-images.githubusercontent.com/68243858/177353614-b0450988-6408-4281-9822-5ca498363cf5.png)

**Comment by nickdnk** [comment]
I played a match last night and looked for this, and it did swap the names after round 15 as expected. Just confirming that it's not a consistent issue with any of the newer builds.

**Comment by anon-is-anonymus** [comment]
Worked for me in my most recent match too, I'll continue to monitor also though in case its just some random glitch or smt

**Comment by nickdnk** [comment]
Reopen this if you can reproduce the issue @anon-is-anonymus.
