### ISSUE TITLE
Remove GitHub Wiki

### ISSUE THREAD

**Issue by nickdnk** [splewis/get5#774]
Hey

Just a reminder to remove the GitHub wiki from Get5. We've moved the docs to mkdocs and built it into the repo.

I'll be doing some work on the docs tonight, removing outdated info and making sure we got it all.

**Comment by nickdnk** [comment]
Also probably take away the discussions tab. Issues + Discord is enough, no?

**Comment by PhlexPlexico** [comment]
By the looks of it, the github wiki has been removed in favour of our docs site [here](splewis.github.io/get5/) :)
