### ISSUE TITLE
[Feature Request] Make clan tags similar to team names.

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#78]
It will be wonderful to see that clan tags auto becomes clan tag in both chat and scoreboard. The example plugin is available on alliedmodders callee Country Tag. It has great features and force users to auto update clan tags even if they keep on using scripts.

**Comment by splewis** [comment]
I'm fine with adding "short names" in addition to team names. I imagine their only use would be for display in the clan tag.

**Comment by splewis** [comment]
Done as part of 7d3c883e07d7cdeb29486f16adc0a322047120f3
