### ISSUE TITLE
Knife round in scrim doesn't seem to work

### ISSUE THREAD

**Issue by AdrianMrn** [splewis/get5#80]
### Expected behavior
When using !get5_scrim and setting side_type to "always_knife", I expected there to be a knife round.
"standard" didn't let me pick sides either.

### Actual behavior
There wasn't a knife round.

I was trying it with only 2 people on the server. The rest of the match ran fine.

### Steps to reproduce
- Plugin version: 0.4.0
- Sourcemod version: 1.8.0.5946

My scrim_template.cfg:

```
"Match"
{
	"side_type"		"always_knife"
	"players_per_team"		"5"

	"cvars"
	{
		"mp_halftime_duration"		"15"
		"mp_match_can_clinch"		"0" // Forces 30-round playout
		"mp_overtime_enable"		"0"
		"get5_max_pause_time"		"0"
		"get5_check_auths"		"0"
		"get5_demo_name_format"		"scrim_{TIME}_{MAPNAME}"
	}
}
```

**Comment by splewis** [comment]
Thanks for reporting this, I pushed a [prospective fix](https://github.com/splewis/get5/commit/9517b0f3fbe0ea5116f7d0a0ba69a0a66cfd8b01). You can try an updated development build from https://ci.splewis.net/job/get5/ (just replacing addons/sourcemod/plugins/get5.smx is sufficient)

After these changes, you'd want a slightly updated scrim_template.cfg file though:
adding
```
"maps_to_win" "1"
"skip_veto" "1"
```

**Comment by AdrianMrn** [comment]
Sweet, seems to be working!
