### ISSUE TITLE
Choose side - Knife

### ISSUE THREAD

**Issue by wunderno** [splewis/get5#81]
When we vetoed map with "side_type standard" we still have to knife about sides when the map changes. As the description says the "standard means the team that doesn't pick a map gets the side choice" seems not to work.

**Comment by Technoblazed** [comment]
@wunderno Standard actually means:

BO1: Knife Round
BO2/3/5/7: Whoever picks a map, the other team will then choose the side to play on that map.

Essentially in BO1, it's always a knife.

**Comment by wunderno** [comment]
Ohh, then its my bad!

**Comment by splewis** [comment]
FYI: this is described in https://github.com/splewis/get5/wiki/Map-Vetoes
