### ISSUE TITLE
Alternative get5_scrim usage

### ISSUE THREAD

**Issue by splewis** [splewis/get5#84]
Instead of get5_scrim requiring these loose settings for steamids (get5_force_auths 0, no steamids set via match config), it could let the server operator set one team (i.e. the team owning the server) in their match config as a "home" team, and then let get5 infer that anyone *not* in that list, is on the other team.

This has the advantage of forcing teams correctly, which simplifies actual in-game use at the cost of a small amount of (one-time) config work.

**Comment by Technoblazed** [comment]
Yay 🎆

**Comment by splewis** [comment]
Done.
