### ISSUE TITLE
Add option for boX to `get5`

### ISSUE THREAD

**Issue by nickdnk** [splewis/get5#848]
We should provide additional options in the menu, such as the option to set up a BoX with map veto using current players. This would also bring the functionality of get5 closer to pugsetup, which seems to be slightly neglected and is missing many of the great features of get5.

**Comment by TandelK** [comment]
Would be only reliable for Scrim Setup. For normal Get5 setup, it is not at all required as for what is intended for.

**Comment by nickdnk** [comment]
I don’t understand what you mean. Why would we not be able to create a bo3 when we can create a bo1? The get5 menu does not create a scri; it calls get5_creatematch internally.
