### ISSUE TITLE
Recompiling the Plugin with smjansson.inc error

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#85]
### Expected behavior
Should compile properly.

### Actual behavior

Get5 recompiling using smjansson.inc and getting a error 

/sourcemod/scripting/include/smjansson.inc(66) error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as a identifier
/sourcemod/scripting/include/smjansson.inc(67) error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as a identifier

2 Errors
### Steps to reproduce
1) Download Get5, Linux Sourcemod , Metamod and Metamod vdf , Smjanssson and system2 files
2) Edit Get5 Native file for Prefix.
3) Open Terminal in Linux and go to Sourcemod/Scripting path.
Once in Scripting path type ./compile.sh
This will start compiling all the plugins. 

- Plugin version:  get5 verison 0.4.0
- Sourcemod version: - 1.8.0-git5950-linux
- SMJansoon plugin from official Github version.

**Comment by splewis** [comment]
You're probably using an older version of the system2 include.

[This](https://github.com/splewis/get5/blob/master/.travis.yml#L29) is how the plugin is compiled on travis CI - which is taking the latest System2 include version on github, and that works fine.
