### ISSUE TITLE
Menu for ready/not ready?

### ISSUE THREAD

**Issue by Technoblazed** [splewis/get5#87]
Not really completely necessary if you don't feel like it, but I'd like a sourcemod panel on the left of my screen to display clients that are ready/not ready :o 

If not, don't worry about it :D

**Comment by splewis** [comment]
I don't plan on adding this. Adding sourcemod menus like these is very tacky and unnecessary, imo.

**Comment by Technoblazed** [comment]
Possible cvar for a hud feature then? i.e. Player count that is ready, and you are not readied up etc.?
