### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Bunker56** [splewis/get5#870]
Russian translation for version [Nightly 0.11.0-a12501f](https://github.com/splewis/get5/releases/tag/v0.11.0-a12501f)
[get5.phrases.txt](https://github.com/splewis/get5/files/9538315/get5.phrases.txt)

I tried to make the translation as complete as possible.

**Comment by nickdnk** [comment]
Hey

Thanks for this. Can you open a pull-request targeting the develop branch instead?

**Comment by Bunker56** [comment]
I tried, for some reason it does not allow me to open

**Comment by nickdnk** [comment]
Click fork, push the changes to your own repository, then a button appears on top of get5 where it attests you open a PR because your branch had changed.

**Comment by nickdnk** [comment]
@Bunker56 See #872.

**Comment by nickdnk** [comment]
Closing as we're tracking this in PR and it's not an actual issue.
