### ISSUE TITLE
Cannot enter get5_web_api_url because double forward slash starts comment

### ISSUE THREAD

**Issue by paoloposo** [splewis/get5#873]
I cannot figure out how to set the `get5_web_api_url` cvar. If I enable debug messages with `get5_debug 1` and then try to set the url with `get5_web_api_url "http://somehost"`, I get this in the console:

    [get5_api] get5_web_api_url now set to https:/

Everything after the colon is cut (and then get5 adds the trailing slash). [This](https://developer.valvesoftware.com/wiki/CFG) states that everything after two forward slashes is regarded as a comment. **So how can I enter the URL then?** Am I missing something blatantly obvious? I searched for how to escape forward slashes, but couldn't find anything. I also tried escaping them with a backward slash, but no luck.

Plugin version is 0.10.1.

**Comment by PhlexPlexico** [comment]
So your example is a bit confusing here - I assume in your actual implementation you're using https? Where are you entering this value? In a config, or setting via console? I believe if you wrap it in quotes it should work. As an example using rcon

```
rcon get5_web_api_url https://somehost.com/
```

Should set it on the server. You can then pipe it back by just running `rcon get5_web_available`

If you're using a config, using quotes should be enough to avoid cfg files treating it as a comment.

**Comment by Apfelwurm** [comment]
This is strange. Do you plan to load a config in the future? That way it is working for sure currently

**Comment by nickdnk** [comment]
Can you try it without `rcon`, directly on the server, just to rule out that this is causing problems?

**Comment by paoloposo** [comment]
Hm, when I tried it using the server conf before it didn't work. Must have done something wrong because it works now that I tried it again. I made a config file with the following content

    get5_web_api_url "https://somehost/"

and then executed using `rcon exec`. That worked. Now I get this output:

```
] rcon exec set_api_url.cfg
[get5_api] get5_web_api_url now set to https://somehost/
] rcon get5_web_api_url
"get5_web_api_url" = "https://somehost" ( def. "" )            - URL the get5 api is hosted at
] rcon get5_web_available
{
    "available": 1,
    "gamestate": 7,
    "plugin_version": "0.10.1"
}
```

Instead of somehost I have actually used a host where a web server is listening. But it doesn't get any requests. The game server is running in a container (using the `cm2network/csgo` image) and I verified that the web server can be reached by running a curl from within the container. Do I have to configure any more settings for the stats to be sent? I didn't yet start any game via the get5 configuration files. I just used the "Create match with current players" option from the chat menu.

**Comment by Apfelwurm** [comment]
Basically if the get5_web_api_url is set, you should get the first request as soon as you create a match and you have mp_teamlogo_1 / mp_teamlogo_2 set or if not the first request will be made when the match goes live. I recommend to take a look into scripting/get5_apistats.sp as it is not really difficult to read, even if you dont really understand sourcepawn.

**Comment by Apfelwurm** [comment]
what version of sourcemod and metamod and steamworks.inc are you using? we had issues in the past related to missing root ca certs after some big certificate issuer changed root certificates. The fastest way to check if there is any basic problem with the https certificate or the communication is that you place a test.json on your webserver for example:
```
{
    "min_spectators_to_ready": 0,
    "skip_veto": false,
    "veto_first": "team1",
    "side_type": "standard",
    "maplist": [
        "de_vertigo",
        "de_dust2",
        "de_inferno"
    ],
    "team1": {
        "name": "Team 4",
        "tag": "Team 4",
        "flag": "DE",
        "players": {
            "12345678901234567": "test"
        }
    },
    "team2": {
        "name": "Team 5",
        "tag": "Team 5",
        "flag": "DE",
        "players": {
            "12345678901234568": "test2"
        }
    },
    "matchid": "Match 123123123",
    "num_maps": 1,
    "players_per_team": "3",
    "min_players_to_ready": "3",
    "cvars": {
        "get5_web_api_url": "https://somehost"
    }
}
```
make sure it is working in your browser and then issue a 
`get5_loadmatch_url "https://somehost/test.json"` to see if the config gets loaded.

**Comment by paoloposo** [comment]
Ok, so I've got the server running properly now. Here is the version information:

<details>
  <summary>Plugin versions</summary>

```
meta version
 Metamod:Source Version Information
    Metamod:Source version 1.11.0-dev+1148
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Jun 26 2022 08:01:45
    Built from: https://github.com/alliedmodders/metamod-source/commit/4bdc218
    Build ID: 1148:4bdc218
    http://www.metamodsource.net/
```

```
sm version
 SourceMod Version Information:
    SourceMod Version: 1.11.0.6911
    SourcePawn Engine: 1.11.0.6911, jit-x86 (build 1.11.0.6911)
    SourcePawn API: v1 = 5, v2 = 16
    Compiled on: Aug  6 2022 16:36:14
    Built from: https://github.com/alliedmodders/sourcemod/commit/2f0ba0f3
    Build ID: 6911:2f0ba0f3
    http://www.sourcemod.net/
```

```
meta list
Listing 5 plugins:
  [01] SourceMod (1.11.0.6911) by AlliedModders LLC
  [02] CS Tools (1.11.0.6911) by AlliedModders LLC
  [03] SDK Tools (1.11.0.6911) by AlliedModders LLC
  [04] SteamWorks Extension (1.2.3) by Kyle Sanderson
  [05] SDK Hooks (1.11.0.6911) by AlliedModders LLC
```

```
get5_version
"get5_version" = "0.10.1" notify singleplayer replicated                         - Current get5 version
```
  
</details>


Using `get5_debug 1` I was able to consistently get these kinds of log messages:

```
[get5_api] Trying to create request to url http://192.168.1.2/match/3123/map/0/start
[get5_api] Trying to create request to url http://192.168.1.2/match/3123/map/0/update
[get5_api] Trying to create request to url http://192.168.1.2/match/3123/map/0/player/76561199243279823/update
```

Again, no request comes in at the server, but performing that same request using curl in the same container works.

**Comment by Apfelwurm** [comment]
Oh, one thing i noticed just now is that you have to set get5_web_api_key as well in the default implementation of apistats, if not, the CreateRequest returns INVALID_HANDLE without ever logging anything. Thats not ideal for sure. Try to set it to anything you want and try again.

**Comment by paoloposo** [comment]
Would you look at that, that made it work :D I knew it would be something simple, just didn't know what...

Thanks for your help!

**Comment by Apfelwurm** [comment]
Info for everyone might reading this in the future:
I could verify that this is indeed a problem when setting get5_web_api_url via rcon. 
If done via rcon, it fails whether the url is wrapped in quotes or not. 

so if you want to set get5_web_api_url manually, do it on the server console (wrapped with quotes) or via config
