### ISSUE TITLE
[Feature Request] Make MESSAGE_PREFIX a convar

### ISSUE THREAD

**Issue by potato20** [splewis/get5#88]
Pretty straightforward, essentially just have [this](https://github.com/splewis/get5/blob/master/scripting/get5/natives.sp#L2) be configurable somehow.

**Comment by Technoblazed** [comment]
https://github.com/splewis/get5/issues/30

--- 

https://github.com/splewis/get5/pull/73

**Comment by splewis** [comment]
I haven't decided if I want that added or not yet.

**Comment by splewis** [comment]
This has been added.
