### ISSUE TITLE
mp_match_restart_delay 15 not working as expected

### ISSUE THREAD

**Issue by 1stator** [splewis/get5#884]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
mp_match_restart_delay 15

The game would restart once it ends after 15 seconds

### Actual behavior

it says mp_match_restart_delay 15 in the live.cfg and even when the game itself is active, but once the game ends, it goes to 120, and i cant force end the map either nor select a team

### Steps to reproduce

i dont really know, im not sure what we're doing wrong. the game says one thing then it changes to 120, as per above, at the end

Please note that "latest" is **NOT** a version! In order to get the version, please use `get5_version` in the server console, or `get5_debuginfo` and attach the file located at `addons/sourcemod/logs/get5_debuginfo.txt`.

- Plugin version: 0.10.2
- Sourcemod version: 1.10.0.6544
- Steps to reproduce (please be specific): i dont really know, im not sure what we're doing wrong. the game says one thing then it changes to 120, as per above, at the end

**Comment by 1stator** [comment]
i did some extra research, and i think it was because gotv is enabled. i cant test it right now, but that might fix it, i will update this ticket when i can next try

**Comment by nickdnk** [comment]
Reduce your GOTV delay. See https://splewis.github.io/get5/latest/gotv/.
