### ISSUE TITLE
Encode json unicode->UTF8?

### ISSUE THREAD

**Issue by 0-BuTaJIuK-0** [splewis/get5#892]
"get5_version" = "0.10.5"

return of the "get_status" command
![bd232655-936b-4733-b0e4-0ad5efdc2ec9](https://user-images.githubusercontent.com/44897927/195357285-293e3e7f-8d0d-4dee-b2da-33e54c4d8209.jpg)
![photo_2022-10-12_16-33-07](https://user-images.githubusercontent.com/44897927/195357291-1ac95ddf-4396-4a0e-aa11-1fda14532bd4.jpg)

**Comment by nickdnk** [comment]
What is the problem exactly? Those are escaped unicode characters and are perfectly valid JSON.

**Comment by nickdnk** [comment]
And it spells out: `ᴋᴇᴠʟ (ɴᴏᴛ ɢᴀʏ)`.

**Comment by 0-BuTaJIuK-0** [comment]
Why is there a normal nickname in one case, and unicode in the second?

**Comment by nickdnk** [comment]
> Why is there a normal nickname in one case, and unicode in the second?

I don't understand the question. Unicode symbols are escaped, regular characters are not.

**Comment by 0-BuTaJIuK-0** [comment]
Nickname player: 𝓐𝓩𝓘𝓚𝟒𝓘𝓚 Т
 
get5_status return:
"name": "team_\u1d4d\u1d4e\u1d4d\u1d4d\u1d7d\u1d4d\u1d4d \u0422"

It is not endcode
