### ISSUE TITLE
If tv_enable is 0, should we skip overriding mp_match_restart_delay?

### ISSUE THREAD

**Issue by potato20** [splewis/get5#90]
Is it possible to maybe call IsTVEnabled() here

https://github.com/splewis/get5/blob/master/scripting/get5/goinglive.sp#L32

to not override the value of `mp_match_restart_delay` in case the user has gotv off (i.e. tv_enable 0), so that it can use the user-defined value?

Thanks.

**Comment by Technoblazed** [comment]
@potato20 Just set your tv_delay to 0 ?

**Comment by splewis** [comment]
The purpose of the override (`` + MATCH_END_DELAY_AFTER_TV + 5``) is to ensure that the end-game panel is shown long enough and the server doesn't follow the default CS:GO server behavior and try to change map - we want get5 to handle any mapchanges needed for the series. (if only 1 map, we still want the kick event to happen before the server tries to change maps on its own)

I think a better fix is just to not use ``tv_delay`` (or treat it as 0) if ``tv_enable 0`` is set.

**Comment by splewis** [comment]
I'm just going to treat tv_delay as 0 if tv_enable is also 0. Let me know if that doesn't fix your concern.
