### ISSUE TITLE
Crash when Match is end

### ISSUE THREAD

**Issue by Iwhite67** [splewis/get5#913]
Hello

Some people have a memory leak in end of match
i see is just after stop record + demo upload

i preconise here to add tv_delay at MATCH_END_DELAY_AFTER_TV 

if tv_delay 90, stop record at 90 + 15 after end match on switchmap at 90+15+xx

https://github.com/splewis/get5/blob/dedc8b65b6a7f1ebf4a4eb21683c886b1c973d86/scripting/get5.sp#L1279-L1286

**Comment by nickdnk** [comment]
This is apparently not fixable without extending the recording. I have added an option in this PR which lets user do that if they have this bug.

https://github.com/splewis/get5/pull/914
