### ISSUE TITLE
Suggestion: Wording for Veto mode

### ISSUE THREAD

**Issue by dudleycodes** [splewis/get5#920]
Amazing mod - we just used it during a charity LAN tournament and it worked great!

There was some confusion with veto mode; where the words "VETO" and "VOTE" looked very similar, resulting in players picking a map they wanted to veto.

Perhaps, changing the word "VETO" to "BAN" and "VOTE" to "PICK" would make it a little more clear.

Thanks for considering!

**Comment by nickdnk** [comment]
We can do this in 0.12.
