### ISSUE TITLE
[Feature Request] Events for pause start/stop

### ISSUE THREAD

**Issue by nickdnk** [splewis/get5#924]
There should be an event for when a pause **starts** and **ends**. Currently, there is only an event when the pause is called for and called for to end. This event should fire during freezetime, either in the first second if a pause is pending or immediately if a pause is called during freezetime.

With this event, it would be easier to build integrations that for instance mute/unmute certain people on other software, such as Discord or TeamSpeak, in relation to pauses.

**Comment by Iwhite67** [comment]
If you make this, you need to send if is a tech or tac

**Comment by nickdnk** [comment]
Yes, of course.
