### ISSUE TITLE
get5_loadmatch, get5_endmatch 

### ISSUE THREAD

**Issue by lugaamn** [splewis/get5#931]
When the get5_loadmatch command is run, it automatically goes to the de_ancient map instead of going to the de_cache and de_train maps. I also tried it on the latest version 0.11.0, but it was the same. What I want is to have a WARMUP before the game.

- Plugin version: "Get5" (0.8.0-dev+545) by splewis
- Sourcemod version: SourceMod Version: 1.12.0.6936

it's my get5.cfg
`"Match"
{
	"matchid"		"LAN #5"
	"num_maps"		"1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

	"spectators" // players allowed in spectator (e.g., admins) should go here
	{
		"players"
		{
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
			"STEAM_1:1:....."		""
		}
	}

	"skip_veto"		"1" // If set to 1, the maps will be preset using the first maps in the maplist below.

	"veto_first"	"team1"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.

	"side_type"		"never_knife" // Either "standard", "always_knife", or "never_knife"

	"players_per_team"		"5"
	"min_players_to_ready"		"0" // Minimum # of players a team must have to ready
	"min_spectators_to_ready"		"0" // How many spectators must be ready to begin.

	// These values wrap mp_teamprediction_pct and mp_teamprediction_txt.
	// You can exclude these if you don't want those cvars set.
	"favored_percentage_team1"		"65"
	"favored_percentage_text"		"HLTV Bets"

	"team1"
	{
		"name"		"" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
		"tag"		""  // Short tags replace the "clan tag" on the scoreboard. They are optional.
		"flag"		"MO"
		"logo"		""
		"players"	""
	}

	"team2"
	{
		"name"		""
		"tag"		""
		"flag"		"MO"
		"logo"		""
		"players"	""
	}

	// These will be executed on each map start or config load.
	// You should not use this as a replacement for the cfg/get5/live.cfg config.
	"cvars"

}`

**Comment by Iwhite67** [comment]
```
"Match"
{
"matchid" "LAN https://github.com/splewis/get5/issues/5"
"num_maps" "1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

"maplist": [
    "de_cache",
  ],

"spectators" // players allowed in spectator (e.g., admins) should go here
{
	"players"
	{
		"STEAM_1:1:....."		""
		"STEAM_1:1:....."		""
		"STEAM_1:1:....."		""
	}
}

"skip_veto"		"1" // If set to 1, the maps will be preset using the first maps in the maplist below.

"veto_first"	"team1"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.

"side_type"		"never_knife" // Either "standard", "always_knife", or "never_knife"


"players_per_team"		"5"
"min_players_to_ready"		"0" // Minimum # of players a team must have to ready
"min_spectators_to_ready"		"0" // How many spectators must be ready to begin.

// These values wrap mp_teamprediction_pct and mp_teamprediction_txt.
// You can exclude these if you don't want those cvars set.
"favored_percentage_team1"		"65"
"favored_percentage_text"		"HLTV Bets"

"team1"
{
	"name"		"" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
	"tag"		""  // Short tags replace the "clan tag" on the scoreboard. They are optional.
	"flag"		"MO"
	"logo"		""
	"players"	""
}

"team2"
{
	"name"		""
	"tag"		""
	"flag"		"MO"
	"logo"		""
	"players"	""
}

// These will be executed on each map start or config load.
// You should not use this as a replacement for the cfg/get5/live.cfg config.
"cvars"
}```

try this, i add ```"maplist": [
    "de_cache",
  ],```

**Comment by lugaamn** [comment]
tried this. When changing to another map, it only goes to de_cache

**Comment by lugaamn** [comment]
"de_train"  ""
"de_dust2" ""
"de_mirage" ""
I tried all the maps, but this one only goes to the map on the top.

**Comment by lugaamn** [comment]
"MatchPoweredBy"
    {
        "en"        "Powered by {GREEN}Get5"

Does anyone know why it disappeared and it is on the latest version? I tried to replace it but I couldn't

**Comment by Iwhite67** [comment]
"num_maps" "1" -> "num_maps" "3"

**Comment by lugaamn** [comment]
yeah yeah i tried same :D 5 7 9 2 -1 0 all same

**Comment by nickdnk** [comment]
You clearly did something wrong, as this is not a problem anyone else has.

>     "MatchPoweredBy"
> 
>     {
> 
>         "en"        "Powered by {GREEN}Get5"
> 
> 
> 
> Does anyone know why it disappeared and it is on the latest version? I tried to replace it but I couldn't

This is not an option. You can remove this.

Please also post the output of `get5_status` and the console output from the server after you run the command.

**Comment by nickdnk** [comment]
Since you have custom translations, you probably didn't update them. Please make sure you update the translations folder and don't change any strings in there.

**Comment by nickdnk** [comment]
> When the get5_loadmatch command is run, it automatically goes to the de_ancient map instead of going to the de_cache and de_train maps. I also tried it on the latest version 0.11.0, but it was the same. What I want is to have a WARMUP before the game.
> 
> * Plugin version: "Get5" (0.8.0-dev+545) by splewis
> * Sourcemod version: SourceMod Version: 1.12.0.6936
> 
> it's my get5.cfg `"Match" { "matchid" "LAN #5" "num_maps" "1" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.
> 
> ```
> "spectators" // players allowed in spectator (e.g., admins) should go here
> {
> 	"players"
> 	{
> 		"STEAM_1:1:....."		""
> 		"STEAM_1:1:....."		""
> 		"STEAM_1:1:....."		""
> 	}
> }
> 
> "skip_veto"		"1" // If set to 1, the maps will be preset using the first maps in the maplist below.
> 
> "veto_first"	"team1"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.
> 
> "side_type"		"never_knife" // Either "standard", "always_knife", or "never_knife"
> 
> 
> "players_per_team"		"5"
> "min_players_to_ready"		"0" // Minimum # of players a team must have to ready
> "min_spectators_to_ready"		"0" // How many spectators must be ready to begin.
> 
> // These values wrap mp_teamprediction_pct and mp_teamprediction_txt.
> // You can exclude these if you don't want those cvars set.
> "favored_percentage_team1"		"65"
> "favored_percentage_text"		"HLTV Bets"
> 
> "team1"
> {
> 	"name"		"" // You should always set a team name, otherwise some chat messages will not make sense. If there is no true team name, use "Team1" at least.
> 	"tag"		""  // Short tags replace the "clan tag" on the scoreboard. They are optional.
> 	"flag"		"MO"
> 	"logo"		""
> 	"players"	""
> }
> 
> "team2"
> {
> 	"name"		""
> 	"tag"		""
> 	"flag"		"MO"
> 	"logo"		""
> 	"players"	""
> }
> 
> // These will be executed on each map start or config load.
> // You should not use this as a replacement for the cfg/get5/live.cfg config.
> "cvars"
> ```
> 
> }`

You also don't have any players defined in any of the teams. You must do this for both teams.

**Comment by nickdnk** [comment]
I will close this as it's not a Get5 bug, you just did not configure it right. You can ask for help in the Discord or read the documentation: https://splewis.github.io/get5/latest/match_schema/.
