### ISSUE TITLE
demo file should be uploaded before cvar restores(RestoreCvars)

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5#934]
Hi, I am having an issue on automated demo upload.

I set get5_demo_upload_url from get5_loadmatch_url command, and when match ends it restores to default.
So it does not upload demo on specified URL.
(Im sorry English is not my first language)

Perhaps because it was BO1.

### Expected behavior
Demo upload should be done before cvar restores
or
Demo upload should be done correctly even after cvar restores

### Actual behavior
get5_demo_upload_url restores to default ("") before demo upload.

### Steps to reproduce

- Plugin version: 0.11.0
- Sourcemod version: 1.11.0.6917
- Steps to reproduce (please be specific): 1:set get5_loadmatch_url via RCON or get5_loadmatch_url 2:game ends 3: get5_loadmatch_url  goes back to default ""

**Comment by nickdnk** [comment]
Hello

We can fix this in 0.12.

You should set your `get5_demo_upload_url` in your general Get5 config instead of the `cvars` to avoid this in the meantime. The same goes for `get5_demo_upload_header_key` and `get5_demo_upload_header_value`, if you set those.

**Comment by FlowingSPDG** [comment]
Hello!

I got it, I will set it via Get5 config next time. Thanks!

Oh okay, so there might be my misconfiguration there.
I'll dig into it more and let you know here!

**Comment by nickdnk** [comment]
Try this pre-release: https://github.com/splewis/get5/releases/tag/v0.12.0-a6dc21b

**Comment by FlowingSPDG** [comment]
Will do! Thank you!

**Comment by nickdnk** [comment]
Here: https://github.com/splewis/get5/releases/tag/v0.12.0-4c83ac7

We only have one prerelease available at a time, so just get the latest.
