### ISSUE TITLE
Can't compile script when including get5.inc

### ISSUE THREAD

**Issue by EllyssonMike** [splewis/get5#937]
I'm trying to compile a custom plugin using Get5.

I've put the get5.inc and all json dependency folder inside addons/sourcemod/scripting/include.
But I can't compile because I'm getting this errors below:

### Expected behavior
Be able to compile.

### Actual behavior

![image](https://user-images.githubusercontent.com/81710688/202586198-24873a43-ce2a-4e54-be26-16829a332772.png)

### Steps to reproduce

Install get5 following the steps reproduced in the docs.

Try to create a plugin. Move then to addons/sourcemod/scripting folder

Compile with spcomp or ./compile.sh
bash$: ./spcomp script_test.sp
or
bash$: ./compile.sh script_test.sp

Other scripts I am able to compile normally, but when I include 'get5.inc', I'm getting this errors.
I'm using the get5_api_stats.sp as reference, but no success.  

- SM-JSON version: 3.3.1
- SourcePawn Compiler version: 1.11.0.6916
- Plugin version: 0.10.5
- Sourcemod version: 1.11.0

**Comment by nickdnk** [comment]
Does it work on SM 1.10? We are still using that for compiling get5.

**Comment by nickdnk** [comment]
You also need SM JSON v4.

**Comment by EllyssonMike** [comment]
> Does it work on SM 1.10? We are still using that for compiling get5.

I will test now, thank you.

**Comment by EllyssonMike** [comment]
> You also need SM JSON v4.

I've tried with v4, but I got a lot more errors

**Comment by EllyssonMike** [comment]
Because the sm version, perhaps?

**Comment by nickdnk** [comment]
> > You also need SM JSON v4.
> 
> 
> 
> I've tried with v4, but I got a lot more errors

Regardless, it's not going to work ever on v3.

**Comment by EllyssonMike** [comment]
Thank you, I will try now with SM 1.10 and SM-JSON 4.1.1.

**Comment by EllyssonMike** [comment]
> > > You also need SM JSON v4.
> > 
> > 
> > I've tried with v4, but I got a lot more errors
> 
> Regardless, it's not going to work ever on v3.
Worked!!, thank you a lot! I've downgraded sm to 1.10 and upgraded sm-json to 4.1.1 and it work. Thanks!
