### ISSUE TITLE
event "demo_upload_ended", "demo_finished" is not fired

### ISSUE THREAD

**Issue by FlowingSPDG** [splewis/get5#943]
`demo_upload_ended`, `demo_finished` should be fired

### Expected behavior
context : https://github.com/splewis/get5/issues/934 / https://github.com/splewis/get5/pull/935
`demo_finished` / `demo_upload_ended` should be fired

### Actual behavior
`get5_remote_log_url` should not be changed before firing `demo_upload_ended`, `demo_finished `

### Steps to reproduce
- Plugin version: `v0.12.0-e2a134b`
- Sourcemod version: `1.11.0.6917`
- Steps to reproduce 1:set `get5_demo_upload_url ` and `get5_remote_log_url` 2. Finish BO1 series flow 3. event won't be fired

edit: I am receiving dem file from server correctly so those event itself should be fine

**Comment by nickdnk** [comment]
This is the same problem as the other one; you have `get5_remote_log_url` in your match config cvars instead of your get5 config.

**Comment by FlowingSPDG** [comment]
Yeah I'll put those cvar on get5config for now.
Just curious(not pushing), Will it be fixed on future release?

**Comment by nickdnk** [comment]
It's a bit harder to solve this in a clean way. The events use global variables, and not just the remote URL, which all get reset on match end. Ideally, match cvars should only contain stuff that's specific to the match being played, not generic server configuration.

**Comment by nickdnk** [comment]
@FlowingSPDG I considered a different approach than trying to maintain the cvar values "after they have been restored", which is essentially what is required as the demo upload _could_ take several minutes.

Instead, I propose we add a cvar, such as `get5_restore_cvars_on_end`, which you can then disable, and the Cvars from your match config won't reset at all. Would that work?

**Comment by FlowingSPDG** [comment]
> @FlowingSPDG I considered a different approach than trying to maintain the cvar values "after they have been restored", which is essentially what is required as the demo upload _could_ take several minutes.
> 
> Instead, I propose we add a cvar, such as `get5_restore_cvars_on_end`, which you can then disable, and the Cvars from your match config won't reset at all. Would that work?

Absolutely! I agree on this approach too
because I wanted to keep some cvars after match finish.
