### ISSUE TITLE
[BUG] Exception opening some log file when starting a match

### ISSUE THREAD

**Issue by potato20** [splewis/get5#95]
Getting this

```
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM] Exception reported: Could not open file "/csgo/csgo_ds/csgo/logs/get5_matchexample_match_event_log.log"
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM] Blaming: get5.smx
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM] Call stack trace:
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM]   [0] LogToFileEx
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM]   [1] Line 27, ./scripting/get5/eventlogger.sp::EventLogger_LogEvent
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM]   [2] Line 69, ./scripting/get5/eventlogger.sp::EventLogger_SeriesStart
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM]   [3] Line 112, ./scripting/get5/matchconfig.sp::LoadMatchConfig
83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM]   [4] Line 616, ./scripting/get5.sp::Command_LoadMatch
```

everytime i do a `loadmatch`. it doesn't crash the server or game, it just continues on.

**Comment by Technoblazed** [comment]
```83177e0fdffc_csgosod_csgo_1 | L 12/07/2016 - 18:33:24: [SM] Exception reported: Could not open file "/csgo/csgo_ds/csgo/logs/get5_matchexample_match_event_log.log"```

Does your system have permission to write to the directory?

**Comment by potato20** [comment]
I think that's the issue. Thanks.

**Comment by potato20** [comment]
Sorry for not doing my homework. I did have permissions to write there, it's just the the log file didn't exist nor the the `log` directory.

**Comment by potato20** [comment]
I manually created the file and it started logging there, no issues.

**Comment by Technoblazed** [comment]
Did you change your logging path? Because by default it goes to logs, not log

**Comment by Technoblazed** [comment]
Can you send me your example loadmatch command please ;)

**Comment by potato20** [comment]
I basically just run this `get5_loadmatch remote.json`. The json file itself is posted in #89

**Comment by potato20** [comment]
I just noticed this commit from 12 hrs ago https://github.com/splewis/get5/commit/905a0d65836b99d80505c02aca44fe563e94f76f

**Comment by potato20** [comment]
I guess we can mark this issue resolved?

**Comment by Technoblazed** [comment]
@potato20 test it again before you resolve.

**Comment by potato20** [comment]
Yup, I re-pulled and tested it again. Last commit fixed it.

**Comment by splewis** [comment]
That commit didn't "fix" anything. It just disabled a feature by default. If that feature breaks anything, that's a bug. 

As far as I can tell this is a user error with not having permissions to the directory the plugin was using. Since this feature is relatively esoteric I changed it to be disabled by default.

**Comment by potato20** [comment]
I did have permissions but the `logs` directory did not exist. When I manually created the `logs` directory, get5 created and wrote to the file just fine.

**Comment by Technoblazed** [comment]
`logs` file comes from default csgo, you probably disabled core csgo logging
