### ISSUE TITLE
can't edit sp file

### ISSUE THREAD

**Issue by lugaamn** [splewis/get5#950]
SourcePawn Compiler 1.11.0.6924
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

get5/matchconfig.sp(635) : warning 230: symbol "SM_INT64_SUPPORTED" is not a preprocessor symbol; this behavior is undefined and will be removed in the future
get5/matchconfig.sp(635) : error 017: undefined symbol "SM_INT64_SUPPORTED"
include/get5.inc(6) : error 417: cannot read from file: "json"
get5.sp(25) : error 417: cannot read from file: "json"

3 Errors.

Please note that "latest" is **NOT** a version! In order to get the version, please use `get5_version` in the server console, or `get5_debuginfo` and attach the file located at `addons/sourcemod/logs/get5_debuginfo.txt`.

- Plugin version: 2.0.7
- Sourcemod version: 1.11.0.6924
- Steps to reproduce (please be specific):

**Comment by nickdnk** [comment]
Get5 does not compile with SM 1.11.

You also don't have your JSON dependency correct. You need version 4.x of sm-json as a git submodule.

We have no plugin version 2.0.7, so I don't know what that means.

**Comment by lugaamn** [comment]
Plugin version is mistaken, Version 0.11.0
sorry i installed json and 

./include/SteamWorks.inc(273) : error 183: brackets after variable name indicates a fixed-size array, but size is missing or not constant
./include/SteamWorks.inc(274) : error 183: brackets after variable name indicates a fixed-size array, but size is missing or not constant
./include/SteamWorks.inc(275) : error 183: brackets after variable name indicates a fixed-size array, but size is missing or not constant
include/get5.inc(1724) : warning 219: local variable "Get5Event" shadows a variable at a preceding level

3 Errors.

The same error occurs again

**Comment by nickdnk** [comment]
You have an older version of the SteamWorks include that does not compile with SM 1.11, and Get5 itself won't compile on 1.11 yet either. You have to use SM 1.10.

Why are you compiling the plugin yourself? It shouldn't be necessary.

**Comment by lugaamn** [comment]
Done. Just learning how to edit .sp thank you
