### ISSUE TITLE
[Feature Request] Add configuration for wingman

### ISSUE THREAD

**Issue by Cyberschorsch** [splewis/get5#953]
It would be great to have a default config for running wingman matches.

Since some users here and in Discord were asking for it I would like to start this discussion here. I will also open up a Pull Request with a config I use for competive wingman matches we use in our internal cup.

**Comment by nickdnk** [comment]
As commented on the PR:

This is a little more complicated than this, unfortunately. Game mode and game type must be correctly set, and the location of the wingman config file needs to be a Cvar like the others. I was planning on properly integrating this in 0.13, after 0.12 is done.
