### ISSUE TITLE
Powered by Get5

### ISSUE THREAD

**Issue by lugaamn** [splewis/get5#956]
Can I change it? I want use it tournament name And add de_train de_cache de_anubis maps. don't ban everything, give your users a choice

**Comment by nickdnk** [comment]
You cannot remove "Powered by Get5", as that's the name of the software you use. You can set the tournament name in the message prefix: https://splewis.github.io/get5/latest/configuration/#get5_message_prefix

You decide the maplist with a match configuration. Nothing is banned. See https://splewis.github.io/get5/latest/match_schema/#schema.
