### ISSUE TITLE
Maplist not working

### ISSUE THREAD

**Issue by lugaamn** [splewis/get5#957]
"maplist": [
    "de_dust2",
    "de_nuke",
    "de_inferno",
    "de_mirage",
    "de_vertigo",
    "de_ancient",
    "de_overpass"
  ]

I added "de_train" and Anubis etc.. it just changed to first map de_dust2. My cfg skip veto 1, map_number 1

**Comment by nickdnk** [comment]
You are doing something wrong then. The maplist feature works fine. You also did not fill out any of the data requested in the issue template.

The maplist you posted here would start on de_dust2, as that's the first map in the list. It's kind of self-explanatory.

Please don't open issues with problems that can be resolved by simply reading the documentation: https://splewis.github.io/get5/latest/.
