### ISSUE TITLE
[Bug]: Backup System

### ISSUE THREAD

**Issue by Kevinwu901113** [splewis/get5#963]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

v0.12.0

### The Issue

When I use the command: [get5_loadbackup] After the loadbackup, the game is backed up. The number of rounds and score are correct, but everyone's money is 16000

**Comment by Iwhite67** [comment]
Hello

Can you send the file use for backups?

**Comment by Kevinwu901113** [comment]
[get5_backup0_matchmanual_map0_round3.txt](https://github.com/splewis/get5/files/10371610/get5_backup0_matchmanual_map0_round3.txt)
[get5_backup0_matchmanual_map0_round4.txt](https://github.com/splewis/get5/files/10371611/get5_backup0_matchmanual_map0_round4.txt)

**Comment by Kevinwu901113** [comment]
I tested the plug-in when there were only two people on the server. In round three, I used the backup command. The game was archived to the beginning of round three, but the money was 16000

**Comment by Kevinwu901113** [comment]
[live.txt](https://github.com/splewis/get5/files/10372573/live.txt)
[server.txt](https://github.com/splewis/get5/files/10372574/server.txt)

**Comment by Kevinwu901113** [comment]
[gamemode_competitive.txt](https://github.com/splewis/get5/files/10372604/gamemode_competitive.txt)
[gamemode_competitive_server.txt](https://github.com/splewis/get5/files/10372605/gamemode_competitive_server.txt)

**Comment by Kevinwu901113** [comment]
I don't understand why this problem arises

**Comment by Kevinwu901113** [comment]
Except for the length and number of pauses, other settings are default

**Comment by nickdnk** [comment]
Please delete all custom configuration files and try again. Your backup file contains the 16000 cash property, meaning you have some file setting it. Get5 is not doing this, so it doesn't really have anything to do with the plug-in.

Remove all the custom files you posted as well as acc_gslt.cfg and xnetserver.cfg, then try again. If you have any other plugins, remove those too. If that doesn't work, reinstall the server to default state and add one plug-in/config file at a time until it breaks to figure out what the problem is.

**Comment by Kevinwu901113** [comment]
ok,i try it later

**Comment by Kevinwu901113** [comment]
It conflicts with another mods.(another 5v5 mod).Sorry to bother you

**Comment by Kevinwu901113** [comment]
Another problem: Yesterday I found ten people to play a game, and also tested the backup system, but the birth point is not the same. Is this a bug or can't be implemented at present?
and sorry for my poor english

**Comment by nickdnk** [comment]
If you mean spawn positions, then no, you cannot fix this. It's not stored in the backups.
