### ISSUE TITLE
[Bug]: Developer documentation and Docker image for building

### ISSUE THREAD

**Issue by LowArte** [splewis/get5#992]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

0.13.0

### The Issue

In documentation for developers specify docker image with latest tag, but latest image doesn't have volumes and not working.
Maybe need to change documentation to previes tag of image
I'm use nickdnk/get5-build:1.10.0-6545-sp-fix, and succesfuly build

**Comment by nickdnk** [comment]
Latest image compiles with 1.11: https://splewis.github.io/get5/dev/developers/

Else use `nickdnk/get5-build:1.10.0-6545-sp-fix`

**Comment by LowArte** [comment]
![image](https://user-images.githubusercontent.com/47986420/223525049-cacd594a-99ba-43ac-b7fb-e1eed41d16ec.png)
I know, but in documentation specifyed latest version, someone try and spent hour like me to undestand why it's not working

**Comment by nickdnk** [comment]
Fixed: https://github.com/splewis/get5/commit/ae973cf9b65e9206bf13a3e5dd50c261b1f7efe5

**Comment by nickdnk** [comment]
Also, if you have a feature request (since you need to compile the plugin yourself), please let me know.

**Comment by LowArte** [comment]
Thanks for fix. I need develop by my own, because i connect plugin to my external system, so this functionality outside of plugin development.

**Comment by nickdnk** [comment]
> Thanks for fix. I need develop by my own, because i connect plugin to my external system, so this functionality outside of plugin development.

Alright, but Get5 can be connected to external systems already using the forwards and the event system, so what exactly is it you need to do that it doesn't do?
