### ISSUE TITLE
[Feature Request]: Change team name after match has loaded

### ISSUE THREAD

**Issue by lugaamn** [splewis/get5#993]
### Prereleases & Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and I don't see the feature anywhere.
- [X] I have looked for [pre-releases](https://github.com/splewis/get5/releases) and the feature has not been added.

### Get5 Version

0.13.0

### The Feature

Can the admin change the team name? Otherwise, if a player joins the team and then becomes a terrorist, the name of the team remains with the name of the person who first joined the team.

**Comment by nickdnk** [comment]
A player cannot change team, so I don't know what you mean by "then becomes a terrorist".

You can preset the team name in the match configuration: https://splewis.github.io/get5/latest/match_schema/#schema if you want the name to be something specific.

**Comment by lugaamn** [comment]
[1sT] You may type !forceready to force-ready your team.
● CERTIFIED BOT‎ : !forceready
[1sT] Your team was force-readied by CERTIFIED BOT.
[1sT] team_CERTIFIED BOT is ready for map selection.

That's how you get the team name. Then, to enter the Terrorist, the name of the Counter Terrorist's team and the name of the person in this terrorist are saved.

**Comment by nickdnk** [comment]
You have not explained what the problem is. Please see my comment above. You can preset the team name if you want it to be something specific. It's in the documentation.

**Comment by lugaamn** [comment]
Okay close hehe thank you
